### ISSUE TITLE
Update cp2k.org Subversion references and instructions to Git

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#10]
- [x] https://www.cp2k.org/download
- [x] https://www.cp2k.org/dev:release_checklist ... might have to change considerably, depending on availability of CI infrastructure to automatically build tarballs
- [x] https://www.cp2k.org/dev:regtesting
- [x] https://www.cp2k.org/dev:starting
- [x] https://www.cp2k.org/performance
- [x] https://www.cp2k.org/dev
- [ ] https://www.cp2k.org/news
- [x] https://www.cp2k.org/howto:install_with_plumed
- [x] https://www.cp2k.org/howto:cp2k_omen
- [x] https://www.cp2k.org/tools:cubecruncher
- [x] https://www.cp2k.org/admin:kohn ... rename to `sham`?
- [x] https://www.cp2k.org/sidebar
- [x] https://www.cp2k.org/about
- [x] https://www.cp2k.org/dbcsr
- [x] https://www.cp2k.org/tools:emacs
- [ ] https://www.cp2k.org/version_history

**Comment by dev-zero** [comment]
@oschuett can you please update the documentation on `admin:kohn`?

**Comment by oschuett** [comment]
I created https://www.cp2k.org/static/download_stats.html.

**Comment by oschuett** [comment]
I remove the https://www.cp2k.org/admin:kohn page. Since I switched to [Ansible](https://github.com/cp2k/cp2k-infra) it's not needed anymore.
