### ISSUE TITLE
Dangling pointer ROW_MAX_EPSS referenced at dbcsr_mm_multrec.F in sparse_multrec

### ISSUE THREAD

**Issue by vzecca** [cp2k/cp2k#1036]
Running test case xTB/regtest-4/H2O-32-xtb-ls-1.inp (and many others)
dangling pointer this%row_max_epss is referenced at dbcsr_mm_multrec.F:534 in sparse_multrec

                                       use_eps=this%use_eps, row_max_epss=this%row_max_epss, &

Target was RETURNed from procedure DBCSR_MM_MULTREC:DBCSR_MM_MULTREC_INIT

**Comment by oschuett** [comment]
Tracked as https://github.com/cp2k/dbcsr/issues/402 in the DBCSR project.
