### ISSUE TITLE
make pretty with new pre-commit introduces changes after clean checkout

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#1061]
```
diff --git a/src/arnoldi/PACKAGE b/src/arnoldi/PACKAGE
index 57bfcf7..f82a40a 100644
--- a/src/arnoldi/PACKAGE
+++ b/src/arnoldi/PACKAGE
@@ -2,5 +2,7 @@
     "description": "Arnoldi iteration eigenvalue algorithm",
     "archive": "libdbcsrarnoldi",
     "requires": ["../mpiwrap", "../base", "../dbcsrx", "../common"],
-    "public": ["arnoldi_api.F",],
+    "public": [
+        "arnoldi_api.F",
+    ],
 }
diff --git a/tools/fix_unused_public.py b/tools/fix_unused_public.py
index fbec77b..7a7a6b5 100755
--- a/tools/fix_unused_public.py
+++ b/tools/fix_unused_public.py
@@ -127,7 +127,10 @@ def parse_file(fn):
     matches = re_use.findall(content)
     for m in matches:
         uses.append((m.strip(), ("*",)))
-        if m.strip() not in ("iso_c_binding", "f77_blas",):
+        if m.strip() not in (
+            "iso_c_binding",
+            "f77_blas",
+        ):
             print("missing ONLY-clause: ", fn, m)
 
     matches = re_useonly.findall(content)
diff --git a/tools/toolchain/scripts/parse_if.py b/tools/toolchain/scripts/parse_if.py
index 03e7484..4d357d6 100755
--- a/tools/toolchain/scripts/parse_if.py
+++ b/tools/toolchain/scripts/parse_if.py
@@ -61,9 +61,9 @@ class Parser:
 
     def ParseIf(self, string, switch):
         """
-ParseIf(string, switch) will replace in string recursively
-occurance of IF_key(A|B) statements with A if val = True;
-B if val = False
+        ParseIf(string, switch) will replace in string recursively
+        occurance of IF_key(A|B) statements with A if val = True;
+        B if val = False
         """
         result = string
         while result.find("IF_" + switch[0]) > -1:
@@ -72,9 +72,9 @@ B if val = False
 
     def ParseString(self, string):
         """
-ParseString(string) will parse in string recursively
-all of IF_key(A|B) statements for all (key, val) pairs
-in dictionary self.mSwitches
+        ParseString(string) will parse in string recursively
+        all of IF_key(A|B) statements for all (key, val) pairs
+        in dictionary self.mSwitches
         """
         result = string
         for switch in self.mSwitches.items():

```

**Comment by oschuett** [comment]
Interesting!

This is due to the recent [release](https://pypi.org/project/black/#history) of `black 20.8b0`, which apparently has some subtle behavior changes.

I guess, we should pin the versions of our precommit tools.

**Comment by mkrack** [comment]
Indeed, we can adopt any kind of formatting, but it has to be unique.

**Comment by oschuett** [comment]
> we can adopt any kind of formatting, but it has to be unique.

True, if anything this proves that installing these tools is not trivial.

I've decided to stick with version 19.10b0 of black for now, because it seems that they are [not quite done](https://github.com/psf/black/commit/7fe19fac5bccc08dbcf21c293ab50f1fcda7716f) yet with their changes.

**Comment by oschuett** [comment]
The old [formatting](https://dashboard.cp2k.org/archive/formatting/index.html) check started failed after the CI [rebuild](https://github.com/cp2k/cp2k-ci/blob/master/toolbox/janitorial_duties.sh#L26) the image and it picked up the latest version of black.

Since the new precommit system seems to works well, I'd suggest we just decommission the old formatting check.

**Comment by juerghutter** [comment]
Currently no PR pass the CI.

Either we have
Reformat Python files with the black code formatter.......................Failed

or 
Precommit Expected — Waiting for status to be reported

**Comment by oschuett** [comment]
> Reformat Python files with the black code formatter.......................Failed

Yes this because the black formatter recently changed its behavior. Since there is no simple solution, we should just remove it.

> Precommit Expected — Waiting for status to be reported

Since the precommit check is new it was missing from old PRs. I now manually triggered it for all old PRs.

**Comment by dev-zero** [comment]
> > Reformat Python files with the black code formatter.......................Failed
> 
> Yes this because the black formatter recently changed its behavior. Since there is no simple solution, we should just remove it.

It is also because you insist on checking things unrelated to a specific PR.

**Comment by oschuett** [comment]
> It is also because you insist on checking things unrelated to a specific PR.

We tried the alternative of checking only modified files: Due to tool changes the formatting became stale. And when somebody modified a file the commit was cluttered with the re-formatting. To prevent this the code base should always be formatted consistently.
