### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#1062]
```
Discovering programs ...
Removing stale archives for psmp ... 
Could not find source for object glob_matching.o in archive /data/user/krack/github/mkrack/cp2k/lib/test/psmp/libcp2kcommon.a , removing archive.
Resolving dependencies for psmp ... 
...
```

**Comment by oschuett** [comment]
Are there any other error messages to this?
The `Could not find source for object ...` is just normal operation of [check_archives.py](https://github.com/cp2k/cp2k/blob/master/tools/build_utils/check_archives.py).

**Comment by mkrack** [comment]
No, there are no other errors. I think the script does not work properly any longer, since there are now two folders with the same name: `common` and `grid/common` at different levels. The logic of the script does not consider that case.
