### ISSUE TITLE
Retire Apidoc and bring back Doxygen

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#1072]
All links to the source files, like to [cp_fm_types](https://github.com/cp2k/cp2k/blob/master/cp2k/src/fm/cp_fm_types.F) linked from [here](https://apidoc.cp2k.org/index.html?cp_fm_types.html), are broken in the  [documentation](https://apidoc.cp2k.org/index.html) since a while.

**Comment by oschuett** [comment]
Yes, the apidoc has been without updates for a while and it's not easy to salvage because it relies on some unlicensed code.
I think we should just return to Doxygen because we're getting more C code and DBCSR (the main use case) has moved away.
