### ISSUE TITLE
i386 regtest failures

### ISSUE THREAD

**Issue by mbanck** [cp2k/cp2k#1118]
Hi,

There's always been some regtesting instability on (some) non-amd64 architectures in Debian, but the recent addition of armhf and i386 to the ci.debian.net testing framework (and making failures there release-critical) makes it somewhat urgent to look at.

Is there a regtester running x86-32/i386, or are they all on x86-64/amd64?

For the subset of tests run on ci.debian.net, I get on i386:

```
Number of FAILED  tests 2
Number of WRONG   tests 52
Number of CORRECT tests 292
```
(the full log is e.g. at https://ci.debian.net/data/autopkgtest/unstable/i386/c/cp2k/7284992/log.gz)

Some of them are maybe just due to too strict tolerances, e.g.
```
QS/regtest-linearscaling/w3-filter-2.inp.out : 
 Total energy: : ref = -78.30555080270769 new = -78.30555080268756  
 relative error :   2.56975017e-13 >  numerical tolerance = 1.0E-14  
```
but a lot are really far off, like:

```
QS/regtest-hybrid-1/H2O-hybrid-b3lyp.inp.out : 
 Total energy: : ref = -76.37338940401885 new = -76.36068865548181  
 relative error :   1.66325746e-04 >  numerical tolerance = 4e-14  
```

The two failures (`QS/regtest-mp2-grad/O2_dyn_mme.inp` and `QS/regtest-mp2-grad/MOM_MP2_geoopt.inp` are due to unconverged SCF. I think a lot of the others are due to libint/HFX though. I ran e.g. `QS/regtest-ri-rpa/RI_RPA_CH3.inp` and I get the same SCF energy (`-7.37035061959636`), but the EXX energy differs (`-2.49845865573804` on i386 vs `-2.52798659291175` on amd64). I thought maybe the

```
 *** WARNING in pw/ps_wavelet_methods.F:236 :: Density non-zero on the ***
 *** edges of the unit cell: wrong results in WAVELET solver           ***
```

were part of the problem, but those are on amd64 as well.

One difference I noticed is

```
- HFX_MEM_INFO| Number of cart. primitive ERI's calculated:               908685
+ HFX_MEM_INFO| Number of cart. primitive ERI's calculated:               908735
```
could that be relevant?

Unfortunately, the RPA part does not seem to have a lot of output otherwise, is there some way to diagnose that?

**Comment by mkrack** [comment]
There is a [armv7l-gnu](https://dashboard.cp2k.org/archive/arm-gnu-psmp/index.html) regression tester running on a Raspberry Pi 4.

**Comment by mbanck** [comment]
Ok, thanks. Looks like the Debian ci.debian.net armhf machine is `armv8l`. I'll try on a `armv7l` porter box to see whether I can reproduce the issues there (or rather, whether regtesting works fine there).

About i386, is the limiting factor that you'd need a 32bit chroot on one of the existing 64bit regtesters (which might be difficult to setup automatically, I haven't looked at the infrastructure), or just that i386 has not been considered a worthwhile target?

**Comment by mbanck** [comment]
I tried, and I get a different result (same as the armhf ci.debian.net results) for the first test (`QS/regtest-mp2-grad/H2O_grad_mme.inp`) already:

```
 ENERGY| Total FORCE_EVAL ( QS ) energy (a.u.):              -16.688924480255722
```
vs.
```
H2O_grad_mme.inp                                      11      4e-09            -16.766973106034889
```

This example already has different SCF energies, on armhf:

```
 SCF WAVEFUNCTION OPTIMIZATION

  Step     Update method      Time    Convergence         Total energy    Change
  ------------------------------------------------------------------------------
     1 P_Mix/Diag. 0.40E+00   34.7     0.73435746       -16.4274644971 -1.64E+01
[...]
    12 DIIS/Diag.  0.12E-06    1.6     0.00000006       -16.6480538895 -1.36E-11

  *** SCF run converged in    12 steps ***


  Electronic density on regular grids:         -7.9999806656        0.0000193344
  Core density on regular grids:                8.0000038809        0.0000038809
  Total charge density on r-space grids:        0.0000232153
  Total charge density g-space grids:           0.0000232153

  Overlap energy of the core charge distribution:               0.00000000257920
  Self energy of the core charge distribution:                -44.06755038100893
  Core Hamiltonian energy:                                     12.64934675101254
  Hartree energy:                                              18.45628186637108
  Exchange-correlation energy:                                  0.00000000000000
  Hartree-Fock Exchange energy:                                -3.68613212849454

  Total energy:                                               -16.64805388954064
```
x86-64:

```
 SCF WAVEFUNCTION OPTIMIZATION

  Step     Update method      Time    Convergence         Total energy    Change
  ------------------------------------------------------------------------------
     1 P_Mix/Diag. 0.40E+00    0.7     0.75843093       -16.4793002399 -1.65E+01
[...]
    12 DIIS/Diag.  0.51E-06    0.0     0.00000043       -16.7241744422 -2.14E-11

  *** SCF run converged in    12 steps ***


  Electronic density on regular grids:         -7.9999807299        0.0000192701
  Core density on regular grids:                8.0000038809        0.0000038809
  Total charge density on r-space grids:        0.0000231511
  Total charge density g-space grids:           0.0000231511

  Overlap energy of the core charge distribution:               0.00000000257920
  Self energy of the core charge distribution:                -44.06755038100893
  Core Hamiltonian energy:                                     12.74056538043811
  Hartree energy:                                              18.38210913985923
  Exchange-correlation energy:                                  0.00000000000000
  Hartree-Fock Exchange energy:                                -3.77929858404536

  Total energy:                                               -16.72417444217774
```

**Comment by mbanck** [comment]
I did some more digging in the old build logs and the regression happened when we did/had to switch from libint to libint2 (which is mandatory from 7.1).

I had a look at the libint2 compile flags, and they seem to be basically the same, I'll have a closer look at libint2 now.

Edit: Well, the libint2 tests don't even compile on 32bit for starters...

**Comment by oschuett** [comment]
> About i386, is the limiting factor that you'd need a 32bit chroot on one of the existing 64bit regtesters (which might be difficult to setup automatically, I haven't looked at the infrastructure),

It should be rather straightforward to add a regtester for i386 using [these](https://hub.docker.com/r/i386/ubuntu) Docker images.

> ... or just that i386 has not been considered a worthwhile target?

I think, HPC stopped caring about i386 a while ago, but we certainly do care about CP2K being in Debian ;-)

**Comment by mbanck** [comment]
> There is a [armv7l-gnu](https://dashboard.cp2k.org/archive/arm-gnu-psmp/index.html) regression tester running on a Raspberry Pi 4.

Is there some documentation on how libint2 was built for this? It seems to use version 2.6.0 according to the regtester output.

I can't get the tests built on 32bit, and even if I do fix that, I get thousands of errors like

```
./test 0 2 && ./test 1 1 && ./test 2 1
Testing  (ss|ss) : ok
Testing  (ss|ps) : ok
Testing  (ss|pp) : ok
Testing  (ss|ds) : ok
Testing  (ss|dp) : Elem 0 di= 0 v=0 : ref = -41.5654 libint = 2.09038 relabs_error = 1.05029
Elem 10 di= 0 v=0 : ref = 17.1098 libint = 6.52341 relabs_error = 0.618733
Elem 17 di= 0 v=0 : ref = 49.9851 libint = 14.8847 relabs_error = 0.702217
failed
Testing  (ss|dd) : Elem 0 di= 0 v=0 : ref = 0.0118779 libint = 0.016896 relabs_error = 0.422471
Elem 1 di= 0 v=0 : ref = -0.00109721 libint = -0.00754032 relabs_error = 5.87225
[...]
```

**Comment by mkrack** [comment]
> Is there some documentation on how libint2 was built for this? It seems to use version 2.6.0 according to the regtester output.

The required libraries, including libint2 (v2.6.0, lmax=5), were built using the CP2K toolchain as usual.

**Comment by mbanck** [comment]
I see. I've now uploaded a new libint2 package to Debian which fixes the compile failure on 32bit arches. Interestingly, all 32bit architectures fail the tests (including i386 and armhf), except for powerpc and alpha, which for some reason pass. Looking at https://wiki.debian.org/ArchitectureSpecificsMemo#Summary what sets them apart is the size of `long double` being 16 instead of 8, so maybe it is related to that.

**Comment by oschuett** [comment]
I've started to setup an i386 tester (#1130). The first [report](https://storage.googleapis.com/cp2k-ci/run-cp2k-i386-81268e22_report.txt) looks rather encouraging: It's mostly tight thresholds and two issues in `Fist/*/UO2-4x4x4*` and `QS/regtest-gapw-1/CO_xastpflex_c0.3.inp`. 

I do not see any evidence for a fundamental issue with libint2 on i386.

**Comment by dev-zero** [comment]
For the record, I see similar problems with libint on our old Opteron machine (with a x86_64 kernel and userland):

```
[...]
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f2e78a48640 in ???
#1  0x7f2e78a47873 in ???
#2  0x7f2e77ce959f in ???
#3  0x0 in ???
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
#0  0x7f9296bbc640 in ???
#1  0x7f9296bbb873 in ???
#2  0x7f9295e5d59f in ???
#3  0x0 in ???
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 0 on node tcopt2 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
EXIT CODE:  139  MEANING:  RUNTIME FAIL
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
/data/tiziano/cp2k/regtesting/local/psmp/TEST-local-psmp-2020-11-02_11-05-13/QS/regtest-ri-laplace-mp2-cubic/RI_laplace_cubic_MP2_CH3_svd.inp.out


 *** WARNING in pw/ps_wavelet_methods.F:235 :: Density non-zero on the ***
 *** edges of the unit cell: wrong results in WAVELET solver           ***
[...]
--------------------------------- Summary --------------------------------
Number of FAILED  tests 53
Number of WRONG   tests 0
Number of CORRECT tests 3333
Total number of   tests 3386
GREPME 53 0 3333 0 3386 X

Summary: correct: 3333 / 3386; failed: 53; 24min
Status: FAILED
```

Essentially all libint-based CP2K regtests fail, but the libint tests themselves succeed:

```
$ make
./eri/test 0 2 && ./eri/test 1 1 && ./eri/test 2 1
Testing  (ss|ss) : ok
Testing  (ss|ps) : ok
[...]
```

**Comment by dev-zero** [comment]
Nevermind, the errors I see on the Opterons seem to be coming from libxsmm:

```
Thread 1 "cp2k.psmp" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
Missing separate debuginfos, use: zypper install libblas3-debuginfo-3.5.0-lp151.4.4.x86_64 libgcc_s1-debuginfo-8.2.1+r264010-lp151.1.33.x86_64 libgfortran4-debuginfo-7.5.0+r278197-lp151.2.12.1.x86_64 libgomp1-debuginfo-8.2.1+r264010-lp151.1.33.x86_64 libibverbs1-debuginfo-22.5-lp151.3.6.1.x86_64 liblapack3-debuginfo-3.5.0-lp151.4.4.x86_64 libnl3-200-debuginfo-3.3.0-lp151.2.3.x86_64 libopenblas_openmp0-debuginfo-0.2.20-lp151.7.7.x86_64 libopenblas_pthreads0-debuginfo-0.2.20-lp151.7.8.x86_64 libquadmath0-debuginfo-8.2.1+r264010-lp151.1.33.x86_64 librdmacm1-debuginfo-22.5-lp151.3.6.1.x86_64 libstdc++6-debuginfo-8.2.1+r264010-lp151.1.33.x86_64 libz1-debuginfo-1.2.11-lp151.5.3.1.x86_64
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x000000000250f827 in ai_contraction_sphi::libxsmm_abc_contract (
    abcint=..., sabc=..., tsphi_a=..., sphi_b=..., sphi_c=..., ncoa=28, 
    ncob=28, ncoc=90, nsgfa=4, nsgfb=4, nsgfc=57, cpp_buffer=..., 
    ccp_buffer=...) at /data/tiziano/cp2k/src/aobasis/ai_contraction_sphi.F:275
#2  0x0000000001ac061b in qs_tensors::build_3c_integrals (t3c=..., 
    filter_eps=5.0000000000000003e-10, qs_env=<optimized out>, nl_3c=..., 
    basis_i=..., basis_j=..., basis_k=..., potential_parameter=..., 
    int_eps=9.9999999999999995e-07, op_pos=1, 
    do_kpoints=<error reading variable: Cannot access memory at address 0x0>, 
    desymmetrize=.FALSE., 
    bounds_i=<error reading variable: Cannot access memory at address 0x0>, 
    bounds_j=..., 
    bounds_k=<error reading variable: Cannot access memory at address 0x0>)
    at /data/tiziano/cp2k/src/qs_tensors.F:1208
#3  0x0000000000eb433a in hfx_ri::hfx_ri_pre_scf_calc_tensors (
    qs_env=0x8d72ed0, ri_data=..., t_2c_int_ri=..., t_2c_int_pot=..., 
    t_3c_int=...) at /data/tiziano/cp2k/src/hfx_ri.F:426
#4  0x0000000000eb7c8e in hfx_ri::hfx_ri_pre_scf_pmat (qs_env=0x8d72ed0, 
    ri_data=...) at /data/tiziano/cp2k/src/hfx_ri.F:571
#5  0x0000000000ec0bca in hfx_ri::hfx_ri_update_ks_pmat (nspins=-42452, 
    geometry_did_change=4294924848, 
    rho_ao=<error reading variable: Location address is not set.>, 
```

**Comment by oschuett** [comment]
The failures in libvoir on i386 have been [fixed](https://github.com/cp2k/cp2k/pull/1258#issuecomment-752161052) in release [201229](https://github.com/cp2k/cp2k/pull/1263).

The [remaining](https://dashboard.cp2k.org/archive/i386/commit_c55fcb5588119868a9ca8a39957089537d54c28f.txt) failures on i386 are apparently two distinct problems:
- Fist/regtest-7-[12]/UO2-4x4x4-*
- QS/regtest-gapw-1/CO_xastpflex_c0.3.inp
