### ISSUE TITLE
Upgrade DBCSR to v2.1 (final)

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#1131]
See https://github.com/cp2k/dbcsr/milestone/5 for the progress on the DBCSR v2.1 final release

**Comment by alazzaro** [comment]
Some of the v2.1 issues will be moved to v2.2... What's the ETA for the v8.1?

**Comment by dev-zero** [comment]
@alazzaro end of year would be good, but we have other blockers as well (still collecting)

**Comment by alazzaro** [comment]
DBCSR v2.1.0-RC19 will (hopefully) become the v2.1.0. The RC is currently under testing in the CP2K-CI.

**Comment by alazzaro** [comment]
DBCSR 2.1.0 is out, you can update to CP2K...

**Comment by oschuett** [comment]
@alazzaro, thanks for making the DBCSR release!

It's maybe a bit too late now, but what should we do about #1203?

**Comment by alazzaro** [comment]
@oschuett I haven't consider the #1203 a real problem for the v2.1 The bug seems related to GCC 6 only... 
My plan was to have a stable release for CP2K 8.1. 
Anyway, we can always have a 2.1.1, assuming someone can look at the problem and provide a patch...

**Comment by oschuett** [comment]
I agree that it shouldn't block the cp2k 8.1 release, because it only affects a few users and does not produce any wrong results.
