### ISSUE TITLE
PLUMED required by Linux-x86-64-gfortran:psmp when not requested

### ISSUE THREAD

**Issue by chrisreidy** [cp2k/cp2k#1154]
If I run install_cp2k_toolchain.sh and leave plumed to default of no, this file arch/Linux-x86-64-gfortran.psmp requires plumed  on line 10
include       $(MPI_PATH)/plumed/2.5.2/lib/plumed/src/lib/Plumed.inc.static
producing
/opt/ohpc/admin/UAbuild/cp2k/cp2k/arch/Linux-x86-64-gfortran.psmp:10: /plumed/2.5.2/lib/plumed/src/lib/Plumed.inc.static: No such file or directory

**Comment by dev-zero** [comment]
It seems you're not really following the instructions given by the toolchain at the end:

```
[...]
==================== generating arch files ====================
arch files can be found in the /data/tiziano/cp2k/tools/toolchain/install/arch subdirectory
Wrote /data/tiziano/cp2k/tools/toolchain/install/arch/local.ssmp
Wrote /data/tiziano/cp2k/tools/toolchain/install/arch/local.sdbg
Wrote /data/tiziano/cp2k/tools/toolchain/install/arch/local.psmp
Wrote /data/tiziano/cp2k/tools/toolchain/install/arch/local.pdbg
Wrote /data/tiziano/cp2k/tools/toolchain/install/arch/local_warn.psmp
Wrote /data/tiziano/cp2k/tools/toolchain/install/arch/local_coverage.pdbg
========================== usage =========================
Done!
Now copy:
  cp /data/tiziano/cp2k/tools/toolchain/install/arch/* to the cp2k/arch/ directory
To use the installed tools and libraries and cp2k version
compiled with it you will first need to execute at the prompt:
  source /data/tiziano/cp2k/tools/toolchain/install/setup
To build CP2K you should change directory:
  cd cp2k/
  make -j 32 ARCH=local VERSION="ssmp sdbg psmp pdbg"
```

The `ARCH` to use together with the arch files generated by the toolchain is `local`: `make ARCH=local ...`.

The arch files already present in `arch/` when checking out the source code (or unpacking the tarball) are example files for different environments. There is no guarantee that they work your environment or the environment generated by the toolchain.

**Comment by chrisreidy** [comment]
Thank you. "local" works better than "Linux-x86-64-gfortran". I wasn't understanding the concept of local
