### ISSUE TITLE
No install path option

### ISSUE THREAD

**Issue by chrisreidy** [cp2k/cp2k#1155]
On a supercomputer, software is usually installed into somewhere like /opt/xx.  cp2k installs where it is built.  There should be a --prefix=/opt/xx or INSTALLDIR=/opt/xx.  Is there a way to direct the installation beyond copying the contents of exe, lib and obj files? 
Also, on linux systems, the executables are typically in 'bin', whereas Windows applications install in 'exe'

**Comment by dev-zero** [comment]
I believe this could be a duplicate of #920 ?

What has to be copied are the executables in `exe/$ARCH/` (without the unittests usually) and the data files in `data/`. Furthermore you should either set `__DATA_DIR` in the `CFLAGS` to point where the data directory is going to reside after the installation or set the `CP2K_DATA_DIR` environment variable in the modules file you are likely to provide.

Please note: for a supercomputer installation we would rather recommend to use something like https://spack.io/ (for which we're actively maintaining the CP2K package) or https://easybuilders.github.io/easybuild/

**Comment by chrisreidy** [comment]
Thanks for the clarification.
