### ISSUE TITLE
redhat 7.9 devtool-9,gcc-9.3, openmpi4.0.5, mkl2002.4,make psmp failure.

### ISSUE THREAD

**Issue by alas-go** [cp2k/cp2k#1165]
redhat 7.9 devtool-9,gcc-9.3, openmpi4.0.5, mkl2002.4,
when compiling cp2k-7.1 in the method of toolchain. sirus-6.4.1 was precompiled successfully, but  when make popt and psmp, both popt and popt test is ok  while that "make psmp" prints errors.
the difference between local.popt and psmp is that the psmp have the sirus.
after typing make arch=local version="psmp",  the psmp fodlers in lib and obj have been created but the lib files and functions files are less than that of popt folders.

I don't  know what's wrong with it.

[local.popt.zip](https://github.com/cp2k/cp2k/files/5541832/local.popt.zip)
[local.psmp.zip](https://github.com/cp2k/cp2k/files/5541833/local.psmp.zip)
[compile.log.zip](https://github.com/cp2k/cp2k/files/5541834/compile.log.zip)

**Comment by mtaillefumier** [comment]
the messages the compilation returns you are warnings mostly defined but unused variables. A hint was this message from cmake 

```
  Manually-specified variables were not used by the project:

    CMAKE_CXXFLAGS_RELEASE

```
Your log does not contain any messages coming from compiling cp2k though. would it possible to have the output file of 

make VERSION=psmp ARCH=local > compile.log

**Comment by dev-zero** [comment]
Can you also please paste the exact command line you used for building the toolchain (`./install_cp2k_toolchain.sh ...`)? The arch file references MKL for FFTW, BLAS, etc. but does not define `__MKL` as it should when the toolchain was called with `--with-mkl`.

**Comment by alas-go** [comment]
> Can you also please paste the exact command line you used for building the toolchain (`./install_cp2k_toolchain.sh ...`)? The arch file references MKL for FFTW, BLAS, etc. but does not define `__MKL` as it should when the toolchain was called with `--with-mkl`.

I think it is OK.

./install_cp2k_toolchain.sh --enable-cuda=no \
                            --math-mode=mkl \
                            --with-cmake=/opt/cmake-3.18.4-Linux-x86_64 \
                            --with-mkl=/home/az/intel/compilers_and_libraries_2020.4.304/linux/mkl \
                            --with-openmpi=system \
                            --with-libxc=install \
                            --with-libint=install \
                            --with-fftw=install \
                            --with-openblas=no \
                            --with-scalapack=no \
                            --with-reflapack=no \
                            --with-libxsmm=install \
                            --with-elpa=install \
                            --with-pexsi=install \
                            --with-superlu=install \
                            --with-quip=install \
                            --with-plumed=install \
                            --with-gsl=install \
                            --with-libvdwxc=install \
                            --with-spglib=install \
                            --with-hdf5=install \
                            --with-spfft=install \
                            --with-sirius=install \
                            -j ${PARALLEL}

**Comment by alas-go** [comment]
the main problem should come from sirus. i do try other version of sius. maybe, it is the compatiblity between sirus and  mkl math lib.
thanks.

**Comment by hfp** [comment]
I had a quick look at the compile log, and it turns out Intel MKL is linked as if Intel MPI is used. Please note, MKL consists of core, thread rt, and other (modular) components. The [choice](https://software.intel.com/content/www/us/en/develop/articles/intel-mkl-link-line-advisor.html) of these components depends threading runtime and mpi library kind, etc.

**Comment by dev-zero** [comment]
Closing since the output of the actual CP2K compilation process is missing.
@alas-go there are more differences between psmp and popt than SIRIUS, and as your log shows, building SIRIUS succeeded.
Please also note that when changing options for the toolchain you may have to rebuild the complete toolchain (`rm -rf build install`) for consistency.
