### ISSUE TITLE
Can cp2k implement the self consistence method of determined U?

### ISSUE THREAD

**Issue by robinzyb** [cp2k/cp2k#117]
I found that a new section in dft_plus_u with name of enforce occupation. 
Can I use this subsection to enforce localized electron into specific atom?
Because I want to determine U from self consistent approach like method  developed by Nicola Marzari.

**Comment by dev-zero** [comment]
Please ask question about using CP2K at https://groups.google.com/forum/#!forum/cp2k
This bug tracker is for reporting specifics with CP2K.
