### ISSUE TITLE
CP2K manual: set default version to 6.1 and replace 'SVN Trunk' reference

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#12]
maybe something like `development version` instead?

**Comment by oschuett** [comment]
`Development Version` is pretty long. How about just `Development` or `Latest` as a label?

**Comment by dev-zero** [comment]
`Development` is fine I guess. `Latest` could also be *latest release*

**Comment by oschuett** [comment]
Fixed via #17
