### ISSUE TITLE
Create Github issue templates

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#1202]
Github can provide reporters with issue templates. Since people continue to create issues with incomplete information we should setup appropriate templates:

* [ ] compilation failures
* [ ] crashes or inconsistencies when running CP2K
* [ ] "need help" type of questions (with a strong hint to use the mailinglist/forum instead)
* [ ] feature requests

**Comment by oschuett** [comment]
I'm not really a fan of templates. How about just adding a friendly reminder:

_Hi there, please note that we use Github issues only for development topics.
For user questions you find a better audience at our [Forum](https://www.cp2k.org/howto:forum).
When reporting a problem, please include the full error message and possibly your arch and input file._

**Comment by dev-zero** [comment]
well, me neither and I for sure don't want to make it too complex, but a simple reminder for each type of issue what kind of information we need to be able to help

**Comment by oschuett** [comment]
Generally, I think the majority of issues we get is fine.

Multiple templates force the user to pick one, which creates friction and there is no guarantee they'll pick the right one.
Hence, I'd suggest we start with a single template and stick to our label based triage process, which works well.

**Comment by dev-zero** [comment]
Within the last week I closed 3 issues due to lack of information (and the reporter failing to repeat), wrong site (forum) and person did not search old issues. All of them could have potentially been prevented by proper templates, sparing time and attention of at least 3 devs and likely reducing frustration on the side of the reporter because they would have gotten the same info earlier.

**Comment by dev-zero** [comment]
> _Hi there, please note that we use Github issues only for development topics.

Please also mention examples for _development topics_ since this is obviously not clear to everyone (see "level" of questions we get on the mailinglist).

**Comment by oschuett** [comment]
> sparing time and attention of at least 3 devs

I'm grateful that you are tending to new issues.  And I'm not saying they are all perfect. I agree, that a simple note with the most common mistakes might help. But creating a bureaucracy of multiple templates will do more harm than good. I think, we just have to accept a certain level of background noise.

Generally, I believe templates are for big projects that receive more issues than they can handle. We are on the opposite end of the spectrum. We are a tiny project and learn about fundamental bugs only [years](https://github.com/cp2k/cp2k/issues/893) later. So, we should be as welcoming as possible to any feedback we can get.

**Comment by dev-zero** [comment]
The point is to tell the user what kind of information we need to be able to help. For that we have to first tell them that there are different classes of issues (which we can now clearly see) by making them select an issue template. For each class of issues we need specific information, that's what we're gonna document in the template issue. No checkbox clicking, not a gazillion of sections for structured reports, just infos for what we need to reduce the number of roundtrips.

As an open source project with unpaid members (at least when it comes to this kind of support work) we can expect from a user a certain amount of legwork. Having to repeat myself over and over again in issues is tiring.

**Comment by oschuett** [comment]
I still think that most new issues we're receiving are very reasonable and we're better off without templates.

**Comment by he-zilong** [comment]
More than half a decade have passed and I have been reading [github docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates) on this topic. Maybe we do not have to use issue and PR templates to restrict types/categories; merely conveying the message that we have [best practice to ask questions](https://manual.cp2k.org/trunk/getting-started/foreword-and-faq.html#what-is-the-best-practice-to-ask-questions) (for opening new issues) or that the precommit check can be run locally as `./make_pretty.sh` (for opening new PRs) would also work.
