### ISSUE TITLE
Tensor-based tests failing with GCC 6.5 in the dashboard

### ISSUE THREAD

**Issue by alazzaro** [cp2k/cp2k#1203]
Since a while, GCC 6.5 dashboard test is failing with the tensors based test. 

https://dashboard.cp2k.org/archive/gcc6/index.html

I know that @pseewald knows already about the problem. Putting here to keep track of the issue.
It seems a compile bug dealing new Fortran features...

**Comment by oschuett** [comment]
I wanted to bring this issue back up because it keeps failing our [gcc 6 test](https://dashboard.cp2k.org/archive/gcc6/index_full.html).

AFAIK, this is actually a bug in GCC. So, do we know of any acceptable workaround or should we just drop support for GCC 6?

**Comment by dev-zero** [comment]
Would that also include GCC 5?

Btw, for everything below gcc 10 there's a memleak in tensors.

**Comment by oschuett** [comment]
> Would that also include GCC 5?

No, GCC 5 seems to work [fine](https://dashboard.cp2k.org/archive/gcc5/index.html).

> for everything below gcc 10 there's a memleak in tensors.

While memleaks are not great, one can usually live with them.
This issue crashes most of the MP2, GW, and HFX-RI tests, which is a sizable chuck of our functionality.
