### ISSUE TITLE
No SCF convergence after 500 iterations for 64 Si atom structure

### ISSUE THREAD

**Issue by cp2kuser** [cp2k/cp2k#1205]
No SCF convergence after 500 iterations for 64 Si atom structure

using the following command
mpiexec -np $PBS_NP --machinefile $PBS_NODEFILE /opt/spack/opt/spack/linux-centos7-x86_64/intel-18.0.2/cp2k-develop-fw3esv3ywfndzwchh6qphm4nfp253aco/bin/cp2k.popt -o cp2kMD.out silicon64.inp 

[silicon64.inp.txt](https://github.com/cp2k/cp2k/files/5645914/silicon64.inp.txt)
[cp2kMD.out.txt](https://github.com/cp2k/cp2k/files/5645915/cp2kMD.out.txt)

Any suggestions are appreciated.

**Comment by oschuett** [comment]
Hi there, please note that we use Github issues only for development topics.
For usage questions, like this, you'll find a better audience at our [Forum](https://www.cp2k.org/howto:forum).
