### ISSUE TITLE
toolchain: update lcov to 1.15

### ISSUE THREAD

**Issue by ltalirz** [cp2k/cp2k#1217]
Just came across [this comment](https://github.com/cp2k/cp2k/blob/cb3df64bbfb67b02f3ed6d2bb60a674856e5d1a6/tools/docker/scripts/install_coverage.sh#L5-L8)

Looks like lcov 1.15 is out https://github.com/linux-test-project/lcov/releases

**Comment by dev-zero** [comment]
@ltalirz thanks for the update!
Yes, we should upgrade. There are also some other packages in the toolchain which should be version bumped before the v8.1 release:

* [x] CMake, either 3.19 or latest minor for 3.18
* [x] lcov 1.15
