### ISSUE TITLE
Should we remove our COPYRIGHT file?

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#1245]
Since we added [SPDX headers](https://github.com/cp2k/cp2k/pull/1074), the [COPYRIGHT](https://github.com/cp2k/cp2k/blob/master/COPYRIGHT) file is now redundant. Removing it would allow GitHub to [detect](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository#detecting-a-license) our GPL license.

Are there any objections?

**Comment by dev-zero** [comment]
ACK, see my comment in https://github.com/cp2k/dbcsr/issues/412#issuecomment-750803344
