### ISSUE TITLE
Replace CPWARN/CPABORT with Fypp macros

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#1250]
The traditional CPP employed by Fortran has some limitations when it comes to handling newline/spaces in macros, making it necessary to explicitly use `CALL cp_abort` when using longer comments since it can't introduce newlines itself.
Fypp has facilities to introduce automatic line breaks which would resolve that.

Together with this change we could also introduce a number of restrictions/improvements:

* do not allow empty comments for `CPABORT`: while useful for debugging/development they may be difficult to understand years later as people also tend to not write documentation
* introduce 2-parameter version of `CPASSERT` (and make it the default): C/C++ has the idiom `ASSERT(foo && "my error message")` to add a runtime-visible error message to an assert, helping to document the assert at the same time. Some of our asserts are clear depending on the context, others are not. A mandatory `CPASSERT(<cond>, "message")` would add this context explicitly and help document the code, provided that the `CPASSERT` macro can handle Fortran line breaks in a portable way.

**Comment by oschuett** [comment]
I believe our current [error reporting routines](https://www.cp2k.org/dev:error_handling) have proven to be sufficient.

While we could use Fypp to add a more convenience it would also make the code less self-explanatory, which I think is not worth it.

**Comment by he-zilong** [comment]
> * do not allow empty comments for `CPABORT`

Just a note that many of these were added in commit 5b6a98f back in 2015. Eliminating them will surely be a systematic project that may use some ai help. After that it should be added to the convention check.
