### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by aslozada** [cp2k/cp2k#1267]
Hi, 
 
In the file "INSTALL.md", in the example of lines 27-30, appear the option --enable-omp to script _install_cp2k_toolchain.sh_. This option is not active in the script of master branch.

This was modified? In the lastest release, v7.1.0, this option appear.

**Comment by oschuett** [comment]
Thanks for the report. The ` --enable-omp` option was removed because CP2K now always requires OpenMP.
