### ISSUE TITLE
cp2k.popt libint2_build_3eri got NULL function pointer

### ISSUE THREAD

**Issue by arm7star** [cp2k/cp2k#1280]
hi,
I tested cp2k 7.1 with libint 2.6.0(--enable-eri3=1 --with-eri3-max-am=7,6) on aarch64 linux, but cp2k.popt failed.
"CALL pbuild(lib%prv)" in cp_libint_get_3eris function faild. It seems that libint2_build_3eri has not been set and all are zero, so  "CALL pbuild(lib%prv)" will call a NULL function pointer. Where libint2_build_3eri is initialized or set?

thank you!

**Comment by dev-zero** [comment]
Can you post the complete configure invocation for libint. Please note that the configure options you posted are not enough. We are using the following to generate a CP2K-"compatible" libint:

```
configure \
        --enable-eri=1 --enable-eri2=1 --enable-eri3=1 \
        --with-max-am=${LMAX} \
        --with-eri-max-am=${LMAX},$((LMAX-1)) \
        --with-eri2-max-am=$((LMAX+2)),$((LMAX+1)) \
        --with-eri3-max-am=$((LMAX+2)),$((LMAX+1)) \
        --with-opt-am=3 \
        --enable-generic-code --disable-unrolling
```

with `LMAX=4,5,6,7`. You can find the different generated libint versions here: https://github.com/cp2k/libint-cp2k/releases/tag/v2.6.0 (they are not compiled, only code-generated, hence these tarballs should work on aarch64 as well).

**Comment by oschuett** [comment]
It's been 28 days without reply. @arm7star, feel free to reopen when you have more details to share.
