### ISSUE TITLE
grid: fails to build with Intel C compiler from Parallel xe studio 2020.4

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#1282]
without quip , it fails at the step of making local version of psmp with intel fortran
the log write the errors about the omp of the intel parallel xe studio 2020.4.
and the arch folder generated has no the file of local.popt 

[make.log](https://github.com/cp2k/cp2k/files/5760008/make.log)
[print.log](https://github.com/cp2k/cp2k/files/5760010/print.log)

_Originally posted by @alas-go in https://github.com/cp2k/cp2k/issues/1275#issuecomment-753451607_

**Comment by oschuett** [comment]
Looking at [print.log](https://github.com/cp2k/cp2k/files/5760010/print.log) it seems we have five distinct errors:

1. `controlling expression is constant:      assert(false && "Unknown ga_gb_function.");`
2. `enumerated type mixed with another type`
3. `variable "old_transpose" may be used before its value is set`
4. `type qualifier is meaningless on cast type`
5. `argument of type "double (*)[3]" is incompatible with parameter of type "const double (*)[3]"`


The first three are in my code and I'll take care of them. @mtaillefumier, could you please have a look at the other two.

**Comment by oschuett** [comment]
Fixed via #1284 and #1286.
