### ISSUE TITLE
toolchain: downloading SIRIUS fails

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#1283]
it seems very hard to compile quip with intel fortran.

the third error is that the download link of sirius 7.0.0 reads a 404 error.
https://github.com/electronic-structure/SIRIUS/archive/v${sirius_ver}.tar.gz

the right location on github is https://github.com/electronic-structure/SIRIUS/tree/v7.0.0

_Originally posted by @alas-go in https://github.com/cp2k/cp2k/issues/1275#issuecomment-753413320_

**Comment by alas-go** [comment]
> ```
> wget https://github.com/electronic-structure/SIRIUS/archive/v7.0.0.tar.gz
> ```

it is ok to download sirius-7  at  very low connetting speed after typing in this commond in a terminal.

--2021-01-06 15:37:59--  https://github.com/electronic-structure/SIRIUS/archive/v7.0.0.tar.gz
Resolving github.com (github.com)... 13.229.188.59
Connecting to github.com (github.com)|13.229.188.59|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/electronic-structure/SIRIUS/tar.gz/v7.0.0 [following]
--2021-01-06 15:38:00--  https://codeload.github.com/electronic-structure/SIRIUS/tar.gz/v7.0.0
Resolving codeload.github.com (codeload.github.com)... 13.250.162.133
Connecting to codeload.github.com (codeload.github.com)|13.250.162.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/x-gzip]
Saving to: ‘v7.0.0.tar.gz’

    [              <=>                                                  ] 628,298     3.97KB/s

![QQ截图20210106153919](https://user-images.githubusercontent.com/63892049/103742298-8af91300-5035-11eb-97d1-1dc268449d37.png)

**Comment by alas-go** [comment]
The download process of latest SIRUS 7.0.2 can not been finished. several hours passed, it only downloaded 15.5 MB，and the terminal stuncked but the size of early editon 7.0.0 is 55 MB. I also download it from github, it is sure that the package is only 15 MB and it report an unexpected ending when tar -xvf to uncompress. I don't think the main problem is the slow connection speed of the internet. kindly, please upload the file fullpack SIRUS 7.0.2 to www.cp2k.org/static/downloads as soon as possible.
thks.
