### ISSUE TITLE
calculate_vxc_atom references unassociated pointer drho_h

### ISSUE THREAD

**Issue by vzecca** [cp2k/cp2k#1289]
Running test case QS/regtest-spin-spin-1/he-polar-1.inp 
the procedure calculate_vxc_atom in file qs_vxc_atom.F line 327 references the unassociated pointer drho_h.
You may easily double check it prepending CPASSERT(associated(drho_h)).

**Comment by oschuett** [comment]
Fixed via #1309.

**Comment by dev-zero** [comment]
as commented in #1327 by @vzecca

ssame bug resurfaced at line 694 of qs_vxc_atom.F

CALL fill_rho_set(rho_set_h, lsd, nspins, needs, rho_h, drho_h, rtau, na, ir)

where drho_h is unassociated.

**Comment by dev-zero** [comment]
while checking whether we can drop the `POINTER` keyword in some places I stumbled over the following (in `xc_rho_set_get`):

https://github.com/cp2k/cp2k/blob/8a5b25a29b073c2e9c89190871898c2374d47822/src/xc/xc_rho_set_types.F#L344

but the `drho` component itself is neither a pointer nor a target (which becomes obvious as soon as the procedure `xc_rho_set_get` is changed to take the `rho_set` as `INTENT(IN)` instead.

https://github.com/cp2k/cp2k/blob/8a5b25a29b073c2e9c89190871898c2374d47822/src/xc/xc_rho_set_types.F#L91-L98

@vzecca do you know by any chance whether or not the "transitivity" of the `POINTER` attribute we see here (from the derived type `xc_rho_set_type` to its component `drho`) is standard Fortran?

**Comment by vzecca** [comment]
Yes, this is standard Fortran because rho_set is a POINTER.
The pointer assignment associates a pointer with a target (rho_set%drho here).
If the target is a variable it must have the TARGET attribute or be a
subobject of a TARGET.

**Comment by oschuett** [comment]
Fixed (some more ;-) via #1333.
