### ISSUE TITLE
calculate_xc_2nd_deriv_atom references disassociated pointer

### ISSUE THREAD

**Issue by vzecca** [cp2k/cp2k#1292]
Running test case QS/regtest-debug-1/h2o_gapw.inp
at line 681 of qs_vxc_atom.F

CALL fill_rho_set(rho_set_h, lsd, nspins, needs, rho_h, drho_h, tau_h, na, ir)

disassociated pointer tau_h is referenced.

You may double check by prepending

CPASSERT(associated(tau_h))

**Comment by dev-zero** [comment]
seems like `needs%tau` was never set to `.TRUE.`, otherwise we should've seen segfaults in `fill_rho_set`.

**Comment by oschuett** [comment]
Fixed via #1309.
