### ISSUE TITLE
documentation: add minimal required versions for packages (like SIRIUS)

### ISSUE THREAD

**Issue by brhr-iwao** [cp2k/cp2k#1295]
Hi

I tried to compile cp2k-8.1 with sirius 6.5.3 (with gfortran 10.2.0 and Cygwin on Windows 10) and got the following errors during compiling sirius_interface.f:

```
   61 |    USE sirius,                          ONLY: &
      |       1
......
  163 |       CALL sirius_create_context(sirius_mpi_comm, sctx)
      |                                                       2
Error: ‘sirius_create_context’ at (1) has a type, which is not consistent with the CALL at (2)
/home/user/cp2k-8.1/src/sirius_interface.F:275:57:

  275 |                                       spin_orbit=.FALSE.)
      |                                                         1
Error: Type mismatch in argument ‘spin_orbit’ at (1); passed LOGICAL(4) to LOGICAL(1)
/home/user/cp2k-8.1/src/sirius_interface.F:61:7:

   61 |    USE sirius,                          ONLY: &
      |       1
......
  423 |          CALL sirius_create_kset_from_grid(sctx, k_grid(1), k_shift(1), use_symmetry=.TRUE., kset_handler=ks_handler)
      |                                                                                                                     2
Error: ‘sirius_create_kset_from_grid’ at (1) has a type, which is not consistent with the CALL at (2)
/home/user/cp2k-8.1/src/sirius_interface.F:61:7:

   61 |    USE sirius,                          ONLY: &
      |       1
......
  425 |          CALL sirius_create_kset_from_grid(sctx, k_grid(1), k_shift(1), use_symmetry=.FALSE., kset_handler=ks_handler)
      |                                                                                                                      2
Error: ‘sirius_create_kset_from_grid’ at (1) has a type, which is not consistent with the CALL at (2)
/home/user/cp2k-8.1/src/sirius_interface.F:61:7:

   61 |    USE sirius,                          ONLY: &
      |       1
......
  428 |       CALL sirius_create_ground_state(ks_handler, gs_handler)
      |                                                             2
Error: ‘sirius_create_ground_state’ at (1) has a type, which is not consistent with the CALL at (2)
/home/user/cp2k-8.1/src/sirius_interface.F:109:53:

  109 |       CALL sirius_finalize(.FALSE., .FALSE., .FALSE.)
      |                                                     1
Error: Type mismatch in argument ‘call_mpi_fin’ at (1); passed LOGICAL(4) to LOGICAL(1)
/home/user/cp2k-8.1/src/sirius_interface.F:98:37:

   98 |       CALL sirius_initialize(.FALSE.)
      |                                     1
Error: Type mismatch in argument ‘call_mpi_init’ at (1); passed LOGICAL(4) to LOGICAL(1)
```

The "passed LOGICAL(4) to LOGICAL(1)" errors can be solved by replaceing ".FALSE./.TRUE." with "LOGICAL(L=.FALSE.(or .TRUE.), KIND=1)".

According to the function declaration on genetated.F90 (found in sirius/src/api. The latest file also can be seen in https://github.com/electronic-structure/SIRIUS/blob/master/src/api/generated.f90),

```
function sirius_create_context(fcomm) result(res)
implicit none
integer(C_INT), intent(in) :: fcomm
    :
END FUNCTION

function sirius_create_kset_from_grid(handler,k_grid,k_shift,use_symmetry) result(res)
implicit none
type(C_PTR), intent(in) :: handler
integer(C_INT), intent(in) :: k_grid
integer(C_INT), intent(in) :: k_shift
logical(C_BOOL), intent(in) :: use_symmetry
    :
END FUNCTION

function sirius_create_ground_state(ks_handler) result(res)
implicit none
type(C_PTR), intent(in) :: ks_handler
   :
END FUNCTION
```

the type of arguments of the functions "sirius_create_context, sirius_create_kset_from_grid and sirius_create_ground_state" are apparently
different between sirius_interface.f and declaration of sirius 6.5.3.

How could be solved the problem?

Thank you in advance.

**Comment by dev-zero** [comment]
it is unfortunately not prominently documented, but the minimal required version of SIRIUS for CP2K 8.1 is SIRIUS 7.0

**Comment by brhr-iwao** [comment]
Dear Dev-zero,

Thank you for quick reply!
~~I just cloned Sirius at Dec. 12 so I did not think the Sirius version is too old.~~
I will clone the latest Sirius, compile and use it with cp2k 8.1.

Best Regards,

**Comment by mtaillefumier** [comment]
hi @brhr-iwao 

Depending on the way you compile SIRIUS you will have two options. 

- Stick to SIRIUS 7.0 (which is the latest version supported by cp2k). The toolchain only supports SIRIUS 7.0 cp2k should support more recent versions provided that you have the right dependencies.
- Or use the dev. version of SIRIUS which means you will have an extra hard dependency to compile before compiling SIRIUS.

**Comment by brhr-iwao** [comment]
Dear @mtaillefumier

Thank you for kind instruction!
I will try to clone or download either of Sirius 7.0.0, 7.0.1 or 7.0.2 and use with cp2k-8.1.

Best Regards,

**Comment by mtaillefumier** [comment]
My pleasure. I would download the archive directly here

https://github.com/electronic-structure/SIRIUS/archive/v7.0.2.tar.gz

or of course on github [here](https://github.com/electronic-structure)

if case of trouble open an issue directly on SIRIUS github (I am one the maintainers/dev of the package)

**Comment by oschuett** [comment]
We officially only support a single version for each of our requirements. Those versions are defined by our toolchain. Other versions might work too, but we don't test them. So, you mileage may vary.

**Comment by dev-zero** [comment]
so it should be documented in the `INSTALL.md` that people should consult the toolchain scripts wrt to supported versions
