### ISSUE TITLE
make test returns exit code 0 if tests fail

### ISSUE THREAD

**Issue by ltalirz** [cp2k/cp2k#1299]
For automated cp2k builds and runs of the test suite it would be useful, if `make test` would only return exit code 0 if all tests pass (and otherwise return a nonzero exit code).

See e.g. [these logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=261784&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=23316) from the conda-forge build where we explicitly ask for `set -e` in the [build script](https://github.com/conda-forge/cp2k-feedstock/blob/52438996ebcf2d79d13711c4b0b025f62ac07f59/recipe/build.sh#L2).

**Comment by dev-zero** [comment]
ifI checked correctly, this is an issue of `tools/regtesting/do_regtest` not emitting the right error code (which is 0 unless compilation fails or something in the script itself went wrong)

**Comment by dev-zero** [comment]
might be fixed by implementing #770

**Comment by oschuett** [comment]
Fix via #1702.
