### ISSUE TITLE
buildsystem: build fails on macOS BigSur: ld: archive has no table of contents file

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#1300]
When trying to build CP2K v8.1 with `ARCH=minimal VERSION=sdbg` (arch-file patched to use `gcc-10` from homebrew due to OpenMP-requirement), building fails at the linker step:

```console
Discovering programs ...
Removing stale archives for sdbg ... 
Resolving dependencies for sdbg ... 
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C /Volumes/data/tiziano/cp2k/exts/dbcsr -f .cp2k/Makefile \
	  INCLUDEMAKE=/Volumes/data/tiziano/cp2k/arch/minimal.sdbg \
	  LIBDIR=/Volumes/data/tiziano/cp2k/lib/minimal/sdbg/exts/dbcsr \
	  OBJDIR=/Volumes/data/tiziano/cp2k/obj/minimal/sdbg/exts/dbcsr \
	  ACC="" \
	  ACCFLAGS=""
Removing stale archives ... 
Resolving dependencies ... 
gfortran -fopenmp   -L/Volumes/data/tiziano/cp2k/lib/minimal/sdbg -o /Volumes/data/tiziano/cp2k/exe/minimal/grid_miniapp.sdbg grid_miniapp.o  -lcp2kgrid -lcp2kgridhybrid -lcp2kgridcpu -lcp2kgridref -lcp2kgridcommon -lcp2ksubsys -lcp2kfm -lcp2kao -lcp2kinput -lcp2kpw -lcp2kfft -lcp2kcommon -lcp2kmpiwrap -lcp2kfpga -lcp2kbase -L/Volumes/data/tiziano/cp2k/lib/minimal/sdbg/exts/dbcsr -ldbcsr -llapack -lblas
ld: archive has no table of contents file '/Volumes/data/tiziano/cp2k/lib/minimal/sdbg/libcp2kgridhybrid.a' for architecture x86_64
collect2: error: ld returned 1 exit status
make[3]: *** [/Volumes/data/tiziano/cp2k/exe/minimal/grid_miniapp.sdbg] Error 1
make[2]: *** [all] Error 2
make[1]: *** [sdbg] Error 2
make: *** [all] Error 2
```

Since there's no CUDA support, the `.a` files of `grid/hybrid` have actually no symbols:

```console
$ nm lib/minimal/sdbg/libcp2kgridhybrid.a
lib/minimal/sdbg/libcp2kgridhybrid.a(grid_collocate_hybrid.o):
no symbols

lib/minimal/sdbg/libcp2kgridhybrid.a(grid_integrate_hybrid.o):
no symbols
```

... and as it seems `ar` (respectively `ranlib`) from Xcode has a problem with linking empty `.a` files: adding a dummy function which is not "ifdefed" out to `hybrid/grid_collocate_hybrid.c` makes the error go away.

The same applies for `libcp2kfpga.a`.

**Comment by oschuett** [comment]
We are [currently](https://github.com/cp2k/cp2k/blob/master/arch/Darwin-gfortran.psmp#L8) using `ar -r`. According to ranlib's [manpage](https://www.freebsd.org/cgi/man.cgi?query=ranlib) the `-r` flag updates the archive symbol table only if it exists. So, maybe adding `-s` helps?

**Comment by dev-zero** [comment]
Maybe, but the problem is not that the source files wouldn't exist, they are simply empty (in the sense of not containing any symbols).

**Comment by oschuett** [comment]
Yes, the empty source files are certainly the root cause. However, I'd like to avoid adding dummy functions if possible. We should instead try to convince either `ranlib` to create an empty table of contents or `ld` to ignore a missing table.

**Comment by oschuett** [comment]
This seems to have been resolved because our new [test for macOS](https://dashboard.cp2k.org/archive/darwin-gnu-arm64-psmp/index.html) builds successfully.
