### ISSUE TITLE
Possible parallel build issue: Error: Unclassifiable statement at (1)

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#1316]
With the following arch file as my `Darwin-gfortran.ssmp` on a MacBook Air with an M1 CPU:

```
CC       = gcc-10
FC       = gfortran
LD       = gfortran
AR       = ar -r
RANLIB   = ranlib
DFLAGS   = -D__NO_STATM_ACCESS -D__ACCELERATE -D__LIBXC -D__FFTW3
CFLAGS   = -std=c11 -fopenmp -O2
FCFLAGS  = -I$(LIBXC_INCLUDE_DIR) -fopenmp -funroll-loops \
           -ftree-vectorize -ffree-form -O2 $(DFLAGS)
LDFLAGS  = $(FCFLAGS)
LIBS     = -framework Accelerate \
           -L$(LIBXC_LIB_DIR) -lxcf03 -lxc -lfftw3_omp -lfftw3
```

I could trigger the issue reported in the Google Groups here:

https://groups.google.com/g/cp2k/c/GJYQd6kh0g4/m/xbkVuPwoDQAJ
([direct link to log file](https://04325810545079678207.googlegroups.com/attach/d28fcb815b9c5/log?part=0.1&view=1&vt=ANaJVrHjmCEGwym-utixsOulhnEcoMbQmhHWZMmJX5KFSieOBZa_F7W7Qv55XIFnsBT5BH3TzJPQ55pIlloUUWIty4o8q8dzbXtUjTqlzdp0SF8T5MlwtjY))

```console
$ make ARCH=Darwin-gfortran VERSION=ssmp -j
[...]
gfortran -c -I/opt/homebrew/include -fopenmp -funroll-loops -ftree-vectorize -ffree-form -O2 -std=f2008 -D__NO_STATM_ACCESS -D__ACCELERATE -D__LIBXC -D__FFTW3 -D__COMPILE_ARCH="\"Darwin-gfortran\"" -D__COMPILE_DATE="\"Mon Jan 18 13:00:51 CET 2021\"" -D__COMPILE_HOST="\"Administrators-MacBook-Air.local\"" -D__COMPILE_REVISION="\"git:42512f7\"" -D__DATA_DIR="\"/Users/admin/Desktop/cp2k/data\"" -D__SHORT_FILE__="\"semi_empirical_int_ana.F\"" -I'/Users/admin/Desktop/cp2k/src/' -I'/Users/admin/Desktop/cp2k/obj/Darwin-gfortran/ssmp/exts/dbcsr' semi_empirical_int_ana.F90 
/Users/admin/Desktop/cp2k/src/semi_empirical_int_debug.F:19:1:

   19 | SUBROUTINE check_rotmat_der(sepi, sepj, rjiv, ij_matrix, do_invert)
      | 1
Error: Unclassifiable statement at (1)
/Users/admin/Desktop/cp2k/src/semi_empirical_int_debug.F:21:22:

   21 |    USE kinds, ONLY: dp
      |                      1
Error: USE statement at (1) cannot follow PRIVATE statement at (2)
/Users/admin/Desktop/cp2k/src/semi_empirical_int_debug.F:22:45:

   22 |    USE semi_empirical_int_utils, ONLY: rotmat
      |                                             1
Error: USE statement at (1) cannot follow PRIVATE statement at (2)
/Users/admin/Desktop/cp2k/src/semi_empirical_int_debug.F:27:54:

   27 |                                    se_int_control_type
      |                                                      1
Error: USE statement at (1) cannot follow PRIVATE statement at (2)
/Users/admin/Desktop/cp2k/src/./base/base_uses.f90:13:53:

   13 |                                              timestop
      |                                                     1
Error: USE statement at (1) cannot follow PRIVATE statement at (2)
/Users/admin/Desktop/cp2k/src/semi_empirical_int_debug.F:29:16:
...
```

Restarting the compilation by simply running `make ARCH=Darwin-gfortran VERSION=ssmp` (without the `-j`) did not work, I ran into the very same issue again.

Rebuilding everything from scratch without `-j` after a `make ARCH=Darwin-gfortran VERSION=ssmp clean` worked.

**Comment by oschuett** [comment]
Could be a corrupted `.mod` file. Was the previous build interrupted?

**Comment by dev-zero** [comment]
That's what I thought at first since the build failed linking one target and I interrupted it then.
But then I tried to recover first with a `... clean` and then a `... realclean`, before rerunning the build with `-j`, always ending up at the same error.

**Comment by oschuett** [comment]
[semi_empirical_int_debug.F](https://github.com/cp2k/cp2k/blob/master/src/semi_empirical_int_debug.F) is another one of those circular dependencies, ie. it's not a Fortran Module.

**Comment by dev-zero** [comment]
Got this now confirmed on an Intel macOS Catalina machine with a gcc+gfortran from MacPorts. Might be OS-related but don't see yet how.

**Comment by fxcoudert** [comment]
We're seeing this in Homebrew too: https://github.com/Homebrew/homebrew-core/pull/78753
It's been several cp2k versions that we can't compile, the last one that built for us was 6.1

**Comment by shiozaki** [comment]
It's an old issue but I just observed that, so commenting here. As of version 8.2, semi_empirical_int_debug.F is causing the same kind of issues on my MacOS 10.15.7 (openmpi, gcc11, etc).

This issue seems to stem from the fact that MacOS does not distinguish between small and capital letters in the filename, and that the CP2K source tree has both semi_empirical_int_debug.F and semi_empirical_int_debug.f90. The .F file is converged to .F90 file when it is compiled in the object directory, which is then somehow picked up at the include statement. (files in the object directory supercedes those in the src).

At leaset as far as I see, the easy fix is to simply remove the semi_empirical_int_debug.F file from the source. Perhaps renaming it works also.
