### ISSUE TITLE
calculate_xc_2nd_deriv_atom references unassociated pointer drho_h

### ISSUE THREAD

**Issue by vzecca** [cp2k/cp2k#1327]
Issue #1289 should be reopened because tha same bug resurfaced at line 694 of qs_vxc_atom.F

 CALL fill_rho_set(rho_set_h, lsd, nspins, needs, rho_h, drho_h, rtau, na, ir)

where drho_h is unassociated.

**Comment by dev-zero** [comment]
Duplicate of #1289
