### ISSUE TITLE
toolchain: elpa fails to build without `python` binary

### ISSUE THREAD

**Issue by akkadaska** [cp2k/cp2k#1329]
I tried to install cp2k to our workstation.

The problem happend when I install elpa and other libraries by toolchain with following command:

`./install_cp2k_toolchain.sh --math-mode=mkl --mpi-mode=intelmpi --with-cmake=install --with-libxsmm=install --with-mkl=system --with-fftw=install --with-reflapack=no --with-scalapack=no --with-sirius=no --with-cosma=no --with-plumed --with-gsl=install --with-hdf5=install --with-superlu=install --with-libvori=no -j 4`

'male.log' of elpa said `/usr/bin/env: ‘python’: Permission denied` because my workstation has python at `/usr/bin/python3`, and  it works only with`python3` command, not `python` command.

It seems that it comes from './build/elpa-2020.05.001/remove_xcompiler'.

To recognize the python path, I tried: 
- run `export PYTHON="/usr/bin/python3"` before install: failure. 
- change script in 'remove_xcompiler': failre because it generates every time.
- add `export PYTHON="/usr/bin/python3"` to configure of elpa: failure because it also regenerate.
- add `export PYTHON="/usr/bin/python3"` to install_elpa.sh: failure.
- add `export PYTHON="/usr/bin/python3"` to install_cp2k_toolchain.sh: failure.

Dose anybody know how to set python path when installing elpa by toolchain?

**Comment by dev-zero** [comment]
Verified, the `remove_xcompiler` in ELPA still refers to `python`.

@akkadaska the easiest workaround for now would be to provide a `python` binary somewhere, which can be a symlink to `/usr/bin/python3`. Without rebuilding everything and since I don't know which paths you have in your `$PATH` environment variable, I believe creating a symlink in the `cmake` bin folder might be the easiest:

```console
$ cd tools/toolchain
$ ln -s /usr/bin/python3 install/cmake-3.18.0/bin/python
```

and then run your `install_cp2k_toolchain.sh` command again to continue.

**Comment by akkadaska** [comment]
Looks good to me. By creating symlink in cmake bin folder, it recognize the python symlink and `remove_xcompiler` runs.

Since it still fails to build without binary, I don't close this issue. If it should be closed, please do so.

Thank you very much @dev-zero .

**Comment by dev-zero** [comment]
> Since it still fails to build without binary, I don't close this issue. If it should be closed, please do so.

We still need to fix it properly, you are right to leave it open.

> Thank you very much @dev-zero .

お力になれて幸いです

**Comment by oschuett** [comment]
We should just upgrade to ELPA 2020.11 where they [officially](https://gitlab.mpcdf.mpg.de/elpa/elpa/-/releases#new_release_2020.11.001) switched to Python 3.

**Comment by dev-zero** [comment]
@oschuett sure, please go ahead, might also need a patch/minor release for v8.1
