### ISSUE TITLE
Move cubecruncher into its own repository

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#133]
The [cubecruncher](https://github.com/cp2k/cp2k/blob/master/tools/cubecruncher/) is a very useful tool that is completely independent from the CP2K code base. Hence, with a bit of love (tests and [docu](https://www.cp2k.org/tools:cubecruncher)) it could be made available to a larger audience. Eventually, it might even get included in Debian / Fedora.

This would also make for a good intern or [GSOC](https://summerofcode.withgoogle.com) project.

**Comment by marci73** [comment]
There are already other tools of this type, i.e., handling cube files for analysis or visualisation. 
The cubecruncher is neither more general nor better. I would rather say that it is clearly oriented to what is available as cp2k output. 
I have the feeling that the effort to make it a meaningful standalone tool is not worth, and would make it less flexible for ad hoc modifications.

**Comment by oschuett** [comment]
Ok, makes sense. Then let's leave it as is.
