### ISSUE TITLE
toolchain: elpa failed to complete remove_xcompiler

### ISSUE THREAD

**Issue by akkadaska** [cp2k/cp2k#1330]
I tried to install elpa to my workstation with following command:

`./install_cp2k_toolchain.sh --math-mode=mkl --mpi-mode=intelmpi --with-cmake=install --with-libxsmm=install --with-mkl=system --with-fftw=install --with-reflapack=no --with-scalapack=no --with-sirius=no --with-cosma=no --with-plumed --with-gsl=install --with-hdf5=install --with-superlu=install --with-libvori=no -j 4`

and it failed with an error assosiated with `./build/elpa-2020.05.001/remove_xcompiler`.

The make.log of elpa says: 
`...`
` F90 MOD  [libelpatest_openmp_la] ../test/shared/test_output_type.F90`
`  F90 DEPS /{workdir}/cp2k/tools/toolchain/build/elpa-2020.05.001/build/.fortran_dependencies/dependencies.mk`
`  PPFC     src/general/libelpa_openmp_private_la-elpa_utilities.lo`
`Traceback (most recent call last):`
`  File "../remove_xcompiler", line 6, in <module>`
`    os.execvp(args[0], args[0:])`
`  File "/usr/lib64/python3.6/os.py", line 559, in execvp`
`    _execvpe(file, args)`
`  File "/usr/lib64/python3.6/os.py", line 583, in _execvpe`
`    exec_func(file, *argrest)`
`FileNotFoundError: [Errno 2] No such file or directory`
`make[1]: *** [Makefile:15157: src/general/libelpa_openmp_private_la-elpa_utilities.lo] Error 1`
`make[1]: Leaving directory '/{workdir}/cp2k/tools/toolchain/build/elpa-2020.05.001/build'`
`make: *** [Makefile:11902: all] Error 2`

Why dose it access nonexistent file/directory? And how to avoid it?

Please note that I did some trick to avoid a certain error which mentioned issue #1329 .
And also note that even editing 'remove_xcompiler' may not make sence since it will regenerate when installing, please.

**Comment by oschuett** [comment]
I think the symlink trick did not work because the scripts are [not ready](https://gitlab.mpcdf.mpg.de/elpa/elpa/-/commit/5e271fd977adf4dd6d7b21eb60e94226d2eec147).

Since this is still problem #1329, let's continue the discussion there.
