### ISSUE TITLE
SIRIUS regresssion tests fail with armv7l-gnu

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#1340]
The SIRIUS regression tests [fail with armv7l-gnu](https://www.cp2k.org/static/regtest/trunk/Linux-armv7l-gnu-regtest/psmp/regtest-0) since the toolchain update to libxc 5.1.0 and elpa-2020.11.001. It seems that there are memory access issues:
``` ============================= SIRIUS UPDATE CONTEXT============================
 ==================== SIRIUS UPDATE CONTEXT FINISHED============================

=== Warning at line 145 of file /home/pi/github/cp2k/tools/toolchain/build/SIRIUS-7.0.0/src/density/density.cpp ===
wrong initial charge density
  integral of the density : 18.9999989125
  target number of electrons : 19


=== Warning at line 797 of file /home/pi/github/cp2k/tools/toolchain/build/SIRIUS-7.0.0/src/potential/xc.cpp ===
Interstitial charge density has negative values
most negatve value : -1.29593


Program received signal SIGBUS: Access to an undefined portion of a memory object.

Backtrace for this error:

Program received signal SIGBUS: Access to an undefined portion of a memory object.
```

**Comment by fstein93** [comment]
Can you check where the memory access issues occur?

**Comment by mkrack** [comment]
I tried valgrind, but there is no more information than in the regression output file. I will rebuild the whole toolchain. Maybe, sirius was built with the wrong libxc version.

**Comment by mkrack** [comment]
A rebuilt of the toolchain resolved the problem.

**Comment by ltalirz** [comment]
I'm trying to add an MPI-enabled executable to the cp2k conda package and I'm seeing the same error `Access to an undefined portion of a memory object` in the regtests of the MPI executable on OSX (linux runs fine, also osx openmp-only runs fine, see [here](https://github.com/conda-forge/cp2k-feedstock/pull/11#issuecomment-817101976)).

Any ideas what might be the cause?

archfile used:
```
FC          = mpifort
CPP         = $(CC)-cpp
CPPFLAGS   += -C -P -traditional -D__NO_IPI_DRIVER -nostdinc
AR         += -r
DFLAGS      = -D__NO_STATM_ACCESS -D__ACCELERATE -D__FFTW3 -D__LIBXSMM -D__parallel -D__SCALAPACK
FCFLAGS     = $(FFLAGS) -I $(PREFIX)/include -fbacktrace -ffree-form -fimplicit-none -std=f2008 -fopenmp $(DFLAGS)
LIBS        = -framework Accelerate -lfftw3 -lfftw3_omp -lxsmmf -lxsmm -ldl -lscalapack

# need to use mpifort also for linking
LD          = $(FC)
LDFLAGS    += -lgfortran -lc -lgomp
```

Hm... I wonder whether the threaded `-framework Accelerate` plays well with MPI?
