### ISSUE TITLE
Elpa-2020.11.001 could not pass through under gnu with devtool-gcc-9.3.1 on centos 7.9 with toolchain method

### ISSUE THREAD

**Issue by alas-go** [cp2k/cp2k#1345]
it reports fortran did not supoort mpi-mode.  do you have any suggestion?

[config.log](https://github.com/cp2k/cp2k/files/5908297/config.log)
[configure.log](https://github.com/cp2k/cp2k/files/5908298/configure.log)

**Comment by oschuett** [comment]
This seems to be the same issue you had with ELPA 2020.05. So, let's continue the discussion at #1275.

**Comment by alas-go** [comment]
this time, it was compiled through devtoolset-gcc 9.3.1, openmpi-4.0.5 and openblas,  not intelmpi.

**Comment by oschuett** [comment]
Fair point. Still, I think your three issues are very related and we should therefore bundle them.

I only now realized that by _devtools_ you were referring to [this product](https://developers.redhat.com/products/developertoolset/overview). So, I've renamed #1275 accordingly.

**Comment by alas-go** [comment]
Yeah, that is it . centos /redhat 7 use  gcc-4.8.5 as the default edtion of fortran / c&c++. for newer edtion, devtoolset has been developed as convienence.

Do you develop and test cp2k-master based on fedora 33 or ubuntu 20.1?  the default edtion of gcc for cp2k 8.1 is  10.2, which  is employed by the referred two open OS.

> 
> 
> Fair point. Still, I think your three issues are very related and we should therefore bundle them.
> 
> I only now realized that by _devtools_ you were referring to [this product](https://developers.redhat.com/products/developertoolset/overview). So, I've renamed #1275 accordingly.

**Comment by oschuett** [comment]
We mostly use Ubuntu but we have one dashboard [test](https://dashboard.cp2k.org/archive/fedora-psmp/index.html) for Fedora. However, it does not use the devtools, but builds GCC from scratch. Essentially, we are using [this Dockerfile](https://github.com/cp2k/cp2k/blob/master/tools/toolchain/Dockerfile) with [Fedora 33](https://github.com/cp2k/cp2k-ci/blob/master/backend/cp2k-ci.conf#L13) as base image. I guess, one could add a test that uses more of the Fedora packages similar to [Dockerfile.ubuntu_nompi](https://github.com/cp2k/cp2k/blob/master/tools/toolchain/Dockerfile.ubuntu_nompi), but it's not gonna be me.
