### ISSUE TITLE
toolchain: building libint 2.6.0 fails on CPUs with FMA4 due to wrong/missing intrinsics

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#1346]
from the `make.log`:

```
[...]
CXX
src/CR_DerivGaussP0InBra_aB_d001__0__d__1___TwoPRep_s__0__s__1___Ab__up_0.lo
CXX
src/CR_DerivGaussP0InBra_aB_d001__0__f__1___TwoPRep_s__0__s__1___Ab__up_0.lo
CXX
src/CR_DerivGaussP0InBra_aB_d001__0__g__1___TwoPRep_s__0__s__1___Ab__up_0.lo
CXX
src/CR_DerivGaussP0InBra_aB_d001__0__h__1___TwoPRep_s__0__s__1___Ab__up_0.lo
CXX
src/CR_DerivGaussP0InBra_aB_d001__0__i__1___TwoPRep_s__0__s__1___Ab__up_0.lo
In file included from ./include/libint2/util/vector.h:186,
                 from ./include/libint2_types.h:24,
                 from ./include/libint2/util/generated/libint2_types.h:29,
                 from ./include/libint2.h:35,
                 from
src/CR_DerivGaussP0InBra_aB_d001__0__g__1___TwoPRep_s__0__s__1___Ab__up_0.cc:21:
./include/libint2/util/vector_x86.h: In function
‘libint2::simd::VectorAVXFloat
libint2::simd::fma_plus(libint2::simd::VectorAVXFloat,
libint2::simd::VectorAVXFloat, libint2::simd::VectorAVXFloat)’:
./include/libint2/util/vector_x86.h:1106:11: error: ‘_mm256_facc_ps’ was
not declared in this scope; did you mean ‘_mm256_macc_ps’?
 1106 |     d.d = _mm256_facc_ps(a.d, b.d, c.d);
      |           ^~~~~~~~~~~~~~
      |           _mm256_macc_ps
In file included from ./include/libint2/util/vector.h:186,
                 from ./include/libint2_types.h:24,
                 from ./include/libint2/util/generated/libint2_types.h:29,
                 from ./include/libint2.h:35,
                 from
src/CR_DerivGaussP0InBra_aB_d001__0__f__1___TwoPRep_s__0__s__1___Ab__up_0.cc:21:
./include/libint2/util/vector_x86.h: In function
‘libint2::simd::VectorAVXFloat
libint2::simd::fma_plus(libint2::simd::VectorAVXFloat,
libint2::simd::VectorAVXFloat, libint2::simd::VectorAVXFloat)’:
./include/libint2/util/vector_x86.h:1106:11: error: ‘_mm256_facc_ps’ was
not declared in this scope; did you mean ‘_mm256_macc_ps’?
 1106 |     d.d = _mm256_facc_ps(a.d, b.d, c.d);
      |           ^~~~~~~~~~~~~~
      |           _mm256_macc_ps 
[...]
```

Inspecting `vector_x86.h` reveals that the stated intrinsics are used when `__FMA4__` is defined, which is most likely only the case on AMD Bulldozer/Piledriver (Opteron).
Unfortunately I couldn't find any references to the specified intrinsics so far.

Furthermore (and here is the problem): it seems that FMA4 on Zen is still available, but seems to be broken and while it doesn't get exposed via `cpuid` there are some binutils around which still enable it. See the [wikipedia entry](https://en.wikipedia.org/wiki/FMA_instruction_set) for an overview and the respective links.

While it currently seems that when `__FMA4__` is set, the build will fail, there is also a chance that it could compile but return wrong results when running on a Zen, hence we should add `-mno-fma4` if we detect that `-fma4` is added as part of `-march=native` to prevent that from happening and fix the build on platforms which would actually support FMA4.
As we have seen in libvori with adding `-mno-avx` we can't simply add `-mno-fma4` all the time.

* [ ] fix the issue in the toolchain
* [ ] report to libint upstream
* [ ] fix/report in Spack (maybe not affected since they maintain their own list of flags for each microarch) and Easybuild

**Comment by oschuett** [comment]
Maybe we can use [check_gcc_flag](https://github.com/cp2k/cp2k/blob/master/tools/toolchain/scripts/tool_kit.sh#L417) to check if `-mno-fma4` is available.

**Comment by oschuett** [comment]
This issue seems to only affect old Opteron CPUs. Since no one has commented on this in the past ~2 years, I guess there are not many of those left anymore.
