### ISSUE TITLE
regtest: use TEST_DIRS for unittests to avoid running leftover tests and support labels

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#1350]
I get in a `make test` run:

```
--------------------------------------------------------------------------
[...]
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
/data/tiziano/cp2k.clean/regtesting/local/sdbg/TEST-local-sdbg-2021-02-03_14-22-31/UNIT/grid_collocate_unittest.out
Could not open task file: /data/tiziano/cp2k.clean/regtesting/local/sdbg/../../../src/grid/sample_tasks/collocate_ortho_density_l0000.task
EXIT CODE:  1  MEANING:  RUNTIME FAIL
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
[...]
```

That binary was renamed some time ago. Unfortunately contrary to our other regtests, unittests are just discovered by convention rather than by explicitly registering them.

This breaks the workflow for people switching branches regularly and makes for example a `git bisect` more difficult since you have to explicitly clean the exe-dir.

**Comment by dev-zero** [comment]
The problem is that you have to know about it, otherwise you'll waste time on investigating why suddenly a unittest fails which worked before.

**Comment by oschuett** [comment]
Well, I guess it would be rather easy to rip out the [discovery](https://github.com/cp2k/cp2k/blob/master/tools/regtesting/do_regtest#L952-L966) part and add the unit tests to [TEST_DIRS](https://github.com/cp2k/cp2k/blob/master/tests/TEST_DIRS) instead. This would have the added benefit that we could add tags to them.
