### ISSUE TITLE
toolchain: COSMA picks up system-MPI instead of builtin/provided one

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#1351]
a user reported the following failure when building COSMA with the toolchain:

```
[...]
/home/user/Software_2021/Source/cp2k-8.1/tools/toolchain/build/cosma-2.2.0/libs/grid2grid/src/grid2grid/mpi_type_wrapper.hpp:

In static member function ‘static ompi_datatype_t*
grid2grid::mpi_type_wrapper<std::complex<double> >::type()’:
/home/user/Software_2021/Source/cp2k-8.1/tools/toolchain/build/cosma-2.2.0/libs/grid2grid/src/grid2grid/mpi_type_wrapper.hpp:24:41:

error: ‘MPI_CXX_DOUBLE_COMPLEX’ was not declared in this scope; did you
mean ‘MPI_C_DOUBLE_COMPLEX’?
    24 |     static MPI_Datatype type() { return
MPI_CXX_DOUBLE_COMPLEX; }
       |                                         ^~~~~~~~~~~~~~~~~~~~~~
       |                                         MPI_C_DOUBLE_COMPLEX
/home/user/Software_2021/Source/cp2k-8.1/tools/toolchain/build/cosma-2.2.0/libs/grid2grid/src/grid2grid/mpi_type_wrapper.hpp:

In static member function ‘static ompi_datatype_t*
grid2grid::mpi_type_wrapper<std::complex<float> >::type()’:
/home/user/Software_2021/Source/cp2k-8.1/tools/toolchain/build/cosma-2.2.0/libs/grid2grid/src/grid2grid/mpi_type_wrapper.hpp:29:41:

error: ‘MPI_CXX_FLOAT_COMPLEX’ was not declared in this scope; did you
mean ‘MPI_C_FLOAT_COMPLEX’?
    29 |     static MPI_Datatype type() { return MPI_CXX_FLOAT_COMPLEX; }
       |                                         ^~~~~~~~~~~~~~~~~~~~~
       |                                         MPI_C_FLOAT_COMPLEX
/home/user/Software_2021/Source/cp2k-8.1/tools/toolchain/build/cosma-2.2.0/libs/grid2grid/src/grid2grid/mpi_type_wrapper.hpp:

In static member function ‘static ompi_datatype_t*
grid2grid::mpi_type_wrapper<bool>::type()’:
/home/user/Software_2021/Source/cp2k-8.1/tools/toolchain/build/cosma-2.2.0/libs/grid2grid/src/grid2grid/mpi_type_wrapper.hpp:64:41:

error: ‘MPI_CXX_BOOL’ was not declared in this scope; did you mean
‘MPI_C_BOOL’?
    64 |     static MPI_Datatype type() { return MPI_CXX_BOOL; }
       |                                         ^~~~~~~~~~~~
       |                                         MPI_C_BOOL
make[2]: ***
[libs/grid2grid/src/grid2grid/CMakeFiles/grid2grid.dir/transform.cpp.o]
Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [libs/grid2grid/src/grid2grid/CMakeFiles/grid2grid.dir/all]
Error 2
make[1]: *** Waiting for unfinished jobs....
[ 28%] Linking CXX static library liboptions.a
[ 28%] Built target options
make: *** [all] Error 2 
```

This error gets triggered by an older MPI which doesn't have the MPI_CXX_BOOL (check the MPI standards/OpenMPI errata). The interesting thing is that the user actually provided a newer OpenMPI release:

```
user@host:~> which mpicc
/home/user/Software_2021/openmpi_4.1.0/bin/mpicc 
```

And looking in the `cmake.log` reveals:

```
-- The CXX compiler identification is GNU 9.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler:
/home/user/Software_2021/gcc_9.3.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found MPI_CXX: /usr/lib64/mpi/gcc/openmpi/lib64/libmpi_cxx.so (found
version "2.1")
-- Found MPI: TRUE (found version "2.1") 
```

For some reason not all packages (in this case COSMA) in the toolchain pick up an MPI implementation just from the `$PATH`. This can potentially be very bad as packages may enable different kind of codepaths for different MPI implementations and versions, leading to link- or runtime failures (at best) or data corruption (at worst) when built against one MPI version but link against a different one.

We need to:

* [ ] investigate why COSMA in this case doesn't pick up the MPI from `$PATH`, likely it is because CMake requires to explicitly have CC/FC/CXX set to ensure it picks up the right MPI implemention, at least that's what we figured out for [DBCSR Cmake](https://cp2k.github.io/dbcsr/develop/page/2-user-guide/1-installation/1-cmake-build-recipes.html)
* [ ] whether other packages in the toolchain suffer from the same issue
* [ ] check in the respective MPI install scripts that the vars are set and the provided implementation is usable, if the user needs to set other paths as well

This may be related to other build issues we see, like #1274, #1275

**Comment by oschuett** [comment]
While working on ELPA I noticed that quotes around the library directory don't (always) work. In my case `-L${mkl_lib_dir}` worked, but `-L'${mkl_lib_dir}'` didn't. Since we generally use those quotes in the toolchain, this might explain why sometimes the wrong libraries are picked up.

**Comment by kabicm** [comment]
Do you think the problem is in the quotes, as suggested by @oschuett or on the COSMA side? I just want to collect and fix all the problems in the next release that we are preparing soon.
