### ISSUE TITLE
[toolchain] Issue on Debian 8

### ISSUE THREAD

**Issue by mretegan** [cp2k/cp2k#138]
I get this error when running the toolchain script.

`cp2k-6.1.0/tools/toolchain/scripts/install_openmpi.sh: line 45: [: 19-18+deb8u10): integer expression expected`

Full output of the `ldd` command:

```
ldd (Debian GLIBC 2.19-18+deb8u10) 2.19
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by dev-zero** [comment]
If you don't want to use the latest git version of CP2K (please make sure to read the instructions in the `README.md` if you do), you can also apply the fix manually to your version using https://github.com/cp2k/cp2k/commit/4ed24fb34dd79fd55e9045546a90279098d8bd73.patch

**Comment by dev-zero** [comment]
Thanks for the report!
