### ISSUE TITLE
cp2k-develop version report  error while loading shared libraries: libplumedKernel.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by alas-go** [cp2k/cp2k#1381]
everything goes well when compiling and make install include make test. all tests has been passed when make test.
cp2k.psmp --9.0 reports  an error while loading shared libraries: libplumedKernel.so: cannot open shared object file: No such file or directory. I don;t know what wrong.

[local.psmp.txt](https://github.com/cp2k/cp2k/files/6056882/local.psmp.txt)

$ cp2k.psmp --version
 CP2K version 9.0 (Development Version)
 Source code revision git:122ed37
 cp2kflags: omp libint fftw3 libxc elpa parallel mpi3 scalapack quip xsmm plumed2 spglib sirius libvori libbqb
 compiler: GCC version 9.3.0

mpirun -n 4 cp2k.psmp -i cp2k.inp -o > cp2k.out 2> cp2k.err
cp2k.psmp: error while loading shared libraries: libplumedKernel.so: cannot open shared object file: No such file or directory
cp2k.psmp: error while loading shared libraries: libplumedKernel.so: cannot open shared object file: No such file or directory
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
cp2k.psmp: error while loading shared libraries: libplumedKernel.so: cannot open shared object file: No such file or directory
cp2k.psmp: error while loading shared libraries: libplumedKernel.so: cannot open shared object file: No such file or directory

**Comment by dev-zero** [comment]
If the dependencies are built with the toolchain, did you do `source tools/toolchain/install/setup` as instructed by the toolchain?

Can you please post the complete output of the following:

```
exe/.../cp2k.psmp --version  # substitute the path to your executable
ldd exe/.../cp2k.psmp # again, substitute correct path to your executable
env
```

**Comment by alas-go** [comment]
I did source the setup before make local arch. these below are for your information. 
tommorow i upload them again after it has been re-made and tested.

[cp2k-version.txt](https://github.com/cp2k/cp2k/files/6056914/cp2k-version.txt)
[ldd-check.txt](https://github.com/cp2k/cp2k/files/6056915/ldd-check.txt)

**Comment by alas-go** [comment]
here, the error has been reproduced.

[cp2k--version.txt](https://github.com/cp2k/cp2k/files/6062074/cp2k--version.txt)
[ldd-cp2k.psmp.txt](https://github.com/cp2k/cp2k/files/6062076/ldd-cp2k.psmp.txt)

**Comment by dev-zero** [comment]
@alas-go can you please also give the output of the `env` command (as written above), after running `source .../setup` ?

**Comment by alas-go** [comment]
sorry, it may take a long time. I install OS on a local physical machine. two days ago, I changed to centos/redhat 7.9 for running materials studio 2017.

last time, three days ago, I tried to install cp2k-master20210327 with intel mkl 2020.4 and openmpi 4.0.5, it is ok to install every default package and passed "make test" command but reported errors about cp2k.F when mpirun a script. it happened on several OS like fedora 33, redhat 8.3 and centos 8.3 on my local equipment Xeon 8273 and Rack motherboard. is it about compatible between code and hardware?

**Comment by alas-go** [comment]
@dev-zero  sorry, it may take a long time. I install OS on a local physical machine. two days ago, I changed to centos/redhat 7.9 with python 2 as default for running materials studio 2017. as you know, the development version of cp2k use python 3 as default.

last time, three days ago, I tried to install cp2k-master20210327 with intel mkl 2020.4 and openmpi 4.0.5, it is ok to install every default package and passed "make test" command but reported errors about cp2k.F when mpirun a script. it happened on several OS like fedora 33, redhat 8.3 and centos 8.3 on my local equipment Xeon 8273 and Rack motherboard. is it about compatible between code and hardware?

**Comment by Charlaiz** [comment]
[ldd_cp2k.txt](https://github.com/cp2k/cp2k/files/6382804/ldd_cp2k.txt)
Hello,

I encounter a similar issue. Compilation via the toolchain didn`t give any trouble, I also followed all instructions. When trying to call the executable (e.g. cp2k.sopt --version) i get this error:  _error while loading shared libraries: libplumedKernel.so: cannot open shared object file: No such file or directory_

I add the output of ldd cp2k.psmp in the attachment. it says **libplumedKernel.so => not found** . it seems like i am missing a library or something?

Thank you very much

**Comment by dev-zero** [comment]
@KarelAsselman did you run `source tools/toolchain/install/setup`? Can you please post the output of `env`? And the output of `find . -iname libplumedKernel.so`?

**Comment by Charlaiz** [comment]
Hello,
I did run the source command, but it appears I did so from a wrong directory (didn`t give me any error then so i figured it was correct). now cp2k.sopt --version command works fine, perhaps this has completely solved the problem. I will update if i encounter the same problem again. Thank you!
[env.txt](https://github.com/cp2k/cp2k/files/6382898/env.txt)

**Comment by Charlaiz** [comment]
EDIT: am i supposed to run source tools/toolchain/install/setup every time before i run cp2k from a different directory?

**Comment by dev-zero** [comment]
> EDIT: am i supposed to run source tools/toolchain/install/setup every time before i run cp2k from a different directory?

I am not sure what you mean by "run cp2k from a different directory", but: you have to run `source tools/toolchain/install/setup` once in a fresh shell before running any CP2K executable from that same directory (in other words a CP2K binary using that toolchain).

**Comment by Charlaiz** [comment]
Understood! I just tested an example input file from the website and works perfectly.
Thanks a lot for the quick assistance
