### ISSUE TITLE
XAS: CP2K won't complete the XAS calculation

### ISSUE THREAD

**Issue by akkadaska** [cp2k/cp2k#1383]
I want to calculate XAS spectra by Gaussian and Augmented Plane Wave Method. I found [official tutorial] (https://www.cp2k.org/exercises:2017_uzh_cp2k-tutorial: gapw) and run cp2k with the input files of * Task 2 : compute the XAS spectrum of ice-1h *, which is not needed to edit. However, cp2k couldn't complete the calculation. Here is what I did.
## comment out `MAP_CONSISTENT`
Without any editing of the input files, cp2k said it didn't know `MAP_CONSISTENT` and aborted the calculation. So I commented out` MAP_CONSISTENT`.
## Aborted with segmentation fault error
Next, it stopped with segmentation fault error. In my workstation, stack size is limited within 8MB by default. So next, I made the stack size unlimited, and run again.
Then, it didn't stop with the error. However, it didn't finish the calculation even after 1 day progress. The system showed no error messase in the log and did not sleep. It had been calculationg sometiong.
According to the output of cp2k, it calculated up to `XAS_TP_SCF WAVEFUNCTION OPTIMIZATION`. The output was finished with following line:
`Calculation of 7 additional virtual states of the subspace complementary to the lowest 160 states`.
`ice1h-xas_at * .spectrum` files did not be generated.

I think this was caused by some cp2k's bug. Please verify this error, please.

**Comment by oschuett** [comment]
This seems more like a usage problem, for which we have the [forum](https://www.cp2k.org/howto:forum).
