### ISSUE TITLE
Cosma compilation with toolchain

### ISSUE THREAD

**Issue by PascalSalzbrenner** [cp2k/cp2k#1397]
Dear CP2K developers,

I am trying to set up the prerequisites for compiling CP2K 8.1 with the toolchain, but am having two (connected) problems with Cosma. The first is that I am setting `--with-cosma=no`, but despite this, the toolchain attempts to install Cosma. This gives rise to the second issue, which is the Cosma install failing, with the following error being the initial one: `/home/pts28/mtg_bin/cp2k-8.1/tools/toolchain/build/cosma-2.2.0/libs/grid2grid/src/grid2grid/scalapack_layout.cpp(68): error: copy-list-initialization cannot use a constructor marked "explicit"
      return {idx_block_proc * block_dimension + idx_in_block, owner};`

I would be grateful for any help and am happy to provide more details if needed. Apologies if this isn't the right place to raise this issue.

**Comment by mkrack** [comment]
Concerning your first problem, SIRIUS requires COSMA and the default for --with-sirius is install. Thus adding --with-sirius=no might help unless you want to have SIRIUS and/or COSMA installed.

**Comment by PascalSalzbrenner** [comment]
Thank you very much for your response, the toolchain worked after adding --with-sirius=no.

**Comment by mtaillefumier** [comment]
COSMA is not a hard dependency for SIRIUS. The toolchain imposes this but it is not requested. I will prepare a patch that fixes this issue so that SIRIUS can be compiled without explicit need of cosma.

**Comment by kabicm** [comment]
Hi @PascalSalzbrenner ,  I am the developer of COSMA and am interested in the installation problem you had. Which compiler did you use? 

We are preparing a new release of COSMA soon, that will bring multiple performance improvements and we would also like to fix all the issues that were discovered in the meantime.

**Comment by PascalSalzbrenner** [comment]
Hi Marko! The compiler is used is g++, I believe the GNU version is 4.8.5. I'm attaching the full cmake.log and make.log in case they are helpful to you.
[cmake.log](https://github.com/cp2k/cp2k/files/6157350/cmake.log)
[make.log](https://github.com/cp2k/cp2k/files/6157351/make.log)

**Comment by alazzaro** [comment]
Please note that 4.8.5 is not supported in CP2K (see https://www.cp2k.org/dev:compiler_support )

**Comment by PascalSalzbrenner** [comment]
I see - thank you for clearing this up, I should really have checked more carefully!

**Comment by kabicm** [comment]
@PascalSalzbrenner and @alazzaro Thanks Pascal and Alfio for clarifications. Indeed, GCC 4.8.5 is probably too old.
