### ISSUE TITLE
toolchain: build cmake without debug symbols or strip binaries/cleanup objects after build

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#1409]
Our cmake binaries are each 200+ MB in size, the whole CMake folder is 3-8 GB (more than libxc, libint and OpenBLAS combined). Stripping the CMake binary brings it down to <10MB, ensuring that `-g` is not passed to CMake could also help.

**Comment by oschuett** [comment]
We [are using](https://github.com/cp2k/cp2k/blob/100c7f8c7142985b03c6060e36ea928dcccbd16e/tools/toolchain/scripts/stage0/install_cmake.sh#L51) the ` ./bootstrap` scripts as recomended by the [cmake documentation](https://cmake.org/install/).


So, while I agree that building cmake takes too much time and disk space, I'd rather not deviate from the instructions.

**Comment by alazzaro** [comment]
Personally, I found building cmake from source very annoying (at least, you don't want to do that within a container).
I use the following:

```
export CMAKE_VERSION=3.18.2
    wget https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-Linux-x86_64.sh
    sh cmake-${CMAKE_VERSION}-Linux-x86_64.sh --prefix=/usr/local --skip-license
    rm -f cmake-${CMAKE_VERSION}-Linux-x86_64.sh
```
