### ISSUE TITLE
Move to Fortran 2008 intrinsic and remove -D__F2008 flag

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#142]
We now state Fortran 2008 as our default standart in the [conventions](https://www.cp2k.org/dev:codingconventions). Hence we should now replace our own implementions with Fortran [intrinsics](https://gcc.gnu.org/onlinedocs/gcc-8.2.0/gfortran/Intrinsic-Procedures.html) were possible. The `__F2008` flag is also no longer needed.

See also https://github.com/cp2k/dbcsr/issues/129 .

**Comment by mkrack** [comment]
The __F2008 flag has been a work around for the transition to Fortran 2008 just to keep the CP2K internal legacy routines for erf and erfc in the module erf_fn. I also suggest to discard erf_fn and to rely on the corresponding intrinsics provided by the compiler. A regression tester run with gfortran showed no numerical issues.

**Comment by mkrack** [comment]
Pull request created (#158)
