### ISSUE TITLE
Does CP2K support ROCm/HIP?

### ISSUE THREAD

**Issue by ipe-zhangyz** [cp2k/cp2k#1430]
Hello, I find that there are  build options for cuda in the install_cp2k_toolchain.sh file, but there is no counterpart for ROCm or HIP. It seems that the DBCSR library can be built with HIP, so I wonder if CP2K can do the same.

Thanks!

**Comment by oschuett** [comment]
CP2K does currently not support HIP. For now I'm focusing on Cuda.

**Comment by ipe-zhangyz** [comment]
OK, thank you for the confirmation! I want to ask further that, do you have any plan to support HIP? If you do, when will the HIP version of CP2K be available?

**Comment by oschuett** [comment]
I'll probably look into HIP later this year. I first want to polish the Cuda kernels and speedup our [GPU regtests](https://dashboard.cp2k.org/archive/cuda-pascal/index.html).
