### ISSUE TITLE
Recent Intel compilers give wrong results and refuse loop unrolling

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#1434]
The test input [CH4-rsLDA.inp](https://github.com/cp2k/cp2k/blob/master/tests/QS/regtest-hfx-wfn-fitting/CH4-rsLDA.inp) returns wrong results using Intel compiler versions newer than 18.0.5.

**Comment by oschuett** [comment]
I recently started using `__attribute__((always_inline))` to generate specialized branches in the [grid ref backend](https://github.com/cp2k/cp2k/blob/master/src/grid/ref/grid_ref_collint.h#L299).
In any case, this should not produce wrong results and smells like a compiler bug.

**Comment by mkrack** [comment]
It is not yet clear where the inlining causes wrong results with the Intel compiler versions 19.x and newer. There is possibly no link to the new grid routines, since the wrong results show up only in a test related to ADMM purify and MO_DIAG. Though an error sometimes occurs in the eigensolver part, the problem is possibly just trapped there caused by an invalid input matrix.

It seems that the Intel compiler ignores your unroll pragmas partially:
```
/data/user/krack/github/mkrack/cp2k/src/grid/ref/grid_ref_collint.h(125): (col. 3) remark: Loop with pragma of unroll = 10 ignored due to unroll factors mismatched
/data/user/krack/github/mkrack/cp2k/src/grid/ref/grid_ref_collint.h(102): (col. 3) remark: Loop with pragma of unroll = 9 ignored due to unroll factors mismatched
/data/user/krack/github/mkrack/cp2k/src/grid/ref/grid_ref_collint.h(102): (col. 3) remark: Loop with pragma of unroll = 9 ignored due to unroll factors mismatched
```

**Comment by oschuett** [comment]
> `Loop with pragma of unroll = 10 ignored due to unroll factors mismatched`

Oh, that's good to know. The gcc doesn't care and unrolls anyways. Unfortunately, I have the exact unroll factors only as a `const` variable - not as preprocessor macro. Since the Intel compiler does not require the unroll factor, we should probably just use the pragma without it.

**Comment by oschuett** [comment]
The icc warnings should be gone with #1476. It still says:
```
remark #11074: Inlining inhibited by limit max-size 
```
... but I think this might actually be legit because for large lp the inner loops become pretty long.

Nevertheless, this might be a good time to check the performance with other compilers besides gcc.

**Comment by oschuett** [comment]
I finally managed to build myself a binary using the Intel stack to investigate the problem with [CH4-rsLDA.inp](https://github.com/cp2k/cp2k/blob/master/tests/QS/regtest-hfx-wfn-fitting/CH4-rsLDA.inp). My findings are:

- When I build with `-fno-inline` then it passes.
- When I build with `-fpe0` then it passes.
- When I build without either then it crashes:

```
  HFX_MEM_INFO| Est. max. program size after HFX  [MiB]:                     164

     1 OT CG       0.15E+00    2.3            NaN        -7.4215709960 -7.42E+00

 *******************************************************************************
 *   ___                                                                       *
 *  /   \                                                                      *
 * [ABORT]  �?�? *
 *  \___/   М��� *
 *    |                            ^^����                        *
 *  O/|                                                                        *
 * /| |                                                                        *
 * / \                                                     fm/cp_fm_diag.F:424 *
 *******************************************************************************


 ===== Routine Calling Stack ===== 

           12 cp_fm_syevd
           11 purify_mo_diag
           10 admm_fit_mo_coeffs
            9 admm_mo_calc_rho_aux
            8 qs_ks_build_kohn_sham_matrix
            7 rebuild_ks_matrix
            6 qs_ks_update_qs_env
            5 scf_env_do_scf_inner_loop
            4 scf_env_do_scf
            3 qs_energies
            2 qs_forces
            1 CP2K
forrtl: error (76): Abort trap signal
Image              PC                Routine            Line        Source             
cp2k.ssmp          0000000009F932BB  Unknown               Unknown  Unknown
libpthread-2.31.s  00007F87DEEA73C0  Unknown               Unknown  Unknown
libc-2.31.so       00007F87DECDE18B  gsignal               Unknown  Unknown
libc-2.31.so       00007F87DECBD859  abort                 Unknown  Unknown
cp2k.ssmp          0000000002FC9B39  message_passing_m        1076  message_passing.F
cp2k.ssmp          0000000002ED0EF7  cp_error_handling          73  cp_error_handling.F
cp2k.ssmp          0000000002FCBE26  base_hooks_mp_cp_          76  base_hooks.F
cp2k.ssmp          0000000002E4C301  cp_fm_diag_mp_cp_         424  cp_fm_diag.F
cp2k.ssmp          000000000100246C  admm_methods_mp_a         750  admm_methods.F
cp2k.ssmp          0000000000FF39AB  qs_ks_methods_mp_         545  qs_ks_methods.F
cp2k.ssmp          0000000000FEDB7C  qs_ks_methods_mp_        1223  qs_ks_methods.F
cp2k.ssmp          0000000001400503  qs_scf_mp_scf_env         462  qs_scf.F
cp2k.ssmp          00000000013F7987  qs_scf_mp_scf_            233  qs_scf.F
cp2k.ssmp          0000000001324535  qs_energy_mp_qs_e          88  qs_energy.F
cp2k.ssmp          0000000000B0EF4E  qs_force_mp_qs_fo         209  qs_force.F
cp2k.ssmp          0000000000B0D20F  qs_force_mp_qs_ca         114  qs_force.F
cp2k.ssmp          00000000007C7DFB  force_env_methods         271  force_env_methods.F
cp2k.ssmp          0000000000417A14  cp2k_runs_mp_run_         354  cp2k_runs.F
cp2k.ssmp          0000000000406A27  MAIN__                    357  cp2k.F
cp2k.ssmp          0000000000405E22  Unknown               Unknown  Unknown
libc-2.31.so       00007F87DECBF0B3  __libc_start_main     Unknown  Unknown
cp2k.ssmp          0000000000405D2E  Unknown               Unknown  Unknown
```

**Comment by oschuett** [comment]
The problem seems to be related to [qs_scf.F](https://github.com/cp2k/cp2k/blob/master/src/qs_scf.F). Dropping a `WRITE` statement anywhere into that file or compiling it with `-O0` makes the test pass.

**Comment by mkrack** [comment]
@oschuett Thanks for further tracking the problem. That looks like a compiler bug. I think reducing the opt level for a high level routine like qs_scf.F might have less performance impact than using a global `-fno-noinline` compiler flag.

**Comment by oschuett** [comment]
Yes, I also suspected a compiler bug at first, but it turns out that adding a `WRITE` statement anywhere before the [end of the outer scf loop](https://github.com/cp2k/cp2k/blob/c26d7619c13f29e07c1cda84127071e9c57fe9ea/src/qs_scf.F#L568) lets the test pass. Even adding it to [cp2k.F](https://github.com/cp2k/cp2k/blob/master/src/start/cp2k.F) does the trick. So, that smells more like a stack corruption.

However, I also noticed that the test passes when the [SRLDA](https://manual.cp2k.org/trunk/CP2K_INPUT/FORCE_EVAL/DFT/XC/XC_FUNCTIONAL/SRLDA.html) functional is disabled. That functional was added somewhat recently ([Dec. 2019](https://github.com/cp2k/cp2k/issues/670)) and it **appears** to be the source of the `NaN` values. Unfortunately, I can't be certain because `-fpe0` makes the problem disappears. Nevertheless, compiling [xc_sr_lda.F](https://github.com/cp2k/cp2k/blob/master/src/xc/xc_sr_lda.F) with `-O1` or `-fp-model strict` lets the test pass.

I'm not yet sure why adding `WRITE` statements helps. Maybe it affects the alignment of some array and as a result a non-AVX branch is used. Then again, this reproducer is so fragile that the SRLDA functional might just be a red herring  ¯\_(ツ)_/¯.

**Comment by oschuett** [comment]
I'm now convinced that the problem is in [xc_sr_lda.F](https://github.com/cp2k/cp2k/blob/master/src/xc/xc_sr_lda.F) because the following check fails:

```
diff --git a/src/xc/xc_sr_lda.F b/src/xc/xc_sr_lda.F
index f6bd5bdfd..b3825045d 100644
--- a/src/xc/xc_sr_lda.F
+++ b/src/xc/xc_sr_lda.F
@@ -230,6 +230,10 @@ CONTAINS
 !$OMP END PARALLEL DO
       END IF
 
+      DO k = 1, npoints
+         CPASSERT(.NOT.ISNAN(e_rho(k)))
+      END DO
+
       CALL timestop(handle)
 
    END SUBROUTINE sr_lda_calc
```

I did not mange to track it down further, because most code modifications let the problem disappear. I believe this problem is caused by over-aggressive compiler optimizations and the fix will be to use `-fp-model strict` for this module.
