### ISSUE TITLE
install_requirements_ubuntu.sh

### ISSUE THREAD

**Issue by k2pc** [cp2k/cp2k#1467]
sudo ./install_requirements_ubuntu.sh
 then
Installing Ubuntu packages...
E: The repository 'http://ppa.launchpad.net/ferramroberto/linuxfreedomlucid/ubuntu focal Release' does not have a Release file.
why?

**Comment by oschuett** [comment]
Check your `/etc/apt/sources.list.d/` directory. There is probably an outdated entry.

**Comment by k2pc** [comment]
Sorry，I still don't know what to do.  In /etc/apt/sources.list.d/ferramroberto-ubuntu-linuxfreedomlucid-focal.list  
deb http://ppa.launchpad.net/ferramroberto/linuxfreedomlucid/ubuntu focal main
# deb-src http://ppa.launchpad.net/ferramroberto/linuxfreedomlucid/ubuntu focal main
thanks

**Comment by oschuett** [comment]
Try commenting the content in that file. The URL is most likely outdated.

**Comment by k2pc** [comment]
Dear Oschuett 
Thank you, I deleted that file directly three days ago.  I compiled cp2k successfully
