### ISSUE TITLE
Installing cosma

### ISSUE THREAD

**Issue by k2pc** [cp2k/cp2k#1468]
Intelmpi+mkl has the problem:

Installing cosma ====================
cosma-2.2.0.tar.gz: OK
Checksum of cosma-2.2.0.tar.gz Ok
Installing from scratch into /home/xxx/cp2k8/cp2k-8.1/tools/toolchain/install/cosma-2.2.0
ERROR: (./scripts/install_cosma.sh, line 48) Non-zero exit code detected.

**Comment by oschuett** [comment]
Can you please share the content of the `cmake.log` file.

**Comment by oschuett** [comment]
Closing this as you [managed](https://github.com/cp2k/cp2k/issues/1467#issuecomment-821151957) to compile cp2k.

**Comment by apachehigh5** [comment]
Hi. I am facing the same issue. 

The following is my cmake.log output:

-- Setting build type to 'Release' as none was specified.
-- Selected BLAS backend for COSMA: CUDA
-- Selected ScaLAPACK backend for COSMA: CUSTOM
-- The CXX compiler identification is GNU 10.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/jeet/installations/cp2k-8.1.0/tools/toolchain/install/gcc-10.2.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found MPI_CXX: /home/jeet/installations/cp2k-8.1.0/tools/toolchain/install/mpich-3.3.2/lib/libmpicxx.so (found version "3.1")
-- Found MPI: TRUE (found version "3.1")
-- Found OpenMP_CXX: -fopenmp (found version "4.5")
-- Found OpenMP: TRUE (found version "4.5")
CUDA not found. Please specify CUDA_PATH variable.
CMake Error at /home/jeet/installations/cp2k-8.1.0/tools/toolchain/install/cmake-3.18.5/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find CUBLAS (missing: CUDA_TOOLKIT_INCLUDE CUDA_CUBLAS_LIB
  CUDA_CUDART_LIB)
Call Stack (most recent call first):
  /home/jeet/installations/cp2k-8.1.0/tools/toolchain/install/cmake-3.18.5/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  libs/Tiled-MM/cmake/FindCUBLAS.cmake:51 (find_package_handle_standard_args)
  libs/Tiled-MM/CMakeLists.txt:30 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/jeet/installations/cp2k-8.1.0/tools/toolchain/build/cosma-2.2.0/build-cuda/CMakeFiles/CMakeOutput.log".



Also, I would like to say that my GPU is a GeForce RTX card whose architecture i don't think is given in the --help option of toolchain that I am using. So was trying to install using the following line:
`./install_cp2k_toolchain.sh --install-all --gpu-ver=P100`

**Comment by kabicm** [comment]
Can you try with the new version of COSMA or the current version on COSMA master branch: https://github.com/eth-cscs/COSMA? Because we switched to using the built-in cmake function for finding cuda, instead of FindCUBLAS.cmake.

**Comment by kabicm** [comment]
This seems to be the same issues as this one: https://github.com/cp2k/cp2k/issues/1525

**Comment by kabicm** [comment]
@catonlyprep This seems to be caused by a bug in cmake versions prior to 3.12.2. Can you try what is suggested [here](https://github.com/eth-cscs/COSMA/issues/86#issuecomment-851559836), and comment in that issue if it works for you?

**Comment by kabicm** [comment]
@catonlyprep This issue is resolved at: https://github.com/eth-cscs/COSMA/issues/86.

It was caused by a bug in cmake versions prior to 3.12.2. We added a workaround for this cmake bug in [COSMA-v2.5.1](https://github.com/eth-cscs/COSMA/releases/tag/v2.5.1). Therefore, the solution is to either use a cmake version >= 3.12.2 or a COSMA version >= 2.5.1.

**Comment by XiaMinqi** [comment]
Hi kabicm,
I'm facing the similar issue and thank you for your kind help above.
However in this case, my cmake version is 3.20.2 and COSMA version is 2.5.1, the package is compiled on CentOS8. 
Here's the content of make.log file:

[  1%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/block.cpp.o
[  3%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/grid2D.cpp.o
[  5%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/interval.cpp.o
[  6%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/scalapack_layout.cpp.o
[  8%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/communication_data.cpp.o
[ 10%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/grid_cover.cpp.o
[ 11%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/ranks_reordering.cpp.o
[ 13%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/utils.cpp.o
[ 15%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/transform.cpp.o
[ 16%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/layout.cpp.o
[ 18%] Linking CXX static library libcosta.a
[ 18%] Built target costa
[ 21%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_scalapack.dir/scalapack.cpp.o
[ 21%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_scalapack.dir/pxtran/costa_pxtran.cpp.o
[ 23%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_scalapack.dir/pxgemr2d/costa_pxgemr2d.cpp.o
[ 25%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_scalapack.dir/pxtran/pxtran.cpp.o
[ 28%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_prefixed_scalapack.dir/scalapack.cpp.o
[ 28%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_scalapack.dir/pxgemr2d/pxgemr2d.cpp.o
[ 30%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_prefixed_scalapack.dir/pxtran/costa_pxtran.cpp.o
[ 31%] Building CXX object src/cosma/CMakeFiles/cosma.dir/blas.cpp.o
[ 33%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_prefixed_scalapack.dir/pxgemr2d/costa_pxgemr2d.cpp.o
[ 36%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_prefixed_scalapack.dir/pxtran/prefixed_pxtran.cpp.o
[ 36%] Building CXX object src/cosma/CMakeFiles/cosma.dir/buffer.cpp.o
[ 38%] Building CXX object src/cosma/CMakeFiles/cosma.dir/communicator.cpp.o
[ 41%] Building CXX object src/cosma/CMakeFiles/cosma.dir/context.cpp.o
[ 41%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_prefixed_scalapack.dir/pxgemr2d/prefixed_pxgemr2d.cpp.o
[ 43%] Building CXX object src/cosma/CMakeFiles/cosma.dir/interval.cpp.o
[ 45%] Building CXX object src/cosma/CMakeFiles/cosma.dir/layout.cpp.o
[ 48%] Building CXX object src/cosma/CMakeFiles/cosma.dir/local_multiply.cpp.o
[ 48%] Building CXX object src/cosma/CMakeFiles/cosma.dir/math_utils.cpp.o
[ 50%] Building CXX object src/cosma/CMakeFiles/cosma.dir/mapper.cpp.o
[ 51%] Building CXX object src/cosma/CMakeFiles/cosma.dir/matrix.cpp.o
[ 53%] Building CXX object src/cosma/CMakeFiles/cosma.dir/memory_pool.cpp.o
[ 58%] Building CXX object src/cosma/CMakeFiles/cosma.dir/strategy.cpp.o
[ 58%] Building CXX object src/cosma/CMakeFiles/cosma.dir/cinterface.cpp.o
[ 58%] Building CXX object src/cosma/CMakeFiles/cosma.dir/multiply.cpp.o
[ 60%] Building CXX object src/cosma/CMakeFiles/cosma.dir/environment_variables.cpp.o
[ 63%] Building CXX object src/cosma/CMakeFiles/cosma.dir/two_sided_communicator.cpp.o
[ 63%] Building CXX object src/cosma/CMakeFiles/cosma.dir/one_sided_communicator.cpp.o
[ 65%] Linking CXX static library libcosta_prefixed_scalapack.a
[ 65%] Built target costa_prefixed_scalapack
[ 66%] Linking CXX static library libcosta_scalapack.a
[ 66%] Built target costa_scalapack
[ 68%] Linking CXX static library libcosma.a
[ 68%] Built target cosma
[ 71%] Building CXX object src/cosma/CMakeFiles/cosma_prefixed_pxgemm.dir/scalapack.cpp.o
[ 71%] Building CXX object src/cosma/CMakeFiles/cosma_pxgemm_cpp.dir/scalapack.cpp.o
[ 75%] Building CXX object src/cosma/CMakeFiles/cosma_pxgemm_cpp.dir/cosma_pxgemm.cpp.o
[ 76%] Building CXX object src/cosma/CMakeFiles/cosma_prefixed_pxgemm.dir/prefixed_pxgemm.cpp.o
[ 78%] Building CXX object benchmarks/CMakeFiles/ubench-allgather.dir/ubench-allgather.cpp.o
[ 78%] Building CXX object src/cosma/CMakeFiles/cosma_prefixed_pxgemm.dir/cosma_pxgemm.cpp.o
[ 81%] Building CXX object benchmarks/CMakeFiles/allgather-volume.dir/allgather-volume.cpp.o
[ 81%] Building CXX object benchmarks/CMakeFiles/sendrecv.dir/sendrecv.cpp.o
[ 83%] Building CXX object benchmarks/CMakeFiles/reduce-scatter.dir/reduce-scatter.cpp.o
[ 85%] Building CXX object benchmarks/CMakeFiles/blocking_vs_non_blocking.dir/blocking_vs_non_blocking.cpp.o
[ 86%] Building CXX object benchmarks/CMakeFiles/dgemm_perf_model.dir/dgemm_perf_model.cpp.o
[ 88%] Linking CXX executable sendrecv
[ 90%] Linking CXX executable allgather-volume
[ 91%] Linking CXX executable reduce-scatter
[ 93%] Linking CXX executable ubench-allgather
CMakeFiles/sendrecv.dir/sendrecv.cpp.o: In function `main':
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/sendrecv.cpp:20: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/sendrecv.cpp:21: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/sendrecv.cpp:32: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/sendrecv.cpp:32: undefined reference to `ompi_mpi_double'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/sendrecv.cpp:32: undefined reference to `ompi_mpi_double'
collect2: error: ld returned 1 exit status
make[2]: *** [benchmarks/CMakeFiles/sendrecv.dir/build.make:108: benchmarks/sendrecv] Error 1
make[1]: *** [CMakeFiles/Makefile2:381: benchmarks/CMakeFiles/sendrecv.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/allgather-volume.dir/allgather-volume.cpp.o: In function `cosma::Timer::~Timer()':
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:34: undefined reference to `ompi_mpi_op_max'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:34: undefined reference to `ompi_mpi_long_long_int'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:35: undefined reference to `ompi_mpi_op_min'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:35: undefined reference to `ompi_mpi_long_long_int'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:36: undefined reference to `ompi_mpi_op_sum'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:36: undefined reference to `ompi_mpi_long_long_int'
CMakeFiles/allgather-volume.dir/allgather-volume.cpp.o: In function `main':
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/allgather-volume.cpp:20: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/allgather-volume.cpp:21: undefined reference to `ompi_mpi_comm_world'
CMakeFiles/allgather-volume.dir/allgather-volume.cpp.o: In function `main':
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:23: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:22: undefined reference to `ompi_mpi_comm_world'
CMakeFiles/allgather-volume.dir/allgather-volume.cpp.o: In function `main':
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/allgather-volume.cpp:35: undefined reference to `ompi_mpi_double'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/allgather-volume.cpp:35: undefined reference to `ompi_mpi_comm_world'
collect2: error: ld returned 1 exit status
make[2]: *** [benchmarks/CMakeFiles/allgather-volume.dir/build.make:108: benchmarks/allgather-volume] Error 1
make[1]: *** [CMakeFiles/Makefile2:354: benchmarks/CMakeFiles/allgather-volume.dir/all] Error 2
CMakeFiles/reduce-scatter.dir/reduce-scatter.cpp.o: In function `cosma::Timer::~Timer()':
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:34: undefined reference to `ompi_mpi_op_max'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:34: undefined reference to `ompi_mpi_long_long_int'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:35: undefined reference to `ompi_mpi_op_min'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:35: undefined reference to `ompi_mpi_long_long_int'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:36: undefined reference to `ompi_mpi_op_sum'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:36: undefined reference to `ompi_mpi_long_long_int'
CMakeFiles/reduce-scatter.dir/reduce-scatter.cpp.o: In function `main':
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/reduce-scatter.cpp:20: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/reduce-scatter.cpp:21: undefined reference to `ompi_mpi_comm_world'
CMakeFiles/reduce-scatter.dir/reduce-scatter.cpp.o: In function `main':
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:23: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:22: undefined reference to `ompi_mpi_comm_world'
CMakeFiles/reduce-scatter.dir/reduce-scatter.cpp.o: In function `main':
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/reduce-scatter.cpp:69: undefined reference to `ompi_mpi_double'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/reduce-scatter.cpp:69: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/reduce-scatter.cpp:69: undefined reference to `ompi_mpi_op_sum'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/reduce-scatter.cpp:69: undefined reference to `ompi_mpi_double'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/reduce-scatter.cpp:69: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/reduce-scatter.cpp:69: undefined reference to `ompi_mpi_op_sum'
collect2: error: ld returned 1 exit status
make[2]: *** [benchmarks/CMakeFiles/reduce-scatter.dir/build.make:108: benchmarks/reduce-scatter] Error 1
make[1]: *** [CMakeFiles/Makefile2:408: benchmarks/CMakeFiles/reduce-scatter.dir/all] Error 2
CMakeFiles/ubench-allgather.dir/ubench-allgather.cpp.o: In function `cosma::Timer::~Timer()':
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:34: undefined reference to `ompi_mpi_op_max'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:34: undefined reference to `ompi_mpi_long_long_int'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:35: undefined reference to `ompi_mpi_op_min'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:35: undefined reference to `ompi_mpi_long_long_int'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:36: undefined reference to `ompi_mpi_op_sum'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/src/cosma/timer.hpp:36: undefined reference to `ompi_mpi_long_long_int'
CMakeFiles/ubench-allgather.dir/ubench-allgather.cpp.o: In function `main':
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/ubench-allgather.cpp:20: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/ubench-allgather.cpp:21: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/ubench-allgather.cpp:49: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/ubench-allgather.cpp:51: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/ubench-allgather.cpp:51: undefined reference to `ompi_mpi_double'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/ubench-allgather.cpp:51: undefined reference to `ompi_mpi_double'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/ubench-allgather.cpp:63: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/ubench-allgather.cpp:65: undefined reference to `ompi_mpi_double'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/ubench-allgather.cpp:65: undefined reference to `ompi_mpi_comm_world'
collect2: error: ld returned 1 exit status
make[2]: *** [benchmarks/CMakeFiles/ubench-allgather.dir/build.make:108: benchmarks/ubench-allgather] Error 1
make[1]: *** [CMakeFiles/Makefile2:327: benchmarks/CMakeFiles/ubench-allgather.dir/all] Error 2
[ 95%] Linking CXX executable blocking_vs_non_blocking
[ 96%] Linking CXX executable dgemm_perf_model
CMakeFiles/blocking_vs_non_blocking.dir/blocking_vs_non_blocking.cpp.o: In function `Timer::~Timer()':
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/blocking_vs_non_blocking.cpp:37: undefined reference to `ompi_mpi_op_max'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/blocking_vs_non_blocking.cpp:37: undefined reference to `ompi_mpi_long_long_int'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/blocking_vs_non_blocking.cpp:38: undefined reference to `ompi_mpi_op_min'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/blocking_vs_non_blocking.cpp:38: undefined reference to `ompi_mpi_long_long_int'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/blocking_vs_non_blocking.cpp:39: undefined reference to `ompi_mpi_op_sum'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/blocking_vs_non_blocking.cpp:39: undefined reference to `ompi_mpi_long_long_int'
CMakeFiles/blocking_vs_non_blocking.dir/blocking_vs_non_blocking.cpp.o: In function `main':
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/blocking_vs_non_blocking.cpp:73: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/blocking_vs_non_blocking.cpp:74: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/blocking_vs_non_blocking.cpp:96: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/blocking_vs_non_blocking.cpp:102: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/blocking_vs_non_blocking.cpp:111: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/blocking_vs_non_blocking.cpp:120: undefined reference to `ompi_mpi_double'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/blocking_vs_non_blocking.cpp:127: undefined reference to `ompi_mpi_double'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/blocking_vs_non_blocking.cpp:139: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/blocking_vs_non_blocking.cpp:157: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/blocking_vs_non_blocking.cpp:160: undefined reference to `ompi_mpi_comm_world'
/home/lijun/softwarez/cp2k-9.1/tools/toolchain/build/COSMA-v2.5.1/benchmarks/blocking_vs_non_blocking.cpp:162: undefined reference to `ompi_mpi_double'
collect2: error: ld returned 1 exit status
make[2]: *** [benchmarks/CMakeFiles/blocking_vs_non_blocking.dir/build.make:108: benchmarks/blocking_vs_non_blocking] Error 1
make[1]: *** [CMakeFiles/Makefile2:435: benchmarks/CMakeFiles/blocking_vs_non_blocking.dir/all] Error 2
[ 96%] Built target dgemm_perf_model
[ 98%] Linking CXX static library libcosma_prefixed_pxgemm.a
[100%] Linking CXX static library libcosma_pxgemm_cpp.a
[100%] Built target cosma_prefixed_pxgemm
[100%] Built target cosma_pxgemm_cpp
make: *** [Makefile:136: all] Error 2




> @catonlyprep This issue is resolved at: [eth-cscs/COSMA#86](https://github.com/eth-cscs/COSMA/issues/86).
> 
> It was caused by a bug in cmake versions prior to 3.12.2. We added a workaround for this cmake bug in [COSMA-v2.5.1](https://github.com/eth-cscs/COSMA/releases/tag/v2.5.1). Therefore, the solution is to either use a cmake version >= 3.12.2 or a COSMA version >= 2.5.1.

**Comment by alazzaro** [comment]
@XiaMinqi I would suggest to post this request in the COSMA repo (https://github.com/eth-cscs/COSMA).

**Comment by hfp** [comment]
@XiaMinqi I also suggest you to use MPI compiler wrappers (if this was not the case already) like `CXX=mpicxx LD=mpicxx cmake ..`.

**Comment by BORIS-ADMIN** [comment]
Hi @XiaMinqi! As @alazzaro has mentioned, we can take this issue on the COSMA repo. Can you first just shortly try what @hfp has suggested, as it seems this is causing the issue?

**Comment by kabicm** [comment]
Hi @XiaMinqi, thanks for reporting the issue. As @alazzaro has said, we can take this issue to the [COSMA repo](https://github.com/eth-cscs/COSMA). Can you just shortly try what @hfp has suggested, as it might be what is causing the issue?

**Comment by XiaMinqi** [comment]
@hfp @kabicm Thank you for your suggestion! The problem has been solved in this way :-)
