### ISSUE TITLE
QS/regtest-dft-vdw-corr-2/argon-vdW-DF-cx0p.inp should be skipped if libint not present

### ISSUE THREAD

**Issue by ltalirz** [cp2k/cp2k#1478]
The test input https://github.com/cp2k/cp2k/blob/master/tests/QS/regtest-dft-vdw-corr-2/argon-vdW-DF-cx0p.inp  requires libint but the corresponding folder only asks for `libxc` (see [test failure](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=307824&view=logs&j=cc7f06b8-47bb-5f80-5e0d-1224ea213530&t=1c90cc3e-b00e-5eab-82a4-21c378b43900&l=6488) )
https://github.com/cp2k/cp2k/blob/36754bb4e7dc0cc3efcd8fb3a055aebc3eb5a960/tests/TEST_DIRS#L135

What do you typically do in such a case - create  `QS/regtest-dft-vdw-corr-4` and move the input there?

**Comment by oschuett** [comment]
> What do you typically do in such a case - create QS/regtest-dft-vdw-corr-4 and move the input there?

Yes :-)

**Comment by oschuett** [comment]
> create QS/regtest-dft-vdw-corr-4 and move the input there?

I think, it's ok to just add libint as a requirement for `QS/regtest-dft-vdw-corr-2`.
