### ISSUE TITLE
Undefined variable referenced in xtb_matrices.F

### ISSUE THREAD

**Issue by vzecca** [cp2k/cp2k#1488]
Running test cases xTB/regtest-debug/ch3br_nonbond_2.inp, xTB/regtest-debug/ch3br_nonbond.inp, and
xTB/regtest-debug/ch3br_atprop_nonbond.inp,
the undefined variable IW is referenced at xtb_matrices.F line 1466:

 IF (iw > 0) WRITE (iw, *) "TESTING ", TRIM(name_atm_a), TRIM(name_atm_b), &

**Comment by oschuett** [comment]
This was again reported in #1490. While this issue came first, the other one mentions more problems. Hence, I'm closing this one as duplicate.
