### ISSUE TITLE
Results from periodic GW should be taken with care

### ISSUE THREAD

**Issue by JWilhelm** [cp2k/cp2k#1495]
Periodic GW calculations in CP2K (https://journals.aps.org/prb/abstract/10.1103/PhysRevB.95.235123) have recently been detected to be numerically unstable when using large, diffuse basis sets. We are working on a replacement of the current periodic GW implementation by a more reliable implementation that includes k-point sampling of the density response and the screened Coulomb interaction.

**Comment by oschuett** [comment]
Was this issue resolved by #1776?

**Comment by oschuett** [comment]
@JWilhelm can we close this issue now?

**Comment by JWilhelm** [comment]
> Was this issue resolved by #1776?

Unfortunately, I see your comment not before today. The periodic GW algorithm is still under development. I hope to be finished next year. 

> can we close this issue now?

If you like, we can close the issue. Once the periodic GW is finished, I will anyways put out new tutorials, etc.
