### ISSUE TITLE
Undefined component smear referenced in qs_kind_types.F

### ISSUE THREAD

**Issue by vzecca** [cp2k/cp2k#1496]
Running test cases QS/regtest-plus_u/H2O-rks-diag-mulliken.inp, QS/regtest-plus_u/H2O-rks-otcg-mulliken.inp,
QS/regtest-plus_u/H2O-uks-diag-mulliken.inp, and others, in qs_kind_types.F line 748

smear = qs_kind%dft_plus_u%smear

the component smear is referenced undefined.

**Comment by mkrack** [comment]
Hopefully resolved by #1497
