### ISSUE TITLE
Undefined variables referenced

### ISSUE THREAD

**Issue by vzecca** [cp2k/cp2k#1502]
Running many test cases, among them QS/regtest-grid/simple_non-ortho_grid_auto.inp,
at fft_lib.F, line 248

IF (plan%valid .AND. plan%fft_type .EQ. 3) THEN

plan%fft_type is referenced undefined.

Running many test cases, among them QS/regtest-grid/simple_non-ortho_grid_validate.inp
at pw_poisson_methods.F, line 536

poisson_env%parameters = parameters

parameters is referenced undefined.

Running many test cases, among them QS/regtest-grid/simple_non-ortho_grid_ref.inp
at dbcsr_ptr_util.F, line 306

dst(:) = src(:)

src is referenced undefined.

Running many test cases, among them QS/regtest-grid/simple_ortho_grid_dgemm.inp
at qs_overlap.F, line 460

 IF (do_forces .AND. ASSOCIATED(p_block) .AND. ((iatom /= jatom) .OR. use_virial)) THEN

use_virial is referenced undefined.

Running many test cases, among them QS/regtest-grid/simple_non-ortho_grid_dgemm
at qs_kinetic.F, line 389

IF (do_forces .AND. ASSOCIATED(p_block) .AND. ((iatom /= jatom) .OR. use_virial)) THEN

use_virial is referenced undefined.

**Comment by fstein93** [comment]
I can fix qs_overlap and qs_kinetic. The issue in pw_poisson_methods.F and fft_lib.F doesn't seem to be caused by the given routine but by the caller which does not provide a proper input.
