### ISSUE TITLE
dashboard: inconsistent arch file comments shown for daint

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#1508]
Currently I see the following in the dashboard logs for daint-gpu:

```
[...]
ModuleCmd_Switch.c(179):ERROR:152: Module 'PrgEnv-cray' is currently not loaded
Switching to atp/3.8.1.
Switching to cray-fftw/3.3.8.8.
Switching to cray-libsci/20.09.1.
Switching to cray-mpich/7.7.16.
Switching to craype/2.7.3.
Switching to gcc/9.3.0.
Switching to modules/3.2.11.4.
Switching to perftools-base/20.10.0.
Switching to pmi/5.0.17.
*************************** testing started ******************************
[...]
--------------------------- ARCH-file ------------------------------------
# === For Cray XC50 (PizDaint GPU-partition) ====
# Program environments:
#
# module load daint-gpu
# module swap PrgEnv-cray PrgEnv-gnu/6.0.8
# module load cray-fftw/3.3.8.7
# module load cudatoolkit/10.2.89_3.28-7.0.2.1_2.17__g52c0314
[...]
---------------------------- Modules -------------------------------------
Currently Loaded Modulefiles:
  1) modules/3.2.11.4(default)
  2) cge/3.2.1463_r03f4dfb_fe3.3.0_2019062614
  3) craype-network-aries
  4) gcc/9.3.0
  5) craype/2.7.3(default)
  6) cray-mpich/7.7.16(default)
  7) slurm/20.11.4-2
  8) craype-haswell
  9) xalt/2.8.10
 10) cray-libsci/20.09.1(default)
 11) udreg/2.3.2-7.0.2.1_2.27__g8175d3d.ari
 12) ugni/6.0.14.0-7.0.2.1_3.46__ge78e5b0.ari
 13) pmi/5.0.17(default)
 14) dmapp/7.1.1-7.0.2.1_2.52__g38cf134.ari
 15) gni-headers/5.0.12.0-7.0.2.1_2.10__g3b1768f.ari
 16) xpmem/2.2.20-7.0.2.1_2.45__g87eb960.ari
 17) job/2.2.4-7.0.2.1_2.49__g36b56f4.ari
 18) dvs/2.12_2.2.170-7.0.2.1_6.10__gfe7b137d
 19) alps/6.6.59-7.0.2.1_3.39__g872a8d62.ari
 20) rca/2.2.20-7.0.2.1_2.55__g8e3fb5b.ari
 21) atp/3.8.1(default)
 22) perftools-base/20.10.0(default)
 23) PrgEnv-gnu/6.0.9
 24) daint-gpu/20.11
 25) cray-fftw/3.3.8.8(default)
 26) cudatoolkit/11.0.2_3.33-7.0.2.1_3.1__g1ba0366
 27) cdt-cuda/20.11
[...]
```

It would be really useful to have the dashboard showing a correct/up-to-date arch file as not everyone has rebased their branch to latest `master` and can use `arch/CRAY-XC50_gnu.psmp`, hence relying on those dashboard logs to obtain an arch-file to build their own versions of CP2K on daint and using the `module` commands noted in there. But as of May 2021 those commands are not working anymore as shown and are obviously not used to load the environment.

**Comment by mkrack** [comment]
I try to keep the arch file [CRAY-XC50_gnu.psmp](https://github.com/cp2k/cp2k/blob/master/arch/CRAY-XC50_gnu.psmp) up-to-date with the current module settings at CSCS for building my own CP2K binaries from the CP2K trunk on Piz Daint. It seems that the CRAY_XC50-gfortran_gpu.psmp regression tester employs a kind of tailored (legacy?) arch file. 
@alazzaro would it be possible to use also the arch file [CRAY-XC50_gnu.psmp](https://github.com/cp2k/cp2k/blob/master/arch/CRAY-XC50_gnu.psmp) for the CRAY_XC50-gfortran_gpu.psmp regression tester?

**Comment by dev-zero** [comment]
@mkrack thanks a lot for that work, unfortunately:

```console
$ ls /store/psi/psi01/mkrack/daint/gpu/gnu/8.3.0
ls: cannot access '/store/psi/psi01/mkrack/daint/gpu/gnu/8.3.0': Permission denied
```

Btw, to make it easier for maintenance and usage, it is possible to make the arch-file sourceable (by bash):

https://github.com/cp2k/cp2k/blob/95ce09f698a59dd5f5deeb752a41a99f49e04193/arch/Eiger-gfortran.psmp

With that one the user can do:

```console
$ source arch/Eiger-gfortran.psmp 

Due to MODULEPATH changes, the following have been reloaded:
  1) cray-mpich/8.1.4

Please check the output above for error messages.
If everything is ok, run with:
    make -j ARCH=Eiger-gfortran VERSION=psmp
$ make -j ARCH=Eiger-gfortran VERSION=psmp
```

**Comment by mkrack** [comment]
@dev-zero I have updated the access rights. There is a sourecable script to set the proper module environment. I prefer that two-step procedure instead of a sourceable arch file. Please, could you try
```
source /store/psi/psi01/mkrack/daint/gpu/gnu/8.3.0/bin/init_gpu_gnu.sh
make -j 12 ARCH=CRAY-XC50_gnu VERSION=psmp
```
The workflow for daint-mc is similar
```
source /store/psi/psi01/mkrack/daint/mc/gnu/8.3.0/bin/init_mc_gnu.sh
make -j 12 ARCH=CRAY-XC40_gnu VERSION=psmp
```

**Comment by dev-zero** [comment]
@mkrack thanks a lot, seems to work!
Wrt sourceable arch file: I still kept it as a two-step procedure (e.g. the user still has to run `make -j ...` after sourcing it), only difference is that they source the arch file so everything is in one place. No worries, I will not touch your arch files ;-)

**Comment by oschuett** [comment]
This issue seems to be resolve, especially since we now have two new tests for Daint:
- https://dashboard.cp2k.org/archive/cray-xc40-gnu-psmp/index.html
- https://dashboard.cp2k.org/archive/cray-xc50-gnu-psmp/index.html
