### ISSUE TITLE
GPU build failed because of COSMA

### ISSUE THREAD

**Issue by cap-jmk** [cp2k/cp2k#1525]
Compiling with 
```bash 
./install_cp2k_toolchain.sh --with-libxsmm=install --with-openblas=system 
--with-fftw=no --with-reflapack=no --with-cosma=no --enable-cuda=yes --gpu-ver=P100
```
Gives 

```bash
==================== Installing cosma ====================
cosma-2.2.0.tar.gz is found
Installing from scratch into /content/cp2k-8.1/tools/toolchain/install/cosma-2.2.0
ERROR: (./scripts/install_cosma.sh, line 89) Non-zero exit code detected.
```

How can I solve the issue?
I think it is a COSMA bug (they did not link CUDA as to my knowledge because compiling COSMA from source with

```bash
cmake -DCOSMA_BLAS=CUDA ..
```

Gives 

```
Make Error at /usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CUBLAS (missing: CUDA_TOOLKIT_INCLUDE CUDA_CUDART_LIB)
```

**Comment by ltalirz** [comment]
while you wait for a reply, maybe consider cross-posting at https://github.com/eth-cscs/COSMA/issues ?

**Comment by kabicm** [comment]
I responded the same day on: https://github.com/eth-cscs/COSMA/issues/86 but still didn't get any feedback. Let me know if you need any further help.

**Comment by cap-jmk** [comment]
I am sorry to kept you waiting. I responded there. The point is to install it on COLAB.

**Comment by kabicm** [comment]
@oschuett This issue is resolved at: https://github.com/eth-cscs/COSMA/issues/86.

It was caused by a bug in cmake versions prior to 3.12.2. We added a workaround for this cmake bug in [COSMA-v2.5.1](https://github.com/eth-cscs/COSMA/releases/tag/v2.5.1). Therefore, the solution is to either use a cmake version >= 3.12.2 or a COSMA version >= 2.5.1.
