### ISSUE TITLE
Smoketests

### ISSUE THREAD

**Issue by mbanck** [cp2k/cp2k#153]
The regtesting is great, but it takes a lot of time. It would be good if `do_regtest` had some machinery to only run a few tests of each functionality (preferably those without huge runtimes) in order to make sure the CP2K basically runs fine.

This could be done e.g. by additional tagging in `TEST_DIRS` and/or individual `TEST_FILES`.

**Comment by oschuett** [comment]
Yes, that's an interesting idea. However, these additional tags would need to be maintained and might become biased towards older tests. I'm actually working on sth similar, namely [sharing](https://github.com/oschuett/cp2k/commit/0ce09ec9601c85ef9d2ba03a7cc1535eee466e67). Maybe you could simply run the first of four shards as smoketest?

**Comment by mbanck** [comment]
Well, right now I have to maintain it by hand in the Debian package, see e.g. https://salsa.debian.org/debichem-team/cp2k/blob/master/debian/rules#L49 which is cherry-picking a set of (hopefully) not too long-running directories. I think the CP2K developers would be in a better position to judge than me but I agree that it is work.

I will look at the new sharding feature, but that does not protect you from hitting a directory which has a really long runtime (unless y'all start agressively splitting up directories even more).

By the way: there is no way to push the `restrictdir` options into the regtester config file?

**Comment by oschuett** [comment]
The sharding feature is now in master: https://github.com/cp2k/cp2k/commit/ce328c223787fa0e3f6e5396f8abd74817664cb6. However, as you pointed out, with these huge differences in directory runtimes it's not quite usable, yet. Hence, I've opened #174.

> By the way: there is no way to push the restrictdir options into the regtester config file?

Yes, the regtester config has full control because it is actually [sourced](https://github.com/cp2k/cp2k/blob/master/tools/regtesting/do_regtest#L34).

**Comment by mbanck** [comment]
> The sharding feature is now in master: [ce328c2](https://github.com/cp2k/cp2k/commit/ce328c223787fa0e3f6e5396f8abd74817664cb6). However, as you pointed out, with these huge differences in directory runtimes it's not quite usable, yet. Hence, I've opened #174.

Ok, I'll have a look. Is the sharding reproducible, or do you get different sets of regtests for a shard number when running it several times in a row?

> > By the way: there is no way to push the restrictdir options into the regtester config file?
> 
> Yes, the regtester config has full control because it is actually [sourced](https://github.com/cp2k/cp2k/blob/master/tools/regtesting/do_regtest#L34).

So you are saying the `restrictdir` option can be part of the config file? I tried that (after seeing that it is sourced), but it did not work for me, do you have an example?

My idea was to centralize the list of regtest dirs to run between the build-time and install-time (aka autopkgtests) runs, but in the end I changed the latter to just run the Debian makefile target of the former, see
https://salsa.debian.org/debichem-team/cp2k/commit/deb94077c66b3b011e19de4050ea5e8b7653b163 so I am basically just curious at this point and don't mind if it can't be done in the end.

**Comment by oschuett** [comment]
Something like this will probably work (haven't tested it though):
```
restrict_dirs[1]="foo"
restrict_dirs[2]="bar"
restrict_dirs[3]="quux"
ndirstorestrict=3
```
However, I actually think the use of the config should be discouraged because it exposes the internals of `do_regtests`. Sooner or later we'll have to rewrite that script in Python.
