### ISSUE TITLE
Convergence issues in development version (v9.0)

### ISSUE THREAD

**Issue by nwinner** [cp2k/cp2k#1531]
Posting to make this issue known to the devs. I pulled the latest development version (v9.0) this morning and built it on my machine to run some tests. I found that electronic convergence is not achieved for this new version, when my other build (v8.0) converges rapidly.

The system in question was MgO, and the same input file is used in both cases, but only v8.0 converges. I have attached two output files and the corresponding input file where I noticed this. Hope the devs find what caused this soon.

[cp2k.inp.txt](https://github.com/cp2k/cp2k/files/6512106/cp2k.inp.txt)
[cp2k.out.8.0.txt](https://github.com/cp2k/cp2k/files/6512107/cp2k.out.8.0.txt)
[cp2k.out.9.0.txt](https://github.com/cp2k/cp2k/files/6512108/cp2k.out.9.0.txt)

**Comment by mkrack** [comment]
I cannot confirm your observation. I have run your input with the cp2k release version 8.1 and with the current trunk version 9.0 of today and from May 15 on a CRAY XC40 and XC50. All runs show the same convergence behavior. The total energies and the electron counts are numerically accurate. I suggest that you check your installation.

**Comment by nwinner** [comment]
@mkrack That is very odd. I've never had CP2K build successfully but not perform correctly. Thanks for checking. My arch is below.

```
GNU_PATH=/work2/06388/nwinner/stampede2/opt

CC          = mpicc
CXX         = mpicxx
FC          = mpif90
LD          = mpif90
AR          = ar -r

ELPA_VERSION = 2021.05.001
ELPA_INC    = $(GNU_PATH)/elpa/$(ELPA_VERSION)/include/elpa_openmp-2021.05.001.rc1
ELPA_LIB    = $(GNU_PATH)/elpa/$(ELPA_VERSION)/lib

FFTW_INC    = ${TACC_FFTW3_INC}
FFTW_LIB    = ${TACC_FFTW3_LIB}

LIBINT_INC  = $(GNU_PATH)/libint/v2.6.0-cp2k-lmax-5/include
LIBINT_LIB  = $(GNU_PATH)/libint/v2.6.0-cp2k-lmax-5/lib

LIBXC_INC   = $(GNU_PATH)/libxc/5.1.4/include
LIBXC_LIB   = $(GNU_PATH)/libxc/5.1.4/lib

LIBXSMM_INC = $(GNU_PATH)/libxsmm/1.10/include
LIBXSMM_LIB = $(GNU_PATH)/libxsmm/1.10/lib

CFLAGS      = -O2 -g -fopenmp  #-fopenmp-simd -ftree-vectorize -funroll-loops -g -march=native -mtune=native

DFLAGS      = -D__FFTW3
DFLAGS     += -D__LIBINT
DFLAGS     += -D__LIBXC
DFLAGS     += -D__LIBXSMM
DFLAGS     += -D__parallel
DFLAGS     += -D__SCALAPACK
DFLAGS     += -D__HAS_NO_SHARED_GLIBC

FCFLAGS     = $(CFLAGS) $(DFLAGS)
FCFLAGS    += -fbacktrace
FCFLAGS    += -ffree-form
FCFLAGS    += -ffree-line-length-none
FCFLAGS    += -fno-omit-frame-pointer
FCFLAGS    += -I$(FFTW_INC)
FCFLAGS    += -I$(LIBINT_INC)
FCFLAGS    += -I$(LIBXC_INC)
FCFLAGS    += -I$(LIBXSMM_INC)

LDFLAGS     = $(FCFLAGS) -static-libgfortran
LDFLAGS_C   = $(FCFLAGS)

LIBS         = $(LIBXC_LIB)/libxcf03.a
LIBS       += $(LIBXC_LIB)/libxc.a
LIBS       += $(LIBINT_LIB)/libint2.a
LIBS       += $(FFTW_LIB)/libfftw3.a
LIBS       += $(FFTW_LIB)/libfftw3_threads.a
LIBS       += $(LIBXSMM_LIB)/libxsmmf.a
LIBS       += $(LIBXSMM_LIB)/libxsmm.a
LIBS       += ${TACC_MKL_LIB}/libmkl_scalapack_lp64.a -Wl,--start-group \
              ${TACC_MKL_LIB}/libmkl_intel_lp64.a \
              ${TACC_MKL_LIB}/libmkl_sequential.a \
              ${TACC_MKL_LIB}/libmkl_core.a \
              ${TACC_MKL_LIB}/libmkl_blacs_intelmpi_lp64.a -Wl,--end-group
LIBS       += -ldl
LIBS       += -lpthread
LIBS       += -lstdc++
```

**Comment by mkrack** [comment]
You are using Intel MKL with a GNU compiler environment, but there is no `-D__MKL` flag for CP2K. Is the FFTW3 library in TACC_FFTW3_LIB from MKL, too? You have possibly an unfortunate merge of incompatible libraries.

**Comment by mkrack** [comment]
@nwinner I have added an [arch file](https://github.com/cp2k/cp2k/blob/master/arch/CRAY-XC40_gnu-mkl.psmp) combining GNU with MKL.

**Comment by nwinner** [comment]
Ah that did not occur to me. Thanks so much for sussing this out for me @mkrack . Closing this issue.
