### ISSUE TITLE
Regtest logs do not indicate which version of DBCSR was used

### ISSUE THREAD

**Issue by shoshijak** [cp2k/cp2k#154]
The regtest logs accessible via the [CP2K Dashboard](https://dashboard.cp2k.org)) (for example, this [one](https://dashboard.cp2k.org/archive/cray-xc50-daint-gpu-psmp_perf/commit_53314e2d2677c6abcb41e93c64382d35294c83cf.txt)) do not indicate which DBCSR version was used in the build, and this information is cumbersome to retrieve a posteriori now that DBCSR is used via git submodules. 

Could the regtests log be completed to include the DBCSR version (or perhaps even better: SHA) used in the CP2K build?

**Comment by alazzaro** [comment]
Well, this info is already printed by the regtest script. For instance, 

https://www.cp2k.org/static/regtest/trunk/cscs-daint-xc50_gpu/CRAY_XC50-gfortran_gpu.psmp.out

you have the lines:

```
----------------------- External Modules ---------------------------------
Discovering programs ...
DCBSR Version: 1.0.0 (2019-01-03)
```

This can be done with the CP2K makefile target:

```
make extversions
```

I think this should be enough for CP2K (note that CP2K will only have an official release).

Now, I see that there is a problem with some regtests, for instance, the PSI test gives the error:

```
Discovering programs ...
Makefile:30: *** "No FYPP submodule available, please read README.md on how to properly download DBCSR".  Stop.
make[2]: *** [dbcsrversion] Error 2
make[1]: *** [psmp] Error 2
make: *** [extversions] Error 2
```

My bad, I have to include FYPP path...

**Comment by shoshijak** [comment]
Oh, my bad, sorry, I didn't find the file you mention (https://www.cp2k.org/static/regtest/trunk/cscs-daint-xc50_gpu/CRAY_XC50-gfortran_gpu.psmp.out) while browsing around the performance Dashboard. 

How do you navigate to it from the dashboard?

**Comment by shoshijak** [comment]
Still, since the regtest result files (like for instance [the one I mentioned in the beginning of the issue](https://dashboard.cp2k.org/archive/cray-xc50-daint-gpu-psmp_perf/commit_53314e2d2677c6abcb41e93c64382d35294c83cf.txt) contain the CP2K arch files as the CP2K git SHA, it would seem natural to add the version of the submodules. 

Moreover, this could simplify the diagnosis of performance issues

**Comment by alazzaro** [comment]
To access the logs you have to click on https://dashboard.cp2k.org/ on the Status column. This valid for the regtests, not for the performance ones.
Concerning performance tests, you are right, the DBCSR version is not there...

**Comment by shoshijak** [comment]
@dev-zero and @alazzaro thanks a lot!

**Comment by alazzaro** [comment]
OK, now the performance tests report the DBCSR version, e.g.

https://www.cp2k.org/static/regtest/trunk/cscs-daint-xc50_gpu_perf/CRAY_XC50-gfortran_gpu.psmp.out

DCBSR Version: 1.0.0 (2019-01-03)
