### ISSUE TITLE
CUDA RT1 Error: out of memory

### ISSUE THREAD

**Issue by zyy-qy** [cp2k/cp2k#1555]
Dear All

I use cp2k-8.2(GPU version) to simulate a system that has 2304 atoms(C and H).
But it report error, error information and output file are attached 
[error.txt](https://github.com/cp2k/cp2k/files/6630640/error.txt)
[cp2k.out.txt](https://github.com/cp2k/cp2k/files/6630642/cp2k.out.txt)

And I want to what's the correlation between physical memory with the max number of atoms of system. 
Because I may create about 80000 atoms system to run cp2k.

Computer information
system: Ubuntu
GNU: 10.2
cuda version: 11.2
driver version: 460.27.04
GPU: 2*  NVIDIA K80
physical memory: 24*16G(=382G)

Could you please help me to answer the question?
Thanks in advance and regards,

Yanyan

**Comment by alazzaro** [comment]
For thise kind of questions, I suggest you use the google forum:

https://groups.google.com/g/cp2k

Github is really meant for developments and bugs...
BTW, the error is on the cuFFT, maybe you can disable it during the CP2K compilation?
In the arch file, you can remove the DFLAG `-D__PW_CUDA`.
