### ISSUE TITLE
specifying ndigit on output position/velocity/forces or output in scientific notation

### ISSUE THREAD

**Issue by tueboesen** [cp2k/cp2k#1556]
I'm currently running some simulations where the output does not come out with enough significant digits (position/velocity/forces), part of the reason for this is that I have chosen to output non-standard units.
Hence forces for instance comes out as:

 H         0.0104393281        0.0054219586       -0.0006507595

The big problem here is that these number are not precise enough to replicate the results to a reasonable degree, but there doesn't seem to be anyway to increase the number of digits, or ensure that the output is generated in scientific notation, which would ensure that digits are at least not lost.

There might be a way to do this that I just haven't found yet, but from reading the documentation I didn't find anything about this.

**Comment by oschuett** [comment]
CP2K supports several [output formats](https://manual.cp2k.org/trunk/CP2K_INPUT/MOTION/PRINT/FORCES.html#list_FORMAT). Probably the DCD format, which is binary, has the highest precision. However, note that numeric noise is usually the limitation - especially with forces.
