### ISSUE TITLE
sirius: configuration params were not recognized and ignored

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#1590]
With the current sirius version from the toolchail (v7.2.5):

```
=== Warning at line 104 of file /data/tiziano/cp2k/tools/toolchain/build/SIRIUS-7.2.5/src/context/simulation_parameters.cpp ===
The following configuration parameters were not recognized and ignored: potential_tol
```

I don't have the output ready, but from earlier tests I remember there were also more, like the evp_solver_type.

**Comment by dev-zero** [comment]
@mtaillefumier

**Comment by oschuett** [comment]
@mtaillefumier, has this issue been resolved by the latest SIRIUS upgrade (#1627)?

**Comment by mtaillefumier** [comment]
It is most probably. We are working on the api to make it more robust. Passing the options is one of the areas that were modified. I have the patch ready but we are finishing work on the api on the sirius side.

**Comment by oschuett** [comment]
Thanks! Then I'll close this issue as you still have https://github.com/electronic-structure/SIRIUS/issues/662 for tracking it on the SIRIUS side.
