### ISSUE TITLE
Makefile: incomplete dependency of cp2k_info on .git/HEAD

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#16]
Unless on a detached HEAD, `.git/HEAD` contains something like `ref: refs/heads/master` (or a reference to the branch) and does not necessarily get updated on a `git pull`. So, to make this work one has to also parse the content and add a dependency on the referenced file (see also the changes to `tools/regtesting/do_regtest` in PR #11)

**Comment by oschuett** [comment]
Maybe this could be solved more elegantly with the [ident gitattribute](https://git-scm.com/docs/gitattributes#_code_ident_code)?

**Comment by dev-zero** [comment]
I don't think so: by the documentation it replaces it by the hash of the respective blob object which is the file itself, but we want to track the state of the complete tree, don't we?

**Comment by oschuett** [comment]
You're right, my bad. I guess then we indeed need to find a way to dynamically add a Make rule that depends on the correct `refs` file.

**Comment by dev-zero** [comment]
the file `.git/HEAD` contains usually the following:

```
ref: refs/heads/master
```

e.g. a reference to a branch. Unless one is on a detached head, in which case it is the actual hash.

So: first check if it the string in with a `ref`, then get the hash from `.git/<the-specified-ref>`.

Furthermore: we should check (if the `git` command is available) whether or not the tree is in a dirty state (uncommitted changes) and add this info the version as well.
