### ISSUE TITLE
USE libxsmm without ONLY in dbcsr_toollib.F

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#163]
/home/krack/github/mkrack_f2008/cp2k/exts/dbcsr/src/utils/dbcsr_toollib.F:208:10:

       USE libxsmm
          1
Warning: USE statement at (1) has no ONLY qualifier [-Wuse-without-only]

**Comment by oschuett** [comment]
I think this should better be filed at the [dbcsr project](https://github.com/cp2k/dbcsr/issues).

**Comment by mkrack** [comment]
Moved to dbcsr project
