### ISSUE TITLE
USPEX 10.5: issue with @INCLUDE 'subsys.uspex' in CP2K

### ISSUE THREAD

**Issue by xavbdlt** [cp2k/cp2k#1631]
Hello,

Used with CP2K, USPEX creates a file containing the cell parameters and atom positions named "subsys.uspex", which can conveniently be included in the Specific files cp2k_options_1 with the line:
  @INCLUDE 'subsys.uspex'

The problem is that the section &SUBSYS in my cp2k_options_1 already contains info about atom types like:
&SUBSYS
    &KIND C
      BASIS_SET DZVP-MOLOPT-SR-GTH
      POTENTIAL GTH-NLCC-PBE-q4
    &END KIND
&END SUBSYS
@INCLUDE 'subsys.uspex'

and the keyword &SUBSYS cannot be used more than once, whereas it is also present in subsys.uspex:
&SUBSYS
&CELL
ABC [angstrom] 4.0505422775 5.829809608 2.280013981
ALPHA_BETA_GAMMA [deg] 90 90 90
PERIODIC XYZ
&END
&COORD
SCALED
C 0.3181270957 0.5 0
C 0.6818729043 0.5 0.5
C 0.6818729043 0.5 0
C 0.3181270957 0.5 0.5
C 0.725584507 0.1219883189 0.25
C 0.274415493 0.8780116811 0.75
C 0.725584507 0.8780116811 0.75
C 0.274415493 0.1219883189 0.25
&END
&END SUBSYS

I tried to find the source file to remove the lines &SUBSYS and &END SUBSYS created by USPEX, but there is none. My guess is it's embedded in the MATLAB file, which cannot be openly modified. So I have no way to make USPEX work properly with CP2K. Besides it should rather be a 'cell.uspex' file rather than a 'subsys.uspex' file which is created by USPEX.

Please advise.

Thank you,
Xavier

**Comment by juerghutter** [comment]
Seems to me a problem for the USPEX developers.

Or you can run a script ahead of CP2K that strips your file
from the &SUBSYS ...&END SUBSYS lines.

**Comment by xavbdlt** [comment]
Indeed more an USPEX problem. I also posted it in USPEX forum.

USPEX generates hundreds or thousands of structures for crystal discovery. And I don't know yet if ducking a script after USPEX generates a structure and before CP2K reads the input file is possible.

Maybe the easiest way at that time would be to modify the "@include" function of CP2K to ditch the 1st and last lines. Or it could work with just ditching the 1st line if I use @include to close the &SUBSYS section. Do you know the source file of CP2K managing the @include function?

**Comment by juerghutter** [comment]
If you want to hack it for personal use:

src/input/cp_parser_inpp_methods.F -- line 119

**Comment by xavbdlt** [comment]
Note that USPEX 10.5.1 corrects this issue.
