### ISSUE TITLE
Feature request: Conjugate gradient diagonalization

### ISSUE THREAD

**Issue by nwinner** [cp2k/cp2k#1668]
Hello devs,

Would it be possible to add conjugate gradient as method for solving diagonalization-based SCF? CP2K farms this step to programs like lapack, so it doesn't seem like it would be hard, but I'm not sure.

Thanks.
-Nick

**Comment by juerghutter** [comment]
Hi
with DIAGONALIZATION / OT and MINIMIZER CG you can request a conjugate gradient diagonalization using an orbital transformation scheme to handle orthogonalization. It is not exactly what is usually done in CG diagonalization, but is very close.

**Comment by nwinner** [comment]
I see Juerg, this makes sense. Thanks.
