### ISSUE TITLE
No DBCSR submodule available

### ISSUE THREAD

**Issue by pplab** [cp2k/cp2k#1684]
Hi all

I tried to install cp2k 8.2 with openmpi 4.1.1, gcc 10.3 and cuda 11.4.

I had finished toolchain installation. I also cloned dbcsr to `exts/dbcsr`  and used `git submodule update --init --recursive` in the directory to check again that every package is ready.

However, when I start make cp2k, it still gave me the error:

```
Discovering programs .../opt/src/cp2k/cp2k_yshen/cp2k-8.2.0/exts/Makefile.inc:2: *** "No DBCSR submodule available, please run 'git submodule update --init --recursive'".  Stop.
make[1]: *** [ssmp] Error 2
make: *** [all] Error 2
```

I checked the file `exts/Makefile.inc:2`, and found it checked whether `$(EXTSHOME)/dbcsr/.cp2k/Makefile` existed. The dbscr cloned from github does not have the .cp2k directory and that's why I got the error.

I tried to fix this problem: 
First, I created the .cp2k directory in `$(EXTSHOME)/dbcsr` and used cmake to generated the Makefile, and everything was fine.

Then I tried to make cp2k again. 
It gave another error:
```
Discovering programs ...
Removing stale archives for ssmp ... 
Resolving dependencies for ssmp ... 
make -C /opt/src/cp2k/cp2k_yshen/cp2k-8.2.0/exts/dbcsr -f .cp2k/Makefile \
   INCLUDEMAKE=/opt/src/cp2k/cp2k_yshen/cp2k-8.2.0/arch/local.ssmp \
   LIBDIR=/opt/src/cp2k/cp2k_yshen/cp2k-8.2.0/lib/local/ssmp/exts/dbcsr \
   OBJDIR=/opt/src/cp2k/cp2k_yshen/cp2k-8.2.0/obj/local/ssmp/exts/dbcsr \
   ACC="" \
   ACCFLAGS=""
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP_Fortran: -fopenmp  
-- Found OpenMP: TRUE   
-- Using BLAS for Small Matrix Multiplication
-- A library with LAPACK API found.
-- GPU target architecture: V100
-- GPU architecture number: 70
-- GPU profiling enabled: OFF
-- FYPP preprocessor found.
Tests will run with 20 MPI ranks and 2 OpenMP threads each
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/src/cp2k/cp2k_yshen/cp2k-8.2.0/exts/dbcsr/.cp2k
make[4]: CMakeFiles/Makefile2: No such file or directory
make[4]: *** No rule to make target `CMakeFiles/Makefile2'.  Stop.
make[3]: *** [all] Error 2
make[2]: *** [dbcsr] Error 2
make[1]: *** [ssmp] Error 2
make: *** [all] Error 2
```

I checked that the missing `CMakeFiles/Makefile2` is in `exts/dbcsr/.cp2k/CMakeFiles`, I don't know why the program can't find it.

I'm confused and need some suggestions. Thanks.

**Comment by alazzaro** [comment]
Why are you trying to use a new DBCSR? 
CP2K 8.2 has its own, so I don't understand the need to touch exts/dbcsr.

**Comment by alazzaro** [comment]
To me more precise, I assume you are dowloading a release via:

> For users, the preferred method is to download a release (use the versioned tarballs, cp2k-X.Y.tar.bz2)

as stated in the [INSTALL](https://github.com/cp2k/cp2k/blob/master/INSTALL.md).

**Comment by pplab** [comment]
I find out that I download the wrong version of cp2k source code, which is automatically generated by github.

This detail is here: https://github.com/cp2k/cp2k/issues/1302

Thanks
