### ISSUE TITLE
geometry optimisation using cp2k8.1 gets stuck in first optimisation step

### ISSUE THREAD

**Issue by mpougin** [cp2k/cp2k#1696]
Hello,
I am currently running cp2k8.1 on the hybrid partition on daint.cscs.ch. When I try to do a geometry optimisation (GEO_OPT) of a metal-organic framework, the calculation gets stuck at `OPTIMIZATION STEP: 1`, i.e. no more output is produced until I run out of walltime. Running the calculation with exactly the same inputs using cp2k7.1 on the hybrid partition on daint.cscs.ch works fine. Here the details of the compiled codes:

`CP2K| version string:                                          CP2K version 8.1
 CP2K| source code revision number:                                  git:0b61f2f
 CP2K| cp2kflags: omp libint fftw3 libxc elpa parallel mpi3 scalapack acc smm_dn
 CP2K|            n smm dbcsr_acc max_contr=4
 CP2K| is freely available from                            https://www.cp2k.org/
 CP2K| Program compiled at                          Wed Mar 17 13:15:24 CET 2021
 CP2K| Program compiled on                                              daint101
 CP2K| Program compiled for                                CP2K-8.1-CrayGNU-cuda
 CP2K| Data directory path    /apps/daint/UES/jenkins/7.0.UP02-20.11/gpu/easybui
 CP2K| Input file name                                                 aiida.inp`
 
 and
 
 `CP2K| version string:                                          CP2K version 7.1
 CP2K| source code revision number:                                  git:e635599
 CP2K| cp2kflags: omp libint fftw3 libxc elpa parallel mpi3 scalapack acc smm_dn
 CP2K|            n smm dbcsr_acc max_contr=4
 CP2K| is freely available from                            https://www.cp2k.org/
 CP2K| Program compiled at                          Wed Mar 17 13:03:11 CET 2021
 CP2K| Program compiled on                                              daint101
 CP2K| Program compiled for                                CP2K-7.1-CrayGNU-cuda
 CP2K| Data directory path    /apps/daint/UES/jenkins/7.0.UP02-20.11/gpu/easybui
 CP2K| Input file name                                                 aiida.inp`
 
 Can somebody help me what went wrong? I have the same issue with different metal-organic frameworks

**Comment by mkrack** [comment]
Try to add
```
 PREFERRED_DIAG_LIBRARY SL
```
in the `&GLOBAL` section

**Comment by mpougin** [comment]
[geo_opt.txt](https://github.com/cp2k/cp2k/files/7417656/geo_opt.txt)
Thank you for your help
[geo_opt.txt](https://github.com/cp2k/cp2k/files/7417653/geo_opt.txt)
 @mkrack. It is working now, but I am a bit confused as I am a quite new CP2K user. I don't use diagonalization but OT (running input script attached). How could specifying the diagonalization library make a difference?

**Comment by mkrack** [comment]
The `PRECONDITIONER FULL_ALL` involves a diagonalization.

**Comment by mpougin** [comment]
thank you

**Comment by ltalirz** [comment]
Thanks for the quick help @mkrack !

Do I understand correctly that the default diagonalization method changed?
Or do you suspect it is a problem with the ELPA version?

Miriam reported that, in her trial run, for 4 out of 5 metal-organic frameworks the geometry optimization failed to converge with cp2k 8.1 while they converged just fine with cp2k 7.1 (with identical input).

**Comment by mkrack** [comment]
It seems that the redistribution scheme implemented in CP2K may run into a deadlock with recent ELPA versions (see #1599)
