### ISSUE TITLE
manual.cp2k.org lists wrong version for branches

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#1756]
Example: https://manual.cp2k.org/cp2k-8_2-branch/CP2K_INPUT/FORCE_EVAL/PW_DFT/PARAMETERS.html

I get at the top: `Input reference of CP2K version 9.0`

For branch 8.1 I get 8.0, etc.

**Comment by oschuett** [comment]
I guess, I used the wrong branch for generating those html pages. Unfortunately, this is still a [manual process](https://www.cp2k.org/dev:release_checklist). Feel free to run `sed -i` on the server to fix this.

Long term I'd really like to have only a single set of html pages that contain the information about all versions.

**Comment by mkrack** [comment]
The input references for the CP2K versions 7.1, 8.1, and 8.2 have been regenerated with the respective code versions and then uploaded.
