### ISSUE TITLE
Dashboard test log: mismatch in NVCC versions

### ISSUE THREAD

**Issue by shoshijak** [cp2k/cp2k#180]
The `CRAY_XC50-gfortran_gpu.psmp` [test log](https://www.cp2k.org/static/regtest/trunk/cscs-daint-xc50_gpu_perf/CRAY_XC50-gfortran_gpu.psmp.out) on the CP2K dashboard reports contradicting `cudatoolkit`/ `NVCC` versions. 

In the section `ARCHITECTURE FILE`, **CUDA 8**: 

```
################# ARCHITECTURE FILE ##################
# === For Cray XC50 (PizDaint GPU-partition) ====
# Program environments:
#
# module load daint-gpu
# module unload PrgEnv-cray
# module load PrgEnv-gnu/6.0.4
# module load fftw/3.3.4.10
# module load cudatoolkit/8.0.61_2.4.3-6.0.4.0_3.1__gb475d12
```

In the section `toolversions`, **CUDA 9**:
```
========== NVCC (psmp) ==========
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
```

**Comment by alazzaro** [comment]
Thanks for reporting it. It is clearly an outdated comment, the code is using CUDA 9. 
I have fixed it (it will be updated in the next run).

**Comment by dev-zero** [comment]
The lines reported unter `ARCHITECTURE FILE` are from the arch file used and are comments  (compare the distributed arch files in `arch/`) which are ignored afaik. The modules are usually loaded by  a wrapper or batch script which runs the regtest.

**Comment by shoshijak** [comment]
Thank you!
