### ISSUE TITLE
ELPA setup prints to standard output

### ISSUE THREAD

**Issue by juerghutter** [cp2k/cp2k#1821]
Since the latest update of the ELPA library, a call to elpa_obj%setup() results in an output of

 In ELPA setup
 MPI_COMM_PARENT is set

This output appears n times at each call to the setup routine, where n is > 1 and <= NCPU.
This causes a spamming of the CP2K output file.

**Comment by mkrack** [comment]
I have recognized that too. We can switch back to 2021.05.002 for the CP2K release.

**Comment by dev-zero** [comment]
https://elpa.mpcdf.mpg.de/software/tarball-archive/ELPA_TARBALL_ARCHIVE.html lists a final `2021.11.001`. As well as a `2021.05.002_bugfix` (which might be a good alternative to `2021.05.002`).

**Comment by hfp** [comment]
I believe there is some disagreement about printing and verbosity. It seems a similar issue was discovered for SIRIUS in the past. Perhaps it only helps to clarify the desired policy. IMHO, I believe libraries should not be printing anything or considering the console output as "NO NO" unless an API permits output (`set_verbosity_level`) or perhaps an API taking an "output unit" or (symbolic) stream/file descriptor like `stdout` or `stderr`. Similar issues are related to calling `exit` in library based code. Before relying on a dependency, it could be useful to ensure such policy upfront.

**Comment by mkrack** [comment]
> https://elpa.mpcdf.mpg.de/software/tarball-archive/ELPA_TARBALL_ARCHIVE.html lists a final `2021.11.001`. As well as a `2021.05.002_bugfix` (which might be a good alternative to `2021.05.002`).

Thanks @dev-zero. With having the release `2021.11.001` now out, we should give a try to that latest release. It seems that `print*` statements are only used when an error occurs like in the previous release.

**Comment by mkrack** [comment]
The release version `2021.11.001` seems to work and it does not spam the CP2K output with info messages.
