### ISSUE TITLE
Segmentation faults with TDDFPT-LRI tests

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#1822]
The tests in `QS/regtest-tddfpt-lri` are failing with the Intel, ARM, i386, and CUDA (Pascal) regression tests. The issue persists for the Intel compiler with `-O0 -g` using only one MPI task and one OMP thread.

**Comment by mkrack** [comment]
The TDDFPT-LRI tests are still failing with Intel 20.4 (19.1.3), i386 and ARMv7l after #1825.

**Comment by oschuett** [comment]
Fixed via #1837.
