### ISSUE TITLE
An error occurred in MPI_Comm_set_errhandler

### ISSUE THREAD

**Issue by xiongxiaojun** [cp2k/cp2k#1831]
when run cp2k.psmp -v(mpirun -np 4 cp2k.psmp test.inp |tee test.out), the error occurred as shown belowas follows.
An error occurred in MPI_Comm_set_errhandler
reported by process
con communicator MPI_COMM_WORLD
MPI_ERR_COMM:invalid communicator
MPI_ERRORS_ARE_FATAL(process in this communicator will now abort，and potentially your MPI job)
（got the exe，not working）

![image](https://user-images.githubusercontent.com/33369568/147475762-f85d7aed-8846-45a2-a239-256bd020cfed.png)

**Comment by dev-zero** [comment]
Please post the output of the following commands:

- `command -v cp2k.psmp`
- `ldd $(command -v cp2k.psmp)`
- `command -v mpirun`

... and share some details on how this executable was obtained (e.g. build steps, etc.)
