### ISSUE TITLE
Incorrectly chosen directories with regtest script

### ISSUE THREAD

**Issue by fstein93** [cp2k/cp2k#1832]
Calling the regtest script with TESTOPTS="--restrictdir QS/regtest-ri-mp2" also checks the regtest directory QS/regtest-ri-mp2-opt .

**Comment by oschuett** [comment]
The behavior of `--restrictdir` has [slightly changed](https://github.com/cp2k/cp2k/blob/99008e90fad2a617e3b7ae4db50a5f9e7516677e/tools/regtesting/do_regtest.py#L124) with the new `do_regtest.py` script. 

Maybe we should call [`re.fullmatch`](https://docs.python.org/3/library/re.html#re.fullmatch) instead?

**Comment by fstein93** [comment]
I am in favor of re.fullmatch to reflect the former behavior. At least, the new behavior is not documented for the user. In my case, I am just interested in testing regtest-ri-mp2, not in the other directory.
