### ISSUE TITLE
Sort out toolchain mathlibs (follow up to #159)

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#185]
Just a reminder to follow up on #159.

**Comment by oschuett** [comment]
Thanks @dev-zero !

**Comment by dev-zero** [comment]
please note: this is yet another band-aid. The proper solution would be to build everything except maybe binutils/gcc/valgrind/... for each combination of MPI/no-MPI, OMP/no-OMP and CUDA/no-CUDA. But at this point we would be replicating what EasyBuild or Spack have solved already.
