### ISSUE TITLE
Some regtests fail on ARM (aarch64)

### ISSUE THREAD

**Issue by Tom-python0121** [cp2k/cp2k#1855]
Hello, I meet a problem:cp2k@9.1  test failed on centos8_aarch64.
### Steps to reproduce the issue

```console
[root@localhost ~]git clone --recursive https://github.com/cp2k/cp2k.git cp2k
[root@localhost ~]cd cp2k
[root@localhost cp2k]#cd tools/toolchain
[root@localhost cp2k]#./install_cp2k_toolchain.sh --with-libxsmm=no  --with-libvori=no
[root@localhost cp2k]#cd ../..
[root@localhost cp2k]#cp tools/toolchain/install/arch/* arch/
[root@localhost cp2k]#source /tools/toolchain/install/setup
[root@localhost cp2k]#yum install liblsan.aarch64 gcc-toolset-10-liblsan-devel.aarch64
[root@localhost cp2k]#make -j 128 ARCH=local VERSION="ssmp sdbg"
[root@localhost cp2k]#make -j 128 ARCH=local VERSION="ssmp sdbg" test
……
    cc2_lri.inp                                                                    OK (  11.08 sec)
<<< /home/stage/root/spack-stage-cp2k-9.1-d2yemk6wqui237fwkyhdwezq6yl3jt5c/spack-src/regtesting/TEST-local-ssmp-2022-01-04_17-02-45/QS/regtest-kp-2 (286 of 286) done in 382.49 sec
------------------------------- Errors ---------------------------------
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
/home/stage/root/spack-stage-cp2k-9.1-d2yemk6wqui237fwkyhdwezq6yl3jt5c/spack-src/regtesting/TEST-local-ssmp-2022-01-04_17-02-45/QS/regtest-gw-cubic/G0W0_kpoints_from_Gamma.inp.out
Difference too large: 7.56e-02 > 1e-05, ref_value: 14.55, value: 13.45.
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
/home/stage/root/spack-stage-cp2k-9.1-d2yemk6wqui237fwkyhdwezq6yl3jt5c/spack-src/regtesting/TEST-local-ssmp-2022-01-04_17-02-45/QS/regtest-gw-cubic/G0W0_kpoints_from_Gamma_RI_regularization_1E-3.inp.out
Difference too large: 1.18e-01 > 1e-05, ref_value: 14.71, value: 12.97.
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
/home/stage/root/spack-stage-cp2k-9.1-d2yemk6wqui237fwkyhdwezq6yl3jt5c/spack-src/regtesting/TEST-local-ssmp-2022-01-04_17-02-45/QS/regtest-hfx-ri-2/H2O-hfx-stress-identity.inp.out
Difference too large: 4.68e-01 > 1e-08, ref_value: 8.19144120830E-01, value: 4.35583649823E-01.
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
/home/stage/root/spack-stage-cp2k-9.1-d2yemk6wqui237fwkyhdwezq6yl3jt5c/spack-src/regtesting/TEST-local-ssmp-2022-01-04_17-02-45/xTB/regtest-5/AdeThyvdW.inp.out


Timed out after 400.09734279010445 seconds.

------------------------------- Timings --------------------------------
Plot: name="timings", title="Timing Distribution", ylabel="time [s]"
PlotPoint: name="100th_percentile", plot="timings", label="100th %ile", y=400.10, yerr=0.0
PlotPoint: name="99th_percentile", plot="timings", label="99th %ile", y=103.18, yerr=0.0
PlotPoint: name="98th_percentile", plot="timings", label="98th %ile", y=75.22, yerr=0.0
PlotPoint: name="95th_percentile", plot="timings", label="95th %ile", y=44.12, yerr=0.0
PlotPoint: name="90th_percentile", plot="timings", label="90th %ile", y=25.62, yerr=0.0
PlotPoint: name="80th_percentile", plot="timings", label="80th %ile", y=12.04, yerr=0.0

------------------------------- Summary --------------------------------
Number of FAILED  tests 1
Number of WRONG   tests 3
Number of CORRECT tests 3609
Total number of   tests 3613

Summary: correct: 3609 / 3613; wrong: 3; failed: 1; 10min
Status: FAILED

*************************** Testing ended ******************************
make[3]: *** [/home/stage/root/spack-stage-cp2k-9.1-d2yemk6wqui237fwkyhdwezq6yl3jt5c/spack-src/Makefile:266: test] Error 4
make[2]: *** [/home/stage/root/spack-stage-cp2k-9.1-d2yemk6wqui237fwkyhdwezq6yl3jt5c/spack-src/Makefile:163: test] Error 2
make[1]: *** [/home/stage/root/spack-stage-cp2k-9.1-d2yemk6wqui237fwkyhdwezq6yl3jt5c/spack-src/Makefile:140: ssmp] Error 2
make[1]: *** Waiting for unfinished jobs....
```
Can you help me?This seems to have something to do with the tolerance.

**Comment by mkrack** [comment]
This is a known issue for aarch64 as shown by the [Linux-arm64-gnu.psmp (11.2.0)](https://www.cp2k.org/static/regtest/trunk/Linux-arm64-gnu/psmp/regtest-0) and [Linux-armv7l-gnu.psmp (8.3.0)](https://www.cp2k.org/static/regtest/trunk/Linux-armv7l-gnu/psmp/regtest-0) regression testers on the [CP2K dashboard](https://dashboard.cp2k.org) since a while. It could not be resolved before the v9.1 release.

**Comment by Tom-python0121** [comment]
@mkrack Thank you. Will there be any patch after the next version is released?

**Comment by mkrack** [comment]
The reason for the numerical deviations on aarch64 is not understood yet. It affects, however, only a few (2-3 out of 3000+) tests related to features implemented quite recently.

**Comment by mkrack** [comment]
Update: The following tests are still failing with GNU aarch64
```
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
/home/pi/github/cp2k/cp2k/regtesting/TEST-Linux-gnu-aarch64-psmp-2022-01-27_01-56-38/QS/regtest-rs-dhft/CH3-rsLDAlrMP2.inp.out
Difference too large: 3.87e-04 > 1e-08, ref_value: -7.337744306690559, value: -7.340586990610659.
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
/home/pi/github/cp2k/cp2k/regtesting/TEST-Linux-gnu-aarch64-psmp-2022-01-27_01-56-38/QS/regtest-gw-cubic/G0W0_kpoints_from_Gamma.inp.out
Difference too large: 2.92e-01 > 1e-05, ref_value: 14.55, value: 10.30.
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
/home/pi/github/cp2k/cp2k/regtesting/TEST-Linux-gnu-aarch64-psmp-2022-01-27_01-56-38/QS/regtest-gw-cubic/G0W0_kpoints_from_Gamma_RI_regularization_1E-3.inp.out
Difference too large: 3.17e-01 > 1e-05, ref_value: 14.71, value: 10.05.
```

**Comment by oschuett** [comment]
I found that all regtests pass on ARM64 when I comment out the following two lines:
https://github.com/cp2k/cp2k/blob/a213519a15191f11b61658d664e7104f22d1fbf8/src/rpa_im_time.F#L317
https://github.com/cp2k/cp2k/blob/a213519a15191f11b61658d664e7104f22d1fbf8/src/rpa_im_time.F#L491

@JWilhelm @abussy

**Comment by JWilhelm** [comment]
Great that you found this, @oschuett. I also have issues with "dbt_batched_contract_init" and "dbt_batched_contract_finalize" in periodic GW either producing wrong numbers or enormous memory overhead. It is currently unclear to me, whether commenting line 317 and line 491 in rpa_im_time.F will affect the performance or the memory consumption in low-scaling RPA/SOS-MP2/GW. So, I'm not sure whether we can just comment these two lines to fix the ARM64 regtests.

@abussy Do you have any recommondation on this issue? Or should we try to ask Patrick Seewald?

**Comment by abussy** [comment]
It's interesting that this particular call to "dbt_batched_contract_init" and "dbt_batched_contract_finalize" causes the ARM regtest to fail. This pattern of initialization and finalization of the batched contraction is used throughout the code, wherever there are sparse tensor contractions.

There is one notable difference though: I generally do not see "dbt_batched_contract_finalized" used with more than 1 argument. I wonder if passing a unit_nr may be the culprit there. A quick grep confirms that this is the only instance in the code. I would try that.

**Comment by oschuett** [comment]
Unfortunately, just removing the `unit_nr` does not help.

>  Or should we try to ask Patrick Seewald?

Yes, we could try that. However, he hasn't worked on CP2K for over two years. So probably somebody has to spend a week of focus time to read the code and [his thesis](https://www.cp2k.org/_media/docs:phd_thesis_patrick_seewald.pdf) to re-learn how `dbt_contract` actually works.

**Comment by abussy** [comment]
Are the failing regtests only those involving K-points? Because I also see in the same file `rpa_im_time.F`, that the `init` and `finalize` routines are called on the `t_dm_occ` and `t_dm_virt` tensors only in case of Gamma point calculation. Maybe there is a link?

**Comment by oschuett** [comment]
We've got our first ARM64 regtest run that [passed](https://dashboard.cp2k.org/archive/arm64-psmp/commit_05f53a495c80b823b1fc428a2384f400b82581f6.txt).

**Comment by Tom-python0121** [comment]
@oschuett yes,I have passed.
![image](https://user-images.githubusercontent.com/77763324/209593805-1ce00a0b-96e4-4b0a-8efa-df56c4b744d3.png)
