### ISSUE TITLE
OMP standard violation in grid_collocate_dgemm.c

### ISSUE THREAD

**Issue by SpinTensor** [cp2k/cp2k#1858]
Hi,

the source file `src/grid/cpu/grid_collocate_dgemm.c` contains several OMP pragmas of the form `#pragma omp simd linear([list]) simdlen(X)`. In some instances the list in the `linear` clause contains pointers which are marked `const`. The first occurence is in line 221.
According to the OMP standard v5.0 section 2.19.4.6 "the *linear* clause  declares one or more list items to be private [...]". However Section 2.19.3 states in the restrictions for privatized variables "A variable that is privatized must not have a const-qualified type [...]".
Therefore, the code in `grid_collocate_dgemm.c` clearly violates the OMP standard.
This does not seem to matter for the gcc compiler, which simply accepts it, but more strict and standard compliant compilers abort with an error message at this point. Since these pointers seem to be local to the loops anyways, I don't see a reason why they need to be marked `const`.

**Comment by oschuett** [comment]
CC @mtaillefumier

**Comment by mtaillefumier** [comment]
it seems to break even openmp 4.5. They give no reasons for that though. Fixing this is straightforward.

**Comment by oschuett** [comment]
Fixed via #1913.
