### ISSUE TITLE
Missing data-sharing clause in OMP PARALLEL region

### ISSUE THREAD

**Issue by SpinTensor** [cp2k/cp2k#1859]
Hi,

in the file `src/qs_tensors.F` there are two `OMP PARALLEL` regions (lines 1354 and 1982). With the `DEFAULT(NONE)` clause it is necessary to specify the data shared attribute for every variable, which is accesses within the region. The variable `i` is omitted although it is referenced in both regions. once in line 1462 and once in line 2091. `i` is used in this context as an implicit loop variable, thus should be declared private, if I'm not mistaken.

**Comment by dev-zero** [comment]
For the refactoring of the HFX OpenMP parallelisation I've looked into this as well, and as far as I understood the [OpenMP standard](https://www.openmp.org/spec-html/5.1/openmpsu113.html) are implicit loop variables (despite being declared at the beginning of the function body in Fortran) automatically declared private, hence do not need extra `PRIVATE` declarations.
On the other hand this behavior also seems compiler and optimization level dependent as I had a case where the compiler (I believe it was the classical Intel) suddenly showed warnings about such a variable when I refactored other parts of the OMP parallel region.

**Comment by SpinTensor** [comment]
Yeah, you are right. The section you posted mentions: "*Implied-do*, FORALL and DO CONCURRENT indices are private." Sorry, that I missed that. I will close this issue.
