### ISSUE TITLE
Fix performance of COSMA with OpenMP

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#1861]
The toolchain already enables [threading for OpenBLAS](https://github.com/cp2k/cp2k/blob/cdcb2793be4c6302478245ba22b1e8c038bd7787/tools/toolchain/scripts/stage2/install_openblas.sh#L97), which [should](https://github.com/cp2k/cp2k/issues/1826#issuecomment-999544877) do the trick.

However, for some reason our [performance test](https://dashboard.cp2k.org/archive/perf-openmp/index.html) still show that COSMA does not take advantage of threads.

Furthermore, the performance fluctuates by 2x:

![GW_PBE_4benzene_timings_32omp](https://user-images.githubusercontent.com/241771/148387230-a8df3787-f168-4653-a0e1-1848cf1d182f.png)

**Comment by fstein93** [comment]
I have found similar issues with the MP2 gradient code. In my case on Daint/GPU, the execution time of COSMA increased by a factor of 6 or 7 (I have to look it up) when I changed the number of threads per rank from 1 to 4 (there is no significant change from 1 to 2). @kabicm told me by mail, we should wait for the next release this month. It is supposed to include some performance improvements.

**Comment by abussy** [comment]
Do we know for sure that this issues lies with OpenMP only? I have observed roughly a 10x slowdown in the performance of COSMA pdgemm when built with OpenBLAS versus MKL or LIBSCI. I just oppened an issue on the subjet: #1870.

**Comment by kabicm** [comment]
Is this issue resolved with https://github.com/cp2k/cp2k/issues/1870#issuecomment-1011235055, or is it still an ongoing problem?

**Comment by kabicm** [comment]
@fstein93 does https://github.com/cp2k/cp2k/issues/1870#issuecomment-1011235055 also resolve the issue you reported to me?

**Comment by oschuett** [comment]
Thanks for looking into this! I believe `USE_OPENMP=1` [implies](https://github.com/xianyi/OpenBLAS/blob/5188aede5dfdc2703ed730c6dade96631c2b0e3a/Makefile.system#L580) `USE_THREAD=1`, but I'll definitely try `NO_AFFINITY=1`.

**Comment by oschuett** [comment]
Unfortunately, [setting `NO_AFFINITY=1`](https://github.com/cp2k/cp2k/pull/1872)  did not do the trick. So, COSMA + OpenMP is still very much an open problem:

![image](https://user-images.githubusercontent.com/241771/155578755-d3833938-bf2d-4e28-a1a7-4eeeb376fa4a.png)

**Comment by kabicm** [comment]
@oschuett Thanks Ole! I would like to have a look into this, as we are working on a new release at the moment. How can I reproduce these tests on daint?

**Comment by kabicm** [comment]
Let me just check one more thing: from my experience, these oscillations usually happen when `--cpu_bind=sockets` is not set. In that case, the performance of local blas gemm oscillates 2x, which as a consequence also affects COSMA. Did you try setting the `--cpu_bind` option in slurm?

**Comment by oschuett** [comment]
These results are not from Daint, they are from GCP where they run on Intel Skylake.

Unfortunately, the behavior seems to be rather flaky. So, I could for example not reproduce it on my AMD Threadripper. Nevertheless, you should give it a try - this is [the input file](https://github.com/cp2k/cp2k/blob/master/benchmarks/QS_single_node/GW_PBE_4benzene.inp).

In the meantime, I've added `-bind-to socket` to our performance tests (https://github.com/cp2k/cp2k/commit/b4b7b1df51f45917a366a6574541801c63b708bf).

**Comment by oschuett** [comment]
> Aren't the valid commands: `--bind-to socket`, `-bind-to-socket` and `--bind-to-socket` instead of `-bind-to socket`? [source]( https://www.open-mpi.org/doc/v3.0/man1/mpirun.1.php). 

I believe this depends on the MPI library. Here we're using MPICH.

In any case, it didn't help. Hence, I took a closer look and it turns out the node is single-socket:

```
$ hwloc-info 
depth 0:           1 Machine (type #0)
 depth 1:          1 Package (type #1)
  depth 2:         1 L3Cache (type #6)
   depth 3:        32 L2Cache (type #5)
    depth 4:       32 L1dCache (type #4)
     depth 5:      32 L1iCache (type #9)
      depth 6:     32 Core (type #2)
       depth 7:    64 PU (type #3)
Special depth -3:  1 NUMANode (type #13)
Special depth -4:  1 Bridge (type #14)
Special depth -5:  1 PCIDev (type #15)
Special depth -6:  1 OSDev (type #16)
```

... at least that's what the VM reports. According to [this doc](https://cloud.google.com/architecture/best-practices-for-using-mpi-on-compute-engine#use_compute-optimized_instances) I might be using the wrong instance type (N1 instead of C2 or C2D).

Then again, all our other timings are pretty steady. Also I feel like 2x is too much and too reproducible to be caused only by sub-optimal scheduling.

**Comment by alazzaro** [comment]
My 2c. COSMA is running DGEMM that is a compute intensive task. It just uses OpenMP, so at least a CPU affinity for threads should be applied (OMP_PLACES...). Even though, any jitter by the OS, including the fact that you are running on a VM instance, can impact on performance, so I would say a 2x effect can be expected. For instance, I assume you are using virtual memory, OS uses to run on core 0, MPI can spawn threads for communications...  

The best way to check the performance stability would be to run a bare-metal system, with affinity, leave some cores empty... i.e. a Supercomputer... If it doesn't work, then you can decide to enable some low-level profiling.

**Comment by oschuett** [comment]
Oh wow, #2021 was quite a trick! The timings for  `cp_gemm_cosma` literally [plunged off the chart](https://dashboard.cp2k.org/archive/perf-openmp/GW_PBE_4benzene_timings_32omp.txt).

This is a good illustration of how difficult it is to integrate so many libraries. It took us [over two years](https://github.com/cp2k/cp2k/pull/648) to get COSMA working!
