### ISSUE TITLE
CCE warning on "variable is used before it is defined."

### ISSUE THREAD

**Issue by alazzaro** [cp2k/cp2k#1862]
It can be a false positive, I haven't checked that...

```
ftn-7212 crayftn: WARNING ANGULAR_D, File = ../../../../../home/users/alazzaro/cp2k/CP2K_AUTO_REGTEST/CRAY-XC40-cce/psmp/cp2k/src/manybody_gal21.F, Line = 737 
  Variable "rjh2" is used before it is defined.
  ```

**Comment by oschuett** [comment]
Wasn't this fixed by #1767?

**Comment by alazzaro** [comment]
> Wasn't this fixed by #1767?

Indeed, it seems a false positive... It complains on the `rjh2(2)` entry, but we actually set that...

**Comment by oschuett** [comment]
There definitely was an issue before my fix. So, maybe you are looking at an old version of the code?

**Comment by alazzaro** [comment]
Well, no, it is running the current master...

**Comment by oschuett** [comment]
Since the [CCE tester](https://dashboard.cp2k.org/archive/cce865-psmp/index.html) managed to build CP2K, this seems to have been resolved.
