### ISSUE TITLE
Adapt CP2K ELPA wrapper to new ELPA API

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#189]
ELPA has a new API (introduced in 2017.05.001): 

https://gitlab.mpcdf.mpg.de/elpa/elpa/blob/master/SWITCHING_TO_NEW_INTERFACE.md

we have to switch since the old API will be removed at some point.

**Comment by oschuett** [comment]
I think this already happened. In fact we have grown quite used to ELPA [changing their API](https://github.com/cp2k/cp2k/blob/master/src/fm/cp_fm_elpa.F) with almost every release. Currently, we support up to version `2017.11` .

**Comment by dev-zero** [comment]
> I think this already happened. 

No, it hasn't. CP2K even still builds with elpa-2018.11 [with minimal patches](https://github.com/dev-zero/cp2k/tree/feature/elpa-2018.11-support) but gives different results (at least when I checked last time pre-drop of `-ffast-math`).

> In fact we have grown quite used to ELPA [changing their API](https://github.com/cp2k/cp2k/blob/master/src/fm/cp_fm_elpa.F) with almost every release. 

So? Someone still has to do it.
