### ISSUE TITLE
add topic quantum-chemistry

### ISSUE THREAD

**Issue by Beliavsky** [cp2k/cp2k#1892]
Please consider adding the topic quantum-chemistry in the About section.

**Comment by oschuett** [comment]
Thanks a lot for the suggestion! I've now added the following topics (feel free to suggest more):
 - simulation
 - hpc
 - quantum-chemistry
 - material-science

Generally, if you interested in discoverability et al., I think our [landing page](https://github.com/cp2k/cp2k/blob/master/README.md) could also use some touching up...
