### ISSUE TITLE
cp2k-ci: include details in failed checks

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#19]
For example here: https://github.com/cp2k/cp2k/runs/21516830

The users can't possibly know what actually failed or what they would have to do to remedy the situation.
Furthermore, clicking the *view more details* leads back to the (almost) same page.

**Comment by oschuett** [comment]
I changed the message. See e.g.: https://github.com/cp2k/cp2k/pull/34/checks?check_run_id=22415485
In the future I could also add a link to some wiki page for more help.

**Comment by dev-zero** [comment]
but the link still points to the same page, doesn't it?

**Comment by oschuett** [comment]
Yes, it seems I can not remove that link. So, the best thing would be if we had a wiki page with instructions to which we could link.

**Comment by dev-zero** [comment]
https://github.com/cp2k/cp2k/wiki/CP2K-CI#git-history-contains-merge-commits if you can use a variable in the link (for example the name of description of the check), otherwise simply link to https://github.com/cp2k/cp2k/wiki/CP2K-CI#checks ?

**Comment by oschuett** [comment]
Ok, that small persisting link at the bottom now always points to https://github.com/cp2k/cp2k/wiki/CP2K-CI.

I moved the links that actually relate to the test results to the output section where I can use Markdown. Have a look:
* https://github.com/cp2k/cp2k/pull/25/checks?check_run_id=22759873
* https://github.com/cp2k/cp2k/pull/36/checks?check_run_id=22757215

**Comment by dev-zero** [comment]
looks good, thanks!
