### ISSUE TITLE
Comiling cp2k-master-20220206 with some warnings

### ISSUE THREAD

**Issue by alas-go** [cp2k/cp2k#1929]
Thanks god. cp2k-master has been successfully compiled on RockyLinux 8.5 OS with mkl 2020.4 and openmpi 4.1.1 but something about plumed 2.7.3 warning printed on the screen. The compiling method is toolchain with all functional packages without GPU and cuda. All scripts under the path-tool/toolchain/scripts are kept unchanged.

After type make -j 8 ARCH="psmp" test and press the Enter key, it prints something about git and some tests about QS were not carried out.

[warnings-about-plumed.txt](https://github.com/cp2k/cp2k/files/8009316/warnings-about-plumed.txt)
[QS-test-not-satified.txt](https://github.com/cp2k/cp2k/files/8009322/QS-test-not-satified.txt)
[warnings-about-git.txt](https://github.com/cp2k/cp2k/files/8009323/warnings-about-git.txt)

**Comment by oschuett** [comment]
All three warnings are benign and nothing to worry about:

> [QS-test-not-satified.txt](https://github.com/cp2k/cp2k/files/8009322/QS-test-not-satified.txt)

Those three test directories [require](https://github.com/cp2k/cp2k/blob/master/tests/TEST_DIRS) >2 mpi ranks. So, essentially they are never executed :-(

> [warnings-about-git.txt](https://github.com/cp2k/cp2k/files/8009323/warnings-about-git.txt)

This warning only means that your binary won't know from which git revision it was built.

> [warnings-about-plumed.txt](https://github.com/cp2k/cp2k/files/8009316/warnings-about-plumed.txt)

This has already been fixed upstream: https://github.com/plumed/plumed2/commit/ee230efca6082f3337b4c97c1b3ead69b9e9b30b. We just have to wait for their next release.

**Comment by alas-go** [comment]
Thanks.
Upload some errors tested for your references.
it was tested on my laptop with RockyLinux 8.5. Plumed-master on 20220207 was downloaded for compiling.
[error_summary.txt](https://github.com/cp2k/cp2k/files/8022126/error_summary.txt)
