### ISSUE TITLE
Re-run failed regtests

### ISSUE THREAD

**Issue by fstein93** [cp2k/cp2k#1940]
I haven't found this option in the new do_regtest script but it was available in the old one: Retesting failed tests of the last run.

**Comment by fstein93** [comment]
It might also be interesting to have an option to explicitly skip certain directories.

**Comment by oschuett** [comment]
I've implemented `--skipdir` via https://github.com/cp2k/cp2k/commit/ccdbba7e9032a0e5bf9b6f8902d18b8bc6b9a77a.

I actually don't want to implement the re-run feature because regtest reports are difficult to parse and I feel it would bloat the `do_regtest.py` script unreasonably.
