### ISSUE TITLE
[How it works? ]function ortho_cx_to_grid has many vectorized assembly versions 

### ISSUE THREAD

**Issue by codyhu** [cp2k/cp2k#1944]
Hey guys, when I looked at the gcc assembly code of `ortho_cx_to_grid_scalar`, in` src/grid/ref/grid_ref_collint.h` , I found a very interesting phenomenon, it has many different versions of vectorized loops, which seems to be good for running performance?
![image](https://user-images.githubusercontent.com/17926010/153837634-fb37a466-5310-4619-ac3d-9f2ed01499a9.png)

And `icc` even has its own special assembly version code
![image](https://user-images.githubusercontent.com/17926010/153837801-140709bb-a489-42fb-9b26-3cd0ded8f9c8.png)

This seems to be related to pragma unroll? Was cp2k designed with this scenario in mind? How does it work?

**Comment by oschuett** [comment]
Hi @codyhu, I wrote that code and I'm happy to answer any questions you might have.

We currently have two implementation: A generic one in plain C and an optimized one for AVX2, ie. Intel/AMD CPUs. The [Intel Intrinsics](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#techs=AVX2) are a convenient way to issue inline assembly instructions. Despite its name they are supported by all major C compilers.

The unroll pragmas are mostly meant to increase instruction level parallelism. In [some cases](https://github.com/cp2k/cp2k/blob/2f1076a9662081232f36ba214e302baf46fa0acc/src/grid/ref/grid_ref_collint.h#L299) I also used them to generate different branches. In C++ one could use templates for that purpose instead.

**Comment by codyhu** [comment]
Thx a lot @oschuett , it is really a good job. And I found it 
![image](https://user-images.githubusercontent.com/17926010/154066289-27cbd9a0-05c3-4b90-89cd-d12269958e2c.png). It's the first time I've seen this way of writing, but it does have some significant performance benefits.
