### ISSUE TITLE
compatablity of xz format in the master

### ISSUE THREAD

**Issue by alas-go** [cp2k/cp2k#1947]
in line 46 of ./scripts/stage6/install_plumed.sh, -xvf is much better than -xzf

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
ERROR: (./scripts/stage6/install_plumed.sh, line 46) Non-zero exit code detected.

**Comment by oschuett** [comment]
It seems the archive got somehow unpacked or corrupted on your disk. Remove it and try again. Generally, the toolchain is tested daily and works fine.

We should really get around to implement #1807.
