### ISSUE TITLE
[feature request] add stress tensor for metagga

### ISSUE THREAD

**Issue by robinzyb** [cp2k/cp2k#1948]
same as title

**Comment by fstein93** [comment]
They are already available for metaGGA-functionals depending on the kinetic energy density only (without double-hybrids or Harris functional etc.). The extension to double-hybrids is work in progress. I have to see whether I will find the time for Laplacian-dependent functionals.

**Comment by robinzyb** [comment]
> They are already available for metaGGA-functionals depending on the kinetic energy density only (without double-hybrids or Harris functional etc.). The extension to double-hybrids is work in progress. I have to see whether I will find the time for Laplacian-dependent functionals.

Thank you for replying so quickly.  Now I'm using SCAN functional from libxc in cp2k v7.1. Does the stress tensor implement in higher version of cp2k like v8.2 or later? I would appreciate if you could tell me the version.

**Comment by robinzyb** [comment]
I found it in v8.1. thanks again. I will close the issue

**Comment by robinzyb** [comment]
> They are already available for metaGGA-functionals depending on the kinetic energy density only (without double-hybrids or Harris functional etc.). The extension to double-hybrids is work in progress. I have to see whether I will find the time for Laplacian-dependent functionals.

Hi, recently, I used SCAN to perform CELL_OPT with v8.2. The CELL OPT with CG or LBFGS quickly predicts steps to numerical zero with large forces and pressure(optimization is stuck, of course). After I changed to Numerical Stress Tensor, the optimization converged after 25 steps. I'm not familiar with the details of metagga. Is this related with the "available for metaGGA-functionals depending on the kinetic energy density only" or something other problem?

**Comment by fstein93** [comment]
No. If you try to use a functional depending on the Laplacian of the electron density with analytical stress tensors, you will receive an error. Can I see your setup? A common problem of metaGGA functionals are the integration grids as they have to be very fine for properly converged results. Maybe, your geometry was off the equilibrium point.

**Comment by robinzyb** [comment]
[files.zip](https://github.com/cp2k/cp2k/files/8160419/files.zip)
coord.xyz is bulk hematite structure from experiment.

**Comment by fstein93** [comment]
Can you rerun the calculation with a higher cutoff (1200 Ry?).
@juerghutter : Do you have any ideas?

**Comment by fstein93** [comment]
It can also help to change the configurations in the [XC_GRID](https://manual.cp2k.org/trunk/CP2K_INPUT/FORCE_EVAL/DFT/XC/XC_GRID.html) section. But I am not sure which is compatible with stress tensor calculations. Some of them redefine the total energies.

**Comment by robinzyb** [comment]
> Can you rerun the calculation with a higher cutoff (1200 Ry?).
> @juerghutter : Do you have any ideas?

rerun the structures or restart another cell optimization?

**Comment by robinzyb** [comment]
> It can also help to change the configurations in the [XC_GRID](https://manual.cp2k.org/trunk/CP2K_INPUT/FORCE_EVAL/DFT/XC/XC_GRID.html) section. But I am not sure which is compatible with stress tensor calculations. Some of them redefine the total energies.

XC_SMOOTH can accelerate SCF converge, which is better achieved by higher cutoff.

**Comment by robinzyb** [comment]
[numerical_stress_tensor.zip](https://github.com/cp2k/cp2k/files/8161003/numerical_stress_tensor.zip)
These are results converged with numerical stress tensor

**Comment by fstein93** [comment]
Have you checked the converged of the stress tensors with respect to EPS_SCF?

**Comment by robinzyb** [comment]
> Can you rerun the calculation with a higher cutoff (1200 Ry?).
> @juerghutter : Do you have any ideas?

You got it. Cutoff 1200 make optimization converged

**Comment by robinzyb** [comment]
Thank You @fstein93 :)
