### ISSUE TITLE
error about sirius_MOD_sirius_option_get_logical

### ISSUE THREAD

**Issue by alas-go** [cp2k/cp2k#1949]
Dear Sir/Madam.

The input could be run with popt/psmp which did not inclued  the sirus package, Since sirus was included when compiling. the 
input code run with the err printed. It could be reproduced both on the cp2k 7.1 and cp2k 8.2. 
How to correct it? Could you help me?
cp2k 8.2 would be easily installed by anacond3 but the sirus package is included.

Attached:
cp2k.psmp: symbol lookup error: cp2k.psmp: undefined symbol: __sirius_MOD_sirius_option_get_logical
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
cp2k.psmp: symbol lookup error: cp2k.psmp: undefined symbol: __sirius_MOD_sirius_option_get_logical
cp2k.psmp: symbol lookup error: cp2k.psmp: undefined symbol: __sirius_MOD_sirius_option_get_logical
cp2k.psmp: symbol lookup error: cp2k.psmp: undefined symbol: __sirius_MOD_sirius_option_get_logical
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[8274,1],0]
  Exit code:    127

**Comment by mtaillefumier** [comment]
We changed sirius api which makes the latest SIRIUS version incompatible with cp2k 7.1 and 8.2. My suggestion would be to use the latest official version as it provides an updated version of SIRIUS.
