### ISSUE TITLE
Suitable warning message for ADMM forces

### ISSUE THREAD

**Issue by ezpzbz** [cp2k/cp2k#1960]
Hi, 
I noticed that if user sets `ADMM_PURIFICATION_METHOD` to values except `MO_DIAG` and `NONE`, geometry optimisation will fail but the log file does not provide an error message. 
<img width="577" alt="image" src="https://user-images.githubusercontent.com/13301031/155486868-4da8f6b1-c474-4619-8c09-842b0e0ba47e.png">

Inspecting the `admm_methods.F` at line 2033 shows the source of error as forces are not implemented otherwise.
https://github.com/cp2k/cp2k/blob/d40d240e9e932ae2deae73189bc2060db0eb963a/src/admm_methods.F#L2026-L2034
but the `CPABORT` does not contain error message.
If it helps I can open a PR adding these error messages.
Best regards,
Pezhman

**Comment by oschuett** [comment]
Sorry, for the late reply. Yes, PRs are always welcome!
