### ISSUE TITLE
Support for other GPU models (A6000, 3080)

### ISSUE THREAD

**Issue by zacharyrs** [cp2k/cp2k#1979]
Hi,

I'm attempting to set up CP2K on a couple of machines, one has a 3080 and the other has an A6000 (both are  `ARCH_NUM=86`).

I can't see direct support for these in the `--gpu-ver` flag, with the closest being the A100 (`ARCH_NUM=80`).
From what I can see, the `SM_80` binary will run on `SM_86`, but won't utilise the full FP32 throughput.

Just wondered if there's something I'm missing, or if targeting the A100 is the best way forward.

I also have several laptops with `SM_75` GPUs. For these should I use V100?

Cheers,
Zach

**Comment by oschuett** [comment]
Yes, using the parameters from the same GPU generation should generally yield the best results.
Currently, the `--gpu-ver` flag really only affects DBCSR because of its auto-tuned kernels.

**Comment by zacharyrs** [comment]
I ended up targetting `SM_70` across all machines - I assume this will still work but with reduced performance.
I couldn't get `elpa` to build with `SM_80`, and then I found this https://github.com/marekandreas/elpa/issues/15 which deterred me from trying more.

This is the end of `make.log` for `elpa` in `build_nvidia`:
```
/usr/bin/ld: ./.libs/libelpa_openmp.a(ev_tridi_band_nvidia_gpu_real_sm80.o): in function `_GLOBAL__sub_I__Z20set_max_shared_bytesPKv':
tmpxft_000bd9d9_00000000-6_ev_tridi_band_nvidia_gpu_real_sm80.cudafe1.cpp:(.text.startup+0x3d0): undefined reference to `std::ios_base::Init::Init()'
/usr/bin/ld: tmpxft_000bd9d9_00000000-6_ev_tridi_band_nvidia_gpu_real_sm80.cudafe1.cpp:(.text.startup+0x3d7): undefined reference to `std::ios_base::Init::~Init()'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:30826: elpa2_print_kernels_openmp] Error 1
make[1]: Leaving directory '/pipeline/cp2k/tools/toolchain/build/elpa-2021.11.001/build_nvidia'
make: *** [Makefile:29870: all] Error 2
```

The exact command that fails on the 3080 machine is:
```
/usr/lib/gcc/x86_64-linux-gnu/9/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/9/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper -plugin-opt=-fresolution=/tmp/cc0vUmTm.res -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lquadmath -plugin-opt=-pass-through=-lm -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lpthread -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lgcc --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o elpa2_print_kernels_openmp /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/9/crtbeginS.o /usr/lib/gcc/x86_64-linux-gnu/9/crtoffloadbegin.o -L/pipeline/cp2k/tools/toolchain/install/scalapack-2.1.0/lib -L/pipeline/cp2k/tools/toolchain/install/openblas-0.3.19/lib -L/usr/local/cuda-11.3/lib64 -L/usr/lib/x86_64-linux-gnu/openmpi/lib -L/usr/lib/gcc/x86_64-linux-gnu/9 -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/9/../../.. -rpath=/pipeline/cp2k/tools/toolchain/install/scalapack-2.1.0/lib --allow-multiple-definition --enable-new-dtags -rpath=/pipeline/cp2k/tools/toolchain/install/openblas-0.3.19/lib -rpath=/pipeline/cp2k/tools/toolchain/install/scalapack-2.1.0/lib src/elpa2/elpa2_print_kernels_openmp-elpa2_print_kernels.o ./.libs/libelpa_openmp.a -lcudart -lcublas -lscalapack -lopenblas -lmpi_usempif08 -lmpi_usempi_ignore_tkr -lmpi_mpifh -lmpi -lgfortran -lm -lgomp -lgcc_s -lgcc -lquadmath -lm -lgcc_s -lgcc -lpthread -lc -lgcc_s -lgcc /usr/lib/gcc/x86_64-linux-gnu/9/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crtn.o /usr/lib/gcc/x86_64-linux-gnu/9/crtoffloadend.o
```

Oddly the same command is ran successfully on my laptop (but targetting `SM_70`).
I'm guessing something in the `SM_80` specific support breaks it.
There's nothing funky in `env` on either machine - no `LD_LIBRARY_PATH` etc.

Maybe you have some suggestions?

**Comment by oschuett** [comment]
Yes, support for `SM_80`, ie. Nvidia A100, is unfortunately not well tested because we have only limited access to that hardware nor the funding to run it on the cloud.

**Comment by zhenkunl** [comment]
I have also met the same issue. Is there any solution? Many Thanks.

**Comment by alazzaro** [comment]
The new release (end of December) will have the A100 kernels for DBCSR.
I'm not sure about the ELPA problem, could you try to build ELPA standalone?

**Comment by zhenkunl** [comment]
Yes, I did. I tried different compilers (gnu and intel compilers), but the error remained. It seems like a misuse of `gcc`,  not `g++`,  to compile a C++ program. I also tried to fix the `Makefile` or change the `configure` options and failed.

**Comment by alazzaro** [comment]
> Yes, I did. I tried different compilers (gnu and intel compilers), but the error remained. It seems like a misuse of `gcc`, not `g++`, to compile a C++ program. I also tried to fix the `Makefile` or change the `configure` options and failed.

Then I suggest raising the issue with ELPA people. I can see [this entry](https://github.com/marekandreas/elpa/blob/master/documentation/INSTALL.md#273-building-for-nvidia-a100-gpus-and-intel-icelake-cpus). Maybe SPACK or Easybuild has already an A100 compilation?

**Comment by alazzaro** [comment]
And this other entry is relevant:

https://github.com/marekandreas/elpa/issues/18

So maybe the toolchain is missing `-lstdc++`? @oschuett any clue?

**Comment by zhenkunl** [comment]
Yes, that works for me. Thanks again.

**Comment by dev-zero** [comment]
Also, in my tests the newly generated kernels for the A100 were only marginally faster on the A100 than the V100 ones, hardware improvements seemed to have a much bigger influence atm.

**Comment by Sassafrass6** [comment]
Hello, just a follow up to this discussion. 
The newest release, 2023.1, still fails to build with the flag --gpu-ver=A100.
The issue is resolved, as alazzaro suggests, by adding -lstdc++ to the LIBS environment variable. I had to add this flag inside of ./scripts/stage5/install_elpa.sh, relative to the toolchain directory.

**Comment by bjoe2k4** [comment]
Still happens with 2023.2 and A100. Could `-lstdc++` still be added as a conditional and would you accept such a pull request?
