### ISSUE TITLE
Crash in Valgrind test due to numerical issues

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#2]
The current trunk fails in the valgrind test (SDBG) on the input QS/regtest-rel/Hg_rel.inp with message: _"Matrix diagonalization failed"_ .

I found that the problem goes away if we run without -ffast-math flag, therefore I can assume that it is due to a numerical instability of the test.

Submitted by @alazzaro .

**Comment by alazzaro** [comment]
Closed via https://github.com/cp2k/cp2k/commit/d4e4bcc892fb345f2fecc61a1a21459ba529b2f2
