### ISSUE TITLE
Patching to work with MPItrampoline

### ISSUE THREAD

**Issue by ocaisa** [cp2k/cp2k#2005]
I'm trying to help patch CP2K so that it can work with [MPItrampoline](https://github.com/eschnett/MPItrampoline) (by @eschnett, it provides a stable MPI ABI so that you can use different implementations without recompiling the code). This requires patching of CP2K so that MPI constants are only used at runtime rather than compile time (for example).

Unfortunately,  Fortran is not my strong point and I struggled to help write the patch (a gist of the current version for CP2K 8.2 is at https://gist.github.com/ocaisa/49aa4aa6ac1bf43b36cde1716e369824).  One issue was it was unclear where exactly the initialisation of the constants should take place, we have something now that seems to work on that front but some advice on the "correct" place for this would be useful. The other problem is that some variables (like `fft_scratch_type%cart_sub_comm`) are initialised, and we seem to be failing to hack this initialisation when this type is used. Finally, the patch is causing a segfault right at the end of the application and I don't fully know how to track this down (though I suspect it is related to the second issue):
```
[ocaisa@xlnode1 ~]$ OMP_NUM_THREADS=1 mpiexec --oversubscribe -n 1 cp2k.psmp /scratch/ocaisa/cp2k_regtesting/H.inp

... 

The number of warnings for this run is : 0
 
 -------------------------------------------------------------------------------
  **** **** ******  **  PROGRAM ENDED AT                 2022-03-14 14:29:23.661
 ***** ** ***  *** **   PROGRAM RAN ON            xlnode1.int.eessi-gpu.learnhpc
 **    ****   ******    PROGRAM RAN BY                                    ocaisa
 ***** **    ** ** **   PROGRAM PROCESS ID                               1106797
  **** **  *******  **  PROGRAM STOPPED IN                          /home/ocaisa
[xlnode1:1106797:0:1106797] Caught signal 11 (Segmentation fault: address not mapped to object at address 0x58)
==== backtrace (tid:1106797) ====
 0  /cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/UCX/1.10.0-GCCcore-10.3.0/lib64/libucs.so.0(ucs_handle_error+0x254) [0x152e972c8474]
 1  /cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/UCX/1.10.0-GCCcore-10.3.0/lib64/libucs.so.0(+0x21657) [0x152e972c8657]
 2  /cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/UCX/1.10.0-GCCcore-10.3.0/lib64/libucs.so.0(+0x2180a) [0x152e972c880a]
 3  /cvmfs/pilot.eessi-hpc.org/versions/2021.12/compat/linux/x86_64/lib/../lib64/libpthread.so.0(+0x120f0) [0x152eaa6020f0]
 4  /cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/OpenMPI/4.1.1-GCC-10.3.0/lib/libmpi.so.40(ompi_request_default_wait+0x24) [0x152ea8931c74]
 5  /cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/OpenMPI/4.1.1-GCC-10.3.0/lib/libmpi.so.40(PMPI_Wait+0x54) [0x152ea89717b4]
 6  /cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/OpenMPI/4.1.1-GCC-10.3.0/lib/libmpi_mpifh.so.40(mpi_wait+0x31) [0x152ea8a6b001]
 7  cp2k.psmp() [0x1d78d1c]
 8  cp2k.psmp() [0x1dbd083]
 9  cp2k.psmp() [0x1d93170]
10  /cvmfs/pilot.eessi-hpc.org/versions/2021.12/software/linux/x86_64/amd/zen2/software/GCCcore/10.3.0/lib64/libgomp.so.1(GOMP_parallel+0x42) [0x152ea88b4902]
11  cp2k.psmp() [0x1d572b0]
12  cp2k.psmp() [0x4723ad]
13  cp2k.psmp() [0x476191]
14  cp2k.psmp() [0x4714d9]
15  cp2k.psmp() [0x40c14f]
16  /cvmfs/pilot.eessi-hpc.org/versions/2021.12/compat/linux/x86_64/lib/../lib64/libc.so.6(__libc_start_main+0xce) [0x152ea86aa7fe]
17  cp2k.psmp() [0x46f96a]
=================================

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x152eaa6020ef in ???
#1  0x152ea8931c74 in ???
#2  0x152ea89717b3 in ???
#3  0x152ea8a6b000 in ???
#4  0x1d78d1b in ???
#5  0x1dbd082 in ???
#6  0x1d9316f in ???
#7  0x152ea88b4901 in GOMP_parallel
        at ../../../libgomp/parallel.c:171
#8  0x1d572af in ???
#9  0x4723ac in ???
#10  0x476190 in ???
#11  0x4714d8 in ???
#12  0x40c14e in ???
#13  0x152ea86aa7fd in ???
#14  0x46f969 in ???
#15  0xffffffffffffffff in ???
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 1106797 on node xlnode1 exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------
``` 

Note that I'm first trying to ensure that patch works with OpenMPI before testing it (beyond compilation) with MPItrampoline.

If someone with CP2K/Fortran expertise had some advice here it would be very helpful.

**Comment by oschuett** [comment]
Sorry for the late reply. I think, MPItrampoline is a really interesting project that addresses an important pain point with containers. 

However, I don't think we should turn MPI constants into runtime values. Instead, MPItrampoline should indeed define its own constants as [already suggested](https://github.com/eschnett/MPItrampoline/issues/27#issuecomment-1087205937).

**Comment by oschuett** [comment]
I'm going to close this for now. I'll be happy to take another look once the issue around MPI constants is worked out.

**Comment by ocaisa** [comment]
A note here from MPI 4.0 §2.5.4 (since this came up again in https://github.com/eschnett/MPItrampoline/issues/34):

> All named constants, with the exceptions noted below for Fortran, can be used in initialization expressions or assignments, but not necessarily in array declarations or as labels in C switch or Fortran select/case statements. This implies named constants to be link-time but not necessarily compile-time constants.

and (from the advice to implementors in the same section):

> Using special values for the constants (e.g., by defining them through PARAMETER statements) is not possible because an implementation cannot distinguish these values from valid data. Typically, these constants are implemented as predefined static variables (e.g., a variable in an MPI-declared COMMON block), relying on the fact that the target compiler passes data by address. Inside the subroutine, this address can be extracted by some mechanism outside the Fortran standard (e.g., by Fortran extensions or by implementing the function in C).

The use of select/case statements and the use of PARAMETER were the issues that we were seeing with CP2K.
