### ISSUE TITLE
Some tests fail after #2006

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#2007]
Some [tests](https://www.cp2k.org/static/regtest/trunk/CRAY-XC50-gnu/9.3.0-mpich-psmp/regtest-0) (and [this one](https://storage.googleapis.com/cp2k-ci/dashboard_cuda-pascal_report.txt)) using CUDA fail after #2006.

**Comment by abussy** [comment]
I am confident that this is linked to the recent implementation of `retain_sparsity` in DBM (#1984). Removing that argument from the tensor contraction leads to working code with GPU. @oschuett, what do you think ?
