### ISSUE TITLE
installing cosma wrong

### ISSUE THREAD

**Issue by LiHengswjtu** [cp2k/cp2k#2022]
hello everyone,
I got an error in installing cosma.
==================== Installing COSMA ====================
COSMA-v2.5.0.tar.gz is found
Installing from scratch into /sob/cp2k-8.2/tools/toolchain/install/COSMA-2.5.0
ERROR: (./scripts/stage4/install_cosma.sh, line 73) Non-zero exit code detected.
can anybody explain it? many thanks
and this is the make.log:

Scanning dependencies of target costa
[  1%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/block.cpp.o
[  3%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/communication_data.cpp.o
[  5%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/grid2D.cpp.o
[  6%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/transform.cpp.o
[  8%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/interval.cpp.o
[ 11%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/ranks_reordering.cpp.o
[ 11%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/scalapack_layout.cpp.o
[ 13%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/grid_cover.cpp.o
[ 15%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/grid2grid/utils.cpp.o
[ 16%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa.dir/layout.cpp.o
[ 18%] Linking CXX static library libcosta.a
[ 18%] Built target costa
Scanning dependencies of target costa_prefixed_scalapack
Scanning dependencies of target costa_scalapack
[ 20%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_scalapack.dir/pxtran/costa_pxtran.cpp.o
[ 23%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_prefixed_scalapack.dir/pxgemr2d/prefixed_pxgemr2d.cpp.o
[ 23%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_prefixed_scalapack.dir/pxgemr2d/costa_pxgemr2d.cpp.o
[ 25%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_prefixed_scalapack.dir/scalapack.cpp.o
[ 26%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_prefixed_scalapack.dir/pxtran/costa_pxtran.cpp.o
[ 28%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_prefixed_scalapack.dir/pxtran/prefixed_pxtran.cpp.o
[ 30%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_scalapack.dir/scalapack.cpp.o
[ 31%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_scalapack.dir/pxgemr2d/costa_pxgemr2d.cpp.o
[ 33%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_scalapack.dir/pxtran/pxtran.cpp.o
[ 35%] Building CXX object libs/COSTA/src/costa/CMakeFiles/costa_scalapack.dir/pxgemr2d/pxgemr2d.cpp.o
Scanning dependencies of target cosma
[ 36%] Building CXX object src/cosma/CMakeFiles/cosma.dir/blas.cpp.o
[ 38%] Building CXX object src/cosma/CMakeFiles/cosma.dir/interval.cpp.o
[ 40%] Building CXX object src/cosma/CMakeFiles/cosma.dir/communicator.cpp.o
[ 41%] Building CXX object src/cosma/CMakeFiles/cosma.dir/local_multiply.cpp.o
[ 43%] Building CXX object src/cosma/CMakeFiles/cosma.dir/math_utils.cpp.o
[ 45%] Building CXX object src/cosma/CMakeFiles/cosma.dir/context.cpp.o
[ 46%] Building CXX object src/cosma/CMakeFiles/cosma.dir/buffer.cpp.o
[ 48%] Building CXX object src/cosma/CMakeFiles/cosma.dir/matrix.cpp.o
[ 50%] Building CXX object src/cosma/CMakeFiles/cosma.dir/memory_pool.cpp.o
[ 51%] Building CXX object src/cosma/CMakeFiles/cosma.dir/one_sided_communicator.cpp.o
[ 53%] Building CXX object src/cosma/CMakeFiles/cosma.dir/layout.cpp.o
[ 55%] Building CXX object src/cosma/CMakeFiles/cosma.dir/strategy.cpp.o
[ 56%] Building CXX object src/cosma/CMakeFiles/cosma.dir/mapper.cpp.o
[ 58%] Building CXX object src/cosma/CMakeFiles/cosma.dir/cinterface.cpp.o
[ 60%] Building CXX object src/cosma/CMakeFiles/cosma.dir/two_sided_communicator.cpp.o
[ 61%] Building CXX object src/cosma/CMakeFiles/cosma.dir/multiply.cpp.o
[ 63%] Building CXX object src/cosma/CMakeFiles/cosma.dir/environment_variables.cpp.o
[ 65%] Linking CXX static library libcosta_prefixed_scalapack.a
[ 65%] Built target costa_prefixed_scalapack
[ 66%] Linking CXX static library libcosta_scalapack.a
[ 66%] Built target costa_scalapack
[ 68%] Linking CXX static library libcosma.a
[ 68%] Built target cosma
Scanning dependencies of target allgather-volume
Scanning dependencies of target ubench-allgather
Scanning dependencies of target dgemm_perf_model
Scanning dependencies of target reduce-scatter
Scanning dependencies of target sendrecv
Scanning dependencies of target cosma_pxgemm_cpp
Scanning dependencies of target cosma_prefixed_pxgemm
Scanning dependencies of target blocking_vs_non_blocking
[ 70%] Building CXX object benchmarks/CMakeFiles/allgather-volume.dir/allgather-volume.cpp.o
[ 71%] Building CXX object src/cosma/CMakeFiles/cosma_pxgemm_cpp.dir/scalapack.cpp.o
[ 73%] Building CXX object src/cosma/CMakeFiles/cosma_prefixed_pxgemm.dir/prefixed_pxgemm.cpp.o
[ 75%] Building CXX object src/cosma/CMakeFiles/cosma_prefixed_pxgemm.dir/cosma_pxgemm.cpp.o
[ 76%] Building CXX object benchmarks/CMakeFiles/reduce-scatter.dir/reduce-scatter.cpp.o
[ 80%] Building CXX object benchmarks/CMakeFiles/blocking_vs_non_blocking.dir/blocking_vs_non_blocking.cpp.o
[ 80%] Building CXX object benchmarks/CMakeFiles/ubench-allgather.dir/ubench-allgather.cpp.o
[ 81%] Building CXX object benchmarks/CMakeFiles/dgemm_perf_model.dir/dgemm_perf_model.cpp.o
[ 83%] Building CXX object src/cosma/CMakeFiles/cosma_pxgemm_cpp.dir/cosma_pxgemm.cpp.o
[ 85%] Building CXX object benchmarks/CMakeFiles/sendrecv.dir/sendrecv.cpp.o
[ 86%] Building CXX object src/cosma/CMakeFiles/cosma_prefixed_pxgemm.dir/scalapack.cpp.o
[ 88%] Linking CXX executable sendrecv
[ 90%] Linking CXX executable allgather-volume
[ 91%] Linking CXX executable ubench-allgather
[ 93%] Linking CXX executable reduce-scatter
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: CMakeFiles/sendrecv.dir/sendrecv.cpp.o: in function `main':
/sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/sendrecv.cpp:20: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/sendrecv.cpp:21: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/sendrecv.cpp:32: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/sendrecv.cpp:32: undefined reference to `ompi_mpi_double'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/sendrecv.cpp:32: undefined reference to `ompi_mpi_double'
collect2: error: ld returned 1 exit status
make[2]: *** [benchmarks/sendrecv] Error 1
make[1]: *** [benchmarks/CMakeFiles/sendrecv.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: CMakeFiles/allgather-volume.dir/allgather-volume.cpp.o: in function `cosma::Timer::~Timer()':
/sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:34: undefined reference to `ompi_mpi_op_max'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:34: undefined reference to `ompi_mpi_long_long_int'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:35: undefined reference to `ompi_mpi_op_min'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:35: undefined reference to `ompi_mpi_long_long_int'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:36: undefined reference to `ompi_mpi_op_sum'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:36: undefined reference to `ompi_mpi_long_long_int'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: CMakeFiles/allgather-volume.dir/allgather-volume.cpp.o: in function `main':
/sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/allgather-volume.cpp:20: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/allgather-volume.cpp:21: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: CMakeFiles/allgather-volume.dir/allgather-volume.cpp.o: in function `cosma::Timer::Timer(int, std::string, ompi_communicator_t*)':
/sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:23: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:22: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: CMakeFiles/allgather-volume.dir/allgather-volume.cpp.o: in function `main':
/sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/allgather-volume.cpp:35: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/allgather-volume.cpp:35: undefined reference to `ompi_mpi_double'
collect2: error: ld returned 1 exit status
make[2]: *** [benchmarks/allgather-volume] Error 1
make[1]: *** [benchmarks/CMakeFiles/allgather-volume.dir/all] Error 2
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: CMakeFiles/ubench-allgather.dir/ubench-allgather.cpp.o: in function `cosma::Timer::~Timer()':
/sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:34: undefined reference to `ompi_mpi_op_max'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:34: undefined reference to `ompi_mpi_long_long_int'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:35: undefined reference to `ompi_mpi_op_min'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:35: undefined reference to `ompi_mpi_long_long_int'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:36: undefined reference to `ompi_mpi_op_sum'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:36: undefined reference to `ompi_mpi_long_long_int'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: CMakeFiles/ubench-allgather.dir/ubench-allgather.cpp.o: in function `main':
/sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/ubench-allgather.cpp:20: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/ubench-allgather.cpp:21: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/ubench-allgather.cpp:49: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/ubench-allgather.cpp:51: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/ubench-allgather.cpp:51: undefined reference to `ompi_mpi_double'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/ubench-allgather.cpp:51: undefined reference to `ompi_mpi_double'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/ubench-allgather.cpp:63: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/ubench-allgather.cpp:65: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/ubench-allgather.cpp:65: undefined reference to `ompi_mpi_double'
collect2: error: ld returned 1 exit status
make[2]: *** [benchmarks/ubench-allgather] Error 1
make[1]: *** [benchmarks/CMakeFiles/ubench-allgather.dir/all] Error 2
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: CMakeFiles/reduce-scatter.dir/reduce-scatter.cpp.o: in function `cosma::Timer::~Timer()':
/sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:34: undefined reference to `ompi_mpi_op_max'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:34: undefined reference to `ompi_mpi_long_long_int'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:35: undefined reference to `ompi_mpi_op_min'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:35: undefined reference to `ompi_mpi_long_long_int'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:36: undefined reference to `ompi_mpi_op_sum'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:36: undefined reference to `ompi_mpi_long_long_int'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: CMakeFiles/reduce-scatter.dir/reduce-scatter.cpp.o: in function `main':
/sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/reduce-scatter.cpp:20: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/reduce-scatter.cpp:21: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: CMakeFiles/reduce-scatter.dir/reduce-scatter.cpp.o: in function `cosma::Timer::Timer(int, std::string, ompi_communicator_t*)':
/sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:23: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/src/cosma/timer.hpp:22: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: CMakeFiles/reduce-scatter.dir/reduce-scatter.cpp.o: in function `main':
/sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/reduce-scatter.cpp:69: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/reduce-scatter.cpp:69: undefined reference to `ompi_mpi_op_sum'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/reduce-scatter.cpp:69: undefined reference to `ompi_mpi_double'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/reduce-scatter.cpp:69: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/reduce-scatter.cpp:69: undefined reference to `ompi_mpi_op_sum'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/reduce-scatter.cpp:69: undefined reference to `ompi_mpi_double'
collect2: error: ld returned 1 exit status
make[2]: *** [benchmarks/reduce-scatter] Error 1
make[1]: *** [benchmarks/CMakeFiles/reduce-scatter.dir/all] Error 2
[ 95%] Linking CXX executable blocking_vs_non_blocking
[ 96%] Linking CXX executable dgemm_perf_model
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: CMakeFiles/blocking_vs_non_blocking.dir/blocking_vs_non_blocking.cpp.o: in function `Timer::~Timer()':
/sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/blocking_vs_non_blocking.cpp:37: undefined reference to `ompi_mpi_op_max'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/blocking_vs_non_blocking.cpp:37: undefined reference to `ompi_mpi_long_long_int'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/blocking_vs_non_blocking.cpp:38: undefined reference to `ompi_mpi_op_min'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/blocking_vs_non_blocking.cpp:38: undefined reference to `ompi_mpi_long_long_int'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/blocking_vs_non_blocking.cpp:39: undefined reference to `ompi_mpi_op_sum'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/blocking_vs_non_blocking.cpp:39: undefined reference to `ompi_mpi_long_long_int'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: CMakeFiles/blocking_vs_non_blocking.dir/blocking_vs_non_blocking.cpp.o: in function `main':
/sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/blocking_vs_non_blocking.cpp:73: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/blocking_vs_non_blocking.cpp:74: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/blocking_vs_non_blocking.cpp:96: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/blocking_vs_non_blocking.cpp:102: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/blocking_vs_non_blocking.cpp:111: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/blocking_vs_non_blocking.cpp:120: undefined reference to `ompi_mpi_double'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/blocking_vs_non_blocking.cpp:127: undefined reference to `ompi_mpi_double'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/blocking_vs_non_blocking.cpp:139: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/blocking_vs_non_blocking.cpp:157: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/blocking_vs_non_blocking.cpp:160: undefined reference to `ompi_mpi_comm_world'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /sob/cp2k-8.2/tools/toolchain/build/COSMA-v2.5.0/benchmarks/blocking_vs_non_blocking.cpp:162: undefined reference to `ompi_mpi_double'
collect2: error: ld returned 1 exit status
make[2]: *** [benchmarks/blocking_vs_non_blocking] Error 1
make[1]: *** [benchmarks/CMakeFiles/blocking_vs_non_blocking.dir/all] Error 2
[ 96%] Built target dgemm_perf_model
[ 98%] Linking CXX static library libcosma_prefixed_pxgemm.a
[ 98%] Built target cosma_prefixed_pxgemm
[100%] Linking CXX static library libcosma_pxgemm_cpp.a
[100%] Built target cosma_pxgemm_cpp
make: *** [all] Error 2

**Comment by oschuett** [comment]
This looks like the mpi libraries are not being linked, presumably because you are calling `ld` directly instead of using a wrapper like `mpicc`.
