### ISSUE TITLE
installing elpa wrong

### ISSUE THREAD

**Issue by LiHengswjtu** [cp2k/cp2k#2024]
hello_ everyone,

I got an error in installing elpa

==================== Installing ELPA ====================
elpa-2019.05.001.tar.gz is found
Installing from scratch into /sob/cp2k-7.1/tools/toolchain/install/elpa-2019.05.001
ERROR: (./scripts/install_elpa.sh, line 103) Non-zero exit code detected.

and there are the “*.log”, but I really don't understand what they mean
can anybody explain it? many thanks

[make.log](https://github.com/cp2k/cp2k/files/8340133/make.log)

[configure.log](https://github.com/cp2k/cp2k/files/8340149/configure.log)

[config.log](https://github.com/cp2k/cp2k/files/8340151/config.log)

**Comment by zc62** [comment]
Looks like an ancient cp2k version, try the most recent commit? Though I compiled ELPA myself, I believe currently the library linking in ELPA generated by up-to-date toolchain script is correct. (I learned from it to solve a strange problem that the linking args generated from mkl link advisor does not work)

You can try compile elpa yourself then use the toolchain script to choose --with-elpa=system
```bash
mkdir build
cd build
../configure --prefix=$HOME/cp2k_install --libdir=$HOME/cp2k_install/lib --enable-openmp=yes --enable-shared=no --enable-static=yes --enable-avx=yes --enable-avx2=yes --enable-avx512=yes FC=mpifort CC=mpicc CXX=mpicxx FCFLAGS="-O2 -xCORE-AVX512 -I${MKLROOT}/include/intel64/lp64 -I${MKLROOT}/include" CFLAGS="-O2 -xCORE-AVX512 -I${MKLROOT}/include" CXXFLAGS="-O2 -xCORE-AVX512 -I${MKLROOT}/include" LIBS="-L${MKLROOT}/lib/intel64 -lmkl_scalapack_lp64 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lmkl_blacs_openmpi_lp64 -lpthread -lm -ldl"
make -j1 && make install
```
(The difference from what mkl link advisor gives is the deletion of `-Wl,--start-group` and `-Wl,--end-group`, which I thought was necessary.)
