### ISSUE TITLE
H TZVP-SR?

### ISSUE THREAD

**Issue by setten** [cp2k/cp2k#203]
Hi there,

I'm performing a comparison between DZVP and TZVP. For reason there does not seem to be a H TZVP-SR

is there a specific reason for this?

thanks

**Comment by dev-zero** [comment]
If referring to the MOLOPT basis sets: I'm not sure about the reason, but we have an unpublished TZVP-SR for H and at least in the deltatest it does not improve significantly over the DZVP.

**Comment by oschuett** [comment]
If you have further user question please visit our [Google Group](https://www.cp2k.org/howto:forum).
