### ISSUE TITLE
Wrong program name in `tools/toolchain/scripts/stage4/install_libxsmm.sh`

### ISSUE THREAD

**Issue by zc62** [cp2k/cp2k#2044]
https://github.com/cp2k/cp2k/blob/aa9c8d9962e810d991202283608a233847e566fc/tools/toolchain/scripts/stage4/install_libxsmm.sh#L92

The actual name should be `libxsmm_gemm_generator`, not `libxsmm_generator` as in the script.

**Comment by hfp** [comment]
We should remove references of the stand-alone generator in the install script. It is legacy and it is unsupported going forward. Practically nobody uses it as all kernels are JIT-generated.

**Comment by oschuett** [comment]
While we're at it we could also remove [install_libsmm.sh](https://github.com/cp2k/cp2k/blob/master/tools/toolchain/scripts/stage4/install_libsmm.sh).

**Comment by hfp** [comment]
> While we're at it we could also remove [install_libsmm.sh](https://github.com/cp2k/cp2k/blob/master/tools/toolchain/scripts/stage4/install_libsmm.sh).

On x86-64, libsmm finally carried almost 90% kernels taken from libxsmm (if I remember correctly). Btw, our mighty LIBXSMM 2.0 will come up with ARM64 kernels incl. SVE.
