### ISSUE TITLE
Forces evaluation for mixed force calculations is printed in the same file if you use sopt or ssmp versions

### ISSUE THREAD

**Issue by VasylStotskyi** [cp2k/cp2k#2045]
Dear CP2K developers,
I noticed interesting bug:
If you use cp2k.sopt or cp2k.ssmp for mixed calculations, your forces evaluation output will be printed in the same file (*-r-1.out). It doesn't effect restart or wavefunctions printing - only messes up with output.
I detected it by running example_multiple_force_eval.py from aiida-cp2k plugin.
Best regards,
Vasyl
[multiple_force_eval.zip](https://github.com/cp2k/cp2k/files/8388405/multiple_force_eval.zip)

**Comment by oschuett** [comment]
You probably have to explicitly set different [filenames](https://manual.cp2k.org/trunk/CP2K_INPUT/FORCE_EVAL/PRINT/FORCES.html#FILENAME).
