### ISSUE TITLE
error when test cp2k9.1

### ISSUE THREAD

**Issue by hooooooot** [cp2k/cp2k#2048]
Hello:
Hello!

I tried to install cp2k 9.1.0 on my cluster, which uses CentOS 7.5, gcc 9.3.0, cmake 3.22.1, python 3.6.1, openmpi 4.1.1.
I install and compile it successful, but when i test it with "make -j 28 ARCH=local VERSION="ssmp psmp" test", the ssmp version is passed successfully and psmp failed. the error log shows many "TIME OUT", what can i do to fix it?

**Comment by fstein93** [comment]
I have already had a similar issue. Can you try to run the following command?
make -j 28 ARCH=local VERSION=psmp test TESTOPTS="--maxtasks 4"
In my case, the compute times reduced significantly.

**Comment by hooooooot** [comment]
> I have already had a similar issue. Can you try to run the following command? make -j 28 ARCH=local VERSION=psmp test TESTOPTS="--maxtasks 4" In my case, the compute times reduced significantly.

thanks, now i have passed tests of psmp.
however, when i run it, it shows error massage:
`By default, for Open MPI 4.0 and later, infiniband ports on a device
are not used by default.  The intent is to use UCX for these devices.
You can override this policy by setting the btl_openib_allow_ib MCA parameter
to true.

  Local host:              node367
  Local adapter:           hfi1_0
  Local port:              1

--------------------------------------------------------------------------
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   node367
  Local device: hfi1_0
--------------------------------------------------------------------------
[node367:07904] 27 more processes have sent help message help-mpi-btl-openib.txt / ib port not selected
[node367:07904] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[node367:07904] 27 more processes have sent help message help-mpi-btl-openib.txt / error in device init
`
and what can i do to fix it ?

**Comment by hooooooot** [comment]
> I have already had a similar issue. Can you try to run the following command? make -j 28 ARCH=local VERSION=psmp test TESTOPTS="--maxtasks 4" In my case, the compute times reduced significantly.
thanks, now i have passed tests of psmp.
however, when i run it, it shows error massage:
`By default, for Open MPI 4.0 and later, infiniband ports on a device
are not used by default.  The intent is to use UCX for these devices.
You can override this policy by setting the btl_openib_allow_ib MCA parameter
to true.

  Local host:              node367
  Local adapter:           hfi1_0
  Local port:              1

--------------------------------------------------------------------------
--------------------------------------------------------------------------
WARNING: There was an error initializing an OpenFabrics device.

  Local host:   node367
  Local device: hfi1_0
--------------------------------------------------------------------------
[node367:07904] 27 more processes have sent help message help-mpi-btl-openib.txt / ib port not selected
[node367:07904] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[node367:07904] 27 more processes have sent help message help-mpi-btl-openib.txt / error in device init
`
and what can i do to fix it?

**Comment by alas-go** [comment]
the make using -j 1, only 1. and Timeout: 400 s.   OpenMP threads: 2 not the 4  I have set.
It really confuses us, confuses users.

make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
DBCSR Version: 2.3.0-rc0 (2022-03-28)
---------------------------- Modules -------------------------------------
No Modulefiles Currently Loaded.
*************************** Testing started ****************************

----------------------------- Settings ---------------------------------
MPI ranks:      2
OpenMP threads: 2
GPU devices:    0
Workers:        2
Timeout [s]:    400
Work base dir:  /home/az/cp2k-20220405/regtesting/TEST-local-psmp-2022-04-06_16-42-43
MPI exec:       ['mpiexec']
Keepalive:      False
Debug:          False
ARCH:           local
VERSION:        psmp
