### ISSUE TITLE
Some wrong about elpa when do make psmp

### ISSUE THREAD

**Issue by alas-go** [cp2k/cp2k#2053]
some wrong about elpa when do make psmp.

f951: Warning: Nonexistent include directory ‘/home/az/cp2kv10-20220403/tools/toolchain/install/elpa-2021.11.002/cpu/include/elpa-2021.11.002/modules’ [-Wmissing-include-dirs]
f951: Warning: Nonexistent include directory ‘/home/az/cp2kv10-20220403/tools/toolchain/install/elpa-2021.11.002/cpu/include/elpa-2021.11.002/elpa’ [-Wmissing-include-dirs]

toolchain install with cp2k on Rockylinux , openmpi with default install, mkl=2022.0.2.

**Comment by alazzaro** [comment]
which CP2K is this? I did a recent fix for this problem...

**Comment by alas-go** [comment]
Master edition of cp2k, on the day before April 3th, 2022, with openmpi 4.1.1 and mkl 2022.0.2.

**Comment by alazzaro** [comment]
could you check what you have in the directory:

/home/az/cp2kv10-20220403/tools/toolchain/install/elpa-2021.11.002/cpu/include/elpa-2021.11.002/

?
It seems ELPA didn't install properly... If so, need to check the logs.

**Comment by alas-go** [comment]
It was reproduced with the newest code of cp2k.  The directory  and the log were uploaded
[elpa-with-openmpi4.1.1+mkl2022.0.2.txt](https://github.com/cp2k/cp2k/files/8419349/elpa-with-openmpi4.1.1%2Bmkl2022.0.2.txt)

[elpa-with-openmpi4.1.1+mkl2022.0.2-config.log](https://github.com/cp2k/cp2k/files/8419363/elpa-with-openmpi4.1.1%2Bmkl2022.0.2-config.log)

**Comment by alazzaro** [comment]
so, you get an OpenMP in the directory (i.e. elpa_openmp-2021.11.002/), while the toolchain is including `elpa-2021.11.002/`. Checking log shows me that you are adding OpenMP. At this point it can be that we are missing installations (with and without OpenMP). Could you run a fresh install of the toolchain in a new directory?

**Comment by alas-go** [comment]
It was a fresh installation with the newest code which were updated by entering "git pull" command, today.  The directory install  under toolchain and setup files in the build under toolchain had been delet before running installation.
any code of elpa.sh under stage 5 directory was not modified except adding "SCALAPACK_LDFLAGS" and "SCALAPACK_FCFLAGS"
In the ~/.bashrc, "export OMP_NUM_THREADS=4" works well. shoud I delet it?

**Comment by alazzaro** [comment]
Well, the fresh installation I mean goes via "git clone".... Try to delete the elpa directories under toolchain/build and toolchain/install. Please note that I'm acting as a user here who faced a similar problem with the elpa installation, I'm not a toolchain expert...

**Comment by alas-go** [comment]
Thanks very much. 
That, elpa does not support openmp fine, stopped the making.

**Comment by alazzaro** [comment]
Here you have the problem... I have no idea why you hit this problem. If you really don't need ELPA, then I suggest to skip it...

**Comment by alas-go** [comment]
the install pkg of elpa had been delet and redownloaded. so the make process passed through.

but the test result was very bad. only 8 correct.
[test-result.txt](https://github.com/cp2k/cp2k/files/8422585/test-result.txt)
[error_summary.txt](https://github.com/cp2k/cp2k/files/8422588/error_summary.txt)

**Comment by alazzaro** [comment]
I see a bunch of timeout's. Could you try what it is suggested here:

https://github.com/cp2k/cp2k/issues/2048#issuecomment-1085631191

**Comment by alas-go** [comment]
the make using -j 1, only 1. and Timeout: 400 s. OpenMP threads: 2 not the 4 I have set.
It really confuses us, confuses users.

and it still has some tests timeout

make[3]: warning: jobserver unavailable: using -j1. Add '+' to parent make rule.
DBCSR Version: 2.3.0-rc0 (2022-03-28)
---------------------------- Modules -------------------------------------
No Modulefiles Currently Loaded.
*************************** Testing started ****************************

----------------------------- Settings ---------------------------------
MPI ranks: 2
OpenMP threads: 2
GPU devices: 0
Workers: 2
Timeout [s]: 400
Work base dir: /home/az/cp2k-20220405/regtesting/TEST-local-psmp-2022-04-06_16-42-43
MPI exec: ['mpiexec']
Keepalive: False
Debug: False
ARCH: local
VERSION: psmp

    H2O_br89_mp2_numer.inp                                   25.54239946           OK (  55.29 sec)
    CH3_br89_mp2_numer.inp                                             -    TIMED OUT ( 401.03 sec)
<<< /home/az/cp2k-20220405/regtesting/TEST-local-psmp-2022-04-06_16-42-43/QS/regtest-double-hybrid-stress-numer-laplace (2 of 310) done in 456.32 sec
>>> /home/az/cp2k-20220405/regtesting/TEST-local-psmp-2022-04-06_16-42-43/QS/regtest-double-hybrid-grad-laplace
    H2O_br89_mp2.inp                                                   -    TIMED OUT ( 401.03 sec)
    CH_br89_mp2.inp                                                    -    TIMED OUT ( 401.03 sec)
<<< /home/az/cp2k-20220405/regtesting/TEST-local-psmp-2022-04-06_16-42-43/QS/regtest-double-hybrid-grad-laplace (3 of 310) done in 802.06 sec
>>> /home/az/cp2k-20220405/regtesting/TEST-local-psmp-2022-04-06_16-42-43/QS/regtest-ec-force-meta
    N2_tpss_pade.inp                                                   -    TIMED OUT ( 401.02 sec)
    N2_pade_tpss.inp                                        -19.79534215           OK ( 312.83 sec)

**Comment by alas-go** [comment]
CH3_tpss_mp2_numer.inp                                             -    TIMED OUT ( 401.05 sec)
<<< /home/az/cp2k-20220405/regtesting/TEST-local-psmp-2022-04-06_16-42-43/QS/regtest-double-hybrid-stress-numer-meta (5 of 310) done in 763.87 sec
>>> /home/az/cp2k-20220405/regtesting/TEST-local-psmp-2022-04-06_16-42-43/QS/regtest-double-hybrid-grad-numer-meta
    H2O_tpss_mp2.inp                                                   -    TIMED OUT ( 401.02 sec)
    CH_tpss_mp2.inp                                                    -    TIMED OUT ( 401.02 sec)
<<< /home/az/cp2k-20220405/regtesting/TEST-local-psmp-2022-04-06_16-42-43/QS/regtest-double-hybrid-grad-numer-meta (6 of 310) done in 802.04 sec
>>> /home/az/cp2k-20220405/regtesting/TEST-local-psmp-2022-04-06_16-42-43/QS/regtest-double-hybrid-stress-meta
    H2O_tpss_mp2_an.inp                                      25.48691942           OK ( 161.32 sec)
    CH3_tpss_mp2_an.inp                                                -    TIMED OUT ( 401.03 sec)

**Comment by alas-go** [comment]
make -j 28 ARCH=local VERSION=psmp test TESTOPTS="--maxtasks 8" but still almost one third test faild .

the make using -j 1, only 1. and Timeout: 400 s. OpenMP threads: 2 not the number 4 I have set.

----------------------- External Modules ---------------------------------
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
DBCSR Version: 2.3.0-rc0 (2022-03-28)

------------------------------- Summary --------------------------------
Number of FAILED  tests 49
Number of WRONG   tests 2
Number of CORRECT tests 110
Total number of   tests 161

Summary: correct: 110 / 161; wrong: 2; failed: 49; 291min
Status: FAILED

*************************** Testing ended ******************************
make[3]: *** [/home/az/cp2k-20220405/Makefile:251: test] Error 51
make[2]: *** [/home/az/cp2k-20220405/Makefile:148: test] Error 2
make[1]: *** [/home/az/cp2k-20220405/Makefile:125: psmp] Error 2
make: *** [Makefile:120: test] Error 2

**Comment by alazzaro** [comment]
Well, you understood that `-j ` is useless for this procedure. Same for OMP_NUM_THREDS, it is resetted. The make test calls [do_regtest.py](https://github.com/cp2k/cp2k/blob/master/tools/regtesting/do_regtest.py). I have no idea where this is documented. I have no idea where this is documented... @oschuett knows better?

**Comment by alas-go** [comment]
Maybe the compilation is sucessful.
Test ends with few fails but it takes a long time.

Maybe, this is the conclusion: toolchain installation with Openmpi and mkl could include all functional packages. 
however, it does not support openmp well.

Thks for your kind help.

[test-results.txt](https://github.com/cp2k/cp2k/files/8441094/test-results.txt)
[error-summary.txt](https://github.com/cp2k/cp2k/files/8441103/error-summary.txt)

**Comment by alazzaro** [comment]
Let's assume it is OpenMPI, maybe it doesn't configure properly on your system. Could you try MPICH?

**Comment by alas-go** [comment]
everything goes smoothly except the make psmp. functional packages has been installed but it reports error differently, it is about dbcscar api.

--line-marker-format=gfortran5 /home/az/cp2k20220406mpich-mkl/src/pw/fast.F fast.F90
f951: Fatal Error: Reading module ‘dbcsr_api’ at line 1 column 2: Unexpected EOF
compilation terminated.
make[3]: *** [/home/az/cp2k20220406mpich-mkl/Makefile:512: arnoldi_types.o] Error 1
make[3]: *** Waiting for unfinished jobs....

[mpich+mkl error-dbcsr api.txt](https://github.com/cp2k/cp2k/files/8442845/mpich%2Bmkl.error-dbcsr.api.txt)

**Comment by alazzaro** [comment]
Please, make sure you do a make distclean before, I have no idea about the error.

**Comment by alas-go** [comment]
em ...   all right.
Thks very very much, anyway!

**Comment by alas-go** [comment]
Still not good enough. Maybe I shoud reinstall and update the OS.
I change back to v7.1. 
Thks a lot.
