### ISSUE TITLE
SomeThingWrongAboutDBSCAR-rc2.3.0.

### ISSUE THREAD

**Issue by alas-go** [cp2k/cp2k#2054]
[SomeThingWrongAboutDBSCAR-rc3.0.txt](https://github.com/cp2k/cp2k/files/8414324/SomeThingWrongAboutDBSCAR-rc3.0.txt)

Rocky Linux 8.5, gcc 8.5，intel parallel studio 2020.4， icc --version=19.1.3 with MKL.  cmake=3.20.4
Libint was 2.7.0-beta.5-lmax 5 and install by cmake.

**Comment by alazzaro** [comment]
the subject caught my attention (DBCSR). However, the reported error message is not DBCSR at all:

```
/home/az/cp2kv10-20220403/src/grid/cpu/grid_integrate_dgemm.c(762): error #3180: unrecognized OpenMP #pragma
  #pragma omp parallel default(shared)
  ^
```

**Comment by alas-go** [comment]
Sorry to my limited knowledge about the code. 


the error was  printed after some DBCSR code end with .k30.  all packages installation went smoothly but after source the setup file. the command make local.psmp produced these codes.

**Comment by oschuett** [comment]
You are compiling without OpenMP - most likely you are missing the `-fopenmp` flag.
