### ISSUE TITLE
Multiple Fist Potentials (from Google group)

### ISSUE THREAD

**Issue by juerghutter** [cp2k/cp2k#206]
Hello,

I'm trying to use a manybody potential between a metallic slab and water molecules in FIST but I would also need to use a simple Lennard-Jones potential to govern my water/water interactions.

Unfortunately, it would seems that the neighbour list building went badly between those modules because as long as my manybody potential (here, Tersoff) is present in the input, some of the Oxygen/Oxygen Lennard-Jones interactions are ignored.
Moreover, the verlet_skin parameters starts switching on or off some of these interactions.

For an example, I looked at two couples of water molecules away from my Pt slab and distant for each other.

- When I use 
    &NEIGHBOR_LISTS
      VERLET_SKIN 0.00
    &END
with 
    &TERSOFF
        ATOMS O Pt
        RCUT [angstrom] 10
     &END TERSOFF
and 
    &LENNARD-JONES
          atoms O O
          EPSILON [kcalmol] 0.102
          SIGMA [angstrom] 3.188
          RCUT 10
     &END LENNARD-JONES

the oxygens of only one of my water couple are experiencing LJ interaction from each others while the others doesn'tfeel any forces at all 

- When I use 
    &NEIGHBOR_LISTS
      VERLET_SKIN 1.00
    &END
with 
    &TERSOFF
        ATOMS O Pt
        RCUT [angstrom] 10
     &END TERSOFF
and 
    &LENNARD-JONES
          atoms O O
          EPSILON [kcalmol] 0.102
          SIGMA [angstrom] 3.188
          RCUT 10
     &END LENNARD-JONES

with no others changes, it is the second water couple that undergoes LJ interaction but not the first one anymore.

- When I use 
    &NEIGHBOR_LISTS
      VERLET_SKIN 1.00
    &END
and 
    &LENNARD-JONES
          atoms O O
          EPSILON [kcalmol] 0.102
          SIGMA [angstrom] 3.188
          RCUT 10
     &END LENNARD-JONES

with no manybodypotential, both couples are resenting LJ interactions.

I have observed the same exact behavior with a Williams potential instead of a Lennard-Jones. I'm joining the example input in the message.

**Comment by oschuett** [comment]
This might have been fixed by https://github.com/cp2k/cp2k/commit/46f1fb81e8ea2aea336c67f9846103a80eca2ccb.

**Comment by oschuett** [comment]
This has probably been fixed by #1343.
