### ISSUE TITLE
SIRIUS warning about inconsistent electron numbers

### ISSUE THREAD

**Issue by GengSS** [cp2k/cp2k#2060]
Hi,
I am using the SIRIUS for a bulk structure, and I downloaded the pseudopotentials from SSSP database, converted them to the json format.
The computation went well, however, I found a warnning in the output:

=== Warning at line 217 of file .......SIRIUS-7.3.0/src/density/density.cpp ===
wrong initial charge density
  integral of the density : 83.9999996332
  target number of electrons : 88

Should I worry about this warning? Are the results from the output correct?

Thanks,
Geng

**Comment by oschuett** [comment]
@toxa81, what do you think?

**Comment by toxa81** [comment]
That's a no-harm message. Just tells that the pseudo-potential has some strange atomic pseudo density. I don't know why some of them are not respecting the number of electrons. The initial density will be re-normalized and the normal SCF will start. QE is doing the same.

**Comment by GengSS** [comment]
> That's a no-harm message. Just tells that the pseudo-potential has some strange atomic pseudo density. I don't know why some of them are not respecting the number of electrons. The initial density will be re-normalized and the normal SCF will start. QE is doing the same.

Thanks toxa81,
Indeed the results make sence to me with this harmless warning.
Best,
Geng
