### ISSUE TITLE
Should we remove GCC from the Toolchain?

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#2062]
I'm contemplating to remove GCC from our Toolchain. It takes 10 minutes to build in the CI and adds 655MB to our Docker images.

When GCC was originally added to the Toolchain we were still suffering from numerous compiler bugs around modern Fortran. Furthermore, we were experimenting with Thread Sanitizer. Both is not the case anymore.

So, it seems nowadays we could just always use the GCC provided by the Linux distribution.

**Comment by mkrack** [comment]
That could a premature action. The generic version on our cluster is still gcc 4.8.5 (RedHat 7.9). Due to my experience, the toolchain build of gcc (if requested) does not trouble too much. Most resources are consumed by the libint build.

**Comment by hfp** [comment]
I believe it is a good idea in particular since 4.8.x phases out by already lost support for RHEL/CentOS 7 bits. We should instead check if the toolchain picks up CXX, CC, and FC (or maybe related MPI flavors) correctly.

Though, we never completed the "latest GCC" effort by building GNU Binutils as well. I especially vote for it since we seem to build GCC in two phases ("bootstrap"), which is the default. The latter is expected to likely double the compile-time for GCC, or in turn we could bring it down to 5 minutes if we wanted to keep this option.

**Comment by oschuett** [comment]
> The generic version on our cluster is still gcc 4.8.5 (RedHat 7.9). 

RedHat 7.9 will be end of life in June 2024, which suggests we should wait two more years.
On the other hand, GCC 7 came out 5 years ago and most clusters should have it by now.

So it's a trade-off between taking the hit on the CI time and Docker images or degrading support for the long tail.

> I especially vote for it since we seem to build GCC in two phases ("bootstrap")

No, we actually [disable bootstraping](https://github.com/cp2k/cp2k/blob/cc2ee1bba734d0e82720bdaeedba90332d361c12/tools/toolchain/scripts/stage0/install_gcc.sh#L72).

> Most resources are consumed by the libint build.

Yes, you are [right](https://storage.googleapis.com/cp2k-ci/run-cp2k-generic-psmp-2bf80dfb_report.txt). Libint takes 12.5 minutes while GCC takes only 8.4 minutes. Unfortunately, at the moment there is nothing we can do about libint.

**Comment by hfp** [comment]
> No, we actually [disable bootstraping](https://github.com/cp2k/cp2k/blob/cc2ee1bba734d0e82720bdaeedba90332d361c12/tools/toolchain/scripts/stage0/install_gcc.sh#L72).

Thanks! I've overlooked it.

**Comment by oschuett** [comment]
So we have one vote in favor and one leaning towards opposition. Any other opinions?

**Comment by juerghutter** [comment]
My understanding is that building GCC is a non mandatory option in the toolchain.
Using the system GCC is the default. So why dropping the functionality to optionally
build a custom GCC?

________________________________________

**Comment by oschuett** [comment]
For testing we build the Toolchain with `--install-all`, which includes GCC. While we could throw in `--with-gcc=system`, that would leave the feature untested, which IMHO would be worse than just keeping it for two more years.

**Comment by juerghutter** [comment]
Why untested? We have on the Dashboard GCC7/8/9/10. If we keep at least one
test with GCC-latest the feature would be tested and you could drop the build
on all other tests.

________________________________________

**Comment by oschuett** [comment]
You are right, we can add a dedicated test for it. That's a good compromise.
