### ISSUE TITLE
Plumed 2.7.3 warnings had been pasted here for your reference.

### ISSUE THREAD

**Issue by alas-go** [cp2k/cp2k#2063]
Plumed 2.7.3 warnings had been pasted here for your reference.

[plumed-warnings-FYI.txt](https://github.com/cp2k/cp2k/files/8478107/plumed-warnings-FYI.txt)

**Comment by hfp** [comment]
@carlocamilloni perhaps this report is targeting Plumed team.

**Comment by oschuett** [comment]
This was [fixed upstream](https://github.com/plumed/plumed2/commit/ee230efca6082f3337b4c97c1b3ead69b9e9b30b) and is now available in the recent [Plumed 2.8](https://github.com/plumed/plumed2/releases/tag/v2.8.0) release. We should upgrade.
