### ISSUE TITLE
error installing json_fortran via toolchain script

### ISSUE THREAD

**Issue by MozhyMemol** [cp2k/cp2k#207]

**Comment by MozhyMemol** [comment]
installing cp2k on ubuntu16 using toolchain script went well but it crashes on centOS on the json_fortran part. 
==================== Installing json_fortran ====================
json-fortran-7.0.0.tar.gz is found
Installing from scratch into /root/cp2k/cp2k/tools/toolchain/install/json_fortran-7.0.0
mkdir: cannot create directory قbuildق: File exists
ERROR: (/root/cp2k/cp2k/tools/toolchain/scripts/install_json_fortran.sh, line 35) Non-zero exit code detected.
any comment to solve the problem?

**Comment by oschuett** [comment]
This should be fixed now. Thanks for reporting.
