### ISSUE TITLE
Compilation error in offload_gemm if CP2K is compiled with toolchain with SIRIUS deactivated

### ISSUE THREAD

**Issue by fstein93** [cp2k/cp2k#2087]
On our local machines, I compile CP2K without SIRIUS because I don't need it. The toolchain installs SPLA by default independently of SIRIUS. Unfortunately, the compiler does not find the module file of SPLA in this case. I have not tested whether that also happens with GPU support. The PR #2086 fixes this behavior without GPUs.

**Comment by oschuett** [comment]
This issue seems to have been fixed via #2086.
