### ISSUE TITLE
Many f951 warnings when make psmp on Ubuntu 22.04 with gfortran v11.2.0

### ISSUE THREAD

**Issue by alas-go** [cp2k/cp2k#2090]
Many f951 warnings like below when make psmp on Ubuntu 22.04 with gcc and gfortran v11.2.0. 

f951: Warning: Nonexistent include directory ‘/home/xx/cp2k10dev20220501/obj/local/psmp/exts/dbcsr-v2.3.0-rc0’ [-Wmissing-include-dirs]

**Comment by oschuett** [comment]
While unfortunate these warnings should be benign. Essentially, if it builds then you're good :-)
I'm going to close this issue as we're in the process of migrating to CMake.
