### ISSUE TITLE
Hybrid CELL_OPT gets stuck

### ISSUE THREAD

**Issue by giopale** [cp2k/cp2k#2091]
When running a hybrid cell optimisation the code gets stuck at the first SCF iteration. The output stops coming, while the code keeps running. 

I'm using the 9.1-CrayGNU-21.09-cuda version installed on Piz Daint and I can reproduce the same issue on the 8.2 version on my local cluster.

I uploaded the input file I used and the output in [TiO2-issue.zip](https://github.com/cp2k/cp2k/files/8602844/TiO2-issue.zip).

**Comment by abussy** [comment]
I do not think that it is a problem with CP2K. You are doing a hybrid calculation on a large system with the DZVP-MOLOPT-SR-GTH basis set, only using 36 MPI ranks. I believe that there is simply not enough resources to calculate all the integrals within the allocated time.

The DZVP-MOLOPT-SR-GTH is very diffuse, and not recommended at all for HFX calculations. For condensed phase systems, you should use the ADMM approximation and/or a RI scheme. And for a system of this size, probably 10x more CPUs (roughly).

**Comment by giopale** [comment]
Thank you @abussy. Using ADMM and a larger number of nodes solved the problem.
