### ISSUE TITLE
Incorrect warning particle_methods.F

### ISSUE THREAD

**Issue by waveman68** [cp2k/cp2k#2098]
Dear cp2k Team

In a simulation with an asymmetric .xyz file, I get a warning that a few atoms are too close but they are on opposite sides of the y-axis. My guess is that there is a bug in indexing.

```
...
16>>> Au      -5.10000000     -10.20000000     -3.06000000
...
21>>>Au      -5.10000000      10.20000000     -3.06000000
...
```

` *** WARNING in particle_methods.F:684 :: The distance between the atoms  ***
 *** 16 and 21 is only 0.400 angstrom and thus smaller than the threshold ***
 *** of 0.500 angstrom                                                    ***
`

The .inp and .xyz files are attached. Note that this occurs on a local Haswell machine with 2 sockets with 8 cores each as well as at cscs.ch Piz Daint gpu node.
[cp2k-particle_methods-bug.zip](https://github.com/cp2k/cp2k/files/8630222/cp2k-particle_methods-bug.zip)

**Comment by marci73** [comment]
There is no bug.
You need to consider the periodic boundary conditions.

**Comment by dev-zero** [comment]
Please note that periodicity is the default: https://www.cp2k.org/periodicity

**Comment by waveman68** [comment]
Thanks!
