### ISSUE TITLE
`HARD_EXP_RADIUS` code/documentation disagreement?

### ISSUE THREAD

**Issue by zc62** [cp2k/cp2k#2120]
I have traced up to commit dc564704f0765c347a399827f6bc38536678696c
https://github.com/cp2k/cp2k/blob/dc564704f0765c347a399827f6bc38536678696c/src/atomic_kind_types.F#L1253-L1265
https://github.com/cp2k/cp2k/blob/dc564704f0765c347a399827f6bc38536678696c/src/input_cp2k_subsys.F#L508-L512
Should the default value be 0.8 or 1.512 for non-H elements?

**Comment by mkrack** [comment]
There is no disagreement. The default `HARD_EXP_RADIUS` for H is 1.2 bohr and it is `0.8*1.8897 = 1.512 bohr` for all other elements.

**Comment by zc62** [comment]
Sorry, variable hover somehow showed me `bohr=1.0`, while it is actually `1.0/angstrom`, which is 1.8897. Thanks for the clarification.
