### ISSUE TITLE
Getting Hirshfeld / Mulliken Charges from the LIBCP2K Interface

### ISSUE THREAD

**Issue by Pibemanden** [cp2k/cp2k#2130]
As the title suggests I would like to be able to get the Hirshfeld or Mulliken charges using the general get results interface provided in `src/start/libcp2k.F`.
As far as I can tell implementing something that would enable one to be able to use the following `call get_result_r1(env, '[HIRSHFELD-CHARGE]', natoms, charges, ierr)` would be rather straight forward using the methods provided in `src/common/cp_result_methods.F`.

**Comment by oschuett** [comment]
Looks like a good plan. Feel free to submit a pull request.
