### ISSUE TITLE
some warnings about mpich on  Ubuntu 22.04 

### ISSUE THREAD

**Issue by alas-go** [cp2k/cp2k#2138]
These warnings could be easily reproduced on Ubuntu 22.04.
[Warning20220531.txt](https://github.com/cp2k/cp2k/files/8802907/Warning20220531.txt)

**Comment by alazzaro** [comment]
Are they using the same GCC version?
The warning is something coming with GCC >=v10 and it is completely harmless.

**Comment by alas-go** [comment]
the GCC version is 11.2.0. I think they use the same version.
these warnings could not be recorded by  "tee" command but it printed out on the screen.

**Comment by alazzaro** [comment]
In any case, they are harmless...

**Comment by alas-go** [comment]
I don't know what this mean.  just update
[Some Hints.txt](https://github.com/user-attachments/files/15872583/Some.Hints.txt)
 for your information.
