### ISSUE TITLE
disappeared keyword in GW PRINT SECTION

### ISSUE THREAD

**Issue by robinzyb** [cp2k/cp2k#2150]
Hi, 
 I found the a missing keyword generation in cp2k manual, which also generates wrong .xml file, see: https://manual.cp2k.org/trunk/CP2K_INPUT/ATOM/METHOD/XC/WF_CORRELATION/RI_RPA/GW/PRINT.html

This missing prevents correctly manual installation of pycp2k. 
see: https://github.com/SINGROUP/pycp2k/issues/15

**Comment by mkrack** [comment]
@robinzyb Thanks for reporting the problem. It should be fixed by #2151.
