### ISSUE TITLE
Pexsi does not work with mpi error

### ISSUE THREAD

**Issue by brhr-iwao** [cp2k/cp2k#2209]
I've built cp2k.ssmp 2022.1 with Cygwin on Windows 10.The built binary cannot process pexsi regtest inputs with the following mpi error.

``
*** The MPI_Comm_f2c() function was called before MPI_INIT was invoked. 
*** This is disallowed by the MPI standard.  
*** Your MPI job will now abort. 
Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
``

The process aborted after writing the Linear scaling SCF section on the output.

````
------------------------------ Linear scaling SCF -----------------------------
 eps_scf:                                                              0.100E-07
 eps_filter:                                                           0.000E+00
 Density mixing in g-space:                                       BROYDEN_MIXING
 max_scf:                                                                     50
 fixed chemical potential (mu)                                                 F
 has unit metric:                                                              F
 Computing inv(S):                                                             F
 Computing sqrt(S):                                                            F
 Computing S preconditioner                                                    F
 S sqrt method:                                                     NEWTONSCHULZ
 S sqrt order:                                                                 3
 Extrapolation order:                                                          4
 Use single precision matrices                                                 F
 S preconditioner type                                                      NONE
 Polarized Atomic Orbitals (PAO)                                               F
 Purification method                                             PEXSI
 Cluster type                                                             ATOMIC
 Computing Chebyshev                                                       FALSE
 Using PAO                                                                     F
 -------------------------------------------------------------------------------
blank after this
````

cp2k 9.1 has the same problem, cp2k 8.1 and 8.2 with pexsi v1.2.0 has no problem.

Pexsi prerequisites (parmetis,scotch,upcxx,sympack and superlu_dist) were re-compiled, but this had no effect.

Any idea?

**Comment by oschuett** [comment]
We currently don't really support Windows. In fact, I'm amazed that you managed to build such a complete version of CP2K on Cygwin. In all likelihood you are the world-expert on the matter ¯\_(ツ)_/¯

**Comment by brhr-iwao** [comment]
Dear Ole
I'm very honored for your comment.
The problem is not yet solved. It needs more time to solve.
I released cp2k 2022.1 binary without Pexsi on github.com/brhr-iwao/releases for now.
Best Regards

**Comment by brhr-iwao** [comment]
The mpi error was fixed by the "mpif90" instructions to FC and LD variables instead of "gfortran" on an arch file for Cygwin.

The updated arch file (Cygwin-x86_64-gfortran-pexsi.ssmp) and the built Windows executables were released on [my github](https://github.com/brhr-iwao/CP2K_for_Windows).

**Comment by oschuett** [comment]
Congratulations!

I assume the [instructions](https://www.cp2k.org/howto:compile_on_windows_with_cygwin) on the wiki are somewhat out of date?
If you like, I could create you a wiki account so you can update the page. Just send me an email: ole.schuett@cp2k.org.

**Comment by brhr-iwao** [comment]
Dear Ole
Thank you for the suggestion.
That's exactly right. The dependencies are complicated, it needs to sort out the ways. (I did not use the toolchain.)
I'll contact you later.
