### ISSUE TITLE
Request for --prefix like installer option

### ISSUE THREAD

**Issue by BradleyMorgan** [cp2k/cp2k#2211]
For use on a multi-user HPC Cluster, it would be nice to have a more practical way to manipulate the installation path.  I attempted a couple of Makefile and make options, but wasn't successful and just ended up building directly in the desired target location.  A more standard --prefix or DESTDIR option would make the build steps a little more consistent, but in absence of that just including the step(s) in the documentation would be helpful.

(Apologies if this is already documented\available, but I wasn't able to find any references using the usual suspect keywords).

**Comment by oschuett** [comment]
Our installation procedure is indeed a bit [rudementary](https://github.com/cp2k/cp2k/blob/2de0518571daaa3c7e20434012645c5fb641810e/Makefile#L290). We're currently exploring the adoption of CMake or Meson.

In the meantime, building at the target location is the simplest solution. Alternatively, you can of course also copy the binary and the data files manually. In that case you probably want to set the [`DATA_DIR` variable](https://github.com/cp2k/cp2k/blob/2de0518571daaa3c7e20434012645c5fb641810e/INSTALL.md?plain=1#L521) in the arch file.
