### ISSUE TITLE
Structure does not change in CELL OPT simulation

### ISSUE THREAD

**Issue by longkunxuluke** [cp2k/cp2k#2232]
Hi, I am running a CELL_OPT simulation for a box of electrolyte solution. But I found the structure of the electrolyte solution was not changed through the simulation, i.e., only cell parameters were changed but the result seems wired (cell vectors are too small). The related files are attached. Besides, maybe a very basic question, what's the difference between cell_opt and NPT_F simulation in CP2K? Thanks
[cp2k_cell_opt.zip](https://github.com/cp2k/cp2k/files/9256365/cp2k_cell_opt.zip)

**Comment by mkrack** [comment]
Check your output file. The wavefunction optimisation stops in many optimisation steps after 128 SCF iteration and the wavefunction is not converged at all. Consequently, the calculated forces are useless. Please, post such cases rather in the [CP2K forum](https://groups.google.com/g/cp2k).
