### ISSUE TITLE
Vanishing MGGA Exc term

### ISSUE THREAD

**Issue by suhwans** [cp2k/cp2k#2233]
Dear developer,

Hi, I'm calculating some MGGA functionals and found XC term is not applied when the alpha_beta_gamma value of the cell is not 90 90 90 degrees.

My input is below and if I change 
1. ALPHA_BETA_GAMMA 89 90 89 into  ALPHA_BETA_GAMMA 90 90 90
or
2. MGGA functional into GGA functional (like PBE)
it works.

But if I just run the input below, I get 
Exchange-correlation energy:                                  0.00000000000000
which seems like XC term is not considered at all.

I'm not sure if this is a bug or if something strange thing happened to me when I'm installing the cp2k...

Thanks

Suhwan

&GLOBAL
  PROJECT water
  RUN_TYPE ENERGY
  WALLTIME 00:30:00
  PRINT_LEVEL LOW
&END GLOBAL
&FORCE_EVAL
  METHOD QS
  STRESS_TENSOR ANALYTICAL
  &DFT
    CHARGE 0
    MULTIPLICITY 1
    BASIS_SET_FILE_NAME BASIS_SET
    POTENTIAL_FILE_NAME GTH_POTENTIALS
    UKS .FALSE.
    &MGRID
      NGRIDS 4
      CUTOFF 250
      REL_CUTOFF 40
    &END MGRID
    &QS
      EPS_DEFAULT 1.0E-10
      METHOD GPW
    &END QS
    &SCF
      SCF_GUESS ATOMIC
      EPS_SCF 1.0E-5
      MAX_SCF 50
      &OUTER_SCF .TRUE.
        EPS_SCF 1.0E-5
        MAX_SCF 50
      &END OUTER_SCF
      &OT
        MINIMIZER DIIS
        PRECONDITIONER FULL_SINGLE_INVERSE
      &END OT
      &PRINT
      &END PRINT
    &END SCF
    &POISSON
      PERIODIC XYZ
      POISSON_SOLVER PERIODIC
    &END POISSON
    &XC
      &XC_FUNCTIONAL
       &MGGA_X_R2SCAN .TRUE.
       &END MGGA_X_R2SCAN
       &MGGA_C_R2SCAN .TRUE.
       &END MGGA_C_R2SCAN
      &END XC_FUNCTIONAL
    &END XC
    &PRINT
      &HIRSHFELD OFF
          FILENAME charge
      &END HIRSHFELD
      &MULLIKEN OFF
          FILENAME charge
      &END MULLIKEN
      &E_DENSITY_CUBE OFF
      &END E_DENSITY_CUBE
    &END PRINT
  &END DFT
  &SUBSYS
    &CELL
      ABC 8.71074 7.52941 7.09859
      ALPHA_BETA_GAMMA 89 90 89
      PERIODIC XYZ
      &CELL_REF
        ABC 8.71074 7.52941 7.09859
        ALPHA_BETA_GAMMA 89 90 89
        PERIODIC XYZ
      &END CELL_REF
    &END CELL
    &COORD
O     0.0000000    0.0000000   -0.3893611
H     0.7629844    0.0000000    0.1946806
H    -0.7629844    0.0000000    0.1946806
    &END COORD
    &KIND H
      BASIS_SET DZVP-GTH-PADE
      POTENTIAL GTH-PBE-q1
    &END KIND
    &KIND O
      BASIS_SET DZVP-GTH-PADE
      POTENTIAL GTH-PBE-q6
    &END KIND
  &END SUBSYS
&END FORCE_EVAL

**Comment by mkrack** [comment]
I cannot reproduce your result, E(xc) = 0, with your input using the current [CP2K release version 2022.1](https://github.com/cp2k/cp2k/releases/download/v2022.1/cp2k-2022.1-Linux-gnu-x86_64.ssmp). E(xc) is -4.24195 Hartree.

[H2O_R2SCAN.zip](https://github.com/cp2k/cp2k/files/9266600/H2O_R2SCAN.zip)

**Comment by suhwans** [comment]
Dear Prof. Matthias Krack,

Thanks for testing. I also tested this with another cluster and found that MGGA works fine. Something seems wrong with installing in the previous cluster... And this is weird because all other things work fine but MGGA.

Thank you for the help.

**Comment by suhwans** [comment]
This issue was resolved when I installed all packages using --install-all using install_cp2k_toolchain.sh.
