### ISSUE TITLE
DBM update causes failure of all Intel regression tests

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#2249]
All [Intel regression tester](https://dashboard.cp2k.org/) are failing after the last [DBM update](https://github.com/cp2k/cp2k/commit/1b908ebe246913d1744f486b1b79590565670e7b). Runs are hanging as soon as multiple MPI tasks AND OpenMP threads are involved. The error can be reproduced by running the [dbt_tas_unittest](https://github.com/mkrack/cp2k/blob/master/src/dbt/tas/dbt_tas_unittest.F).

**Comment by oschuett** [comment]
@mkrack, can you confirm that the extra brackets from https://github.com/cp2k/cp2k/pull/2250/commits/e5f6aab4193d2dc97a92b9276601eda07f176a81 fix the problem?

**Comment by mkrack** [comment]
@oschuett yes, e5f6aab seems to fix the problem with [dbt_tas_unittest](https://github.com/mkrack/cp2k/blob/master/src/dbt/tas/dbt_tas_unittest.F).
