### ISSUE TITLE
Make problem :Mismatch in components of derived type ‘libxsmm_matdiff_info’ from ‘libxsmm’ at (1): expecting ‘l1_ref’, but got ‘rsq’ compilation terminated.

### ISSUE THREAD

**Issue by hxzwqw** [cp2k/cp2k#2254]
/media/hxz/Mdel/gmx/cp2k_qm/cp2k/src/aobasis/../base/base_uses.f90:4:6:

    4 |   USE base_hooks,                      ONLY: cp__a,&
      |      1
Fatal Error: Mismatch in components of derived type ‘libxsmm_matdiff_info’ from ‘libxsmm’ at (1): expecting ‘l1_ref’, but got ‘rsq’
compilation terminated.
make[3]: *** [/media/hxz/Mdel/gmx/cp2k_qm/cp2k/Makefile:515：ai_contraction_sphi.o] ERROR 1
make[3]: *** Waiting for Unfinished Tasks....
make[2]: *** [/media/hxz/Mdel/gmx/cp2k_qm/cp2k/Makefile:154：libcp2k] ERROR 2
make[1]: *** [/media/hxz/Mdel/gmx/cp2k_qm/cp2k/Makefile:125：psmp] ERROR 2
make: *** [Makefile:120：libcp2k] ERROR 2

I need some advice for this, thanks

**Comment by hfp** [comment]
Is this issue still current? If so, can you share the versions like CP2K/master and LIBXSMM 1.17?

**Comment by hfp** [comment]
Thank you for reporting! Feel free to reopen with more details.
