### ISSUE TITLE
make 2022.1 have some problem 

### ISSUE THREAD

**Issue by hsianghualite** [cp2k/cp2k#2259]
/usr/bin/ld: cannot find -lspla
collect2: error: ld returned 1 exit status
make[3]: *** [/opt/apps/cp2k/cp2k-2022.1/obj/local/pdbg/all.dep:168：/opt/apps/cp2k/cp2k-2022.1/exe/local/memory_utilities_unittest.pdbg] error 1
make[3]: *** waiting for unfinished task....
/usr/bin/ld: cannot find  -lspla not found 
collect2: error: ld returned 1 exit status
make[3]: *** [/opt/apps/cp2k/cp2k-2022.1/obj/local/pdbg/all.dep:184：/opt/apps/cp2k/cp2k-2022.1/exe/local/dbm_miniapp.pdbg] error 1
/usr/bin/ld: cannot find -lspla
collect2: error: ld returned 1 exit status
make[3]: *** [/opt/apps/cp2k/cp2k-2022.1/obj/local/pdbg/all.dep:144：/opt/apps/cp2k/cp2k-2022.1/exe/local/graph.pdbg] error 1
/usr/bin/ld: cannot find -lspla
collect2: error: ld returned 1 exit status
make[3]: *** [/opt/apps/cp2k/cp2k-2022.1/obj/local/pdbg/all.dep:164：/opt/apps/cp2k/cp2k-2022.1/exe/local/parallel_rng_types_unittest.pdbg] error  1
make[2]: *** [/opt/apps/cp2k/cp2k-2022.1/Makefile:143：all] error  2
make[1]: *** [/opt/apps/cp2k/cp2k-2022.1/Makefile:125：pdbg] error  2
make[1]: *** waiting for unfinished task....
make[2]: *** [/opt/apps/cp2k/cp2k-2022.1/Makefile:143：all] error 2
make[1]: *** [/opt/apps/cp2k/cp2k-2022.1/Makefile:125：psmp] error  2
make: *** [Makefile:120：all] error  2

**Comment by picassotech** [comment]
Have your problem been solved?

**Comment by hsianghualite** [comment]
> Have your problem been solved?
No, only ssmp can be complied,psmp can not

**Comment by fstein93** [comment]
If you use the arch files of the toolchain, the path to the SpLA-libraries are missing. You have to manually add them like -L'/path/to/cp2k/tools/toolchain/install/SpLA-<version number>/lib' .

**Comment by hsianghualite** [comment]
> If you use the arch files of the toolchain, the path to the SpLA-libraries are missing. You have to manually add them like -L'/path/to/cp2k/tools/toolchain/install/SpLA-/lib' .

many thanks

**Comment by mkrack** [comment]
Seems to be resolved.
