### ISSUE TITLE
Building v2022.1 with HIP: hipcc cannot find 'omp.h'

### ISSUE THREAD

**Issue by vvsteg** [cp2k/cp2k#2265]
Hi!

I am trying building CP2K with HIP (ROCm ver. 5.0):

After building the toolchain

``./install_cp2k_toolchain.sh --with-mpich --with-elpa=no --with-cosma=no --enable-hip --gpu-ver=Mi50``

I do the make

``make -j 8 ARCH=local_hip VERSION=psmp``

but it fails with

```
/opt/rocm//hip/bin/hipcc -c -fopenmp -fPIE -D__HIP_PLATFORM_AMD__ -g --offload-arch=gfx906 -O3 --std=c++11 -Wall -Wextra -Werror -D__LIBXSMM   -D__MKL -D__FFTW3   -D__LIBINT -D__LIBXC    -D__SPGLIB -D__LIBVORI  -D__OFFLOAD_GEMM       -D__HIP_PLATFORM_AMD__ -D__OFFLOAD_HIP   -D__DBCSR_ACC -I/opt/rocm//include /mnt/storage/home/vvsteg/repos/cp2k/cp2k-2022.1/src/dbm/dbm_multiply_gpu.cu
In file included from /mnt/storage/home/vvsteg/repos/cp2k/cp2k-2022.1/src/dbm/dbm_multiply_gpu.cu:15:
In file included from /mnt/storage/home/vvsteg/repos/cp2k/cp2k-2022.1/src/dbm/dbm_multiply_gpu.h:15:
In file included from /mnt/storage/home/vvsteg/repos/cp2k/cp2k-2022.1/src/dbm/dbm_multiply_internal.h:11:
/mnt/storage/home/vvsteg/repos/cp2k/cp2k-2022.1/src/dbm/dbm_shard.h:10:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated when compiling for gfx906.
```

If I add ``-D__NO_OFFLOAD_DBM`` it fails too

```
/opt/rocm//hip/bin/hipcc -c -fPIE -D__HIP_PLATFORM_AMD__ -g --offload-arch=gfx906 -O3 --std=c++11 -Wall -Wextra -Werror -D__LIBXSMM   -D__MKL -D__FFTW3   -D__LIBINT -D__LIBXC    -D__SPGLIB -D__LIBVORI  -D__OFFLOAD_GEMM       -D__HIP_PLATFORM_AMD__ -D__OFFLOAD_HIP   -D__DBCSR_ACC -D__NO_OFFLOAD_DBM -I/opt/rocm//include /mnt/storage/home/vvsteg/repos/cp2k/cp2k-2022.1/src/grid/gpu/grid_gpu_collocate.cu
/mnt/storage/home/vvsteg/repos/cp2k/cp2k-2022.1/src/grid/gpu/grid_gpu_task_list.cu:12:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated when compiling for gfx906.
```

And only if I add ``-D__NO_OFFLOAD_GRID`` the building is successful.

As far as I understand, the problem is connected with the general problem  that ``hipcc`` (clang) does not see ``omp.h``

Please let me know if it is possible to make a full HIP build without switching off those 2 GPU acceleration options?

NB: Building for CUDA (``--enable-cuda``) does not show such a problem.

Best regards,
Vladimir

**Comment by alazzaro** [comment]
Interesting, I don't have OpenMP in my OFFLOAD flag... Could you check the line

```
OFFLOAD_FLAGS = -fPIE -D__HIP_PLATFORM_AMD__ -g --offload-arch=gfx90a -O3 --std=c++11 -Wall -Wextra -Werror $(DFLAGS) -I/opt/rocm/include
```
(this is mine)

in your local_hip.psmp?

**Comment by vvsteg** [comment]
My OFFLOAD flag looks exactly the same

```
OFFLOAD_FLAGS = -fPIE -D__HIP_PLATFORM_AMD__ -g --offload-arch=gfx906 -O3 --std=c++11 -Wall -Wextra -Werror $(DFLAGS) -I/opt/rocm//include
```

However, e.g. in ``cp2k-2022.1/src/grid/gpu/grid_gpu_task_list.cu`` there is the following

```
#include "../../offload/offload_runtime.h"
#if defined(__OFFLOAD) && !defined(__NO_OFFLOAD_GRID)

#include <assert.h>
#include <omp.h>
```

And ``hipcc`` cannot find ``omp.h``...

**Comment by oschuett** [comment]
I believe this is a mistake because we're not actually using OpenMP in the grid GPU backend. I'll look into it.

**Comment by alazzaro** [comment]
Well, I can compile in my case... What I see as a difference is that your compile line is

```
/opt/rocm//hip/bin/hipcc -c -fopenmp -fPIE -D__HIP_PLATFORM_AMD__ -g --offload-arch=gfx906 -O3 --std=c++11 -Wall -Wextra -Werror -D__LIBXSMM   -D__MKL -D__FFTW3   -D__LIBINT -D__LIBXC    -D__SPGLIB -D__LIBVORI  -D__OFFLOAD_GEMM       -D__HIP_PLATFORM_AMD__ -D__OFFLOAD_HIP   -D__DBCSR_ACC -I/opt/rocm//include /mnt/storage/home/vvsteg/repos/cp2k/cp2k-2022.1/src/dbm/dbm_multiply_gpu.cu
```

while I don't have `-fopenmp`. So I wonder where that flag is coming...

**Comment by alazzaro** [comment]
> I believe this is a mistake because we're not actually using OpenMP in the grid GPU backend. I'll look into it.

The original error is reported in the dbm code too, in particular from dbm_shard.h....

**Comment by oschuett** [comment]
> The original error is reported in the dbm code too, in particular from dbm_shard.h....

Oh, I missed that. Well, `dbm_shard.h` does need OpenMP because `dbm_shard_t` contains a member of type `omp_lock_t`.

**Comment by alazzaro** [comment]
I can actually compile that code with the following line

```
/opt/rocm//hip/bin/hipcc -c -fopenmp -fPIE -D__HIP_PLATFORM_AMD__ -g --offload-arch=gfx906 -O3 --std=c++11 -Wall -Wextra -Werror -D__LIBXSMM   -D__MKL -D__FFTW3   -D__LIBINT -D__LIBXC    -D__SPGLIB -D__LIBVORI  -D__OFFLOAD_GEMM       -D__HIP_PLATFORM_AMD__ -D__OFFLOAD_HIP   -D__DBCSR_ACC -I/opt/rocm//include /pfs/lustrep4/projappl/project_462000003/lazzaroa/regtests/cp2k_alazzaro/src/dbm/dbm_multiply_gpu.cu
```

and it compiles. There is something wrong in ROCM installation...

**Comment by vvsteg** [comment]
> while I don't have `-fopenmp`. So I wonder where that flag is coming...

removing  does not change anything in my case...

```
/opt/rocm//hip/bin/hipcc -c -fPIE -D__HIP_PLATFORM_AMD__ -g --offload-arch=gfx906 -O3 --std=c++11 -Wall -Wextra -Werror -D__LIBXSMM   -D__MKL -D__FFTW3   -D__LIBINT -D__LIBXC    -D__SPGLIB -D__LIBVORI  -D__OFFLOAD_GEMM       -D__HIP_PLATFORM_AMD__ -D__OFFLOAD_HIP   -D__DBCSR_ACC -I/opt/rocm//include /mnt/storage/home/vvsteg/repos/cp2k/cp2k-2022.1/src/dbm/dbm_multiply_gpu.cu
In file included from /mnt/storage/home/vvsteg/repos/cp2k/cp2k-2022.1/src/dbm/dbm_multiply_gpu.cu:15:
In file included from /mnt/storage/home/vvsteg/repos/cp2k/cp2k-2022.1/src/dbm/dbm_multiply_gpu.h:15:
In file included from /mnt/storage/home/vvsteg/repos/cp2k/cp2k-2022.1/src/dbm/dbm_multiply_internal.h:11:
/mnt/storage/home/vvsteg/repos/cp2k/cp2k-2022.1/src/dbm/dbm_shard.h:10:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated when compiling for gfx906.
```

**Comment by vvsteg** [comment]
> and it compiles. There is something wrong in ROCM installation...

Please let me know what ROCm version do you use? The latest one?

**Comment by vvsteg** [comment]
I use the following

```
hipcc --version
HIP version: 5.0.13601-6b731c37
AMD clang version 14.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.0.0 22051 235b6880e2e515507478181ec11a20c1ec87945b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-5.0.0/llvm/bin
```

**Comment by alazzaro** [comment]
I'm using 5.0.2.

```
> hipcc --version
HIP version: 5.0.13601-ded05588
AMD clang version 14.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.0.2 22065 030a405a181176f1a7749819092f4ef8ea5f0758)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
```

Let me see if I have 5.0.0 somewhere...

**Comment by alazzaro** [comment]
OK, just tried with 5.0.0:

```
AMD clang version 14.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.0.0 22051 235b6880e2e515507478181ec11a20c1ec87945b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm-5.0.0/llvm/bin
> /opt/rocm-5.0.0/hip/bin/hipcc -c -fPIE -D__HIP_PLATFORM_AMD__ -g --offload-arch=gfx906 -O3 --std=c++11 -Wall -Wextra -Werror -D__LIBXSMM   -D__MKL -D__FFTW3   -D__LIBINT -D__LIBXC    -D__SPGLIB -D__LIBVORI  -D__OFFLOAD_GEMM       -D__HIP_PLATFORM_AMD__ -D__OFFLOAD_HIP   -D__DBCSR_ACC -I/opt/rocm-5.0.0/include src/dbm/dbm_multiply_gpu.cu
```

it compiles. No sure where the problem can be... Maybe you can make a small code (helloworld like) with the include and see if it works?

**Comment by vvsteg** [comment]
@alazzaro , thank you very much! 

I'll try to find what is wrong with my ROCm installation...

**Comment by vvsteg** [comment]
Indeed, our ROCm installation was not complete. After additional dev packages have been installed, building with HIP goes without issues. Excuse me for the confusion and thank you for the help.

P.S. The GPU performance, however, is far from being proportional to the theoretical peak performance if we compare with the CPU build of CP2K:

H2O-512 benchmark:
1 node x (E5-1650v3 with 6 MPI ranks + one Mi50): `144 sec` for 1st iteration and `47 sec` for the next iterations
2 nodes x (E5-1650v3 with 6 MPI ranks + one Mi50): `79 sec` and `26 sec`
1 node x (2 x EPYC 7662 with 128 MPI ranks): `18 sec` and `6 sec`

**Comment by oschuett** [comment]
I'm glad you got it to work!

For GGA calculations currently only the grid routines (collocate and integrate) can take advantage of GPUs. See https://www.cp2k.org/gpu for more info.
