### ISSUE TITLE
Different Total Energy for Same input with different verion of CP2K

### ISSUE THREAD

**Issue by FayettG** [cp2k/cp2k#2298]
Hi CP2K group,

I was testing the consistence in total energies with different version of CP2K with a 5-atom metalic system.
I kept the input the same and grep the total energy from the output, as listed below:

test-2022.out: ENERGY| Total FORCE_EVAL ( QS ) energy [a.u.]:             -590.007000597674619
test-9.1.out: ENERGY| Total FORCE_EVAL ( QS ) energy [a.u.]:             -590.007000597715887
test-8.2.out: ENERGY| Total FORCE_EVAL ( QS ) energy [a.u.]:             **-590.007000597679507**
test-7.1.out: ENERGY| Total FORCE_EVAL ( QS ) energy (a.u.):             **-590.137753139325127**
test-6.1.out: ENERGY| Total FORCE_EVAL ( QS ) energy (a.u.):             -590.137753139571487

As you can see there's a huge energy difference between verion 7.1 and later versions as it's just a 5 atom system.

The cp2k binaries were downloaded from github directly.

Best 
Fayette

**Comment by fstein93** [comment]
Hi Fayette,

Without any further information, your observation may be caused by changes in basis sets or pseudo potentials or bugs in libraries. It is easier to pin it down if you provide your input files and the geometry and maybe the two relevant output files.

Best,
Frederick

**Comment by FayettG** [comment]
Hi Frederick,

Thank you for your reply!
I calculate the same input with different binaries, so it shouldn't be related with the basis sets or pseudo potentials.
Here I list the difference between the output of 7.1 and 8.2:
 
![Screenshot from 2022-09-23 15-55-44](https://user-images.githubusercontent.com/87972281/191990571-3ad7d9ae-479d-4f53-8edc-669cd541dc3a.png)


![Screenshot from 2022-09-23 15-56-33](https://user-images.githubusercontent.com/87972281/191990596-2d5f1089-7c38-466a-a1ee-ccb3bd7c5bfe.png)

Thank you!

Best wishes
Fayette

**Comment by fstein93** [comment]
Okay, the geometry did not change. But without knowing the actual method, noone can help you. Can you also provide the input file and the geometry?

**Comment by juerghutter** [comment]
You show a screen shot from the atomic calculation used for the initial guess.
What about the energy from the calculation of the real system?
 JH

________________________________________

**Comment by FayettG** [comment]
Dear both,

Sorry for my late reply! 
Here attach my output.
I am studying Iron oxide with GGA+U, using OT.
As it's just a test, I was using a 1x1x1 unit cell. 

[8.2.txt](https://github.com/cp2k/cp2k/files/9646426/8.2.txt)
[7.1.txt](https://github.com/cp2k/cp2k/files/9646427/7.1.txt)

Best wishes
Fayette

**Comment by oschuett** [comment]
I'm going to close this as it seems to be a stale usage issue. If you're still having this problem please post you question in our [user forum](https://www.cp2k.org/howto:forum).
