### ISSUE TITLE
Input preprocessor should export essential built-in settings as variables

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#231]
The input preprocessor should export built-in settings like the data directory (built-in, can be overwritten in the environment) and configuration flags as pre-defined `$VARIABLES`.

This could then be a more generic replacement for the `@XCTYPE` directive:

```
@INCLUDE "${_DATADIR}/xc_section/PBE.sec"
```

or allow for more generic input files.

Currently we're not injecting any variables.

**Comment by oschuett** [comment]
Paths relative to the data directory already work. Simply pass `./xc_section/PBE.sec` or `xc_section/PBE.sec` to `open_file()`. The logic for this resides in [`discover_file()`](https://github.com/cp2k/cp2k/blob/master/src/common/cp_files.F#L517).

**Comment by oschuett** [comment]
As noted in my previous comment, I think this use-case is already covered by [discover_file](https://github.com/cp2k/cp2k/blob/e56e7b7d9ba6c1949772cc2fc61fa2959be6313e/src/common/cp_files.F#L508).

**Comment by dev-zero** [comment]
the point here is about being able to define paths explicitly according to builtin paths, for people who like to avoid random overrides of `@INCLUDE`d paths due to different working directories

**Comment by oschuett** [comment]
No comments in the last year. I don't think there is really an audience for this feature.
