### ISSUE TITLE
Segmentation fault in pw/pw_methods.F:2289

### ISSUE THREAD

**Issue by k9cdt** [cp2k/cp2k#2312]
I'm running a DFT based QM/MM job with PBE functional. This is a newly compiled version so it may be a compile time problem. Initially I compiled with other external libraries like libint and libxsmm, etc. Then this problem can be repeated even if I only use the bare minimum--compiled only with MKL 2018.2 and PLUMED. CP2K is version 9.1 cloned from the git.

> ```
>  SCF WAVEFUNCTION OPTIMIZATION
> 
>   ----------------------------------- OT ---------------------------------------
>   Minimizer      : BROYDEN             : Broyden 
>                    BETA                :       0.90000000
>                    GAMMA               :       0.50000000
>                    SIGMA               :       0.25000000
>                             using      : -   7 BROYDEN vectors
>   Preconditioner : FULL_ALL            : diagonalization, state selective
>   Precond_solver : DEFAULT
>   stepsize       :    0.15000000                  energy_gap     :    0.10000000
>   eps_taylor     :   0.10000E-15                  max_taylor     :             4
>   ----------------------------------- OT ---------------------------------------
> 
>   Step     Update method      Time    Convergence         Total energy    Change
>   ------------------------------------------------------------------------------
> 
> Program received signal SIGSEGV, Segmentation fault.
> 0x0000000002d31371 in pw_methods::pw_integral_ab (pw1=..., pw2=..., 
>     sumtype=<error reading variable: Cannot access memory at address 0xd8000>)
>     at /project2/gavoth/dteng/cp2k-qm-cgmm/src/pw/pw_methods.F:2289
> 2289	            integral_value = REAL(accurate_sum(CONJG(pw1%cc(:))*pw2%cc(:)), KIND=dp) !? complex bit
> 
> ```

Calling stack:
>```
> Image              PC                Routine            Line        Source             
> cp2k.psmp          00000000033F638D  Unknown               Unknown  Unknown
> libpthread-2.17.s  00007FE826DB5630  Unknown               Unknown  Unknown
> cp2k.psmp          0000000002D31371  pw_methods_mp_pw_        2289  pw_methods.F
> cp2k.psmp          0000000002D3B2CE  pw_poisson_method         320  pw_poisson_methods.F
> cp2k.psmp          0000000000AF8302  qs_ks_methods_mp_         404  qs_ks_methods.F
> cp2k.psmp          0000000000AF6AE9  qs_ks_methods_mp_        1177  qs_ks_methods.F
> cp2k.psmp          000000000181212D  qs_scf_mp_init_sc         794  qs_scf.F
> cp2k.psmp          000000000180C0BC  qs_scf_mp_scf_env         454  qs_scf.F
> cp2k.psmp          00000000018029C8  qs_scf_mp_scf_            244  qs_scf.F
> cp2k.psmp          0000000001405A55  qs_energy_mp_qs_e          93  qs_energy.F
> cp2k.psmp          00000000015881CD  qs_force_mp_qs_fo         202  qs_force.F
> cp2k.psmp          00000000015867DF  qs_force_mp_qs_ca         112  qs_force.F
> cp2k.psmp          00000000015262B4  qmmm_force_mp_qmm         170  qmmm_force.F
> cp2k.psmp          0000000001223007  force_env_methods         285  force_env_methods.F
> cp2k.psmp          00000000005D3754  md_run_mp_qs_mol_         373  md_run.F
> cp2k.psmp          00000000005D2B99  md_run_mp_qs_mol_         153  md_run.F
> cp2k.psmp          0000000000417474  cp2k_runs_mp_run_         365  cp2k_runs.F
> cp2k.psmp          000000000040E4FA  MAIN__                    379  cp2k.F
> cp2k.psmp          00000000034615C2  Unknown               Unknown  Unknown
> libc-2.17.so       00007FE81E48D545  __libc_start_main     Unknown  Unknown
> cp2k.psmp          000000000040CFE9  Unknown               Unknown  Unknown
>```

And GDB shows neither pw1%cc and pw2%cc is associated

**Comment by k9cdt** [comment]
It looks to me that in `pw/pw_type.F`, after `ALLOCATE(pw)`, it was not kept by the compiler but destroyed? Here's additional debug information I had.

In line 168 the object is still existing but in line 180 it is again not associated.

```
Breakpoint 8, pw_types::pw_create (pw=0x200000000, 
    pw_grid=<error reading variable: Cannot resolve DW_OP_push_object_address for a missing object>, 
    use_data=<error reading variable: Cannot access memory at address 0x1>, in_space=0, 
    cr3d_ptr=<object is not associated>) at /project2/gavoth/dteng/cp2k-qm-cgmm/src/pw/pw_types.F:168
168	      ALLOCATE (pw)
(gdb) p pw
$8 = (PTR TO -> ( Type pw_type
REAL(8) :: cr(65125549027899:7236893877685950381)
REAL(8) :: cr3d(65125549027899:7236893877685950381,281784214356022,281784214355968:563568428777543)
COMPLEX(8) :: cc(65125549027899:7236893877685950381)
COMPLEX(8) :: cc3d(65125549027899:7236893877685950381,281784214356022,281784214355968:563568428777543)
INTEGER(4) :: in_use
INTEGER(4) :: in_space
INTEGER(4) :: id_nr
INTEGER(4) :: ref_count
PTR TO -> (     Type pw_grid_type
INTEGER(8) :: ngpts
INTEGER(8) :: ngpts_cut
INTEGER(4) :: bounds(2,3)
INTEGER(4) :: npts(3)
INTEGER(4) :: ngpts_local
INTEGER(4) :: ngpts_cut_local
INTEGER(4) :: bounds_local(2,3)
INTEGER(4) :: npts_local(3)
REAL(8) :: dr(3)
REAL(8) :: dh(3,3)
REAL(8) :: dh_inv(3,3)
LOGICAL(4) :: orthorhombic
REAL(8) :: dvol
REAL(8) :: vol
REAL(8) :: cutoff
        Type map_pn
INTEGER(4) :: pos(65125549027899:7236893877685950381)
INTEGER(4) :: neg(65125549027899:7236893877685950381)
        End Type map_pn :: mapl
        Type map_pn
INTEGER(4) :: pos(65125549027899:7236893877685950381)
INTEGER(4) :: neg(65125549027899:7236893877685950381)
        End Type map_pn :: mapm
        Type map_pn
---Type <return> to continue, or q <return> to quit---q
Quit
(gdb) c
Continuing.

Breakpoint 7, pw_types::pw_create (pw=0x7fffea16eb00, pw_grid=<object is not associated>, use_data=2, 
    in_space=<error reading variable: Cannot access memory at address 0xffffffffffffffff>, 
    cr3d_ptr=<object is not associated>) at /project2/gavoth/dteng/cp2k-qm-cgmm/src/pw/pw_types.F:180
180	      IF (PRESENT(cr3d_ptr)) THEN
(gdb) p pw
$9 = (PTR TO -> ( Type pw_type
REAL(8) :: cr(Cannot access it because the object is not associated.
```

**Comment by fstein93** [comment]
Sorry for the late reply. Have you tried to run the regtests (make -j ARCH=... VERSION=... test ) ? From the code (second post), I do not see any reason how pw should lose its association state between the given lines. How do you compile the code? Can you try a later version (2022.1) ?

**Comment by alazzaro** [comment]
Maybe it is a problem of stacksizes?

**Comment by k9cdt** [comment]
Thank you @alazzaro !  It is indeed a stack size problem. Running `ulimit -s <a_bigger_size>` helps.
