### ISSUE TITLE
[regtesting] set CP2K_DATA_DIR environment variable to use data in source directory

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#234]
Tests are usually run between the build and installation steps. If `CP2K_DATA` is set to point to the final location after installation but installation is not done already, regtests may fail to find referenced files and/or load files from the current installation dir.

**Comment by oschuett** [comment]
So, where and when should we set `$CP2K_DATA_DIR`?

**Comment by dev-zero** [comment]
I guess either in our `Makefile` when running `make test` (assuming the `do_regtest` does not clean the environment) or in the `do_regtest` script itself

**Comment by oschuett** [comment]
Yes, `do_regtest` seems like a good place.
