### ISSUE TITLE
Is hybrid functional available in CP2K/SIRIUS?

### ISSUE THREAD

**Issue by suhwans** [cp2k/cp2k#2344]
Dear developers,

Hi, I'm trying to calculate PW-only hybrid calculation using SIRIUS in CP2K environment.
But seems like DFA part is working but not the HF part.
Below is my input file and thank you for the help.

&FORCE_EVAL
  METHOD SIRIUS
  &PW_DFT
    &CONTROL
       PROCESSING_UNIT cpu
       STD_EVP_SOLVER_NAME lapack
       GEN_EVP_SOLVER_NAME lapack
       VERBOSITY 1
    &END CONTROL
    &PARAMETERS
       ELECTRONIC_STRUCTURE_METHOD  pseudopotential
       SMEARING_WIDTH 0.01
       USE_SYMMETRY true
       NUM_MAG_DIMS 0
       GK_CUTOFF 5.0
       PW_CUTOFF 20.00
       ENERGY_TOL 1e-10
       DENSITY_TOL 1e-8
       NUM_DFT_ITER 100
       NGRIDK 2 2 2
    &END PARAMETERS
    &ITERATIVE_SOLVER
       ENERGY_TOLERANCE 1e-5
       NUM_STEPS 20
       SUBSPACE_SIZE 4
       TYPE davidson
       CONVERGE_BY_ENERGY 1
    &END ITERATIVE_SOLVER
    &MIXER
       TYPE broyden2
       MAX_HISTORY 8
    &END MIXER
  &END PW_DFT
  &DFT
    &XC
      &XC_FUNCTIONAL
       &GGA_X_PBE
         SCALE 0.75
       &END GGA_X_PBE
       &GGA_C_PBE
         SCALE 1.0
       &END GGA_C_PBE
      &END XC_FUNCTIONAL
      &HF
        FRACTION 0.25
        &SCREENING
          EPS_SCHWARZ 1.0E-8
          SCREEN_ON_INITIAL_P FALSE
        &END
        &INTERACTION_POTENTIAL
          POTENTIAL_TYPE TRUNCATED
          CUTOFF_RADIUS  7
          T_C_G_DATA t_c_g.dat
        &END
        &MEMORY
          MAX_MEMORY 1000
          EPS_STORAGE_SCALING 0.1
        &END
      &END HF
    &END XC
  &END DFT
  &SUBSYS
    &CELL
A 16 0 0
B 0 16 0
C 0 0 16
    &END CELL
    &COORD
H     7.0    6.0    6.0
H     6.0    7.0    6.0
O     6.2   6.0    6.0
    &END COORD
    &KIND H
      POTENTIAL UPF H.json
    &END KIND
    &KIND O
      POTENTIAL UPF O.json
    &END KIND
  &END SUBSYS
&END FORCE_EVAL
&GLOBAL
  PROJECT C
  PRINT_LEVEL LOW
&END GLOBAL

**Comment by juerghutter** [comment]
Hi

this functionality is not available.

regards

JH

________________________________________
From: suhwans ***@***.***>
Sent: Tuesday, October 11, 2022 4:29 AM
To: cp2k/cp2k
Cc: Subscribed
Subject: [cp2k/cp2k] Is hybrid functional available in CP2K/SIRIUS? (Issue #2344)

Dear developers,

Hi, I'm trying to calculate PW-only hybrid calculation using SIRIUS in CP2K environment.
But seems like DFA part is working but not the HF part.
Below is my input file and thank you for the help.

&FORCE_EVAL
METHOD SIRIUS
&PW_DFT
&CONTROL
PROCESSING_UNIT cpu
STD_EVP_SOLVER_NAME lapack
GEN_EVP_SOLVER_NAME lapack
VERBOSITY 1
&END CONTROL
&PARAMETERS
ELECTRONIC_STRUCTURE_METHOD pseudopotential
SMEARING_WIDTH 0.01
USE_SYMMETRY true
NUM_MAG_DIMS 0
GK_CUTOFF 5.0
PW_CUTOFF 20.00
ENERGY_TOL 1e-10
DENSITY_TOL 1e-8
NUM_DFT_ITER 100
NGRIDK 2 2 2
&END PARAMETERS
&ITERATIVE_SOLVER
ENERGY_TOLERANCE 1e-5
NUM_STEPS 20
SUBSPACE_SIZE 4
TYPE davidson
CONVERGE_BY_ENERGY 1
&END ITERATIVE_SOLVER
&MIXER
TYPE broyden2
MAX_HISTORY 8
&END MIXER
&END PW_DFT
&DFT
&XC
&XC_FUNCTIONAL
&GGA_X_PBE
SCALE 0.75
&END GGA_X_PBE
&GGA_C_PBE
SCALE 1.0
&END GGA_C_PBE
&END XC_FUNCTIONAL
&HF
FRACTION 0.25
&SCREENING
EPS_SCHWARZ 1.0E-8
SCREEN_ON_INITIAL_P FALSE
&END
&INTERACTION_POTENTIAL
POTENTIAL_TYPE TRUNCATED
CUTOFF_RADIUS 7
T_C_G_DATA t_c_g.dat
&END
&MEMORY
MAX_MEMORY 1000
EPS_STORAGE_SCALING 0.1
&END
&END HF
&END XC
&END DFT
&SUBSYS
&CELL
A 16 0 0
B 0 16 0
C 0 0 16
&END CELL
&COORD
H 7.0 6.0 6.0
H 6.0 7.0 6.0
O 6.2 6.0 6.0
&END COORD
&KIND H
POTENTIAL UPF H.json
&END KIND
&KIND O
POTENTIAL UPF O.json
&END KIND
&END SUBSYS
&END FORCE_EVAL
&GLOBAL
PROJECT C
PRINT_LEVEL LOW
&END GLOBAL

**Comment by oschuett** [comment]
Please submit your feature request to the [SIRIUS project](https://github.com/electronic-structure/SIRIUS/issues/).
