### ISSUE TITLE
CP2K problem with simple compilation

### ISSUE THREAD

**Issue by adda-2020** [cp2k/cp2k#2361]
Hello 
I tried to compile CP2K 2022.2  with script ./install_cp2k_toolchain.sh and make -j 12 ARCH=local VERSION="ssmp sdbg psmp pdbg" after a few minutes of compilation I got the following error
Please can you help me to pass this error

opt/intel/oneapi/intel_one_api_base_2022/mpi/2021.5.0/bin/mpiifort -c -nofor-main -O2 -fopenmp -fp-model precise -funroll-loops -g -qopenmp-simd -traceback -xHost -wd279      -m64 -I/opt/intel/oneapi/intel_one_api_base_2022/mkl/2022.0.1/include -I/opt/intel/oneapi/intel_one_api_base_2022/mkl/2022.0.1/include/fftw -I'/homenfs/aabdelghani/soft/cp2k/cp2k-2022.2/tools/toolchain/install/libint-v2.6.0-cp2k-lmax-5/include' -I'/homenfs/aabdelghani/soft/cp2k/cp2k-2022.2/tools/toolchain/install/libxc-5.2.3/include' -I'/homenfs/aabdelghani/soft/cp2k/cp2k-2022.2/tools/toolchain/install/libxsmm-1.17/include' -I'/homenfs/aabdelghani/soft/cp2k/cp2k-2022.2/tools/toolchain/install/COSMA-2.5.1/include' -I'/homenfs/aabdelghani/soft/cp2k/cp2k-2022.2/tools/toolchain/install/elpa-2021.11.002/cpu/include/elpa_openmp-2021.11.002/modules' -I'/homenfs/aabdelghani/soft/cp2k/cp2k-2022.2/tools/toolchain/install/elpa-2021.11.002/cpu/include/elpa_openmp-2021.11.002/elpa' -I'/homenfs/aabdelghani/soft/cp2k/cp2k-2022.2/tools/toolchain/install/gsl-2.7/include' -I/homenfs/aabdelghani/soft/cp2k/cp2k-2022.2/tools/toolchain/install/hdf5-1.12.0/include -I/homenfs/aabdelghani/soft/cp2k/cp2k-2022.2/tools/toolchain/install/spglib-1.16.2/include -I'/homenfs/aabdelghani/soft/cp2k/cp2k-2022.2/tools/toolchain/install/SpFFT-1.0.6/include' -I'/homenfs/aabdelghani/soft/cp2k/cp2k-2022.2/tools/toolchain/install/SpLA-1.5.4/include/spla' -I/homenfs/aabdelghani/soft/cp2k/cp2k-2022.2/tools/toolchain/install/sirius-7.3.1/include   -D__LIBXSMM  -D__parallel  -D__MKL -D__FFTW3  -D__SCALAPACK -D__LIBINT -D__LIBXC -D__COSMA -D__ELPA  -D__GSL -D__HDF5 -D__SPGLIB -D__LIBVORI -D__SPFFT    -D__SPLA -D__SIRIUS    -D__COMPILE_ARCH="\"local\"" -D__COMPILE_DATE="\"mar. oct. 18 21:56:56 CET 2022\"" -D__COMPILE_HOST="\"haytham42\"" -D__COMPILE_REVISION="\"git:a95ec40\"" -D__DATA_DIR="\"/homenfs/aabdelghani/soft/cp2k/cp2k-2022.2/data\"" -D__SHORT_FILE__="\"eri_mme/eri_mme_lattice_summation.F\"" -I'/homenfs/aabdelghani/soft/cp2k/cp2k-2022.2/src/eri_mme/' -I'/homenfs/aabdelghani/soft/cp2k/cp2k-2022.2/obj/local/psmp/exts/dbcsr' eri_mme_lattice_summation.F90
ifort: command line warning #10006: ignoring unknown option '-wd279'
make[3]: *** wait : Aucun processus enfant. Arrêt.
make[2]: *** [all] Erreur 2
make[1]: *** [ssmp] Erreur 2
make[1]: *** Attente des tâches non terminées....
make[2]: *** [all] Erreur 2
make[1]: *** [pdbg] Erreur 2
make[2]: *** [all] Erreur 2
make[1]: *** [sdbg] Erreur 2
make[2]: *** [all] Erreur 2
make[1]: *** [psmp] Erreur 2
make: *** [all] Erreur 2

**Comment by mkrack** [comment]
To build CP2K with the

- Intel classic compiler run in the cp2k folder
```
source arch/Linux-intel-x86_64.psmp <intel module name if not yet loaded>
make -j16 ARCH=Linux-intel-x86_64 VERSION=psmp
```
- For the Intel oneapi compiler have a look at [this Docker file](https://github.com/cp2k/cp2k/blob/master/tools/docker/Dockerfile.test_intel-psmp#L27) for the toolchain install command.

Note that the Intel oneapi compiler does not support all CP2K dependencies/features, yet.
