### ISSUE TITLE
incomplete CI toolchain 

### ISSUE THREAD

**Issue by mtaillefumier** [cp2k/cp2k#238]
Hi,

I need to have a couple of tools accessible to be able to build some of SIRIUS dependencies. Would it be possible to have autotools, automake, autogen, libtool, and autoconf included in the CI image or shall I build them myself. Without these tools, any of my pull request will be rejected which would be a pity.

I do not mind building them though but I do think that the CI image should include the most basic tools for compiling which is not the case. I am open to suggestion.

Best

Mathieu

**Comment by oschuett** [comment]
Yes, it probably makes sense to have `autotools` and alike as external dependency. If we start to go down this road then we should probably treat `make` and `cmake` the same way.

The toolchain image is build from this [Dockerfile](https://github.com/cp2k/cp2k/blob/master/tools/toolchain/Dockerfile). Feel free to send in a PR.

**Comment by mtaillefumier** [comment]
Ok I will modify the dockerfile to include these packages. These tools should not be built by hand. They do not affect in any ways the runtime of cp2k whatsoever.

**Comment by oschuett** [comment]
Closed via fb915d00caf535890ffeaf89243b0f3f6474581a.
