### ISSUE TITLE
Slim down the toolchain

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#244]
The aim of the [toolchain](https://github.com/cp2k/cp2k/tree/master/tools/toolchain) is to provide a simple reproducible way of building CP2K's dependencies. Naturally, the toolchain can not replace a full Linux distribution and has to have dependencies of its own. With fb915d00caf535890ffeaf89243b0f3f6474581a we added a few more of such dependencies. Hence, we should revisit if components like `make`, `cmake`, `binutils`, and `lcov` can also become external dependencies.

**Comment by mtaillefumier** [comment]
I think the toolchain should only contain dependencies which cp2k calculations are sensitive of. GCC (binutils to lesser degree) and scientific libraries should be present. 

As for make, binutils, git, sed, cmake, autotools, etc, then they are provided by distributions already and we should rely on that. 

The toolchain has defaults but it is a very practical tool (at least for me). I could built cp2k on openpower just with the toolchain (I built many of the dependencies by hand for simplicity) in a couple of hours, without any specfic teaks to it.  they are probably better tools (spark maybe) but right now it is good enough to build cp2k without too much difficulties.

**Comment by oschuett** [comment]
I moved lcov out of the toolchain via https://github.com/cp2k/cp2k/commit/b436df0f42cf0eef86daf91a6b5e0e7e4484143f. I'll leave valgrind for the time beeing because it's pretty entangled and I have no good way of testing it at the moment.
