### ISSUE TITLE
install_openmpi not tested on Dashboard

### ISSUE THREAD

**Issue by fstein93** [cp2k/cp2k#2464]
As pointed out in #2463, the script install_openmpi.sh is not properly tested on the Dashboard. It would be great if there was an appropriate test at our dashboard as this script is potentially run by users.

**Comment by abussy** [comment]
Actually it looks like it is (https://dashboard.cp2k.org/archive/openmpi-psmp/index.html), and it has been failing for a while. PR #2463 should fix it. I did not scrutinize the Dashboard well enough, my bad!

**Comment by mkrack** [comment]
There is the test [OpenMPI Toolchain (psmp)](https://dashboard.cp2k.org/archive/openmpi-psmp/index.html) in the dashboard, but it seems to fail for another reason currently.

**Comment by fstein93** [comment]
It was [1ed20a1](https://github.com/cp2k/cp2k/commit/1ed20a10a625a7316c33ffd111a2e2b815707aa1) which introduced the curly bracket. Since then, the dashboard test fails because the -D__parallel flag is not defined in favor of an erroneous -D__parallel} . I was also confused because I used the exact same test for my PR #2438 and I am not too familiar with build systems in general. I will close this issue as you PR will fix the dashboard.
