### ISSUE TITLE
nmr fails with CPASSERT failed pw/realspace_grid_types.F:2012

### ISSUE THREAD

**Issue by recohen** [cp2k/cp2k#2485]
This used to run but now always fails. I have restarted from scratch and it happens again. The files needed to quickly reproduce are too large to attach. Here they are in the link:

https://www.dropbox.com/s/myf0ridn5ata9jj/4H.tar.gz?dl=0

Thank you for your attention. Happy New Year!

Ron Cohen

**Comment by recohen** [comment]
I have this same problem with 
Intel(R) Fortran Intel(R) 64 Compiler for applications running on Intel(R) 64, Version 19.1.1.217 Build 20200306
and with
oneapi

I recompiled with -check pointers and it gives an error:
 
forrtl: severe (408): fort: (7): Attempt to use pointer LB_GLOBAL when it is not associated with a target

Image              PC                Routine            Line        Source
cp2k.psmp          000000000D5CF68F  Unknown               Unknown  Unknown
cp2k.psmp          0000000003FFF2DE  realspace_grid_ty         524  realspace_grid_types.F
cp2k.psmp          00000000015CCB5F  qs_linres_current         890  qs_linres_current.F
cp2k.psmp          00000000015C6F18  qs_linres_current         419  qs_linres_current.F
cp2k.psmp          000000000175F9A4  qs_linres_module_         509  qs_linres_module.F
cp2k.psmp          0000000001761001  qs_linres_module_         260  qs_linres_module.F
cp2k.psmp          00000000022E38A8  qs_energy_utils_m         153  qs_energy_utils.F
cp2k.psmp          0000000001BA1565  qs_energy_mp_qs_e         136  qs_energy.F
cp2k.psmp          0000000001941C8A  force_env_methods         259  force_env_methods.F
cp2k.psmp          0000000000ACE61D  integrator_mp_ref        1658  integrator.F
cp2k.psmp          0000000000AAD687  velocity_verlet_c          91  velocity_verlet_control.F
cp2k.psmp          000000000094810B  md_run_mp_qs_mol_         480  md_run.F
cp2k.psmp          0000000000946947  md_run_mp_qs_mol_         149  md_run.F
cp2k.psmp          00000000006EF171  cp2k_runs_mp_cp2k         364  cp2k_runs.F
cp2k.psmp          00000000006EDC2C  cp2k_runs_mp_run_         997  cp2k_runs.F
cp2k.psmp          00000000006EB97A  MAIN__                    379  cp2k.F
cp2k.psmp          00000000006EA722  Unknown               Unknown  Unknown
libc-2.17.so       00002AFBF5CB1555  __libc_start_main     Unknown  Unknown
cp2k.psmp          00000000006EA629  Unknown               Unknown  Unknown

which is at
 SUBROUTINE rs_grid_create(rs, desc)

    ELSE
         ! CASE 2 : general case
         ! extract some more derived quantities about the local grid
         rs%lb_real = desc%lb_global(:, desc%my_virtual_pos)

when I print the refcount it shows:
DESC%refcount           0
at this place when it dies.


Ron

**Comment by fstein93** [comment]
Please excuse the slow answer. Thank you for your report? Can you reproduce this error also with a smaller system or a reduced setup? This might help to pin down the actual culprit. I will have a look at it tomorrow.

**Comment by recohen** [comment]
Yes, actually I just tried TMS and it runs quickly and fails the same way. Attached.

Thank you so much for your help,

Ron

---
Ronald Cohen
Extreme Materials Initiative
Carnegie Institution for Science
5251 Broad Branch Rd., N.W.
Washington, D.C. 20015
***@***.***

**Comment by recohen** [comment]
If I make the following changes the TMS example runs. (Bold just for tracing)
```

diff --git a/src/pw/pw_grids.F b/src/pw/pw_grids.F
index f26e2ee..b6e19f4 100644
--- a/src/pw/pw_grids.F
+++ b/src/pw/pw_grids.F
@@ -2170,7 +2170,7 @@ CONTAINS
 !>      see doc/ReferenceCounting.html
 ! **************************************************************************************************
    SUBROUTINE pw_grid_release(pw_grid)
**-
_+      USE IFCORE_**
       TYPE(pw_grid_type), POINTER              :: pw_grid
 
 #if defined(__OFFLOAD) && !defined(__NO_OFFLOAD_PW)
@@ -2179,6 +2179,7 @@ CONTAINS
 #endif
 
       IF (ASSOCIATED(pw_grid)) THEN
+         **CALL TRACEBACKQQ(STRING="pw_grid_release",USER_EXIT_CODE=-1)**
          CPASSERT(pw_grid%ref_count > 0)
          pw_grid%ref_count = pw_grid%ref_count - 1
          IF (pw_grid%ref_count == 0) THEN
diff --git a/src/pw/realspace_grid_types.F b/src/pw/realspace_grid_types.F
index b301a14..c65f5ea 100644
--- a/src/pw/realspace_grid_types.F
+++ b/src/pw/realspace_grid_types.F
@@ -493,6 +493,8 @@ CONTAINS
 
       CALL timeset(routineN, handle)
 
+      **PRINT *,'DESC%refcount',desc%ref_count**
+      if(desc%ref_count < 1) desc%ref_count=1
       rs%desc => desc
       CALL rs_grid_retain_descriptor(rs%desc)
 
@@ -2023,7 +2025,7 @@ CONTAINS
    SUBROUTINE rs_grid_release(rs_grid)
       TYPE(realspace_grid_type), INTENT(INOUT)           :: rs_grid
 
-      **CALL rs_grid_release_descriptor(rs_grid%desc)
+      ! REC CALL rs_grid_release_descriptor(rs_grid%desc)** THIS IS THE MAIN CHANGE FOR NMR
 
       CALL offload_free_buffer(rs_grid%buffer)
       NULLIFY (rs_grid%r)
@@ -2041,9 +2043,12 @@ CONTAINS
 !>        (c) The Numerical Algorithms Group (NAG) Ltd, 2009 on behalf of the HECToR project
 ! **************************************************************************************************
    SUBROUTINE rs_grid_release_descriptor(rs_desc)
+      USE IFCORE
       TYPE(realspace_grid_desc_type), POINTER            :: rs_desc
 
       IF (ASSOCIATED(rs_desc)) THEN
+         **print *,'in grid_release_descriptor, ref_count=',rs_desc%ref_count
+         CALL TRACEBACKQQ(STRING="rs_grid_release_descriptor",USER_EXIT_CODE=-1)**
          CPASSERT(rs_desc%ref_count > 0)
          rs_desc%ref_count = rs_desc%ref_count - 1
          IF (rs_desc%ref_count == 0) THEN
```
Note I also have to make this change for anything to run!
```
--- a/src/input/input_keyword_types.F
+++ b/src/input/input_keyword_types.F
@@ -201,7 +201,7 @@ CONTAINS
       keyword%location = location
       keyword%removed = .FALSE.
 
-      CPASSERT(LEN_TRIM(name) > 0)
+      !REC CPASSERT(LEN_TRIM(name) > 0)
 
       IF (PRESENT(variants)) THEN
          ALLOCATE (keyword%names(SIZE(variants) + 1))

```

HOWEVER, THIS IS NOT SATISFACTORY AS THE ref_COUNT KEEPS GOING UP AND FINALLY FAILS IN CLOSING WITH
*******************************************************************************
 *   ___                                                                       *
 *  /   \                                                                      *
 * [ABORT]                                                                     *
 *  \___/        mp_world_finalize: assert failed:  leaking communicators      *
 *    |                                                                        *
 *  O/|             

                                                           *
 * /| |                                                                        *
 * / \                                           mpiwrap/message_passing.F:920 *
 *******************************************************************************

Ron
[TMS2.tar.gz](https://github.com/cp2k/cp2k/files/10348285/TMS2.tar.gz)

**Comment by recohen** [comment]
Please see update at github. Thank you! Ron

---
Ronald Cohen
Extreme Materials Initiative
Carnegie Institution for Science
5251 Broad Branch Rd., N.W.
Washington, D.C. 20015
***@***.***

**Comment by fstein93** [comment]
Did you use Intel in all cases?

Your whole update is not portable as it targets the Intel compiler only. But I will check it on GCC.

**Comment by fstein93** [comment]
I can reproduce the issue with GCC locally.

**Comment by fstein93** [comment]
I have meanwhile narrowed it down to #2382 . I am currently bisecting to find the erroneous commit.

**Comment by recohen** [comment]
Thank you. It was not meant as an update but as a test, and it wasn’t correct as I mentioned. Though I get correct results in the TMS test case. But it has a communicator leak.

Ron
.
