### ISSUE TITLE
Toolchain --target-cpu=haswell not propagated to openblas

### ISSUE THREAD

**Issue by bjoe2k4** [cp2k/cp2k#2517]
When installing the toolchain on a skylake system but setting `--target-cpu=haswell`, then openblas still is built with native target incl avx512.

```
./install_cp2k_toolchain.sh --with-openmpi=system --target-cpu=haswell
```
This is because in `toolchain/scripts/stage2/install_openblas.sh` there is no `TARGET` flag in the make call, unless `--target-cpu=generic`. Since `haswell` is given as an example in `./install_cp2k_toolchain.sh --help` it is probably confusing for users.

The obvious fix is to add the `TARGET=HASWELL` variable to the make call. But this requires manual intervention.

**Comment by mkrack** [comment]
@bjoe2k4 Thanks for pointing this out. Unfortunately, the target labels of [OpenBLAS](https://github.com/xianyi/OpenBLAS/blob/develop/TargetList.txt) do not match the `gcc` compiler arch flags very well. The fix #2522 should at least make `--target-cpu=haswell` work as expected.
