### ISSUE TITLE
libxc_add_sections: call to `keyword_create` with empty name

### ISSUE THREAD

**Issue by RemiLacroix-IDRIS** [cp2k/cp2k#2549]
Hi,

I just compiled version 2023.1 with libxc 6.0.0 and I'm getting this error at start up.
```
 ===== Routine Calling Stack =====

            2 libxc_add_sections
            1 create_cp2k_root_section

 *******************************************************************************
 *   ___                                                                       *
 *  /   \                                                                      *
 * [ABORT]                                                                     *
 *  \___/                             CPASSERT failed                          *
 *    |                                                                        *
 *  O/|                                                                        *
 * /| |                                                                        *
 * / \                                         input/input_keyword_types.F:204 *
 *******************************************************************************


 ===== Routine Calling Stack =====

            2 libxc_add_sections
            1 create_cp2k_root_section
```

It's failing on this assert:
https://github.com/cp2k/cp2k/blob/d9e473979eaef93bf16d7abafb9f21845af16eb8/src/input/input_keyword_types.F#L204

As far as I can tell it's happening because CP2K is getting an empty name from libxc:
https://github.com/cp2k/cp2k/blob/d9e473979eaef93bf16d7abafb9f21845af16eb8/src/xc/xc_libxc.F#L270-L279

Any clues on what might be happening?

Rémi

**Comment by fstein93** [comment]
Apparently, you compiled LibXC yourself because the current toolchain has a [patch](https://github.com/cp2k/cp2k/blob/support/v2023.1/tools/toolchain/scripts/stage3/libxc-6.0.0_mgga_xc_b97mv.patch). Alternatively, you may switch to LibXC 6.1.0.

**Comment by RemiLacroix-IDRIS** [comment]
Yeah, I'm updating Spack's recipe for CP2K 2023.1. Sorry I missed that!

**Comment by RemiLacroix-IDRIS** [comment]
I can confirm it works fine with the patch.
