### ISSUE TITLE
Workers in psmp regtests do not run concurently

### ISSUE THREAD

**Issue by abussy** [cp2k/cp2k#2573]
Until this morning, I was using the old regtesting bash script `do_regtest` due to my working branch being behind. I just changed to the new python script `do_regtest.py` and encounter issues when running with the `psmp` version.

Namely, if I run `./do_regtest.py --maxtasks 100 --workbasedir ../../.. local psmp`, it seems that only one test is running at any given time, whereas 25 are expected to do so. It can tell because of the very slow timing and an obviously empty machine when running `htop`.

On the other hand, when I run the `ssmp` version, I observe that 50 tests are run at the same time. Any idea @oschuett ?

**Comment by oschuett** [comment]
Can you share some of the outout? Especially, the `---- Settings ----` section and the `Launched X test directories and Y worker...` line?

Btw, a more convenient way run the tests is via `make VERSION=psmp test`.

**Comment by fstein93** [comment]
I have exactly the same issue and I never run regtests by launching the regtest script but with `make <options> test` instead

**Comment by abussy** [comment]
```
./do_regtest.py --maxtasks 100 --workbasedir ../../.. local psmp
*************************** Testing started ****************************

----------------------------- Settings ---------------------------------
MPI ranks:      2
OpenMP threads: 2
GPU devices:    0
Workers:        25
Timeout [s]:    400
Work base dir:  ../../../TEST-local-psmp-2023-02-10_12-27-48
MPI exec:       ['mpiexec']
Smoke test:     False
Valgrind:       False
Keepalive:      False
Flag slow:      False
Debug:          False
ARCH:           local
VERSION:        psmp
Flags:          omp,libint,fftw3,libxc,parallel,scalapack,cosma,xsmm,spglib,libvori,libbqb,libvdwxc
------------------------------------------------------------------------
Copying test files ... done
Skipping UNIT/nequip_unittest because its requirements are not satisfied.
Skipping TMC/regtest_ana_on_the_fly because its requirements are not satisfied.
Skipping SIRIUS/regtest-1 because its requirements are not satisfied.
Skipping QS/regtest-elpa-2 because its requirements are not satisfied.
Skipping QS/regtest-pexsi because its requirements are not satisfied.
Skipping QS/regtest-elpa-qr because its requirements are not satisfied.
Skipping QS/regtest-elpa because its requirements are not satisfied.
Skipping Fist/regtest-plumed2 because its requirements are not satisfied.
Skipping Fist/regtest-quip because its requirements are not satisfied.
Skipping Fist/regtest-nequip because its requirements are not satisfied.
Launched 331 test directories and 25 worker...

>>> ../../../TEST-local-psmp-2023-02-10_12-27-48/UNIT/memory_utilities_unittest
    memory_utilities_unittest                                                                        -           OK (   2.48 sec)
<<< ../../../TEST-local-psmp-2023-02-10_12-27-48/UNIT/memory_utilities_unittest (1 of 331) done in 2.48 sec
>>> ../../../TEST-local-psmp-2023-02-10_12-27-48/UNIT/parallel_rng_types_unittest
    parallel_rng_types_unittest                                                                      -           OK (   3.80 sec)
<<< ../../../TEST-local-psmp-2023-02-10_12-27-48/UNIT/parallel_rng_types_unittest (2 of 331) done in 3.80 sec
>>> ../../../TEST-local-psmp-2023-02-10_12-27-48/UNIT/grid_unittest
    grid_unittest                                                                                    -           OK (  10.76 sec)
<<< ../../../TEST-local-psmp-2023-02-10_12-27-48/UNIT/grid_unittest (3 of 331) done in 10.76 sec
```

**Comment by alazzaro** [comment]
Since I also use do_regtest.py directly (even if I haven't tried it recently), I would assume `make test` calls it (see https://github.com/cp2k/cp2k/blob/81b98074ff81a90f7db02d243fbffd4159582537/Makefile#L255), so I wonder what is the difference...

**Comment by oschuett** [comment]
> On the other hand, when I run the ssmp version, I observe that 50 tests are run at the same time. 

There might be restrictions on the number of concurrent MPI jobs. This is e.g. the case at CSCS.

If you launch `do_regtest.py` with the `--debug` flag then it will print a message whenever it spawns a subprocess.

**Comment by abussy** [comment]
When adding the `dbug` flag, I indeed see that 25 subprocesses are launched. I can also see a brief peak of activity with `htop`. It seems that the initial 25 instances of CP2K are launched, but not more.

**Comment by oschuett** [comment]
> It seems that the initial 25 instances of CP2K are launched, but not more.

This probably means that 24 of the workers are somehow stuck - probably due to MPI.
You can run with `--keepalive --debug` to get the live output from all workers.

**Comment by abussy** [comment]
Using the `--keepalive` flag to monitor the output, I see that the calculations are taking place, but at an extremely slow rate. Combining this observation with the `htop` command that show a tiny fraction of the machine being used, I would say that all 25 workers are actually sharing the same 4 physical CPUs.

**Comment by alazzaro** [comment]
Is this OpenMPI? Try to avoid affinity then... Something like `--bind-to none` (check mpiexec --help)

**Comment by abussy** [comment]
Thanks! This is indeed OpenMPI. Passing the argument `--mpiexec "mpiexec --bind-to none"` to the `do_regtest.py` script seems to do the trick. The question now is: should this be somehow included as default in the regtest script, such that this does not happen in the future?

**Comment by oschuett** [comment]
Yes, it would be good to change [the default](https://github.com/cp2k/cp2k/blob/685d0dbee4de4cc9de9525d9fb9a5bb641aab1e1/tools/regtesting/do_regtest.py#L51).

Is `--bind-to none` part of the MPI standard, ie. will it work with all MPI implementations?

**Comment by alazzaro** [comment]
No, it is not part of the standard. Moreover, it is not part of OpenMPI default (it only works if you require hwloc). So, in principle, I'm against introducing it in the default... Maybe a mention of a README would be fine...

**Comment by hfp** [comment]
> Yes, it would be good to change [the default](https://github.com/cp2k/cp2k/blob/685d0dbee4de4cc9de9525d9fb9a5bb641aab1e1/tools/regtesting/do_regtest.py#L51).
> 
> Is `--bind-to none` part of the MPI standard, ie. will it work with all MPI implementations?

I don't think so. Real background is that affinity is counterproductive for job-like execution (unrelated tasks). Most MPIs incl. MPICH/2 (Intel MPI) also have something similar. However, MPICH's/Intel's default is not such intrusive pinning or no affinity by default.

**Comment by fstein93** [comment]
I have just checked the [MPI standard](https://www.mpi-forum.org/docs/mpi-4.0/mpi40-report.pdf): The answer is no. But the library developers are allowed to support additional options.

**Comment by hfp** [comment]
In the light of job schedulers, MPI's behavior could also be modified by the environment (pinning applied without user consensus). I think it's best to mention this in the README or issuing a console message prior to running the tests.

**Comment by oschuett** [comment]
> No, it is not part of the standard. Moreover, it is not part of OpenMPI default (it only works if you require hwloc).
> So, in principle, I'm against introducing it in the default... Maybe a mention of a README would be fine...

It seems to me that it's very common to build MPI with hwloc.
So, I still think we should make `--bind-to none` the default for `do_regtest.py`.

If hwloc is missing then there is a clear error message. In the other (more common) case the performance is just mysteriously low.
