### ISSUE TITLE
Automatically trigger CMake CI?

### ISSUE THREAD

**Issue by RMeli** [cp2k/cp2k#2575]
Currently, the CMake CI has to be trigger manually on demand. With two build systems available, there is a risk of divergence between the two (see for example #2574). 

**Should builds in CI be triggered automatically, to prevent such divergences?**

---

*Pros*:
- Avoid divergences

*Cons*:
- Additional burden on developers
- CI usage

**Comment by oschuett** [comment]
> Should builds in CI be triggered automatically, to prevent such divergences?

Yes, it should. I'll take care of it.

**Comment by oschuett** [comment]
An alternative would be to write a script that scans the source tree and generates [src/CMakeLists.txt](https://github.com/cp2k/cp2k/blob/master/src/CMakeLists.txt).


The CI would then ensure that the checked in version is up-to-date.

We already use this approach in [two other places](https://github.com/cp2k/cp2k/blob/master/tools/docker/scripts/test_python.sh#L29-L30).

**Comment by mtaillefumier** [comment]
It should be the developer responsibility to actually add the relevant lines in the CMakeLists.txt as it is easy to get the syntax of the CMakeLists.txt wrong (a missing '>' for instance) and second avoid including files that the dev does not want to be included.
I think `make pretty` sorts the list so the dev does not have to think about this. A script is useful to check if the CMakeLists.txt contains the src/*.F files though but I do not know if a cmake parser exists.
