### ISSUE TITLE
(re-) upload the pre-compiled binaries

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#26]
maybe put them all into one `cp2k-6.1.0-bin.tar.gz`?

**Comment by mkrack** [comment]
Hi Tiziano, I have uploaded the precompiled binaries for v6.1.0

**Comment by dev-zero** [comment]
@mkrack thank you very much! Do you think it would make sense to either compress the binaries (with `xz` and default settings the size is reduced to 1/4 of the original) and/or strip the debug symbols (reduction of ~40%)? Should we also rebuild and upload binaries for older versions?

Since I plan to setup an automated build and upload via Continuous Integration after adding a tag, reducing the number of manual steps required for doing a release: What is the required environment to build them, respectively how do you currently build them? Is the arch-file for those builds in `arch/`?

**Comment by mkrack** [comment]
An automated build and upload of verified CP2K binaries would be great. The svn release process was quite cumbersome and time consuming. The pre-compiled CP2K binaries were generated with the Linux-x86-64-gfortran.s* arch files. I will commit soon updated versions of these arch files.
For an automated build, however, it would be perhaps better to use a toolchain sopt version with static linking.

**Comment by oschuett** [comment]
Sounds like a good match for Docker...
I'm regularly building a [toolchain image](https://github.com/cp2k/cp2k/blob/master/tools/toolchain/Dockerfile) - in case you're interested.

**Comment by mkrack** [comment]
@oschuett thanks for the suggestion. I will have a look at Docker.

**Comment by oschuett** [comment]
Yes, as you know I already run a bunch of Docker-Jobs for every pull request. Hence, it'd be very easy to also run your container on each tag push.

I'll publish the cp2k-ci code within the next few weeks so that others can modify it too.
