### ISSUE TITLE
mpich-3.3 fails to configure

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#261]
There seems to be bug in mpich's configure script. When they call configure in `test/mpi/dtpools` it fails because it can't find `mpicc` (see below). While dtpools seems to be a new feature `--disable-dtpools`  does not help either. Then it simply fails somewhere else in the test suite because it can't find `mpi.h`.

I guess, this problem did not appear in the CI because there mpich was installed a second time. I don't have more time to spend on this. So, maybe someone else could have a look, or we simply rollback to `mpich-3.2.1`.

```
$ grep -B 24  "more details" build/mpich-3.3/test/mpi/dtpools/config.log 

configure:2631: checking whether the C compiler works
configure:2653: mpicc -O2 -ftree-vectorize -g -fno-omit-frame-pointer -march=native   -I/opt/cp2k-toolchain/build/mpich-3.3/src/mpl/include -I/opt/cp2k-toolchain/build/mpich-3.3/src/mpl/include -I/opt/cp2k-toolchain/build/mpich-3.3/src/openpa/src -I/opt/cp2k-toolchain/build/mpich-3.3/src/openpa/src -D_REENTRANT -I/opt/cp2k-toolchain/build/mpich-3.3/src/mpi/romio/include  conftest.c  >&5
./configure: line 2655: mpicc: command not found
configure:2657: $? = 127
configure:2695: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "dtpools"
| #define PACKAGE_TARNAME "dtpools"
| #define PACKAGE_VERSION "0.0"
| #define PACKAGE_STRING "dtpools 0.0"
| #define PACKAGE_BUGREPORT "discuss@mpich.org"
| #define PACKAGE_URL ""
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:2700: error: in `/opt/cp2k-toolchain/build/mpich-3.3/test/mpi/dtpools':
configure:2702: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by mtaillefumier** [comment]
Any reasons to use mpich by default. I do not think this should be blocking anything else, so it might be worth rolling back to the previous version of mpich since it is independent of the toolchain to some extend.

**Comment by mkrack** [comment]
Locally, I cannot reproduce that error, even if no other mpicc is around.

**Comment by oschuett** [comment]
Yes, it must be some weird corner case that only occurs in the rather empty docker environment.
@mkrack, do you have docker available and want to further investigate or should we roll back for the time being?

**Comment by mkrack** [comment]
I have docker on my linux box (openSUSE Leap 15.0) and I will have a look at that problem, but I don't want to block any further progress, i.e. feel free to rollback.

**Comment by mkrack** [comment]
Seems to work now #273
