### ISSUE TITLE
pointer issue in development code

### ISSUE THREAD

**Issue by recohen** [cp2k/cp2k#2617]
I am getting the following error:

 !-----------------------------------------------------------------------------!
forrtl: severe (408): fort: (7): Attempt to use pointer LUMO_PTR when it is not associated with a target

Image              PC                Routine            Line        Source             
cp2k.psmp          000000000D505A8F  Unknown               Unknown  Unknown
cp2k.psmp          0000000000C8EAFC  qs_scf_post_gpw_m         751  qs_scf_post_gpw.F
cp2k.psmp          0000000002B5F438  qs_scf_post_scf_m          78  qs_scf_post_scf.F
cp2k.psmp          000000000240896D  qs_scf_mp_scf_            300  qs_scf.F
cp2k.psmp          0000000001D1DE46  qs_energy_mp_qs_e         111  qs_energy.F
cp2k.psmp          0000000001A4C391  force_env_methods         257  force_env_methods.F
cp2k.psmp          00000000006F0A2F  cp2k_runs_mp_cp2k         396  cp2k_runs.F
cp2k.psmp          00000000006EF2FC  cp2k_runs_mp_run_         996  cp2k_runs.F
cp2k.psmp          00000000006ECE7A  MAIN__                    379  cp2k.F
cp2k.psmp          00000000006EBC22  Unknown               Unknown  Unknown
libc-2.17.so       00002B5934C57555  __libc_start_main     Unknown  Unknown
cp2k.psmp          00000000006EBB29  Unknown               Unknown  Unknown
forrtl: severe (408): fort: (7): Attempt to use pointer LUMO_PTR when it is not associated with a target

**Comment by fstein93** [comment]
I will fix it tomorrow.
