### ISSUE TITLE
Error during CMAKE in GROMACS-CP2K installation

### ISSUE THREAD

**Issue by gayatripanda5** [cp2k/cp2k#2625]
Dear sir, 
I am facing this issue while compiling Gromacs 2023 with Cp2K. 
CMake Error at cmake/gmxManageCP2K.cmake:74 (message):
  pkg-config could not find libcp2k, define CP2K_LINKER_FLAGS for custom
  linking of libcp2k
the cmake command used was
 cmake .. -DGMX_BUILD_OWN_FFTW=ON -DREGRESSIONTEST_DOWNLOAD=ON -DGMX_MPI=on-DGMX_GPU=CUDA -DBUILD_SHARED_LIBS=OFF -DGMXAPI=OFF -DGMX_INSTALL_NBLIB_API=OFF -DGMX_CP2K=ON -DCP2K_DIR=/storage3/gayatrip/cp2k-try2/cp2k/lib/local/psmp

Kindly guide me how I can install it.

**Comment by oschuett** [comment]
Have a look at [this script](https://github.com/cp2k/cp2k/blob/master/tools/docker/scripts/test_gromacs.sh), which we're using for our [daily test](https://dashboard.cp2k.org/archive/gromacs/index.html) of Gromacs-CP2K.

**Comment by mtaillefumier** [comment]
thanks for this report. I was intending to test gromacs-cp2k with cmake but did not have time yet
