### ISSUE TITLE
New do_regtest.py using python3.9

### ISSUE THREAD

**Issue by juerghutter** [cp2k/cp2k#2634]
When running the latest regtest python scripts with python3.9 I get

Copying test files ... done
Traceback (most recent call last):
  File "cp2k/tools/regtesting/do_regtest.py", line 626, in <module>
    loop.run_until_complete(main())
  File "/usr/lib64/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "cp2k/tools/regtesting/do_regtest.py", line 136, in main
    batch.regtests.append(Regtest(line, test_types, batch.workdir))
  File "cp2k/tools/regtesting/do_regtest.py", line 347, in __init__
    self.test_type = test_types[int(parts[1])]
IndexError: list index out of range

I thought the new requirement was python version >= 3.8?

**Comment by oschuett** [comment]
Is this the complete message? I does not seem to contain the actual error.

Generally, I'm trying to keep the `do_regtest.py` as backwards compatible as possible. It should work with Python 3.6 and perhaps even 3.5.

**Comment by juerghutter** [comment]
Sorry, missed the last line (now update).
Here is the same for python 3.6

------------------------------------------------------------------------
Copying test files ... done
Traceback (most recent call last):
  File "./do_regtest.py", line 626, in <module>
    loop.run_until_complete(main())
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "./do_regtest.py", line 136, in main
    batch.regtests.append(Regtest(line, test_types, batch.workdir))
  File "./do_regtest.py", line 347, in __init__
    self.test_type = test_types[int(parts[1])]
IndexError: list index out of range

**Comment by oschuett** [comment]
It fails to parse one of the `TEST_FILES` files.

You can add a print statement [here](https://github.com/cp2k/cp2k/blob/26d600e12bff5522b5f728dc67c33a404743faf9/tools/regtesting/do_regtest.py#L131) to figure out the offending file and one [here](https://github.com/cp2k/cp2k/blob/26d600e12bff5522b5f728dc67c33a404743faf9/tools/regtesting/do_regtest.py#L342) to find the specific line.

**Comment by juerghutter** [comment]
Thank you. I had introduced an error in TEST_FILES and updated the do_regtest.py at the same time.
