### ISSUE TITLE
Increase resolution of cubes

### ISSUE THREAD

**Issue by antoscha** [cp2k/cp2k#264]
Dear developers,

Could you add options to print gaussian cube files having higher resolution? The current maximum (STRIDE 1) is not enough for, say, Bader analysis.

Thanks in advance.

**Comment by mattatlincoln** [comment]
I would be possible - but an easier option is just to rerun the calculation with a higher cutoff. As the wfn is stored in Gaussian AO form, there is no problem reading in the converged density matrix from a calculation with a different cutoff.

Matt

**Comment by antoscha** [comment]
Thank you, it is the answer I needed.
