### ISSUE TITLE
mpirun detected that one or more processes exited with non-zero status,

### ISSUE THREAD

**Issue by gayatripanda5** [cp2k/cp2k#2681]
[QM-cp2k_Sp.inp.txt](https://github.com/cp2k/cp2k/files/10961324/QM-cp2k_Sp.inp.txt)
I am new to CP2K and I am trying to simulate a system containing ~150 QM atoms. I have manipulated the input file used for CIC tutorial and added my system's prmtop and inpcrd file. The box size was taken from the last line of inpcrd file. The input file used is also attached. I was able to run this tutorial https://www.cp2k.org/howto:biochem_qmmm successfully. But I am getting error while running it for my system. The command used was 
**mpirun -np 24 cp2k.popt -i QM-cp2k_Sp.inp > QM-cp2k_Sp.out**
**ERROR
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[41014,1],12]
  Exit code:    2**

**Comment by fstein93** [comment]
I think that your question is better asked to the Google user group. The github repository targets the developers.
I am not familiar with the method but your error message is definitely too unspecific. Could you enclose the output files if there are any?

**Comment by gayatripanda5** [comment]
Thanks for your response. 
[QM-cp2k_Sp.out.txt](https://github.com/cp2k/cp2k/files/10967064/QM-cp2k_Sp.out.txt)
I was not sure where to post this query so I thought this could probably be the right place to at least get an idea about the error. The output files are attached.

**Comment by alazzaro** [comment]
"CP2K version 6.1", really? I don't think we can help you, the version is too old. You can ask in teh google forum, as suggested above: https://groups.google.com/g/cp2k?hl=it

**Comment by gayatripanda5** [comment]
Thanks.

**Comment by fstein93** [comment]
Apparently, this issue is resolved.
