### ISSUE TITLE
Status for CP2K dashboard entry "AiiDA-CP2K Plugin" is unstable

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#2699]
The dashboard status for the [AiiDA-CP2K Plugin tester](https://dashboard.cp2k.org/archive/aiida/index.html) toggles between `Something is wrong` and `works fine` for the same `aiida-cp2k commit 3807418`. Maybe, that is a caching issue of the dashboard test?

**Comment by oschuett** [comment]
My guess would be that one of the tests is taking too long and occasionally hits the timeout:
```
WARNING  aiida.orm.nodes.process.calculation.calcjob.CalcJobNode:calcjob.py:676 output parser returned exit code<303>: The output file was incomplete.
```

@yakutovicha, what do you think?

**Comment by yakutovicha** [comment]
> My guess would be that one of the tests is taking too long and occasionally hits the timeout:
> 
> ```
> WARNING  aiida.orm.nodes.process.calculation.calcjob.CalcJobNode:calcjob.py:676 output parser returned exit code<303>: The output file was incomplete.
> ```
> 
> @yakutovicha, what do you think?

I think it might very well be the case since the error says that the file is incomplete. I will have a look once the Marvel review is over. A bit packed with preparation for it.

~I assigned myself.~ Please assign me to this issue, I don't have the right to do that.

**Comment by oschuett** [comment]
Gentle ping :-)

**Comment by oschuett** [comment]
I've opened https://github.com/aiidateam/aiida-cp2k/pull/183.

**Comment by yakutovicha** [comment]
Sorry, I got hooked up with other pressing issues. There were just too many recently 🙈
