### ISSUE TITLE
Cray regression testers are failing

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#2735]
The CRAY regression tester are failing because of the build issues related to [COSTA](https://github.com/eth-cscs/COSTA/issues/16) and [COSMA](https://github.com/eth-cscs/COSMA/issues/131).

**Comment by mtaillefumier** [comment]
We fixed these issues in the latest master. We will soon release a new version of COSTA and COSMA then I can update the toolchain.

**Comment by mtaillefumier** [comment]
we never picked this up with the toolchain. Surprizing.

**Comment by mkrack** [comment]
The problem appears with the toolchain only if an installation using CRAY_LIBSCI is requested.

**Comment by mtaillefumier** [comment]
should be fixed with this PR #2738

**Comment by mkrack** [comment]
@mtaillefumier Thanks for the fix.

**Comment by mtaillefumier** [comment]
no problem.
