### ISSUE TITLE
Compilation on AMD EPYC

### ISSUE THREAD

**Issue by lmiroslaw** [cp2k/cp2k#274]
Could you provide the compilation guidance for AMD EPYC?

I have tried to use standard flags with Intel Compiler ver. 2018.
https://xconfigure.readthedocs.io/en/latest/cp2k/#build-the-intel-fork-of-cp2k

After the compilation with Intel Compiler series 18 using Intel tool chain, I get an error: 

`[azure@ip-0A000104 cp2k]$ ./exe/Linux-x86-64-intelx/cp2k.sopt
Please verify that both the operating system and the processor support Intel(R) X87, CMOV, MMX, FXSAVE, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, MOVBE, POPCNT, F16C, AVX, FMA, BMI, LZCNT, AVX2, AVX512DQ, AVX512F, ADX, AVX512CD, AVX512BW, AVX512VL and CLWB instructions.`

**Comment by dev-zero** [comment]
Please note that `xconfigure` is a separate project and you should report problems with their documentation on their bugtracker: https://github.com/hfp/xconfigure/issues

We successfully build and deploy CP2K using [our toolchain scripts](https://github.com/cp2k/cp2k/blob/master/INSTALL.md#2-install-prerequisites) or via [Spack](https://spack.io/) on AMD EPYC machines (using `gfortran`).

**Comment by hfp** [comment]
Just for reference, the issue is covered here: https://github.com/hfp/xconfigure/issues/12
