### ISSUE TITLE
COSTA breaks cross-compilation

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#2748]
See COSTA issue [#19](https://github.com/eth-cscs/COSTA/issues/19).

**Comment by mkrack** [comment]
@mtaillefumier Could you have a look at this issue?

**Comment by mtaillefumier** [comment]
@mkrack: It should be fixed now with https://github.com/cp2k/cp2k/pull/2781.

**Comment by mkrack** [comment]
Confirmed, the build of generic cp2k binaries works again. 
Thanks for the fix @mtaillefumier

**Comment by mtaillefumier** [comment]
I need to fix yet another small issue in the cp2k cmake build system. I thought I had it fixed already but it is not.
