### ISSUE TITLE
cp2k output not printing but the job is running

### ISSUE THREAD

**Issue by GerardPareras** [cp2k/cp2k#276]
Dear developers,

I'm contacting you because I'm facing a problem with the program and I'm not able to find any solution for it.

I'm trying to run some B3LYP calculations with CP2K. However I noticed that while the job is running it is not writing anything on the output. 
 
Please see examples below:
Example 1:
 
rw-r--r-- 1 gpareras sm18   3232 Mar 20 20:49 TMEDAC2H4CO2.inp
-rw-r--r-- 1 gpareras sm18 142632 Mar 20 20:49 TMEDAC2H4CO2-GSpace-SplInterp-
-rw-r--r-- 1 gpareras sm18 115876 Mar 20 22:19 TMEDAC2H4CO2-RESTART.wfn
-rw-r--r-- 1 gpareras sm18 796828 Mar 20 22:19 TMEDAC2H4CO2.out
-rw-r--r-- 1 gpareras sm18   1354 Mar 20 22:49 slurm-12494799.out
 
It started to run at 20:49, stopped writing at 22:19 and the calculation finished at 22:49 due to time limit.
 
Example 2: 
 
-rw-r--r-- 1 gpareras sm18   3485 Mar 21 13:04 TMEDAC2H4CO2.inp
-rw-r--r-- 1 gpareras sm18     37 Mar 21 13:04 slurm-12505393.out
-rw-r--r-- 1 gpareras sm18  15848 Mar 21 13:04 TMEDAC2H4CO2-GSpace-SplInterp-
-rw-r--r-- 1 gpareras sm18 115876 Mar 21 13:07 TMEDAC2H4CO2-RESTART.wfn
-rw-r--r-- 1 gpareras sm18  98350 Mar 21 13:07 TMEDAC2H4CO2.out
 
It started to run at 13:04, the last update on the output file was at 13:07 and at 13:35 was still running without writing anything.
 
It finished at 15:04 but the last updated was at 14:33 and it finished at 15:04 due to time limit.
 
-rw-r--r-- 1 gpareras sm18   3485 Mar 21 13:04 TMEDAC2H4CO2.inp
-rw-r--r-- 1 gpareras sm18  15848 Mar 21 13:04 TMEDAC2H4CO2-GSpace-SplInterp-1.ddapcLog
-rw-r--r-- 1 gpareras sm18 115876 Mar 21 14:33 TMEDAC2H4CO2-RESTART.wfn
-rw-r--r-- 1 gpareras sm18 110167 Mar 21 14:33 TMEDAC2H4CO2.out
-rw-r--r-- 1 gpareras sm18   1354 Mar 21 15:04 slurm-12505393.out
 
I'm wondering if this is normal or there is an error on the input, I've never seen that before, usually the output file is getting updated all the time while the job is running.

I've been in contact with my super computer provider and they couldn't find any explanation for this either.

Please find attached below a folder with: input, output and submission script. 

Any help would be really appreciated.

Thank you.

Best regards,
Gerard
[Test.tar.gz](https://github.com/cp2k/cp2k/files/3019461/Test.tar.gz)

**Comment by alazzaro** [comment]
I'm not sure if this issue is still relevant. As a general rule, the github issues are only for the developers, while users requests should be put in the CP2K google forum (https://groups.google.com/forum/#!forum/cp2k ) Please provide there how you are compiling CP2K (arch files, libraries, compilers, MPI version)... As far as I know, there are problems with OpenMPI that can hang at some point... I can suggest using the TRACE keyword to see the last CP2K call (https://manual.cp2k.org/trunk/CP2K_INPUT/GLOBAL.html#TRACE )
