### ISSUE TITLE
Invalid unit number in optimize_embedding_potential

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#28]
At line 2726 of file /gpfs/data/krack/rt/auto/pdbg/cp2k/src/optimize_embedding_potential.F
Fortran runtime error: Unit number is negative and unit was not already opened with OPEN(NEWUNIT=...)

Error termination. Backtrace:
#0  0x3443869 in data_transfer_init
	at /opt/tmp/stadler_h/src/gcc-7.3.0/libgfortran/io/transfer.c:2686
#1  0x9f241e in print_folded_coordinates
	at /gpfs/data/krack/rt/auto/pdbg/cp2k/src/optimize_embedding_potential.F:2726

**Comment by mkrack** [comment]
See report of the regtester Linux-x86-64-gfortran.pdbg in the CP2k dashboard:
[https://www.cp2k.org/static/regtest/trunk/Linux-x86-64-gfortran-regtest/pdbg/regtest-0](https://www.cp2k.org/static/regtest/trunk/Linux-x86-64-gfortran-regtest/pdbg/regtest-0)

**Comment by mkrack** [comment]
I think it needs just an if clause for non-zero unit number

**Comment by rybkinjr** [comment]
Thanks, done.
