### ISSUE TITLE
ECP for replicating results from Gaussian 

### ISSUE THREAD

**Issue by Poonam-p1** [cp2k/cp2k#2826]
Hello all, 

I am working on replicating a few calculations that were done in Gaussian using LANL2DZ for heavy elements and 6-31G* for lighter elements. I found the reference of LANL2DZ formulation for Zn from the https://www.basissetexchange.org/basis/lanl2dz/format/cp2k/?version=0&elements=30) but the simulation crashes from  CP2K version 7.1 to 2023.1 with the error same as - https://github.com/cp2k/cp2k/blob/186428f4e848f883d21da2d2b78d036968ebedff/src/aobasis/ai_overlap_ppl.F#L404 

I came across some mentions of ECPs integrated into CP2K around the docs; however, this mostly is support around data input with no real validation/examples done.
https://github.com/cp2k/cp2k/commit/6f4f0dc4126dacb3ac626ca5cbde39e8e741a89d
https://github.com/cp2k/cp2k/pull/2315 → here, it specifically says that you need to adjust things.

Me, not really being an expert in Fortran or the CP2K-codebase, if someone could help with understanding what exactly is `nexp_ppl` in textbook-terms, I would be very grateful. Additionally, if there can be a way to resolve the error - 
 "CPASSERT failed aobasis/ai_overlap_ppl.F:404"; any guidance would be highly appreciated. 

P.S. I am attaching the example input and log files for more clarity. 

Thanks a lot for your time!

[minex.log.txt](https://github.com/cp2k/cp2k/files/11757268/minex.log.txt)
[minex.txt](https://github.com/cp2k/cp2k/files/11757286/minex.txt)

**Comment by juerghutter** [comment]
Hi

the ECP code in CP2K trys to transform internally to a fully separable form and fitting to a Gaussian expansion.
This code was never very stable and production ready. As there are now open source libraries for the
ECP integrals available, we will abandon this approach.

regards
JH

________________________________________
From: Poonam-p1 ***@***.***>
Sent: Thursday, June 15, 2023 2:14 PM
To: cp2k/cp2k
Cc: Subscribed
Subject: [cp2k/cp2k] ECP for replicating results from Gaussian  (Issue #2826)

Hello all,

I am working on replicating a few calculations that were done in Gaussian using LANL2DZ for heavy elements and 6-31G* for lighter elements. I found the reference of LANL2DZ formulation for Zn from the https://www.basissetexchange.org/basis/lanl2dz/format/cp2k/?version=0&elements=30) but the simulation crashes from CP2K version 7.1 to 2023.1 with the error same as - https://github.com/cp2k/cp2k/blob/186428f4e848f883d21da2d2b78d036968ebedff/src/aobasis/ai_overlap_ppl.F#L404

I came across some mentions of ECPs integrated into CP2K around the docs; however, this mostly is support around data input with no real validation/examples done.
6f4f0dc<https://github.com/cp2k/cp2k/commit/6f4f0dc4126dacb3ac626ca5cbde39e8e741a89d>
#2315<https://github.com/cp2k/cp2k/pull/2315> → here, it specifically says that you need to adjust things.

Me, not really being an expert in Fortran or the CP2K-codebase, if someone could help with understanding what exactly is nexp_ppl in textbook-terms, I would be very grateful. Additionally, if there can be a way to resolve the error -
"CPASSERT failed aobasis/ai_overlap_ppl.F:404"; any guidance would be highly appreciated.

P.S. I am attaching the example input and log files for more clarity.

Thanks a lot for your time!

minex.log.txt<https://github.com/cp2k/cp2k/files/11757268/minex.log.txt>
minex.txt<https://github.com/cp2k/cp2k/files/11757286/minex.txt>

―

**Comment by abussy** [comment]
ECPs are available as of #3147 (without gradients for now). Make sure you recompile the development version of CP2K with the `libgrpp` library.
