### ISSUE TITLE
issue when install cp2k/7.1 and 9.1

### ISSUE THREAD

**Issue by veritas496** [cp2k/cp2k#2828]
when i used toolchain to install cp2k 7.1 or 9.1 version, i used this command
```
  ./install_cp2k_toolchain.sh \--with-openmpi=install \--math-mode=mkl \--with-scalapack=no
```
But i met this issue

```
==================== Installing OpenMPI ====================
openmpi-4.1.1.tar.gz: OK
Checksum of openmpi-4.1.1.tar.gz Ok
Installing from scratch into /jet/home/yguan1/cp2k-9.1.0/tools/toolchain/install/openmpi-4.1.1
ERROR: (./scripts/stage1/install_openmpi.sh, line 61) Non-zero exit code detected.
```
Thanks for your time and help
Best

**Comment by mkrack** [comment]
I suggest to try the latest CP2K release 2023.1, because several issues related to the toolchain build have been fixed in the meantime. Moreover, I do not recommend to combine OpenMPI and MKL. Either use OpenMPI with OpenBLAS or Intel/MKL, i.e. a setup purely based on Intel.
