### ISSUE TITLE
unknown subsection LIBXC of section XC_FUNCTIONAL 

### ISSUE THREAD

**Issue by ZengZezhu** [cp2k/cp2k#2851]
Hi,

I am trying to run the scf calculations in cp2k with optB88-vdw functional, and this is my input file:

    &XC
      &XC_FUNCTIONAL
        &LIBXC
          FUNCTIONAL XC_GGA_X_OPTB88_VDW
        &END LIBXC
        &VWN
        &END VMN
      &END XC_FUNCTIONAL
      &VDW_POTENTIAL
        POTENTIAL_TYPE NON_LOCAL
         &NON_LOCAL
           TYPE DRSLL
           KERNEL_FILE_NAME vdW_kernel_table.dat
         &END NON_LOCAL
      &END VDW_POTENTIAL
    &END XC

However, I encountered a error: 
" unknown subsection LIBXC of section XC_FUNCTIONAL"

I think the LIBXC has already compiled successfully, so I have no idea about this issue. Could you give me some advices? Thanks!

Cheers,
zezhu

**Comment by hfp** [comment]
Can you share the version of CP2K (source code or revision release version)?  Is this report about CP2K master revision?

**Comment by ZengZezhu** [comment]
The version is cp2k/2022.1 in our cluster.

**Comment by ZengZezhu** [comment]
<img width="1473" alt="image" src="https://github.com/cp2k/cp2k/assets/46587891/069e801c-1261-4840-8e8d-bcad3b0f5a03">

**Comment by juerghutter** [comment]
Hi please use the correct definitions of these functionals provided at

cp2k/data/xc_section

regards
JH

________________________________________

**Comment by ZengZezhu** [comment]
Thank you Professor, I am not familiar with CP2K and I will learn it now!

**Comment by ZengZezhu** [comment]
Thanks Prof, It is working now. 

Cheers,
zezhu

**Comment by rongjiawen2025-cell** [comment]
您好，请问能告诉我最后是怎么解决的吗？非常感谢
