### ISSUE TITLE
Cannot find libint during installing cp2k v2023.1

### ISSUE THREAD

**Issue by PolyuWeldingSpock** [cp2k/cp2k#2856]
Dear all,

I have installed libint on my workstation and I can find libint with command 
`whereis libint`
`libint:/usr/local/libint`
However, when I installed cp2k with toolchain option --with-libint=system, it showed 
`==================== Finding LIBINT from system paths ====================
ERROR: (./scripts/stage3/install_libint.sh) ld cannot find -lint2, please check if libint is installed or in system search path
ERROR: (./scripts/stage3/install_libint.sh, line 101) Non-zero exit code detected.
`
Can anyone help me how to solve this problem? Thank you!

**Comment by jobs-git** [comment]
set --with-libint=/path

**Comment by fstein93** [comment]
Apparently, this issue was solved. Feel free to reopen it if necessary.
