### ISSUE TITLE
Issues about the diagonal values of stress tensor by CP2K

### ISSUE THREAD

**Issue by tamaswells** [cp2k/cp2k#2879]
I tried to use cp2k to calculate stress tensor of liquid water.  The test configuration was selected from the DeePMD library (https://www.aissquare.com/datasets/detail?pageType=datasets&name=H2O-Phase-Diagram) 
I found that the diagonal values of  stress tensor calculated by CP2K differ from those calculated by VASP, while the off-diagonal values are similar. It seems that there is a overall offset for  the diagonal values of  stress tensor. 
In both cases, the SCAN functional were used.  I used TZV2PX-MOLOPT-GTH and GTH-SCAN-POTENTIAL in CP2K.
<img width="474" alt="1" src="https://github.com/cp2k/cp2k/assets/30830824/739e755e-e0a6-48bc-8ac9-b35dd8a81cef">
Input and ouput files: 
[cp2k.zip](https://github.com/cp2k/cp2k/files/12190373/cp2k.zip)

**Comment by gabriele16** [comment]
It might be because you are using smoothing of the density, which should be avoided when computing the stress, see also a recent post in the [CP2K google group](https://groups.google.com/g/cp2k/c/GLZ7xO7U4mc/m/Ryk88ufgCAAJ).

**Comment by tamaswells** [comment]
Thanks for your reply. I remove the smearing parameters and increase the cutoff to 1200 Ry
The diagonal values changes a lot but still away from the values by VASP.
Are there any other factors that may influence the results?
[in.zip](https://github.com/cp2k/cp2k/files/12206754/in.zip)


<img width="964" alt="1" src="https://github.com/cp2k/cp2k/assets/30830824/be76cdc7-fb73-4bbb-b4dd-6bb6e3054edf">

**Comment by gabriele16** [comment]
Without smoothing enabled the stress looks correct and, from my own tests, it is well converged wtr PW cutoff. A potential issue might be in the basis sets, see below. Besides the `TZV2PX-MOLOPT-GTH` basis set that you used, one can try the ones specifically optimized for SCAN, such as `TZV2P-MOLOPT-SCAN-GTH`, in the file `BASIS_MOLOPT_UZH`.  I have tried the following to see if there are some possible sources of errors or convergence issues: 

- I ran using `STRESS_TENSOR NUMERICAL` as well to check for possible differences with analytical, but there are none (differences are of about 1E-5 GPa), showing that the analytical expression for the stress for SCAN is correct.
- Differences between `TZVP-MOLOPT-SCAN-GTH` and `TZV2P-MOLOPT-SCAN-GTH` basis sets are also small, around 0.06-0.07 GPa. The values for  `TZV2P-MOLOPT-SCAN-GTH` and with a 1500 Ry PW cutoff are 
```
 STRESS|                        x                   y                   z
 STRESS|      x        5.89041399790E-01   1.31495525351E-01  -2.31010452877E-01
 STRESS|      y        1.31495525351E-01   5.14055946675E-01   2.32709932825E-01
 STRESS|      z       -2.31010452877E-01   2.32709932825E-01   9.63590281071E-01
 STRESS| 1/3 Trace                                             6.88895875845E-01
 STRESS| Determinant                                           2.01643949166E-01
```
- Increasing the PW cutoff from 1500 to 2000 Ry produces changes of the order of 1E-4 GPa, so a cutoff 1000 -1200 Ry might also be enough.
- Using  `TZV2P-MOLOPT-SCAN-GTH` and a PW cutoff of 1500 Ry, I have run 50 steps of MD to look roughly at the average and the standard deviation to see if the values observed are within the range of the fluctuations:
```
stress x +- 1 std [GPa]: -0.15051 +- 0.553935
stress y +- 1 std [GPa]: -0.106065 +-0.726428
stress z +- 1 std [GPa]: 0.109895 +- 0.68089
```
The data for the md run is here: [MD_water_stress.tar.gz](https://github.com/cp2k/cp2k/files/12239533/MD_water_stress.tar.gz)

- However, differences between the  `TZV2P-MOLOPT-SCAN-GTH`  and the  `TZV2PX-MOLOPT-GTH`  basis set that you are using are a bit larger, about 0.4 -0.5 GPa. I am not entirely sure but the `TZV2PX-MOLOPT-GTH` result should be more accurate.

**Comment by tamaswells** [comment]
Thanks for your testing. It there any possiblities that the stress tensor output by CP2K is principally different from the VASP, for example, the diagonal elements are subtracted by a constant？

**Comment by gabriele16** [comment]
Since the stress tensor computed from the analytical expression and with finite differences are the same, no, I wouldn't think so. The VASP values also seem within the standard deviation obtained from the (short) MD. To investigate further, besides possibly running on a simpler system and/or using a GGA functional (e.g. silicon and PBE?), one could also check all the terms contributing to the stress by running with debug flags on, with `STRESS_TENSOR ANALYTICAL`, `RUN_TYPE DEBUG` and something like the debug section below, ideally for multiple configurations.

```
&DEBUG
DEBUG_FORCES .FALSE.
DEBUG_STRESS_TENSOR .TRUE.
DEBUG_DIPOLE .FALSE.
DEBUG_POLARIZABILITY .FALSE.
DE 0.001
STOP_ON_MISMATCH .FALSE.
EPS_NO_ERROR_CHECK 5.e-5
&END
```

**Comment by tamaswells** [comment]
I rerun the case with debug mode, and also perform a case for Si using the PBE functional. The results are similar to vasp.
![image](https://github.com/cp2k/cp2k/assets/30830824/a6690354-77d7-41ab-b449-5255ddd7b13d)
[debug&Si.zip](https://github.com/cp2k/cp2k/files/12265900/debug.Si.zip)

**Comment by fstein93** [comment]
Apparently, this issue was solved. Feel free to reopen it if necessary.
