### ISSUE TITLE
Error: 'get_handle' at (1) is not an inquiry reference to an intrinsic type component 'mp_group'

### ISSUE THREAD

**Issue by yurivict** [cp2k/cp2k#2881]
Build breaks:
```
gfortran12 -c -O2 -fopenmp -funroll-loops -ftree-vectorize -ffree-form -D__FFTW3 -D__NO_STATM_ACCESS -I/usr/local/include -D__COMPILE_ARCH="\"FreeBSD-gfortran\"" -D__COMPILE_DATE="\"Sat Jul 29 01:05:58 PDT 2023\"" -D__COMPILE_HOST="\"yv.noip.me\"" -D__COMPILE_REVISION="\"git:65cca6c\"" -D__DATA_DIR="\"/usr/local/share/cp2k\"" -D__SHORT_FILE__="\"qs_active_space_types.F\"" -I'/usr/ports/science/cp2k/work/cp2k-2023.2/src/' -I'/usr/ports/science/cp2k/work/cp2k-2023.2/obj/FreeBSD-gfortran/ssmp/exts/dbcsr' qs_active_space_types.F90 
/usr/ports/science/cp2k/work/cp2k-2023.2/tools/build_utils/fypp -n /usr/ports/science/cp2k/work/cp2k-2023.2/src/motion/thermostat/thermostat_types.F thermostat_types.F90
/usr/ports/science/cp2k/work/cp2k-2023.2/src/qs_active_space_types.F:338:58:

  338 |          CALL mp_group%set_handle(eri%mp_group%get_handle())
      |                                                          1
Error: 'get_handle' at (1) is not an inquiry reference to an intrinsic type component 'mp_group'
gmake[5]: *** [/usr/ports/science/cp2k/work/cp2k-2023.2/Makefile:514: qs_active_space_types.o] Error 1
gmake[5]: *** Waiting for unfinished jobs....
```

Version: 2023.2
gfortran-12
FreeBSD 13.2

**Comment by fstein93** [comment]
Interestingly, we do not find that issue on our dashboard where we are also testing gfortran-12. I see that your compilation flags do not include `-std=f2008` whereas we explicitly add it in our tests. Could you add it to the `FCFLAGS` variable in your arch files and recompile?

**Comment by fstein93** [comment]
Apart from that, I have an idea how to fix it. I will prepare a fix soon.

**Comment by fstein93** [comment]
I cannot reproduce this issue with Gfortran 11 and 13. Have you tried it with `-std=f2008` added to your compilation flags?

**Comment by fstein93** [comment]
I have found it. Apparently, you do not have an up-to-date DBCSR submodule. Can you run
`git config submodule.recurse true`
`git pull`
`git submodule update`
`make -j ARCH=... realclean`
`make -j ARCH=...`

**Comment by fstein93** [comment]
The problem seems to be solved now. Feel free to reopen this thread if necessary.
