### ISSUE TITLE
How to suppress Mulliken and Hirshfeld output when PRINT_LEVEL MEDIUM

### ISSUE THREAD

**Issue by PolyuWeldingSpock** [cp2k/cp2k#2892]
I am using CP2K for AIMD simulations. When PRINT_LEVEL is set to MEDIUM in the input file, Mulliken and Hirshfeld charge are calculated after each SCF convergence. Is there a keyword that can be used to suppress these two calculations and their output when PRINT_LEVEL set to MEDIUM?

**Comment by mkrack** [comment]
You can disable both properties explicitly via their `&PRINT` sections
```
&FORCE_EVAL
 ...
 &DFT
  ...
  &PRINT
   ...
   &HIRSHFELD off
   &END HIRSHFELD
   &MULLIKEN off
   &END MULLIKEN
  &END PRINT
 &END DFT
&END FORCE_EVAL
```
Note, that such questions should be asked in the [CP2K forum](https://www.cp2k.org/howto:forum).
