### ISSUE TITLE
Wrong gradients of densities in g-space

### ISSUE THREAD

**Issue by fstein93** [cp2k/cp2k#2911]
While studying the code, I have found this comment by @edditler 
https://github.com/cp2k/cp2k/blob/edd4516f21e906c8b61ea482e109fdec03b276f6/src/qs_dcdr_ao.F#L578

**Comment by edditler** [comment]
From what I remember, `calculate_drho_elec` has an output parameter `drho_g`, but it appears that it is never used. Comparing a numerical derivative of the electron density with `drho_r`, I found that the real-space quantity was fine and could simply be transferred to the reciprocal grid.

I think, that I decided that the error must be in `density_rs2pw_basic`, but I never got around to investigate it in more detail. FWIW, this routine does a bunch of `pw_transfer` as well.

**Comment by fstein93** [comment]
I think I found the culprit. In principal, `density_rs2pw_basic` does the same as `density_rs2pw` but does not consider the case of spherical grids. As it turns out, only the contribution of the very first grid in r-space is considered in drho in g-space then (see [here](https://github.com/cp2k/cp2k/blob/d1376dc4969b25e1013bb42635e3ab0fe8739442/src/pw_env/rs_pw_interface.F#L208)). I will prepare a PR to fix it.
