### ISSUE TITLE
Feature Request: Hybrid Functional (HSE06, PBE0, etc.) with k-points.

### ISSUE THREAD

**Issue by flwang1998** [cp2k/cp2k#2913]
Dear developers,
Is there any news about Hybrid Functional (HSE06, PBE0, etc.) with k-points in QS module?

**Comment by flwang1998** [comment]
Dear developers,  
Is there any news about Hybrid Functional (HSE06, PBE0, etc.) with k-points in QS module?

**Comment by abussy** [comment]
Hi,
it's currently in development, it should come online within the next couple of months.
Cheers

**Comment by flwang1998** [comment]
Exciting with cp2k to make atoms dance!
Cheers
