### ISSUE TITLE
VDW_Potential Case sensitivity for Type

### ISSUE THREAD

**Issue by cpashartis** [cp2k/cp2k#2941]
Hello,

It seems that there is a case sensitivity bug for the reference potential for the vdw potential you choose in &PAIR_POTENTIAL.

In particular, I'm using version 2023.1 of CP2K and if you choose REFERENCE_FUNCTIONAL PBE**Sol**, it cannot find the appropriate parameters where as REFERENCE_FUNCTIONAL PBE**sol** works.

**Comment by mkrack** [comment]
Thanks for reporting. The issue should be fixed now in the current CP2K development version.
