### ISSUE TITLE
Bug: Errors into the the toolchain for cp2k version 9.1

### ISSUE THREAD

**Issue by ithilbor** [cp2k/cp2k#2968]
Hi everyone , I've been working with cp2k in order to compile the version 9.1 and I think I've fond some bugs into the toolchain. Before describing all the bugs that've run into I give you some of the specs of my machine and all the software that has been used in order to run the toolchain.

## Hw specifics

CPU: Intel(R) Xeon(R) Silver 4210 CPU @ 2.20GHz
Core(s): 20
Socket(s): 2
Core(s) per socket: 10
Thread(s) per core:  1 (Hyperthreading is disabled)
GPU: 4 x Nvidia Tesla V100-sxm2-16gb

## Sw specifics

OS: Rocky Linux release 8.8 (Green Obsidian)
GCC Compiler: gcc-8.5.0 --> OS package
CMAKE: cmake-3.20.2 --> OS package
OpenMPI: ompi-4.1.4 --> Compiled with: gcc-8.5.0 + cuda-12.0.0 + hwloc-2.9.0 + pmix-4.2.2 + gdrcopy-2.3.1 + ucx-1.14.1 + ucc-1.2.0
FFTW: fftw-3.3.10 --> Compiled with: gcc-8.5.0 (single precision)
Plumed: plumed-2.9.0 --> Compiled with: gcc-8.5.0 + ompi-4.1.4 (The verison above) + libtorch2.0.1noabi
CUDA: cuda-12.0.0
Nvidia driver version: 525.60.13

## Command to build the Toolchain

```bash
./install_cp2k_toolchain.sh -j 20 --no-check-certificate --mpi-mode=openmpi --math-mode=openblas --gpu-ver=V100 --libint-lmax=5 --enable-cuda=yes --enable-hip=no --with-gcc=system --with-cmake=system --with-openmpi=system --with-libxc=install --with-fftw=system --with-openblas=install --with-libint=install --with-libxsmm=install --with-elpa=install --with-pexsi=install --with-ptscotch=install --with-superlu=install --with-quip=install --with-plumed=system --with-cosma=install | tee install-cp2k-9.1.0-out.txt
```

## Bugs

1. Building Superlu: If I launch the command like this without say anything about CFLAGS or other vars I get an error while compiling Superlu, the complete error log is pretty long so I will resume it like this:

```bash
undefined reference to `MPI::Comm::Comm()'
...
Other undefined references
...
collect2: error: ld returned 1 exit status
make: *** [Makefile:326: amr3d] Error 1
```

(Let me know if you need the complete log)

The error goes away if I use these variables:

```bash
export OMPI_CC=gcc
export OMPI_CXX=g++ 
export OMPI_FC=gfortran
export CC=mpicc
export CXX=mpic++
export FC=mpif90
```

I don't know why the toolchain fails to pass these definitions in order to compile correctly.

2. Stage 7 - Build spglib

The build fails immediately because it tries to download the spglib from the wrong git url, the change I've made is in the script "cp2k/tools/toolchain/scripts/stage7/install_spglib.sh" line 37, in particular I've done this substitution:

```bash
# From this:
https://github.com/atztogo/spglib/archive/v${spglib_ver}.tar.gz \

# To this:
https://github.com/spglib/spglib/archive/refs/tags/v${spglib_ver}.tar.gz \
```

3. Stage 8 - Build spfft & sirius

Even if in the file toolchain.env I see that these variable are correctly setted (except for FFTW_ROOT):

```bash
declare -x FFTW3_INCLUDES="-I'/fftw-3.3.10/include'"
declare -x FFTW3_LIBS="IF_MPI(-lfftw3_mpi|) -lfftw3 -lfftw3_omp"
declare -x FFTW_CFLAGS="-I'/fftw-3.3.10/include'"
declare -x FFTW_LDFLAGS="-L'/fftw-3.3.10/lib' -Wl,-rpath='/fftw-3.3.10/lib'"
declare -x FFTW_LIBS="IF_MPI(-lfftw3_mpi|) -lfftw3 -lfftw3_omp"
declare -x FFTW_ROOT=""
```

I had to set in both the installation script for both the build (cpu and cuda) the cmake variables:

```bash
-DFFTW_LIBRARIES=/fftw-3.3.10/lib \
-DFFTW_INCLUDE_DIRS=/fftw-3.3.10/include \
```

In order to make the builds work correctly.

## Extra:

How can I also tell to the installer to install cp2k in a custom path and not in the same directory? Like the `--prefix=/my/custom/path` for the cmake (I've tried using the variable `CURRENT_DIR` but it didn't work)

**Comment by fstein93** [comment]
Thank you for your bug report. The CP2K version you attempt to compile, is an old one. Is there a specific reason for you to stick to version 9.1? If not, I recommend to try the latest release 2023.2 which fixes several bugs, has improved performance and a few more features.

**Comment by ithilbor** [comment]
Hi @fstein93 I saw the new version and I will compile this one too probably, but the reason why I'm still using this old one is because the customer has specifically requested this version on the cluster so I had to compile this version.

**Comment by hfp** [comment]
> Hi @fstein93 I saw the new version and I will compile this one too probably, but the reason why I'm still using this old one is because the customer has specifically requested this version on the cluster so I had to compile this version.

This is a clear sign to confirm with the customer v9.1 is really required. CP2K developer team would also like to learn about why this is the case. Fixing such an old release shall be justified (because of the effort fixing bug back in time, etc). Btw, if it's related to a commercial inquiry and stated by some document on your desk, it's still no reason not to ask. It's a clear sign of disconnection.

**Comment by ithilbor** [comment]
Ok, I will for sure discover why this version is really needed by this customer and I will let you know the reason. Till now all I know is that the customer requested us this specific version because he was working with that version on the previous cluster so I suppose It's because he wanted to finish his research on this version, but I will let you now the details soon. 

PS: Btw I will be happy to help to fix the bugs if It will be needed and helpful.

**Comment by ithilbor** [comment]
Ok the customer told me that the only reason why he was using this version was to finish the project started on the other cluster on the new cluster by using the same version of cp2k but as he will finish this project he will pass to the newer version  of cp2k so being that I've already build the version 9.1 I suppose that we can close this topic or if you want to fix in order to have the version without bugs let me know it, I will be happy to help.

Thanks again!

**Comment by hfp** [comment]
One cause of version-to-version incompatibility for scientific/sophisticated/any work or input is about evolved keywords or meaning of keywords carried forward. First of all, this is rather rare but still possible ("sophisticated input"). If a customer notices an error messages with input from previous versions (using a new version of CP2K), it is wise to seek help from community and experts; please see https://groups.google.com/g/cp2k.

**Comment by ithilbor** [comment]
Thanks a lot @hfp for the link, I will suggest at my customer to look at this group if he notice something wrong with his inputs in the new version of cp2k.

**Comment by fstein93** [comment]
It seems, the issue is solved. For the given (old) bugs, @IronCub3 provided some simple fixes. If there are any further questions, feel free to reopen it.
