### ISSUE TITLE
FINDLOC not available in GCC 8

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#2971]
The Fortran 2008 function `FINDLOC`is only implemented in GCC 9 and later. It is now used in [qs_active_space_utils.F](https://github.com/cp2k/cp2k/blob/master/src/qs_active_space_utils.F#L127-L128). Either the GCC 8 regression test has to be dropped or `FINDLOC` has to be replaced by an equivalent piece of code (function).

**Comment by fstein93** [comment]
I will prepare a workaround for GCC8.
