### ISSUE TITLE
Possible warning message for double calling a XC functional

### ISSUE THREAD

**Issue by BelizSertcan** [cp2k/cp2k#2978]
I recently made the mistake of calling the PBE0 functional in the following way:

      &XC_FUNCTIONAL **PBE**
         &GGA_C_PBE
         &END GGA_C_PBE
         &GGA_X_PBE
            SCALE 0.75
         &END GGA_X_PBE
      &END XC_FUNCTIONAL

This certainly gave wrong results and it was not trivial to spot the error in the input. I was thinking some warning can be printed if a keyword and a section are used together. I wanted to do this but I am not sure if the warning should be printed when parsing the input or right before the calculation of the functional starts.

**Comment by fstein93** [comment]
I think it makes sense to test the presence of other functional sections while [expanding the keyword](https://github.com/cp2k/cp2k/blob/113f45f1e20ca7051e33753af9624929131b7698/src/input_cp2k_check.F#L145C15-L145C36). In general, crashes or warnings should be emitted as early as possible.
