### ISSUE TITLE
CP2K gromacs on cuda installation error

### ISSUE THREAD

**Issue by avinashkarkada** [cp2k/cp2k#3009]
Hello all,

I was trying to install gromacs with cp2k on an nvidia GPU. I installed the psmp version of “local_cuda” cp2k. The cmake command I used for gromacs is:
`cmake ..  -DBUILD_SHARED_LIBS=OFF -DGMXAPI=OFF -DGMX_INSTALL_NBLIB_API=OFF -DGMX_GPU=CUDA -DGMX_CP2K=ON -DCP2K_DIR=/home/aka/Documents/cp2k-2023.2/lib/local_cuda/psmp -DCMAKE_PREFIX_PATH='/home/aka/Documents/cp2k-2023.2/tools/toolchain/install/openblas-0.3.23;/home/aka/Documents/cp2k-2023.2/tools/toolchain/install/scalapack-2.2.1' -DGMX_MPI=ON -DCMAKE_INSTALL_PREFIX=/usr/local/gromacs-cp2k-gpu/ -DCMAKE_C_COMPILER=/usr/bin/gcc-10 -DCMAKE_CXX_COMPILER=/usr/bin/g++-10 -DGMX_EXTERNAL_BLAS=ON -DGMX_EXTERNAL_LAPACK=ON -DGPU_DEPLOYMENT_KIT_ROOT_DIR=/usr/share/cmake-3.16/Modules/FindCUDA/run_nvcc.cmake -DCP2K_LINKER_FLAGS="-Wl,--enable-new-dtags -L'/home/aka/Documents/cp2k-2023.2/tools/toolchain/install/openmpi-4.1.5/lib' -Wl,-rpath,'/home/aka/Doc

After running “make” I get the error that there is an undefined reference to mpi_*f08 such as in the [make_error.log](https://github.com/cp2k/cp2k/files/12740368/make_error.log) file

GROMACS version:2023.2
GROMACS modification: No
CP2K version: 2023.2

Thank you

**Comment by oschuett** [comment]
Try removing the `-DCP2K_LINKER_FLAGS`. For our daily test we use [this](https://github.com/cp2k/cp2k/blob/04dd4284328246f8f7259e2ea433868052050a67/tools/docker/scripts/test_gromacs.sh#L30). The [pkg-config](https://github.com/cp2k/cp2k/blob/04dd4284328246f8f7259e2ea433868052050a67/Makefile#L179) should take care of all the rest.

**Comment by avinashkarkada** [comment]
Thank you for your suggestion. I removed the -DCP2K_LINKER_FLAGS argument. I still have the following error:
[make_error-2.log](https://github.com/cp2k/cp2k/files/12741150/make_error-2.log)

**Comment by oschuett** [comment]
It seems you are building against the Fortran 2008 API of MPI. Try removing `-D__MPI_F08` from your arch files.

**Comment by avinashkarkada** [comment]
No luck :(
I still got the same error

**Comment by avinashkarkada** [comment]
Hey,
the issue got resolved after using -DMPI_C_COMPILER to specify mpicc. However, gpu utilization is zero with occasional spike in its usage. Would this be an issue with the installation of cp2k or gromacs?
Also, using mpirun crashes the system completely.

**Comment by oschuett** [comment]
Glad you solved it! In CP2K only [some operations](https://www.cp2k.org/gpu) are GPU accelerated.
