### ISSUE TITLE
compile errors

### ISSUE THREAD

**Issue by fengbit** [cp2k/cp2k#301]
Dear developers,
When I tried compile the cp2k, there encountered some errors:

..............
/home/room/cp2k/src/wannier90.F:842:57:

          bweight(1:num_shells) = MATMUL(TRANSPOSE(vmat), MATMUL(smat, MATMUL(TRANSPOSE(umat), TARGET)))
                                                         1
ERROR: Code for reallocating the allocatable array at (1) will be added [-Werror=realloc-lhs]
................

/home/room/cp2k/src/molsym.F:1679:36:

       sym%center_of_mass(:) = MATMUL(coord(:, 1:natoms), sym%aw(1:natoms))/SUM(sym%aw(1:natoms))
                                    1
ERROR: Code for reallocating the allocatable array at (1) will be added [-Werror=realloc-lhs]
.............

Please give me some suggests,Thanks.

**Comment by dev-zero** [comment]
Most likely you can simply remove the `-Werror=realloc-lhs` flag in your arch file, but unless you add more information on which version of CP2K you're trying to build, the arch file, compiler vendor and version being used, there is not much we can do.

Furthermore, this does not look like an actual bug in the code but rather a problem with building the software. As such you're kindly referred to use our [User Forum](https://www.cp2k.org/howto:forum).

**Comment by fengbit** [comment]
Thank you for your suggest.
I'm trying to compile cp2k v6.1 ,  VERSION="sopt ssmp" ,  gcc 8.3.0  
And, I will try to use the User Forum if I can sign in to Google

**Comment by dev-zero** [comment]
Can you attach the arch file you're using?

**Comment by fengbit** [comment]
Yes. I use the local.ssmp
CC          = gcc
CXX         = g++
CPP         =
AR          = ar -r
FC          = gfortran
LD          = gfortran
#
DFLAGS      = -D__LIBXSMM   -D__FFTW3  -D__LIBINT -D__LIBINT_MAX_AM=6 -D__LIBDERIV_MAX_AM1=5 -D__LIBXC   
#
WFLAGS      = -Werror=aliasing -Werror=ampersand -Werror=c-binding-type -Werror=intrinsic-shadow -Werror=intrinsics-std -Werror=line-truncation -Werror=tabs -Werror=target-lifetime -Werror=underflow -Werror=unused-but-set-variable -Werror=unused-variable -Werror=unused-dummy-argument -Werror=conversion -Werror=zerotrip -Wno-maybe-uninitialized -Wuse-without-only 
#
FCDEBFLAGS  = -ffree-form -std=f2003 -fimplicit-none 
CFLAGS      = -march=native -fno-omit-frame-pointer -g  -O3 -funroll-loops -ffast-math $(PROFOPT) -fopenmp   -I'/home/room/cp2k/tools/toolchain/install/openblas-0.2.20/include' -I'/home/room/cp2k/tools/toolchain/install/fftw-3.3.7/include' -I'/home/room/cp2k/tools/toolchain/install/libint-1.1.6/include' -I'/home/room/cp2k/tools/toolchain/install/libxc-4.0.3/include' -I'/home/room/cp2k/tools/toolchain/install/libxsmm-1.9.0/include' $(DFLAGS)
FCFLAGS     = -march=native -fno-omit-frame-pointer -g  -O3 -funroll-loops -ffast-math $(PROFOPT) -fopenmp   -I'/home/room/cp2k/tools/toolchain/install/openblas-0.2.20/include' -I'/home/room/cp2k/tools/toolchain/install/fftw-3.3.7/include' -I'/home/room/cp2k/tools/toolchain/install/libint-1.1.6/include' -I'/home/room/cp2k/tools/toolchain/install/libxc-4.0.3/include' -I'/home/room/cp2k/tools/toolchain/install/libxsmm-1.9.0/include' $(FCDEBFLAGS) $(WFLAGS) $(DFLAGS)
#
LDFLAGS     = $(FCFLAGS) -Wl,--enable-new-dtags   -L'/home/room/cp2k/tools/toolchain/install/openblas-0.2.20/lib' -Wl,-rpath='/home/room/cp2k/tools/toolchain/install/openblas-0.2.20/lib' -L'/home/room/cp2k/tools/toolchain/install/fftw-3.3.7/lib' -Wl,-rpath='/home/room/cp2k/tools/toolchain/install/fftw-3.3.7/lib' -L'/home/room/cp2k/tools/toolchain/install/libint-1.1.6/lib' -Wl,-rpath='/home/room/cp2k/tools/toolchain/install/libint-1.1.6/lib' -L'/home/room/cp2k/tools/toolchain/install/libxc-4.0.3/lib' -Wl,-rpath='/home/room/cp2k/tools/toolchain/install/libxc-4.0.3/lib' -L'/home/room/cp2k/tools/toolchain/install/libxsmm-1.9.0/lib' -Wl,-rpath='/home/room/cp2k/tools/toolchain/install/libxsmm-1.9.0/lib' 
LIBS        =  -lxsmmf -lxsmm -ldl -lpthread -lxcf03 -lxc -lderiv -lint -lfftw3 -lfftw3_omp    -lopenblas_omp -lstdc++

and local.sopt
CC          = gcc
CXX         = g++
CPP         =
AR          = ar -r
FC          = gfortran
LD          = gfortran
#
DFLAGS      = -D__LIBXSMM   -D__FFTW3  -D__LIBINT -D__LIBINT_MAX_AM=6 -D__LIBDERIV_MAX_AM1=5 -D__LIBXC   
#
WFLAGS      = -Werror=aliasing -Werror=ampersand -Werror=c-binding-type -Werror=intrinsic-shadow -Werror=intrinsics-std -Werror=line-truncation -Werror=tabs -Werror=target-lifetime -Werror=underflow -Werror=unused-but-set-variable -Werror=unused-variable -Werror=unused-dummy-argument -Werror=conversion -Werror=zerotrip -Wno-maybe-uninitialized -Wuse-without-only 
#
FCDEBFLAGS  = -ffree-form -std=f2003 -fimplicit-none 
CFLAGS      = -march=native -fno-omit-frame-pointer -g  -O3 -funroll-loops -ffast-math $(PROFOPT)    -I'/home/room/cp2k/tools/toolchain/install/openblas-0.2.20/include' -I'/home/room/cp2k/tools/toolchain/install/fftw-3.3.7/include' -I'/home/room/cp2k/tools/toolchain/install/libint-1.1.6/include' -I'/home/room/cp2k/tools/toolchain/install/libxc-4.0.3/include' -I'/home/room/cp2k/tools/toolchain/install/libxsmm-1.9.0/include' $(DFLAGS)
FCFLAGS     = -march=native -fno-omit-frame-pointer -g  -O3 -funroll-loops -ffast-math $(PROFOPT)    -I'/home/room/cp2k/tools/toolchain/install/openblas-0.2.20/include' -I'/home/room/cp2k/tools/toolchain/install/fftw-3.3.7/include' -I'/home/room/cp2k/tools/toolchain/install/libint-1.1.6/include' -I'/home/room/cp2k/tools/toolchain/install/libxc-4.0.3/include' -I'/home/room/cp2k/tools/toolchain/install/libxsmm-1.9.0/include' $(FCDEBFLAGS) $(WFLAGS) $(DFLAGS)
#
LDFLAGS     = $(FCFLAGS) -Wl,--enable-new-dtags   -L'/home/room/cp2k/tools/toolchain/install/openblas-0.2.20/lib' -Wl,-rpath='/home/room/cp2k/tools/toolchain/install/openblas-0.2.20/lib' -L'/home/room/cp2k/tools/toolchain/install/fftw-3.3.7/lib' -Wl,-rpath='/home/room/cp2k/tools/toolchain/install/fftw-3.3.7/lib' -L'/home/room/cp2k/tools/toolchain/install/libint-1.1.6/lib' -Wl,-rpath='/home/room/cp2k/tools/toolchain/install/libint-1.1.6/lib' -L'/home/room/cp2k/tools/toolchain/install/libxc-4.0.3/lib' -Wl,-rpath='/home/room/cp2k/tools/toolchain/install/libxc-4.0.3/lib' -L'/home/room/cp2k/tools/toolchain/install/libxsmm-1.9.0/lib' -Wl,-rpath='/home/room/cp2k/tools/toolchain/install/libxsmm-1.9.0/lib' 
LIBS        =  -lxsmmf -lxsmm -ldl -lpthread -lxcf03 -lxc -lderiv -lint -lfftw3     -lopenblas -lstdc++

Thank you for your help. The compiling seems to be finished when I remove the -Werror=realloc-lhs and -Werror=uninitialized flags. And the following regtesting showed the test results: 
--------------------------------- Summary --------------------------------
Number of FAILED  tests 17
Number of WRONG   tests 9
Number of CORRECT tests 2967
Number of NEW     tests 14
Total number of   tests 3007
GREPME 17 9 2967 14 3007 X
--------------------------------------------------------------------------
Regtest took 481.00 seconds.
-----------------------------
Is that mean a bug has been introduced, how can I check and fix it ? 

best regards,
Feng

**Comment by roastduck** [comment]
Maybe you should patch with commit f34a5e414d68cff20ee8ff6e09f57f9fbe6a063f. It mentioned GCC 8, and removed `-Werror=realloc-lhs`. But `-Werror=uninitialized` was kept, so this commit didn't solve all the problems.

**Comment by hawkaye** [comment]
I ran into the very same problem. Thanks for pointing out the commit that fixes the "realloc-lhs" problem. The very next commit (5e5e14d6930fc3996d0c4c7135a92e5de57ef453) fixes the "uninitialized" problem.

With those two /slightly modified) commits CP2K compiles fine for me but still fails a few of the regression tests. Especially `vib-int-mixed.inp` takes ages (minutes when other tests finish in seconds) and in the end is killed.

BTW: I beg to differ about the compilation errors being a bug. If code does not compile on a standard-compliant compiler, either it, its build system, or the compiler is buggy ;-)

**Comment by dev-zero** [comment]
ok, after looking into this again I'd say this was fixed in latest `master`: `-Werror=realloc-lhs` is not enabled for the sopt,popt,ssmp,psmp versions anymore, hence a user should not encounter them.

@fengbit: the error report means that some tests gave wrong numbers while others failed to run completely. Most likely those things are already fixed in latest master. If you can still reproduce it there please open a new bug and also paste the list of tests reported with `RUNTIME FAIL` or `WRONG RESULT TEST`
