### ISSUE TITLE
H2O linear-scaling post-HF benchmarks; use existing HFX calculation

### ISSUE THREAD

**Issue by svandenhaute** [cp2k/cp2k#3017]
From what I understand, these examples start the post-HF calculation from a set of PBE orbitals. They proceed on a fairly large number of GPU nodes, yet they begin with a very expensive HF SCF which makes no use of the GPUs and is enormously slow when executed using 1 rank / GPU.
Wouldn't it be more efficient to use the PBE orbitals for a HF SCF (performed with 1-4 cores per rank, on CPU-only nodes), and use the converged HF orbitals as input for the RI-MP2 part, on GPU nodes? This would avoid the GPU idling during calculation of HFX...

(I'm testing on LUMI-G, with the provided Easybuild installation.)

**Comment by svandenhaute** [comment]
On 64 LUMI-G nodes (4x MI250X, 8 effective GPUs, 64 cores, 512 GB RAM) with 8 ranks per node, I get the following timings for the HF SCF.

```
 Number of electrons:                                                        256
 Number of occupied orbitals:                                                128
 Number of molecular orbitals:                                               128

 Number of orbital functions:                                               3648
 Number of independent orbital functions:                                   3648

 Extrapolation method: initial_guess


 SCF WAVEFUNCTION OPTIMIZATION

  ----------------------------------- OT ---------------------------------------
  Minimizer      : DIIS                : direct inversion
                                         in the iterative subspace
                                         using   7 DIIS vectors
                                         safer DIIS on
  Preconditioner : FULL_SINGLE_INVERSE : inversion of
                                         H + eS - 2*(Sc)(c^T*H*c+const)(Sc)^T
  Precond_solver : DEFAULT
  stepsize       :    0.08000000                  energy_gap     :    0.08000000
  eps_taylor     :   0.10000E-15                  max_taylor     :             4
  ----------------------------------- OT ---------------------------------------

  Step     Update method      Time    Convergence         Total energy    Change
  ------------------------------------------------------------------------------

  HFX_MEM_INFO| Est. max. program size before HFX [MiB]:                     845
  HFX_MEM_INFO| Number of cart. primitive ERI's calculated:       17375968139863
  HFX_MEM_INFO| Number of sph. ERI's calculated:                  13050829340679
  HFX_MEM_INFO| Number of sph. ERI's stored in-core:                611779728818
  HFX_MEM_INFO| Number of sph. ERI's stored on disk:                           0
  HFX_MEM_INFO| Number of sph. ERI's calculated on the fly:       12439049611861
  HFX_MEM_INFO| Total memory consumption ERI's RAM [MiB]:                 756912
  HFX_MEM_INFO| Whereof max-vals [MiB]:                                       30
  HFX_MEM_INFO| Total compression factor ERI's RAM:                         6.17
  HFX_MEM_INFO| Total memory consumption ERI's disk [MiB]:                     0
  HFX_MEM_INFO| Total compression factor ERI's disk:                        0.00
  HFX_MEM_INFO| Size of density/Fock matrix [MiB]:                           102
  HFX_MEM_INFO| Size of buffers [MiB]:                                         3
  HFX_MEM_INFO| Number of periodic image cells considered:                    33
  HFX_MEM_INFO| Est. max. program size after HFX  [MiB]:                    7328

     1 OT DIIS     0.80E-01 1155.2     0.00209796      -541.2350089494 -5.41E+02
     2 OT DIIS     0.80E-01 1062.5     0.00155964      -541.3781652118 -1.43E-01
     3 OT DIIS     0.80E-01 1063.1     0.00032084      -541.5583420040 -1.80E-01
```

**Comment by alazzaro** [comment]
Few questions:

- which CP2K version is this? Is this using COSMA?
- do you have the full log so that we can see the timers? Be aware that not all DBCSR kernels are provided for the Mi250 GPUs, so we can check what it is missing and you can run the autotuning (described in the [DBCSR section](https://cp2k.github.io/dbcsr/develop/page/3-developer-guide/3-programming/2-accelerator-backend/2-libsmm_acc/3-tune.html))...

**Comment by svandenhaute** [comment]
Thanks for the quick reply.
This is 2023.1, as installed using the following easybuild:
```
# contributed by Luca Marsella (CSCS)
# modified for LUMI-G by Peter Larsson
easyblock = 'MakeCp'

name = 'CP2K'
version = '2023.1'
versionsuffix = '-GPU'

homepage = 'http://www.cp2k.org/'

whatis = [
    'Description: CP2K is a program to perform atomistic and molecular simulations of solid state, liquid, molecular and biological systems.'
]

description = """
CP2K is a freely available (GPL) program, written in Fortran 95, to
perform atomistic and molecular simulations of solid state, liquid,
molecular and biological systems. It provides a general framework for
different methods such as e.g. density functional theory (DFT) using a
mixed Gaussian and plane waves approach (GPW), and classical pair and
many-body potentials.
"""

toolchain = {'name': 'cpeGNU', 'version': '22.08'}
toolchainopts = {'openmp': True, 'usempi': True}

source_urls = ['https://github.com/%(namelower)s/%(namelower)s/releases/download/v%(version)s']
sources = [SOURCELOWER_TAR_BZ2]
patches = [
    ('LUMIG-20231.psmp', '%(builddir)s/%(namelower)s-%(version)s/arch')
]

builddependencies = [('buildtools', '%(toolchain_version)s', '', True)]

dependencies = [
    ('ELPA', '2022.11.001.rc1','-CPU'),
    ('Libint-CP2K', '2.6.0'),
    ('libvori', '220621'),
    ('libxc', '6.1.0'),
    ('libxsmm', '1.17'),
    ('spglib', '1.16.3'),
    ('cray-fftw', EXTERNAL_MODULE),
    ('cray-hdf5', EXTERNAL_MODULE),
    ('COSMA','2.6.2'),
    ('SPLA','1.5.4','-GPU'),
    ('SpFFT','1.0.6','-GPU'),
    ('GSL','2.7.1','-OpenMP')
]

# build type
prebuildopts = 'module load craype-accel-amd-gfx90a && module load rocm/5.3.3 && '
buildopts = "ARCH=LUMIG-20231 VERSION=psmp"

files_to_copy = [
    (['./arch/LUMIG-20231.psmp'], 'arch'),
    (['./exe/LUMIG-20231/*'], 'bin'),
    (['./data'], '.'),
    (['./tests'], '.'),
    (['./tools'], '.')
]

sanity_check_paths = {
    'files': ['arch/LUMIG-20231.psmp', 'bin/%(namelower)s.psmp'],
    'dirs': ['data', 'tests'],
}

parallel = 16

# set custom CP2K_DATA_DIR
modextravars = {'CP2K_DATA_DIR': '%(installdir)s/data'}

moduleclass = 'chem'
```
Would it be possible to share the install script that was used to run the calculations in the 2023 J. Chem. Phys paper on the GPU implementation of the low-scaling post-HF methods?

I don't have the full log because I had to cancel the calculation. It would have consumed a very large amount of GPU time (with 0% GPU utilization, as checked by logging into one of the nodes during the calculation) ... I do have the jobscript: 
```
#!/bin/bash

#SBATCH -p standard-g
#SBATCH --account=project_*
#SBATCH --time=12:00:00
#SBATCH --gres=gpu:8
#SBATCH --nodes=16
#SBATCH --exclusive
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=6
#SBATCH -e error.txt
#SBATCH -o output.txt

export OMP_PLACES=cores
export OMP_PROC_BIND=close
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}

ulimit -s unlimited
export OMP_STACKSIZE=512M

export MPICH_OFI_NIC_POLICY=GPU
export MPICH_GPU_SUPPORT_ENABLED=1

module load LUMI/22.08
module load partition/G
module load CP2K/2023.1-cpeGNU-22.08-GPU
module load rocm/5.3.3

cat << EOF > select_gpu
#!/bin/bash

export ROCR_VISIBLE_DEVICES=\$SLURM_LOCALID
exec \$*
EOF
chmod +x ./select_gpu

curl -O https://raw.githubusercontent.com/cp2k/cp2k/master/data/POTENTIAL
curl -O https://raw.githubusercontent.com/cp2k/cp2k/master/data/BASIS_ccGRB_UZH
curl -O https://raw.githubusercontent.com/cp2k/cp2k/master/data/BASIS_RI_cc-TZ
curl -O https://raw.githubusercontent.com/cp2k/cp2k/master/data/BASIS_ADMM_UZH
curl -O https://raw.githubusercontent.com/cp2k/cp2k/master/data/t_c_g.dat

srun --cpu-bind=mask_cpu:7e000000000000,7e00000000000000,7e0000,7e000000,7e,7e00,7e00000000,7e0000000000 ./select_gpu cp2k.psmp -i mp2-qz.inp
```
This is mostly taken from the LUMI docs [here](https://lumi-supercomputer.github.io/LUMI-EasyBuild-docs/c/CP2K/)

**Comment by alazzaro** [comment]
I cannot see anything wrong here... Still, we don't know where it is actually spending time...

Could you try to run by setting 

```
DBCSR_MM_DENSE=1
```
?
Alternatively you can use https://manual.cp2k.org/trunk/CP2K_INPUT/GLOBAL.html#CP2K_INPUT.GLOBAL.WALLTIME to stop CP2K and get the timers output.

**Comment by svandenhaute** [comment]
Setting that env variable doesn't change anything. I'm trying to use the WALLTIME keyword to gracefully stop CP2K after some time but it just keeps on running ... This is the input file (which I believe is not using COSMA)


[mp2-qz.txt](https://github.com/cp2k/cp2k/files/12796891/mp2-qz.txt)

**Comment by alazzaro** [comment]
I'm not a real expert in CP2K, so cannot check your input file...
Can you post the start of the CP2K log? (where we can see the configuration).
From what I can see COSMA was compiled with GPU support, but I don't think it is used here... 
You can try to run with https://manual.cp2k.org/trunk/CP2K_INPUT/GLOBAL.html#CP2K_INPUT.GLOBAL.TRACE so we know which functions is calling...

**Comment by svandenhaute** [comment]
```
 DBCSR| CPU Multiplication driver                                           XSMM (U)
 DBCSR| Multrec recursion limit                                              512 (U)
 DBCSR| Multiplication stack size                                          30000 (D)
 DBCSR| Maximum elements for images                                    UNLIMITED (U)
 DBCSR| Multiplicative factor virtual images                                   1 (U)
 DBCSR| Use multiplication densification                                       F (D)
 DBCSR| Multiplication size stacks                                             3 (U)
 DBCSR| Use memory pool for CPU allocation                                     F (U)
 DBCSR| Number of 3D layers                                               SINGLE (U)
 DBCSR| Use MPI memory allocation                                              F (U)
 DBCSR| Use RMA algorithm                                                      F (U)
 DBCSR| Use Communication thread                                               T (U)
 DBCSR| Communication thread load                                             68 (D)
 DBCSR| MPI: My process id                                                     0
 DBCSR| MPI: Number of processes                                             128
 DBCSR| OMP: Current number of threads                                         6
 DBCSR| OMP: Max number of threads                                             6
 DBCSR| ACC: Number of devices/node                                            1
 DBCSR| ACC: Number of stack-buffers per thread                                8 (U)
 DBCSR| ACC: Avoid driver after busy                                           F (U)
 DBCSR| ACC: Process inhomogeneous stacks                                      T (U)
 DBCSR| ACC: Min. flop for processing                                          0 (U)
 DBCSR| ACC: Min. flop for sorting                                          4000 (U)
 DBCSR| ACC: Number of binning bins                                         4096 (U)
 DBCSR| ACC: Size of binning bins                                             16 (U)
 DBCSR| Split modifier for TAS multiplication algorithm                  1.0E+00 (U)


  **** **** ******  **  PROGRAM STARTED AT               2023-10-03 21:57:54.511
 ***** ** ***  *** **   PROGRAM STARTED ON                             nid005775
 **    ****   ******    PROGRAM STARTED BY                              vandenha
 ***** **    ** ** **   PROGRAM PROCESS ID                                 83709
  **** **  *******  **  PROGRAM STARTED IN /pfs/lustrep4/scratch/project_4650003
                                           15/svandenhaute/extreme/scaling/lumig
                                           /64

 CP2K| version string:                                       CP2K version 2023.1
 CP2K| source code revision number:                                  git:b888bd8
 CP2K| cp2kflags: omp libint fftw3 libxc elpa parallel scalapack cosma xsmm dbcs
 CP2K|            r_acc spglib libvori libbqb offload_hip spla_gemm_offloading
 CP2K| is freely available from                            https://www.cp2k.org/
 CP2K| Program compiled at                      Fri 29 Sep 2023 11:12:38 AM EEST
 CP2K| Program compiled on                                                 uan02
 CP2K| Program compiled for                                          LUMIG-20231
 CP2K| Data directory path    /project/project_465000315/EasyBuild_Massimo/SW/LU
 CP2K| Input file name                                                mp2-qz.inp

 GLOBAL| Force Environment number                                              1
 GLOBAL| Basis set file name                                      BASIS_RI_cc-TZ
 GLOBAL| Potential file name                                           POTENTIAL
 GLOBAL| MM Potential file name                                     MM_POTENTIAL
 GLOBAL| Coordinate file name                                       ./H2O-64.xyz
 GLOBAL| Method name                                                        CP2K
 GLOBAL| Project name                                          H2O-64-SOS-MP2-TZ
 GLOBAL| Run type                                                   ENERGY_FORCE
 GLOBAL| FFT library                                                       FFTW3
 GLOBAL| Diagonalization library                                       ScaLAPACK
 GLOBAL| DGEMM library                                                      SPLA
 GLOBAL| Orthonormality check for eigenvectors                          DISABLED
 GLOBAL| Matrix multiplication library                                     COSMA
 GLOBAL| All-to-all communication in single precision                          F
 GLOBAL| FFTs using library dependent lengths                                  F
 GLOBAL| Grid backend                                                       AUTO
 GLOBAL| Global print level                                               MEDIUM
 GLOBAL| MPI I/O enabled                                                       T
 GLOBAL| Total number of message passing processes                           128
 GLOBAL| Number of threads for this process                                    6
 GLOBAL| This output is from process                                           0
 GLOBAL| Stack size for threads created by OpenMP (OMP_STACKSIZE)           512M
 GLOBAL| CPU model name                          AMD EPYC 7A53 64-Core Processor
 GLOBAL| CPUID                                                              1002

 MEMORY| system memory details [Kb]
 MEMORY|                        rank 0           min           max       average
 MEMORY| MemTotal            527647364     527636196     527647364     527636926
 MEMORY| MemFree             501468600     497698588     501468600     498704446
 MEMORY| Buffers                     0             0             0             0
 MEMORY| Cached                2255344       2255344       6186796       5424772
 MEMORY| Slab                  4551456       4551456       4714196       4624580
 MEMORY| SReclaimable           109196        109196        119536        115950
 MEMORY| MemLikelyFree       503833140     503797936     504573520     504245169
```
Though this was from a slightly different run

**Comment by alazzaro** [comment]
well, this is without the DBCSR variable, I assume:

```
DBCSR| Use multiplication densification                                       F (D)
```
It should report `T (E)`...

**Comment by svandenhaute** [comment]
Right, so the Easybuild install is essentially useless.
Any idea which install scripts were used by the developers on LUMI? I believe LUMI was used during GPU acceleration development ...

**Comment by alazzaro** [comment]
What do you mean by useless? Are you saying that setting `DBCSR_MM_DENSE=1` (check the configure output) you don't get any improvement in performance? That has nothing to do with Easybuild though...

I'm one of the persons who ported CP2K on LUMI for the first GPU testings (as part of the HPE/AMD activity), but it was only for the RPA tests. Then, as you see, it is not fully ported. I'm not aware of any other configuration... I see LUMI Easybuild has support for 2023.2, so you can give a try, but I don't expect changes in performance...

For instance, I mentioned DBCSR where you don't have all GPU kernels (but I'm not sure this is your problem). Please note that LUMI has currently [an opening for an hackathon](https://www.lumi-supercomputer.eu/events/hackathon-nov23/), just in case you are interested in more optimizations...

**Comment by svandenhaute** [comment]
Well, it looks like the easybuild config, which is supposed to run on the GPU, does not actually install CP2K correctly to allow it to use the GPU efficiently (i.e DBCSR was not running). I'm assuming this has nothing to do with either the input files, LUMI's modules, or the CP2K code, but simply with the way Easybuild configures and compiles it?

Setting that environment variable indeed didn't change anything...
Thanks for your efforts. Given that I cannot reproduce the timings in the paper from @abussy @oschuett with virtually the same input, I'm still kind of assuming that the problem is related to easybuild.
The 2023.2 easyconfig is CPU-only ...

**Comment by alazzaro** [comment]
> Well, it looks like the easybuild config, which is supposed to run on the GPU, does not actually install CP2K correctly to allow it to use the GPU efficiently (i.e DBCSR was not running). I'm assuming this has nothing to do with either the input files, LUMI's modules, or the CP2K code, but simply with the way Easybuild configures and compiles it?

To be clear: it is not DBCSR that it is not configured, it is actually that it is not fully ported to the AMD GPUs...

**Comment by svandenhaute** [comment]
Hmm OK. Well I retried using `srun --export=ALL`, and now it does in fact show T for multiplication densification. However, it doesn't really solve the issue...

```
 DBCSR| CPU Multiplication driver                                           XSMM (U)
 DBCSR| Multrec recursion limit                                              512 (U)
 DBCSR| Multiplication stack size                                          30000 (D)
 DBCSR| Maximum elements for images                                    UNLIMITED (U)
 DBCSR| Multiplicative factor virtual images                                   1 (U)
 DBCSR| Use multiplication densification                                       T (E)
 DBCSR| Multiplication size stacks                                             3 (U)
 DBCSR| Use memory pool for CPU allocation                                     F (U)
 DBCSR| Number of 3D layers                                               SINGLE (U)
 DBCSR| Use MPI memory allocation                                              F (U)
 DBCSR| Use RMA algorithm                                                      F (U)
 DBCSR| Use Communication thread                                               T (U)
 DBCSR| Communication thread load                                             68 (D)
 DBCSR| MPI: My process id                                                     0
 DBCSR| MPI: Number of processes                                             512
 DBCSR| OMP: Current number of threads                                         6
 DBCSR| OMP: Max number of threads                                             6
 DBCSR| ACC: Number of devices/node                                            1
 DBCSR| ACC: Number of stack-buffers per thread                                8 (U)
 DBCSR| ACC: Avoid driver after busy                                           F (U)
 DBCSR| ACC: Process inhomogeneous stacks                                      T (U)
 DBCSR| ACC: Min. flop for processing                                          0 (U)
 DBCSR| ACC: Min. flop for sorting                                          4000 (U)
 DBCSR| ACC: Number of binning bins                                         4096 (U)
 DBCSR| ACC: Size of binning bins                                             16 (U)
 DBCSR| Split modifier for TAS multiplication algorithm                  1.0E+00 (U)


  **** **** ******  **  PROGRAM STARTED AT               2023-10-04 01:02:47.991
 ***** ** ***  *** **   PROGRAM STARTED ON                             nid005775
 **    ****   ******    PROGRAM STARTED BY                              vandenha
 ***** **    ** ** **   PROGRAM PROCESS ID                                 62759
  **** **  *******  **  PROGRAM STARTED IN /pfs/lustrep4/scratch/project_4650003
                                           15/svandenhaute/extreme/scaling/lumig
                                           /32

 CP2K| version string:                                       CP2K version 2023.1
 CP2K| source code revision number:                                  git:b888bd8
 CP2K| cp2kflags: omp libint fftw3 libxc elpa parallel scalapack cosma xsmm dbcs
 CP2K|            r_acc spglib libvori libbqb offload_hip spla_gemm_offloading
 CP2K| is freely available from                            https://www.cp2k.org/
 CP2K| Program compiled at                      Fri 29 Sep 2023 11:12:38 AM EEST
 CP2K| Program compiled on                                                 uan02
 CP2K| Program compiled for                                          LUMIG-20231
 CP2K| Data directory path    /project/project_465000315/EasyBuild_Massimo/SW/LU
 CP2K| Input file name                                                mp2-qz.inp

 GLOBAL| Force Environment number                                              1
 GLOBAL| Basis set file name                                      BASIS_RI_cc-TZ
 GLOBAL| Potential file name                                           POTENTIAL
 GLOBAL| MM Potential file name                                     MM_POTENTIAL
 GLOBAL| Coordinate file name                                       ./H2O-32.xyz
 GLOBAL| Method name                                                        CP2K
 GLOBAL| Project name                                          H2O-32-SOS-MP2-TZ
 GLOBAL| Run type                                                   ENERGY_FORCE
 GLOBAL| FFT library                                                       FFTW3
 GLOBAL| Diagonalization library                                       ScaLAPACK
 GLOBAL| DGEMM library                                                      SPLA
 GLOBAL| Orthonormality check for eigenvectors                          DISABLED
 GLOBAL| Matrix multiplication library                                     COSMA
 GLOBAL| All-to-all communication in single precision                          F
 GLOBAL| FFTs using library dependent lengths                                  F
 GLOBAL| Grid backend                                                       AUTO
 GLOBAL| Global print level                                               MEDIUM
 GLOBAL| MPI I/O enabled                                                       T
 GLOBAL| Total number of message passing processes                           512
 GLOBAL| Number of threads for this process                                    6
 GLOBAL| This output is from process                                           0
 GLOBAL| Stack size for threads created by OpenMP (OMP_STACKSIZE)           512M
 GLOBAL| CPU model name                          AMD EPYC 7A53 64-Core Processor
 GLOBAL| CPUID                                                              1002

 MEMORY| system memory details [Kb]
 MEMORY|                        rank 0           min           max       average
 MEMORY| MemTotal            527647364     527636196     527647572     527638323
 MEMORY| MemFree             502016212     497636952     506178564     500009458
 MEMORY| Buffers                     0             0             0             0
 MEMORY| Cached                2240172       2235468       6182996       4814784
 MEMORY| Slab                  4460412       4459328       4755044       4549247
 MEMORY| SReclaimable            91456         91456        131256        114435
 MEMORY| MemLikelyFree       504347840     503815744     508863744     504938677
```

**Comment by abussy** [comment]
Generally, standard 4-center HFX is not GPU accelerated. The main bottleneck is the calculation of the ERIs, which is done with the libint library (and only on the CPU). From your initial post:

> On 64 LUMI-G nodes (4x MI250X, 8 effective GPUs, 64 cores, 512 GB RAM) with 8 ranks per node, I get the following timings for the HF SCF.
> 
> ```
>  Number of electrons:                                                        256
>  Number of occupied orbitals:                                                128
>  Number of molecular orbitals:                                               128
> 
>  Number of orbital functions:                                               3648
>  Number of independent orbital functions:                                   3648
> 
>  Extrapolation method: initial_guess
> 
> 
>  SCF WAVEFUNCTION OPTIMIZATION
> 
>   ----------------------------------- OT ---------------------------------------
>   Minimizer      : DIIS                : direct inversion
>                                          in the iterative subspace
>                                          using   7 DIIS vectors
>                                          safer DIIS on
>   Preconditioner : FULL_SINGLE_INVERSE : inversion of
>                                          H + eS - 2*(Sc)(c^T*H*c+const)(Sc)^T
>   Precond_solver : DEFAULT
>   stepsize       :    0.08000000                  energy_gap     :    0.08000000
>   eps_taylor     :   0.10000E-15                  max_taylor     :             4
>   ----------------------------------- OT ---------------------------------------
> 
>   Step     Update method      Time    Convergence         Total energy    Change
>   ------------------------------------------------------------------------------
> 
>   HFX_MEM_INFO| Est. max. program size before HFX [MiB]:                     845
>   HFX_MEM_INFO| Number of cart. primitive ERI's calculated:       17375968139863
>   HFX_MEM_INFO| Number of sph. ERI's calculated:                  13050829340679
>   HFX_MEM_INFO| Number of sph. ERI's stored in-core:                611779728818
>   HFX_MEM_INFO| Number of sph. ERI's stored on disk:                           0
>   HFX_MEM_INFO| Number of sph. ERI's calculated on the fly:       12439049611861
>   HFX_MEM_INFO| Total memory consumption ERI's RAM [MiB]:                 756912
>   HFX_MEM_INFO| Whereof max-vals [MiB]:                                       30
>   HFX_MEM_INFO| Total compression factor ERI's RAM:                         6.17
>   HFX_MEM_INFO| Total memory consumption ERI's disk [MiB]:                     0
>   HFX_MEM_INFO| Total compression factor ERI's disk:                        0.00
>   HFX_MEM_INFO| Size of density/Fock matrix [MiB]:                           102
>   HFX_MEM_INFO| Size of buffers [MiB]:                                         3
>   HFX_MEM_INFO| Number of periodic image cells considered:                    33
>   HFX_MEM_INFO| Est. max. program size after HFX  [MiB]:                    7328
> 
>      1 OT DIIS     0.80E-01 1155.2     0.00209796      -541.2350089494 -5.41E+02
>      2 OT DIIS     0.80E-01 1062.5     0.00155964      -541.3781652118 -1.43E-01
>      3 OT DIIS     0.80E-01 1063.1     0.00032084      -541.5583420040 -1.80E-01
> ```

We can see that only a fraction of all ERIs are stored in-core, while the large majority is calculated on the fly. This leads to very expensive SCF steps. Ideally, you want all the ERIs to be calculated once and for all at the first SCF step and store them in memory, such that they can be efficiently retrieved for the rest of the calculation.

The keyword that controls how much memory is allocated to HFX ERIs is `MAX_MEMORY` in `HF%MEMORY`, measured in MiB per MPI rank. In the paper you mentioned, I used to run 16 MPI ranks with 3 OMP threads per node, with MAX_MEMORY set up to 25000. In the output above, we see that the estimated max program size after HFX is 7 GiB per MPI rank, which leads to 56 GiB per node if we assume one rank per GPU (8 ranks per node). Since there is 512 GB per node on LUMI-G, you have a lot of room to spare.

Edit: post-HF is also memory hungry, so maybe don't use the full node memory for HFX.

**Comment by dev-zero** [comment]
Depending on how fast the storage is, even caching the HFX primitive integrals on-disk might be faster than recalculation, in particular on GPU nodes where the CPU might not be as fast as the ones used in CPU partitions.

**Comment by svandenhaute** [comment]
> We can see that only a fraction of all ERIs are stored in-core, while the large majority is calculated on the fly. This leads to very expensive SCF steps. Ideally, you want all the ERIs to be calculated once and for all at the first SCF step and store them in memory, such that they can be efficiently retrieved for the rest of the calculation.
> 
> The keyword that controls how much memory is allocated to HFX ERIs is `MAX_MEMORY` in `HF%MEMORY`, measured in MiB per MPI rank. In the paper you mentioned, I used to run 16 MPI ranks with 3 OMP threads per node, with MAX_MEMORY set up to 25000. In the output above, we see that the estimated max program size after HFX is 7 GiB per MPI rank, which leads to 56 GiB per node if we assume one rank per GPU (8 ranks per node). Since there is 512 GB per node on LUMI-G, you have a lot of room to spare.
> 
> Edit: post-HF is also memory hungry, so maybe don't use the full node memory for HFX.

When using HF%MEMORY 24000, most integrals are still computed on the fly:
```
  HFX_INFO| Replica ID:                                                        1
  HFX_INFO| FRACTION:                                               1.0000000000
  HFX_INFO| Interaction Potential:                                     TRUNCATED
  HFX_INFO| Cutoff Radius [angstrom]:                               4.9000000000
  HFX_INFO| EPS_SCHWARZ:                                                 1.0E-07
  HFX_INFO| EPS_SCHWARZ_FORCES                                           1.0E-06
  HFX_INFO| EPS_STORAGE_SCALING:                                         1.0E+00
  HFX_INFO| NBINS:                                                            64
  HFX_INFO| BLOCK_SIZE:                                                        1
  HFX_INFO| NUMBER_OF_SHELLS:                                               AUTO
  HFX_INFO| Number of periodic shells considered:                             -1
  HFX_INFO| Number of periodic cells considered:                              33


 RI-SOS-Laplace-MP2| using GPW style


 Number of electrons:                                                        256
 Number of occupied orbitals:                                                128
 Number of molecular orbitals:                                               128

 Number of orbital functions:                                               3648
 Number of independent orbital functions:                                   3648

 Extrapolation method: initial_guess


 SCF WAVEFUNCTION OPTIMIZATION

  ----------------------------------- OT ---------------------------------------
  Minimizer      : DIIS                : direct inversion
                                         in the iterative subspace
                                         using   7 DIIS vectors
                                         safer DIIS on
  Preconditioner : FULL_SINGLE_INVERSE : inversion of
                                         H + eS - 2*(Sc)(c^T*H*c+const)(Sc)^T
  Precond_solver : DEFAULT
  stepsize       :    0.08000000                  energy_gap     :    0.08000000
  eps_taylor     :   0.10000E-15                  max_taylor     :             4
  ----------------------------------- OT ---------------------------------------

  Step     Update method      Time    Convergence         Total energy    Change
  ------------------------------------------------------------------------------

  HFX_MEM_INFO| Est. max. program size before HFX [MiB]:                     829
  HFX_MEM_INFO| Number of cart. primitive ERI's calculated:       17375968139863
  HFX_MEM_INFO| Number of sph. ERI's calculated:                  13050829340679
  HFX_MEM_INFO| Number of sph. ERI's stored in-core:               4959624363975
  HFX_MEM_INFO| Number of sph. ERI's stored on disk:                           0
  HFX_MEM_INFO| Number of sph. ERI's calculated on the fly:        8091204976704
  HFX_MEM_INFO| Total memory consumption ERI's RAM [MiB]:                6119786
  HFX_MEM_INFO| Whereof max-vals [MiB]:                                      265
  HFX_MEM_INFO| Total compression factor ERI's RAM:                         6.18
  HFX_MEM_INFO| Total memory consumption ERI's disk [MiB]:                     0
  HFX_MEM_INFO| Total compression factor ERI's disk:                        0.00
  HFX_MEM_INFO| Size of density/Fock matrix [MiB]:                           102
  HFX_MEM_INFO| Size of buffers [MiB]:                                         3
  HFX_MEM_INFO| Number of periodic image cells considered:                    33
  HFX_MEM_INFO| Est. max. program size after HFX  [MiB]:                   25397

     1 OT DIIS     0.80E-01  596.9     0.00209796      -541.2350089494 -5.41E+02
```
I'll try increasing it but I'm a bit puzzled by 
```
  HFX_MEM_INFO| Total memory consumption ERI's RAM [MiB]:                6119786
```
Why does he compute the ERI's on the fly if he still has 24 - 6 = 18 GB of RAM available per rank?

**Comment by abussy** [comment]
To be perfectly honest with you, I am not sure how to interpret the `HFX_MEM_INFO| Total memory consumption ERI's RAM [MiB]:` information. What is certain is that after calculation of the ERIs, you are using ~25GiB of memory per MPI rank, as stated by:

`HFX_MEM_INFO| Est. max. program size after HFX  [MiB]:                   25397`,

which is in line with your value of `MAX_MEMORY`.

Note that in the paper you were mentioning earlier, I systematically used that ADMM approximation for the ground state calculation. ADMM has a drastic impact on the cost and memory requirements of HFX.

**Comment by svandenhaute** [comment]
I tried with ADMM, but couldn't figure the proper input. Would you mind sharing it?

**Comment by hfp** [comment]
> [...] which makes no use of the GPUs and is enormously slow when executed using 1 rank / GPU.

I think one needs to put multiple ranks onto each GPU and find a sweet-spot balancing the need for ranks on CPU vs avoiding overhead from sharing/time-slicing the GPU.

> Wouldn't it be more efficient to use the PBE orbitals for a HF SCF (performed with 1-4 cores per rank, on CPU-only nodes), and use the converged HF orbitals as input for the RI-MP2 part, on GPU nodes?

Do you suggest restarting the calculation w/ GPU acceleration after some initial work on CPU-only?

**Comment by svandenhaute** [comment]
> Do you suggest restarting the calculation w/ GPU acceleration after some initial work on CPU-only?

Precisely!

**Comment by abussy** [comment]
[water64_SOS-MP2.zip](https://github.com/cp2k/cp2k/files/12802288/water64_SOS-MP2.zip)

> I tried with ADMM, but couldn't figure the proper input. Would you mind sharing it?

No problem! In this zip file there is my input and output file corresponding to the 32 LUMI-G nodes GPU data point of figure 9 of the paper

**Comment by svandenhaute** [comment]
Thanks, that works!! The system sizes I'd be looking at would be around 300 - 400 atoms, and I'd only need to evaluate the energy. Given the architecture of LUMI-G, would I rather use the cubic or quartically scaling algorithm in terms of GPU efficiency?
When I monitor GPU usage during a calculation with more or less your exact input, GPU usage is rather spiky (though I didn't bother setting all the environment variables that you set...)

**Comment by abussy** [comment]
I believe that the quartic scaling approach has better GPU performance. That being said, 300-400 atoms is large enough that the cubic-scaling approach could become more efficient overall. The short answer is: try both and pick the one that works best for your kind of system.

**Comment by svandenhaute** [comment]
@abussy makes sense.
Does CP2K's restart functionality allow us to enter directly into the RI-MP2 section with a HF-converged restart file? In this way, you'd avoid the GPU idling during the initial HF SCF (which itself is started from a PBE solution)...

**Comment by abussy** [comment]
No, this is unfortunately not possible. At least one SCF cycle (where all the ERIs are calculated) is necessary. In principle, I think it could be possible to do a MP2 calculation simply starting from MOs and orbital energies, but CP2K is not implemented that way.

**Comment by abussy** [comment]
Note that if GPU usage is your main concern, you can switch to RI-HFX. In this approach, the workload is shifted from computing the ERIs to tensor contraction (which is GPU accelerated). RI-HFX is however rarely faster than standard 4-center HFX, especially for large molecular systems.

**Comment by svandenhaute** [comment]
I tried to look into RI-HFX, but it wasn't really clear to me how to specify this in the input file. Does it also use the RI basis for the correlation part? Do you have a (recent) example maybe?

**Comment by abussy** [comment]
In its simplest form, switching to RI-HFX comes downs to adding an empty `&RI` section in the `&HF` section of the input file. The RI basis it will use is then automatically generated from the orbital basis set according to https://doi.org/10.1021/acs.jctc.6b01041. You can also impose the use of a given basis set by setting the `BASIS_SET RI_HFX` keyword in the `&KIND` section. The RI_HFX basis set can be taken to be the same as the RI_AUX basis set for post-HF, but this is not necessary. In particular, if ADMM is used, these two basis sets will be different.

Another aspect for RI-HFX performance if the choice of the RI metric. The most accurate results are obtained of the RI metric is the same as the HFX potential. However, using shorter ranged metric brings sparsity and improves performance. 

I join 2 examples. One is a TiO2 SOS-MP2 calculation based on an ADMM-RI-HFX ground state with the overlap RI metric (figure 10 of the paper). The other one is a simple PBE0 RI-HFX calculation of 64 water molecules (figure 5 of the paper)

[64water_RI-HFX.zip](https://github.com/cp2k/cp2k/files/12804148/64water_RI-HFX.zip)

[TiO2_SOS-MP2.zip](https://github.com/cp2k/cp2k/files/12804154/TiO2_SOS-MP2.zip)

**Comment by fstein93** [comment]
Apparently, this issue is solved. Feel free to reopen it, if necessary.
