### ISSUE TITLE
RFE: Need to be able to build and install multiple MPI implementations

### ISSUE THREAD

**Issue by opoplawski** [cp2k/cp2k#3078]
The Fedora cp2k package builds for multiple MPI implementations - currently openmpi and mpich.  However with cp2k's current cmake build systems the two builds write their executables to the same location.  Also, the fedora package currently suffixes the executables with the MPI names, e.g. `cp2k.psmp_openmpi`.  I'm not sure this is strictly necessary as they are installed (finally) into different directories (`/usr/lib64/{mpich,openmpi/}bin`), but might be one solution.

Another might be to able to define a suffix to the `__cp2k_cmake_name` variable.

**Comment by oschuett** [comment]
Fixed via #3079.
