### ISSUE TITLE
Wrong atom kinds with cif file generated by ase

### ISSUE THREAD

**Issue by tsaihsiaoyi** [cp2k/cp2k#3085]
Usually the atom_info of a cif file (e.g. Material Studio) will follow the following order
```
_atom_site_label
_atom_site_type_symbol
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
Ti0    Ti    0.00000   0.00000   0.00000
```
But cif file generated by ase may follow order like
```
_atom_site_type_symbol
_atom_site_label
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
Ti  Ti1       0.00000  1.00000  0.02294 
```
which will cause subroutine `read_coordinate_cif` in topology_cif.F take `_atom_site_label` as the atom type. For example, the type of oxygen atom is O1, but the other oxygen atom is O2.
The result is that atom kinds is equal to the number of atoms, which may lead a HF funcitonal calculation cost several times the time. My solution now is turn `USE_ELEMENT_AS_KIND` on. But I still wish this bug can be fixed. The following are my modifications to the code, please let me know if there are any problems. With my respect.
```patch
diff --git a/src/topology_cif.F b/src/topology_cif.F
index 7eab185f1..164a59f47 100644
--- a/src/topology_cif.F
+++ b/src/topology_cif.F
@@ -161,15 +161,15 @@ CONTAINS
       IF (.NOT. found) &
          CPABORT("The field _atom_site_label was not found in CIF file! ")
       ifield = 0
-      ii = 1
-      ifield(ii) = 0
+      ii = 0
+      ! ifield(ii) = 0
       CALL parser_search_string(parser, "_atom_site_", ignore_case=.FALSE., found=found, &
                                 begin_line=.FALSE., search_from_begin_of_file=.TRUE.)
       DO WHILE (INDEX(parser%input_line, "_atom_site_") /= 0)
-         IF (INDEX(parser%input_line, "_atom_site_label") /= 0) THEN
-            CALL parser_get_next_line(parser, 1)
-            CYCLE
-         END IF
+         ! IF (INDEX(parser%input_line, "_atom_site_label") /= 0) THEN
+            ! CALL parser_get_next_line(parser, 1)
+            ! CYCLE
+         ! END IF
          ii = ii + 1
          CPASSERT(ii <= 20)
```

**Comment by oschuett** [comment]
Thanks for the great analysis. Your patch looks good. Do you want to send it as a pull request or should I take care of it?

**Comment by juerghutter** [comment]
Have you checked this with the latest version? We fixed a similar problem some months ago.
Generalize CIF file reader (#2843)

**Comment by tsaihsiaoyi** [comment]
> Have you checked this with the latest version? We fixed a similar problem some months ago. Generalize CIF file reader (#2843)
> Thanks for the great analysis. Your patch looks good. Do you want to send it as a pull request or should I take care of it?

After further research into this issue, I discovered that things are not as simple as I initially thought.
The code modified in this commit (#2843) is exact where I thought where the bug is. But When I try to run the example by using newest version of CP2k, which is [tests/xTB/regtest-1/tcif.inp](https://github.com/cp2k/cp2k/blob/master/tests/xTB/regtest-1/tcif.inp), also generated by ase, it doesn't show the same error. `atom kinds` shows 5, which is correct. But my input file and cif file still show the wrong atom kinds.
Please forgive my lack of understanding about CP2K. This patch maybe only fix my problem but cause more problems. I will not send PR for now until I figure out where the bug is.
Here is my input file and cif file. If it is convenient for you, you can try to reproduce this error and fix it.
[testsuite.zip](https://github.com/cp2k/cp2k/files/13251532/testsuite.zip)
Thanks for the reply!

**Comment by oschuett** [comment]
My understanding of the CIF file format is that the lines with `_atom_site_` are the column headers for the subsequent table of atoms.

Therefore, I'm really puzzled by the `CYCLE` before `ii = ii + 1` because it effectively shifts the headers of all later columns:

https://github.com/cp2k/cp2k/blob/27465532c224d97ca9b5ed5de7173fb2f9dcfc01/src/topology_cif.F#L168-L173

**Comment by juerghutter** [comment]
Hi

The code first sets up a table with the list of key words and gives
them a label. The label is then used to identify the action needed.
-1 -> skip
0 -> get the atom name and molecule name
1 -> x coordinate
2 -> y coordinate
3 -> z coordinate

The problem is now that action 0 (atom name) is hard wired to the first column!
Your changes are going in the right direction but need to set the correct
ifield(ii) = 0

regards
JH

________________________________________

**Comment by tsaihsiaoyi** [comment]
Agree, so my first thought was different sequence of `_atom_site_type_symbol` and `_atom_site_label` may cause the bug. But the test file in #2834 shows that my thoughts could be wrong. I need further investigation.

**Comment by oschuett** [comment]
How about this:

```diff
diff --git a/src/topology_cif.F b/src/topology_cif.F
index 7eab185f1..e53a3c758 100644
--- a/src/topology_cif.F
+++ b/src/topology_cif.F
@@ -160,20 +160,11 @@ CONTAINS
                                 begin_line=.FALSE., search_from_begin_of_file=.TRUE.)
       IF (.NOT. found) &
          CPABORT("The field _atom_site_label was not found in CIF file! ")
-      ifield = 0
+      ifield(:) = -1 // skip field by default
       ii = 1
-      ifield(ii) = 0
       CALL parser_search_string(parser, "_atom_site_", ignore_case=.FALSE., found=found, &
                                 begin_line=.FALSE., search_from_begin_of_file=.TRUE.)
       DO WHILE (INDEX(parser%input_line, "_atom_site_") /= 0)
-         IF (INDEX(parser%input_line, "_atom_site_label") /= 0) THEN
-            CALL parser_get_next_line(parser, 1)
-            CYCLE
-         END IF
-         ii = ii + 1
-         CPASSERT(ii <= 20)
-
-         ifield(ii) = -1
          ! Check for   _atom_site_type_symbol
          IF (INDEX(parser%input_line, "_atom_site_type_symbol") /= 0) ifield(ii) = 0
          ! Check for   _atom_site_fract_x
@@ -183,6 +174,8 @@ CONTAINS
          ! Check for   _atom_site_fract_z
          IF (INDEX(parser%input_line, "_atom_site_fract_z") /= 0) ifield(ii) = 3
          CALL parser_get_next_line(parser, 1)
+         ii = ii + 1
+         CPASSERT(ii <= 20)
       END DO
       ! Parse real info
       natom = 0
```

**Comment by tsaihsiaoyi** [comment]
Now I figure out why the example in #2843 won't cause this bug, `METHOD xTB` will turn the option `USE_ELEMENT_AS_KIND` by default.
https://github.com/cp2k/cp2k/blob/27465532c224d97ca9b5ed5de7173fb2f9dcfc01/tests/xTB/regtest-1/tcif.inp#L9
https://github.com/cp2k/cp2k/blob/27465532c224d97ca9b5ed5de7173fb2f9dcfc01/src/qs_environment.F#L308-L309
So the problem still exists in `topology_cif.F`. Your patch looks work. So the decision is yours. Please fix this bug appropriately. Thanks!
