### ISSUE TITLE
[toolchain] doesn't set nvcc optimisation flags

### ISSUE THREAD

**Issue by shoshijak** [cp2k/cp2k#311]
When using the toolchain script to create arch files and activating the `--enable-cuda` option, the generated arch file does not contain any optimisation flags for CUDA (see  `NVFLAGS` variable). 

We should probably add `-O2` (maybe even `fast-math`?) at least in the `?smp` versions.

**Comment by shoshijak** [comment]
For completion: DBCSR passes `-O3`, but no `fast-math` to `nvcc`.

**Comment by alazzaro** [comment]
We don't support fast math anymore. -O3 is fine.
