### ISSUE TITLE
After completing cp2k compilation, an error occurs when performing cp2k testing.

### ISSUE THREAD

**Issue by 12jscvb** [cp2k/cp2k#3117]
When I perform a cp2k test, I enter the mpirun -np 6 cp2k.popt |tee test.out command on the ubuntu terminal(ubuntu version 20.04 is used). The following error occurs: I tried a lot but still couldn't solve it. Thank you for your help

![捕获](https://github.com/cp2k/cp2k/assets/145745956/b53b4ae2-9a39-45b0-a2e6-663df6349043)

**Comment by fstein93** [comment]
As the error message suggests, you are missing command line arguments. Your CP2K call command should look like `mpirun -np <number of requested processes> cp2k.popt -i <your input file> -o <your output file>`. (The command `mpiexec` is preferred over `mpirun` because it is standardized whereas `mpirun` is not.) Call CP2K with `cp2k.popt -h` to get some help with the command line interface.

**Comment by 12jscvb** [comment]
> As the error message suggests, you are missing command line arguments. Your CP2K call command should look like `mpirun -np <number of requested processes> cp2k.popt -i <your input file> -o <your output file>`. (The command `mpiexec` is preferred over `mpirun` because it is standardized whereas `mpirun` is not.) Call CP2K with `cp2k.popt -h` to get some help with the command line interface.


Hello. When I run the "mpiexec/mpirun -np 1 cpek.popt -i 1.inp -o test.out" command, the following error occurs: How to solve it next
![2023-11-17](https://github.com/cp2k/cp2k/assets/145745956/3215548a-f801-4d88-8ed0-9fa7aefcdcd9)

**Comment by fstein93** [comment]
Can you upload your input file and the output file? Your error message is too unspecific without any details on the attempted calculation.

**Comment by 12jscvb** [comment]
> Can you upload your input file and the output file? Your error message is too unspecific without any details on the attempted calculation.

Sorry, these are my input files and output files. Thank you very much for your help
[input.txt](https://github.com/cp2k/cp2k/files/13389735/input.txt)
[test.out.txt](https://github.com/cp2k/cp2k/files/13389736/test.out.txt)

**Comment by mkrack** [comment]
The line
```
CP2K| cp2kflags: omp libint fftw3 libxc xsmm spglib libvori libbqb
```
in your output file does not contain the feature keyword `parallel`, but only `omp`. Thus your CP2K binary has not been built with MPI support, but only with OpenMP threading support, and thus it won't run in parallel using MPI via `mpirun` or `mpiexec`.

**Comment by 12jscvb** [comment]
> The line
> 
> ```
> CP2K| cp2kflags: omp libint fftw3 libxc xsmm spglib libvori libbqb
> ```
> 
> in your output file does not contain the feature keyword `parallel`, but only `omp`. Thus your CP2K binary has not been built with MPI support, but only with OpenMP threading support, and thus it won't run in parallel using MPI via `mpirun` or `mpiexec`.

**Comment by 12jscvb** [comment]
> > The line
> > ```
> > CP2K| cp2kflags: omp libint fftw3 libxc xsmm spglib libvori libbqb
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in your output file does not contain the feature keyword `parallel`, but only `omp`. Thus your CP2K binary has not been built with MPI support, but only with OpenMP threading support, and thus it won't run in parallel using MPI via `mpirun` or `mpiexec`.

Thank you for your answer. How do I solve this problem. Could you give me some suggestions?

**Comment by fstein93** [comment]
You have to recompile CP2K (see [here](https://github.com/cp2k/cp2k/blob/master/INSTALL.md) or via [CMake](https://github.com/cp2k/cp2k/blob/master/README_cmake.md)).

**Comment by 12jscvb** [comment]
thank your reply. when recompiling cp2k, l need to pay attention to which part to avoid this problem .&nbsp;

---Original---
From: "Frederick ***@***.***&gt;
Date: Fri, Nov 17, 2023 20:42 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [cp2k/cp2k] After completing cp2k compilation, an error occurswhen performing cp2k testing. (Issue #3117)




 
You have to recompile CP2K (see here or via CMake).
