### ISSUE TITLE
Variable "MULTIPLICITY" setting in NEB

### ISSUE THREAD

**Issue by tsaihsiaoyi** [cp2k/cp2k#3123]
In NEB calculations, each electronic state of a structure may have different multiplicities. Is it possible to change the MULTIPLICITY parameter setting for each step in CP2K's NEB calculation? If not, is it possible to modify the source code to achieve this? As far as I know, NEB calculations rely on stack operations of the force environment. So, is it possible to modify the multiplicity setting for each step?
With my respect, Thank you!

**Comment by juerghutter** [comment]
Hi

Yes, individual force environments can be setup independently.
For a NEB calculation, only the number and order of the atoms
has to be the same in all environments.

regards
JH

________________________________________
From: Hsiaoyi Tsai ***@***.***>
Sent: Wednesday, November 22, 2023 8:04 AM
To: cp2k/cp2k
Cc: Subscribed
Subject: [cp2k/cp2k] Variable "MULTIPLICITY" setting in NEB (Issue #3123)

In NEB calculations, each electronic state of a structure may have different multiplicities. Is it possible to change the MULTIPLICITY parameter setting for each step in CP2K's NEB calculation? If not, is it possible to modify the source code to achieve this? As far as I know, NEB calculations rely on stack operations of the force environment. So, is it possible to modify the multiplicity setting for each step?
With my regard, Thank you!

**Comment by tsaihsiaoyi** [comment]
Thanks for your reply!
So, for now, cp2k can't do this, right? If not, is there any plan for you to do this?
With my respect, Thank you!

**Comment by juerghutter** [comment]
Right.
No plans to implement such an option from my side.

regards
JH

________________________________________

**Comment by tsaihsiaoyi** [comment]
Got it.
Thanks again for your reply!
