### ISSUE TITLE
Inconsistent result between builtin and LibXC B3LYP

### ISSUE THREAD

**Issue by yizeyi18** [cp2k/cp2k#3131]
Using input below, builtin B3LYP gives inconsistent result compared to libxc HYB_GGA_XC_B3LYP or HYB_GGA_XC_B3LYP5.
The result is:

```
 builtin               -76.38085340418614 
 HYB_GGA_XC_B3LYP      -74.63525048993552 
 HYB_GGA_XC_B3LYP5     -74.59818843158433 
```

<details><summary>Builtin B3LYP Input</summary>

&FORCE_EVAL
  METHOD Quickstep
  &DFT
    BASIS_SET_FILE_NAME EMSL_BASIS_SETS
    POTENTIAL_FILE_NAME POTENTIAL
    &MGRID
      CUTOFF 250
      REL_CUTOFF 50
    &END MGRID
    &QS
      METHOD GAPW
    &END QS
    &POISSON
      PERIODIC NONE
      PSOLVER MT
    &END
    &SCF
      EPS_SCF 1.0E-6
      SCF_GUESS ATOMIC
      MAX_SCF 100
    &END SCF
      &XC
      &XC_FUNCTIONAL B3LYP
      &END XC_FUNCTIONAL
    &END XC
  &END DFT
  &SUBSYS
    &CELL
      ABC 6.0 6.0 6.0
      PERIODIC NONE
    &END CELL
    &COORD
    O   0.000000    0.000000   -0.065587
    H   0.000000   -0.757136    0.520545
    H   0.000000    0.757136    0.520545
    &END COORD
    &KIND H
      BASIS_SET 6-31Gxx
      POTENTIAL ALL
    &END KIND
    &KIND O
      BASIS_SET 6-31Gxx
      POTENTIAL ALL
    &END KIND
  &END SUBSYS
&END FORCE_EVAL
&GLOBAL
  PROJECT H2O-B3LYP
#  TRACE
  PRINT_LEVEL MEDIUM
&END GLOBAL

</details>
<details><summary>LibXC Input, just replaced B3LYP with an empty HYB_GGA_XC_B3LYP section</summary>

&FORCE_EVAL
  METHOD Quickstep
  &DFT
    BASIS_SET_FILE_NAME EMSL_BASIS_SETS
    POTENTIAL_FILE_NAME POTENTIAL
    &MGRID
      CUTOFF 250
      REL_CUTOFF 50
    &END MGRID
    &QS
      METHOD GAPW
    &END QS
    &POISSON
      PERIODIC NONE
      PSOLVER MT
    &END
    &SCF
      EPS_SCF 1.0E-6
      SCF_GUESS ATOMIC
      MAX_SCF 100
    &END SCF
      &XC
      &XC_FUNCTIONAL
        &HYB_GGA_XC_B3LYP
        &END HYB_GGA_XC_B3LYP
      &END XC_FUNCTIONAL
    &END XC
  &END DFT
  &SUBSYS
    &CELL
      ABC 6.0 6.0 6.0
      PERIODIC NONE
    &END CELL
    &COORD
    O   0.000000    0.000000   -0.065587
    H   0.000000   -0.757136    0.520545
    H   0.000000    0.757136    0.520545
    &END COORD
    &KIND H
      BASIS_SET 6-31Gxx
      POTENTIAL ALL
    &END KIND
    &KIND O
      BASIS_SET 6-31Gxx
      POTENTIAL ALL
    &END KIND
  &END SUBSYS
&END FORCE_EVAL
&GLOBAL
  PROJECT H2O-B3LYP
#  TRACE
  PRINT_LEVEL MEDIUM
&END GLOBAL

</details>

Here attatches full output:
[B3LYP-builtin.log](https://github.com/cp2k/cp2k/files/13464046/B3LYP-builtin.log)
[B3LYP-libxc.log](https://github.com/cp2k/cp2k/files/13464047/B3LYP-libxc.log)
[B3LYP5-libxc.log](https://github.com/cp2k/cp2k/files/13464048/B3LYP5-libxc.log)

**Comment by fstein93** [comment]
If you use LibXC, you have to set the Hartree-Fock section (&HF) manually. If you check your output files, you will find that the Hartree-Fock exchange energy of your system has a magnitude of 1.8 Hartree which is roughly the difference between the LibXC and the builtin B3LYP implementation.

**Comment by fstein93** [comment]
Apparently, this issue is solved. If there are still related questions left, feel free to reopen this issue.
