### ISSUE TITLE
General slowdown due to DLA-Future 

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#3187]
After the [introduction of DLAF](https://github.com/cp2k/cp2k/pull/3143) the timings of the [CMake regtests](https://dashboard.cp2k.org/archive/cmake/index.html) went up by 3-5x:

![image](https://github.com/cp2k/cp2k/assets/241771/90cb6df1-0aaa-47eb-a65f-7c995f80ce25)

It can't be `cp_fm_diag_dlaf` because it's only called for matrices larger than 1024.

Suspects that come to mind are:

- [MPI_THREAD_MULTIPLE](https://github.com/cp2k/cp2k/blob/ad61d0fb47758fedc409ed1d609b4bb070cc6269/src/mpiwrap/message_passing.F#L1149)
- [cp_pdpotrf_dlaf](https://github.com/cp2k/cp2k/blob/ad61d0fb47758fedc409ed1d609b4bb070cc6269/src/fm/cp_fm_cholesky.F#L81)
- An incompatibility between [do_regtest.py and pika-bind](https://github.com/cp2k/cp2k/blob/ad61d0fb47758fedc409ed1d609b4bb070cc6269/tools/docker/scripts/test_regtest_cmake.sh#L84)

@RMeli what do you think?

**Comment by RMeli** [comment]
@oschuett thanks for pointing this out! I think this might be caused by improper bindings, which I did not take into account (`pika-bind` is a simple wrapper script that tries to get binding information from MPI or SLURM). Is the test running with a 2 MPI ranks on a single 32 cores AMD EPYC CPU? Is it possible to have a look at the output of one of the tests, to see what `pika-bind` prints out?

**Comment by oschuett** [comment]
The [do_regtest.py](https://github.com/cp2k/cp2k/blob/master/tests/do_regtest.py) parallelizes over [TEST_DIRS](https://github.com/cp2k/cp2k/blob/master/tests/TEST_DIRS). In the case of the CMake test it uses  8 worker each running CP2K with 2 MPI ranks and 2 OpenMP threads.

As a workaround I've now hard-coded `PIKA_PROCESS_MASK="0x3"`, which brings the time back down to 10 minutes.

A proper solution, in my opinion, would require DLAF/pika to better integrate with OpenMP. As a start, it should not use more threads that `$OMP_NUM_THREADS`.

**Comment by oschuett** [comment]
Fixed by #3191.

**Comment by RMeli** [comment]
Thanks Ole. I did miss the parallelism over multiple workers, so my quick test in #3189 did reduce contention but did not remove it completely. Thanks for fixing this in #3191, LGTM.
