### ISSUE TITLE
The command “mpirun  - np cores cp2k.popt -i input -o out ”  cannot implement cp2k parallel computing

### ISSUE THREAD

**Issue by 12jscvb** [cp2k/cp2k#3190]
The hardware is configured as two nodes, each with 64 cores, the operating system is set with hyperthreading turned off, the cp2k version is 2023, and the toolchain is compiled using the OpenMPI library. cp2k runs an aimd with a 255 atom system. When the command "mpirun-np 32/64/128 cp2k.popt -i input.in -o 1.out "is used, the cpu usage immediately spikes to 200%~300%. After a period of time, cp2k automatically stops the program, and no error information is reported in the output file. When I use the command "cp2k.popt -i input.in -o 1.out", cp2k only works as a single-core program. That is, multi-core cpu resources cannot be invoked. How could I solve it? Thank you very much for your help

**Comment by fstein93** [comment]
Can you run the command `mpirun -np 64 --bind-to none cp2k.popt -i input.in -o 1.out` instead? If the issue persits: Can you also post the input and output files? How have you compiled CP2K and OpenMPI?

**Comment by 12jscvb** [comment]
Thank you for reply, I have solved the problem. thr reason is that I run cp2k in the anaconda environment, which caused MPI conflicts



---Original---
From: "Frederick ***@***.***&gt;
Date: Tue, Jan 2, 2024 00:43 AM
To: ***@***.***&gt;;
Cc: "Express ***@***.******@***.***&gt;;
Subject: Re: [cp2k/cp2k] The command “mpirun  - np cores cp2k.popt -i input -o out ”  cannot implement cp2k parallel computing (Issue #3190)




 
Can you run the command mpirun -np 64 --bind-to none cp2k.popt -i input.in -o 1.out instead? If the issue persits: Can you also post the input and output files? How have you compiled CP2K and OpenMPI?
