### ISSUE TITLE
Decrease in performance for DFTB in cp2k 2023.2 compared to 9.1

### ISSUE THREAD

**Issue by blah17** [cp2k/cp2k#3198]
Hello everyone,

I am doing most of my calculations using version 9.1 of cp2k, however I wanted to move to the newer 2023.2 version. I Installed this on the same machine using the same flags for the toolchain and ultimately the make command. `./install_cp2k_toolchain.sh --with-sirius=no --with-spla=no --with-elpa=no --with-plumed=install` `make -j 4 ARCH=local VERSION="ssmp sdbg psmp pdbg"`

But now i see around a ~5x decrease in performance for the newer version while also using the exact same input file. I am unsure what is causing this drop in performance. Could someone help me out with this?

Here is a zip file with the 2 calculations I ran.
[quick_cp2k_tests.zip](https://github.com/cp2k/cp2k/files/13821115/quick_cp2k_tests.zip)

Kind regards,
Roel v/d Ven

**Comment by juerghutter** [comment]
Hi

In recent versions of CP2K the default for the electrostatic energy in
DFTB calculations has changed.
In older versions this was always direct summation, Ewald summation
had to be switched on in the input for periodic calculations.
Now, the defaults are direct summation for non-periodic and Ewald
for periodic calculations. You can still switch the methods in the input.

In your case I would suggest to add PERIODIC NONE to the cell definition.

regards
JH

________________________________________
From: blah17 ***@***.***>
Sent: Wednesday, January 3, 2024 5:08 PM
To: cp2k/cp2k
Cc: Subscribed
Subject: [cp2k/cp2k] Decrease in performance for DFTB in cp2k 2023.2 compared to 9.1 (Issue #3198)

Hello everyone,

I am doing most of my calculations using version 9.1 of cp2k, however I wanted to move to the newer 2023.2 version. I Installed this on the same machine using the same flags for the toolchain and ultimately the make command. ./install_cp2k_toolchain.sh --with-sirius=no --with-spla=no --with-elpa=no --with-plumed=install make -j 4 ARCH=local VERSION="ssmp sdbg psmp pdbg"

But now i see around a ~5x decrease in performance for the newer version while also using the exact same input file. I am unsure what is causing this drop in performance. Could someone help me out with this?

Here is a zip file with the 2 calculations I ran.
quick_cp2k_tests.zip<https://github.com/cp2k/cp2k/files/13821115/quick_cp2k_tests.zip>

Kind regards,
Roel v/d Ven

**Comment by blah17** [comment]
Hi,

That did the trick. In fact it is now even slightly faster!
Thanks for the help! 

Kind regards,
Roel v/d Ven
