### ISSUE TITLE
v2024.1 build failure on Linux for Homebrew

### ISSUE THREAD

**Issue by p-linnane** [cp2k/cp2k#3200]
Hello 👋 . I'm a maintainer for the [Homebrew](https://brew.sh) project. While packaging v2024.1 of cp2k, we are encountering a failure with only our Linux build. It appears to be trying to download libgrpp despite us not enabling that feature. 
```
  ==================== Installing LIBGRPP ====================
  wget  --quiet https://www.cp2k.org/static/downloads/libgrpp-main-20231215.zip
  /tmp/cp2k-20240104-8029-fwyppc/cp2k-2024.1/tools/toolchain/scripts/tool_kit.sh: line 631: wget: command not found
  ERROR: (./scripts/stage3/install_libgrpp.sh) failed to download https://www.cp2k.org/static/downloads/libgrpp-main-20231215.zip
  ERROR: (./scripts/stage3/install_libgrpp.sh, line 39) Non-zero exit code detected.
```
Of note: wget isn't found because it is not installed unless actually required as a dependency. In this case, since we are not using libgrpp features, I would think that this wouldn't download at all. Any assistance here would be greatly appreciated.

Relates to https://github.com/Homebrew/homebrew-core/pull/158906

**Comment by abussy** [comment]
By default, the `libgrpp` library is installed with the toolchain in the newest release. To actively disable the feature, you should run the toolchain script with `--with-libgrpp=no`. Was that the case for you?

**Comment by oschuett** [comment]
@p-linnane, thanks a lot for taking care of the Homebrew package!

This might be a good time to try out our new CMake build system. We're planning to phase out the Makefile and the toolchain this year.

**Comment by p-linnane** [comment]
Adding `--with-libgrpp=no` worked. Thank you both for your help. I will look into moving over to CMake now that this version bump is unblocked.
