### ISSUE TITLE
Bug in printing MO in MD

### ISSUE THREAD

**Issue by tsaihsiaoyi** [cp2k/cp2k#3238]
In the recent #3232, by opening the `do_rotate` in [calculate_subspace_eigenvalues](https://github.com/cp2k/cp2k/blob/master/src/qs_scf_output.F#L325-L328) will change the original MO. It will seriously affect the stability of molecular dynamics with OT method. Set the PRINT MO in DFT section and running MD with OT method will reveal the problem. The temperature will rise unreasonably. Saving the `mo_coeff` as `mo_coeff_tmp` and reset it after writing MO would be a solution as I committed in 50b458891f30211e030c1ddb65c600bd9e3f077f. I may give a PR if this solution is accepted. Thanks!

**Comment by mkrack** [comment]
Thanks for the bug report. Please, could you check if #3239 will fix the bug?

**Comment by tsaihsiaoyi** [comment]
Thanks for the effort! This solution will definitely solve the problem of molecular dynamics, but I'm not so sure how much impact it will have on the MO printed. Is there any reason to use `calculate_subspce_eigenvalues` ​​at the beginning?

**Comment by mkrack** [comment]
Originally, the occupied MOs as available were printed. The call to `calculate_subspace_eigenvalues` should only be needed for the unoccupied MOs not yet available. The additional [call](https://github.com/cp2k/cp2k/commit/3e3e97baaaa2ad3527b8c647778527a5ff04dc64#diff-03b3061edbe741dc8c17260458db79750b0218b531142d87b770012078011ff8R332-R336) to `calculate_subspace_eigenvalues` for the occupied MOs introduced by #3230 was indeed a bug. Thanks again for reporting.

**Comment by tsaihsiaoyi** [comment]
In this case, this bug has been fixed. Thank you for your timely reply!
