### ISSUE TITLE
SGP refactoring broke SIRIUS

### ISSUE THREAD

**Issue by mtaillefumier** [cp2k/cp2k#3258]
A minor refactoring of the CP2K pseudo potentials lead to a corruption during the calculations of the atomic wave function. The problem is not present when cp2k is compiled with the commit before. 

The error happens here https://github.com/cp2k/cp2k/blob/577b676415f3d2d1924bda4bef9a238f96821cb1/src/sirius_interface.F#L408 but i have no idea why this is happening. The changes seems harmless.

**Comment by oschuett** [comment]
Linking to #3129, which contains https://github.com/cp2k/cp2k/commit/bbd14a5fe6b002419d127c8ec63e3062d934e058. 

@mtaillefumier could you elaborate a bit. All our tests are passing, including Address Sanitizer.

**Comment by mtaillefumier** [comment]
> Linking to #3129, which contains [bbd14a5](https://github.com/cp2k/cp2k/commit/bbd14a5fe6b002419d127c8ec63e3062d934e058).
> 
> @mtaillefumier could you elaborate a bit. All our tests are passing, including Address Sanitizer.

The regtests do not cover the case where CP2K pseudo are used with SIRIUS. 

This test case [N2.txt](https://github.com/cp2k/cp2k/files/14162318/N2.txt) does not work with cp2k/sirius and commit  bbd14a5, but works with the commit before. I do not know what is wrong with the code as the interface is not modified by the specified commit at all.

**Comment by mtaillefumier** [comment]
to illustrate the problem further, I printed some of the wave function values

before the commit

```
beta   1.2564438941344399E-012   4.0124181568721641E-011   3.0467832352444726E-010   1.2838619605467242E-009
 wavefunction  -6.0090862151493163E-016  -1.9189847432451659E-014  -1.4571588293696297E-013  -6.1402162446661590E-013
 wavefunction  -6.3267546532562017E-026  -6.4521902840425971E-023  -3.7202995299437783E-021  -6.6058917942688099E-020
```

after

```
beta   1.2564438941344399E-012   4.0124181568721641E-011   3.0467832352444726E-010   1.2838619605467242E-009
 wavefunction   6.4918700113020975E-167   2.0731603875831547E-165   1.5742303184534543E-164   6.6335353287434450E-164
 wavefunction   6.4918700113020975E-167   2.0731603875831547E-165   1.5742303184534543E-164   6.6335353287434450E-164

```

**Comment by oschuett** [comment]
Since the original values were already very small (1e-26), my first guess would be that this is a numerical issue.  Unfortunately, those are difficult to debug. I know of no other method than to run both version side-by-side and use WRITE statements to narrow down the culprit.

**Comment by mtaillefumier** [comment]
found the error. uninitialized variable.

**Comment by RMeli** [comment]
Fixed by https://github.com/cp2k/cp2k/pull/3261?

**Comment by mtaillefumier** [comment]
Oh yes. I will close it.

**Comment by oschuett** [comment]
It seems there is a remaining issue which was caught by the [pdbg test](https://dashboard.cp2k.org/archive/current-pdbg/commit_14e431119277e2f0aa53cf24ac09b5860de697e5.txt) and [macOS test](https://dashboard.cp2k.org/archive/darwin-gnu-arm64-psmp/commit_14e431119277e2f0aa53cf24ac09b5860de697e5.txt):
```
At line 400 of file /opt/cp2k/src/sirius_interface.F
Fortran runtime error: Index '3' of dimension 1 of array 'wfninfo' above upper bound of 2
```

**Comment by mtaillefumier** [comment]
Sorry about this. I forgot to remove the incriminated line. The problem should be fixed with https://github.com/cp2k/cp2k/pull/3265
