### ISSUE TITLE
RI-RPA quadrature points convergence

### ISSUE THREAD

**Issue by mbocus** [cp2k/cp2k#3267]
Dear CP2K users/developers,

We are testing RI-RPA (CP2K 2023.1) energy-only calculations on a dataset of similar structures, i.e. an isobutene molecule chemisorbed in the pores of a zeolite. We noticed that relatively similar structures present very different convergence behavior with respect to the number of quadrature points (see graph in attachment, each line corresponds to a certain structure with a numerical identifier). In appears that poor convergence is associated with a small gap for the minimax approximation (~0.1 for well-behaved structures and ~0.005 for the troublesome ones). Over a set of ~1000 structures, bad convergence happens for ~10 of them (at least these were the obvious ones). Is this an expected behavior and - if not - is there any way to foresee which structures might present this type of problem?

Thank you in advance, 
Massimo

[output_bad.txt](https://github.com/cp2k/cp2k/files/14258934/output_bad.txt)
[output_good.txt](https://github.com/cp2k/cp2k/files/14258935/output_good.txt)
[input.txt](https://github.com/cp2k/cp2k/files/14258936/input.txt)
[quadrature_points_results.pdf](https://github.com/cp2k/cp2k/files/14258937/quadrature_points_results.pdf)

**Comment by fstein93** [comment]
This behavior is to be expected. The accuracy of the minimax grid depends on the energy range, i.e. the quotient of the largest difference and the smallest one(=band gap). A larger range increases the error which is only overcome by a larger number of quadrature points. From my experience, the largest orbital energy difference is usually also much higher in cases of small band gaps (no proof for that).
There are some more aspects to consider:
Systems with small band gaps usually show stronger correlation effects requiring more advanced methods than RPA. This implies that RPA is less reliable for these systems anyways (except maybe from simple metals but then the convergence w.r.t. the number of quadrature points is poor anyways and might require larger super cells.
It might be necessary to employ a different reference than PBE such as meta-GGA functionals (SCAN, R2SCAN, TPSS) or hybrid functionals (HSE, PBE0) depending on what you can afford.

**Comment by mbocus** [comment]
Hi Frederick, 

Many thanks for the explanation. Does the band gap used for the minimax approximation come from the PBE calculation? Would that mean that for the problematic structures PBE predicts a very small bandgap? That would be surprising for me, as the system should be quite a strong insulator independently on the isobutene location in the unit cell.

**Comment by fstein93** [comment]
The orbital energies for the RPA calculation are always taken from the preceding SCF calculation. I do not know your test structures. If you consider chemisorbed molecules, you will expect bond-deformations, interaction between substrate and zeolithe, or maybe even a chemical reaction. The resulting structures might have small bandgaps even if your molecule is chemically stable. The actual number will depend on the functional in use. Please check also EPS_DEFAULT because QZ basis sets contain more diffuse functions requiring tighter thresholds. If the band gap is not significantly improving, then the functional might be a bad choice for your system.

**Comment by mbocus** [comment]
Understood, thank you very much for your help!

**Comment by fstein93** [comment]
Apparently, the issue was solved. Feel free to reopen it if needed.
