### ISSUE TITLE
Migration to `ctest`

### ISSUE THREAD

**Issue by LecrisUT** [cp2k/cp2k#3314]
I had a look on the `do_regtest.py`, and I would suggest to convert this script to native ctest, because:
- path to the appropriate executable is automatically resolved regardless of the build environment
- scheduling parallel tests are handled automatically after setting the `PROCESSORS` test property, i.e. it can account for `ctest`, `mpi`, and `openmp` parallelization
- `ctest` can reschedule the test execution order based on the previous test runtime cost
- scheduling based on gpu availability is also available (may require coding the gpu selection based on CMake environment variable)
- Allows the tests to be run both within the build environment, as well as after installation

Proposed migration procedure:
1. Migrate the unit tests to be called as `add_test`
2. Create a regression test wrapper (`cp2k_add_test`) that calls `cp2k` and sets appropriate regex evaluations: [`PASS_REGULAR_EXPRESSION`](https://cmake.org/cmake/help/latest/prop_test/PASS_REGULAR_EXPRESSION.html) [`SKIP_REGULAR_EXPRESSION`](https://cmake.org/cmake/help/latest/prop_test/SKIP_REGULAR_EXPRESSION.html) [`FAIL_REGULAR_EXPRESSION`](https://cmake.org/cmake/help/latest/prop_test/FAIL_REGULAR_EXPRESSION.html)
3. Add `cp2k_add_test` regression tests based on the folder structure
4. Add relevant test labels, e.g. `unit`, `regression`, `smoke`, etc.
5. Add the `PROCESSORS` property for parallelizing tests
5b. (optional) Add handling of `CTEST_RESOURCE_GROUP_*` to efficiently parallelize GPU tests as well
6. Phase out `do_regtest.py` depending on CMake migration

---

Another use-case for `do_regtest.py` is to perform individual test evaluation, i.e. passing the full executable path, test name and additional input variables, the script would run the test and evaluate the stdout and everything else.

**Comment by oschuett** [comment]
Thanks for the suggestion. I haven't really looked at ctest yet. As we're migrating to CMake we should presumably also integrate with ctest.

That being said, our `do_regtests` script has been refined for over 20 years and contains many bells and whistles that we have come to rely on. So, I don't think we can retire it anytime soon.

**Comment by LecrisUT** [comment]
> That being said, our `do_regtests` script has been refined for over 20 years and contains many bells and whistles that we have come to rely on. So, I don't think we can retire it anytime soon.

I don't suggest to completely retire it, just to gradually remove some functionalities out of it, as things are being covered by `ctest`, particularly the scheduling. I think it's still a perfectly valid choice to have `do_regtests` to wrap the `cp2k` execution and tests, but I think it should be considered more carefully on what is included in the python script beyond the basic functionality of performing regression tests (re: https://github.com/cp2k/cp2k/issues/2996)

**Comment by LecrisUT** [comment]
PS: Feel free to check [my template](https://github.com/LecrisUT/CMake-Template/tree/main/test) about a design for the `ctest` testsuite. It includes unit testing, regression testing, packaging tests, and example testing. If you want to discuss it in more details, let me know.

**Comment by LecrisUT** [comment]
Just saw that `CP2K_ENABLE_REGTESTS` makes it write files in the source folder. That is really bad and error prone in multi-build environments like when packaging and trying to build for multiple MPI environments. I understand that it was done to have minimal effect on the `do_regtest.py`, but still that creates dangerous setups for the end-user in order to accommodate the limitations of the test scripts.

**Comment by jpoto** [comment]
How is it going with the transition to ctest? 
Since the transition to CMake is planned and the paths change it requires a overhaul of  the do_regtest.py script for it to work. This could be combined with the transition to ctest.

**Comment by oschuett** [comment]
> How is it going with the transition to ctest?

Short answer: It's not ;-)

I simply don't see a compelling reason to adopt ctest. The `do_regtest.py` does everything we need and we [plan to extend](https://github.com/cp2k/cp2k/issues/2996) it.

However, I'll fix the issue of writing to the source tree, as raised by https://github.com/cp2k/cp2k/issues/3314#issuecomment-2067012155.

**Comment by LecrisUT** [comment]
I would *strongly* encourage not to reinvent the wheel when much of the complexity of `do_regtest.py` is handled already by `ctest`. Believe me that the parallelization and test scheduling of `ctest` is phenomenal, especially if you cache the test costs.

**Comment by jpoto** [comment]
I am looking onto the `CMake` build and testing. 
The executable is now in a different path, which `ctest` could take care of. 

As far as I can tell we cannot give the path of the executable to `do_regtest`, but it expects `arch` and `version`, which would need to be changed.

**Comment by oschuett** [comment]
> As far as I can tell we cannot give the path of the executable to do_regtest, but it expects arch and version, which would need to be changed.

Yes, my plan is to just pass the binary path to `do_regtest.py` instead of `arch` and `version`. 
Furthermore, I'd change the default of `--workbasedir` to the directory of the given binary.
What do you think? Do we need any other changes?

**Comment by jpoto** [comment]
I think this should be enough.

**Comment by oschuett** [comment]
> I would strongly encourage not to reinvent the wheel...

It's a judgment call. We made a conscious decision to invest in our own testing framework to have full customizability and are now enjoying a perfectly tailored solution.

> Believe me that the parallelization and test scheduling of ctest is phenomenal, especially if you cache the test costs.

That's a fair point. However, since we have lots of small tasks the scheduling is not a big concern for us. As a final touch, I [occasionally](https://github.com/cp2k/cp2k/pull/3647) re-order the test directories to run the slower ones first.

I think we are now well set to run regtests for CMake builds. Hence, I'm going to close this issue now.

**Comment by LecrisUT** [comment]
> That's a fair point. However, since we have lots of small tasks the scheduling is not a big concern for us.

That argument is completely inversed. Because `ctest` is aware of the processor needs for each test, it is *especially* well suited to schedule a myriad of small tests to *maximize* the workload throughout.

There are various other benefits:
- better integration with downstream, e.g. managing how many CPUs are made available including in shared environments
- native integration with unit tests executables or other frameworks like `Catch2`. There are plans for `Fortuno` to add similar interfaces like `Catch2` to automatically register tests
- basic junit output that can be used by other tools
- wider test coverage, e.g. testing if an example CMake project is buildable and executable, testing if the packaging and install commands were configured correctly
