### ISSUE TITLE
nvcc with cuda_toolkit 12.4 not support gcc versions later than 12

### ISSUE THREAD

**Issue by AntEffect** [cp2k/cp2k#3323]
![0a1f16da5adec7fd17dac0a77085156f](https://github.com/cp2k/cp2k/assets/12670263/6c8b3fa0-2bad-4ca0-98e1-e472c4484d3d)

But as default the script cp2k/tools/toolchain/install_cp2k_toolchain.sh will install gcc13.2.0 with cp2k(tag v2024.1).

Is there any solution?

**Comment by mkrack** [comment]
The script [install_cp2k_toolchain.sh](https://github.com/cp2k/cp2k/blob/master/tools/toolchain/install_cp2k_toolchain.sh) uses by default the [gcc compiler version of the system](https://github.com/cp2k/cp2k/blob/master/tools/toolchain/install_cp2k_toolchain.sh#L149). The flags `--with-gcc=install` and `--install-all` cause, however, an installation of the gcc compiler version 13.2.0.

**Comment by AntEffect** [comment]
Switched gcc version in [install_gcc.sh](https://github.com/cp2k/cp2k/blob/master/tools/toolchain/scripts/stage0/install_gcc.sh) from 13.2.0 to 12.2.0. It‘s OK now.

**Comment by mkrack** [comment]
Great, that you could solve the problem.
