### ISSUE TITLE
OpenMP variable `ngpts` in cp2k-2024.1/src/pw/pw_methods.F

### ISSUE THREAD

**Issue by 1234zou** [cp2k/cp2k#3327]
Hi, CP2K developers and users,

I encountered an OpenMP error during compiling CP2K (in the final `make` step):
```
/public/home/jxzou/software/cp2k-2024.1/src/pw/pw_methods.F(1738): error #6752: Since the OpenMP* DEFAULT(NONE) clause applies, the PRIVATE, SHARED, REDUCTION, FIRSTPRIVATE, or LASTPRIVATE attribute must be explicitly specified for every variable.   [NGPTS]
            DO gpt = 1, ngpts
------------------------^
/public/home/jxzou/software/cp2k-2024.1/src/pw/pw_methods.F(1750): error #6752: Since the OpenMP* DEFAULT(NONE) clause applies, the PRIVATE, SHARED, REDUCTION, FIRSTPRIVATE, or LASTPRIVATE attribute must be explicitly specified for every variable.   [NGPTS]
            DO gpt = 1, ngpts
------------------------^
```

My environment is Intel OneAPI 2021.1, Anaconda Python 3.11.7, gcc-9.2.0, openmpi-4.1.1, etc. And my compilation commands are
```
./install_cp2k_toolchain.sh --with-gcc=no --with-intel=system --with-cmake=system \
 --with-openmpi=system --with-openblas=no --math-mode=mkl --with-mkl=system \
 --with-scalapack=system --with-libint=system --with-fftw=install --with-libxc=system \
 --with-sirius=no --with-cosma=no --with-libvori=no -j 64

cp install/arch/* ../../arch/
source install/setup
cd ../..
make -j64 ARCH=local VERSION="ssmp psmp" >make.log 2>&1
```

I find that in the file `cp2k-2024.1/src/pw/pw_methods.F`, the OpenMP variable `ngpts` is not declared within `SHARED()` and such cases occur **12 times**. For example,
```
$OMP PARALLEL DO PRIVATE(gpt, l, m, n) DEFAULT(NONE) SHARED(c, pw, scale)
            DO gpt = 1, ngpts
               l = mapl(ghat(1, gpt)) + 1
               m = mapm(ghat(2, gpt)) + 1
               n = mapn(ghat(3, gpt)) + 1
               pw%cc(gpt) = scale*c(l, m, n)
            END DO
!$OMP END PARALLEL DO
```

Then I add `ngpts` into `SHARED()`, e.g. `SHARED(c, pw, scale, ngpts)` and compile CP2K again (from scratch), everything works normally.

My question is: are these modifications reasonable? If reasonable, would you please consider update them to the CP2K main branch?

Thank you very much.

**Comment by fstein93** [comment]
I think that this is a compiler bug. `ngpts` is defined by an `ASSOCIATED` construct which means that it is a mere shortcut, not an actual variable which means that you cannot make it a shared/private/... variable within OpenMP. In this case, the associate name is shared implicitly because it is defined outside of the OpenMP construct but apparently, the compiler does not catch this subtlety. Are you restricted to this compiler version or can you use a later one?

**Comment by 1234zou** [comment]
@fstein93 Hi, do you mean a newer Intel compiler?

I understand this is might be a compiler bug. But it does no harm that adding it into `SHARED()`, right? I want to make sure that my installation of CP2K is O.K. since I perform an energy calculation and the result is reproducible as well as correct.

**Comment by fstein93** [comment]
I do not know on what kind of machine you are working on, but as far as I can tell the latest available version of the Intel OneAPI is version 2024.0.1. For our own tests, we employ later versions of this compiler without any issues, so your observation is related to a bug of this compiler version.
Your suggested bugfix might work with your compiler but is considered a syntax error. This means you can apply your addition locally if you work with your compiler but we will not add it to the code because it is considered an error. If we want to workaround it to support your compiler, we need a different solution.

**Comment by oschuett** [comment]
For context, we encountered trouble with ASSOCIATE + OpenMP before (#2668) and ended up introducing [conv#c008](https://www.cp2k.org/conv#c008).

**Comment by fstein93** [comment]
It is case 1 of [my comment](https://github.com/cp2k/cp2k/issues/2668#issuecomment-1464529408). The compiler has this bug before version 2022 (which we are still testing). @1234zou Did the regtest suite pass with your modifications?
@oschuett Do you know how common this compiler is, i.e. is it worth working this bug around?

**Comment by 1234zou** [comment]
@fstein93 Sorry, I'm not sure about `regtest suite`. Is the following command OK?
```
./do_regtest.py --mpiranks 64 --ompthreads 1 --maxtasks 1 --num_gpus 0 \
 --mpiexec $HOME/software/openmpi-4.1.1/bin/mpiexec --smoketest \
 ARCH=local VERSION="psmp"
```
if I want to run only the first test of each directory. I will write the command above into a SLURM script with correct environment variables of CP2K.

**Comment by fstein93** [comment]
@1234zou Sorry for not being clear enough. I meant this command. You may also use `make -j <your number of CPUs> ARCH=local VERSION="psmp" test TESTOPTS="--smoketest"` instead.

**Comment by 1234zou** [comment]
Thank you for your quick response. There are 3 examples failed
```
cp2k-2024.1/regtesting/local/psmp/TEST-local-psmp-2024-03-21_22-41-50/QS/regtest-loc_powf/run.inp
cp2k-2024.1/regtesting/local/psmp/TEST-local-psmp-2024-03-21_22-41-50/QS/regtest-pod/helium-pbe-3A.inp
cp2k-2024.1/regtesting/local/psmp/TEST-local-psmp-2024-03-21_22-41-50/QS/regtest-lrigpw-2/2H2O_dpa_1.inp
```

Here is the content of the error file
```
Discovering programs ...
make[3]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
ifort: command line warning #10006: ignoring unknown option '-fc='
icc: command line warning #10006: ignoring unknown option '-cc='
make[3]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
make[3]: *** [test] Error 1
make[2]: *** [test] Error 2
make[1]: *** [psmp] Error 2
make: *** [test] Error 2
```

And here is the SLURM output file [slurm-2234947.zip](https://github.com/cp2k/cp2k/files/14697060/slurm-2234947.zip)

It seems that the error information is not related to my modifications.

**Comment by fstein93** [comment]
I also think that they are unrelated. So your modifications do work.

**Comment by 1234zou** [comment]
Great. Thanks a lot. I'll close this issue temporarily. I'm going to use this modified CP2K to perform computations. I'll try a more recent version of Intel compilers next week (and report that whether I still need to modify `pw_methods.F`).
