### ISSUE TITLE
Compilation cp2k on AMD EPYC 9654/9754 Using Intel oneAPI.

### ISSUE THREAD

**Issue by hongyi-zhao** [cp2k/cp2k#3332]
Do you know if anyone here has experience in compiling cp2k on AMD EPYC 9654/9754 using Intel oneAPI?

Regards,
Zhao

**Comment by oschuett** [comment]
Intel compilers generally work on AMD. IIRC, I once had an issue where `-march=native` would enable the wrong instruction set. Performance is another matter though, especially for MKL.

**Comment by hongyi-zhao** [comment]
> I once had an issue where -march=native would enable the wrong instruction set. 

Till now, I only tried to compile vasp, and changing `-xHost` to `-axCORE-AVX512` will do the trick.

> Performance is another matter though, especially for MKL.

Based on my testings, for the vasp case, it seems that performance is pretty good: AMD EPYC 9654 even defeated [Intel Xeon Platinum 8383C](https://www.cpu-world.com/CPUs/Xeon/Intel-Xeon%208383C.html).

But the compilation of cp2k is a quite complex task that I haven't tried yet. Therefore, I am asking here to anticipate potential challenges as I plan to purchase such a CPU, but I am unsure if I can successfully compile CP2K based on the Intel OneAPI toolchain.

See [here](https://www.vasp.at/forum/viewtopic.php?t=19453) for the related discussion.

**Comment by hongyi-zhao** [comment]
On the AMD partition of my supercomputer cluster, I saw the module file below, so for the issue here, it should be possible to compile cp2k in my case:

```shell
[scg7612@ln2%zc-m6 ~]$ module show cp2k/9.1-oneAPI.2022.1-plumed
-------------------------------------------------------------------
/public3/soft/modulefiles/cp2k/9.1-oneAPI.2022.1-plumed:

conflict        cp2k
module load     mpi/oneAPI/2022.1
prepend-path    PATH /public3/soft/cp2k/9.1-oneAPI.2022.1-plumed/exe/Linux-x86-64-intel-minimal
prepend-path    CP2K_DATA_DIR /public3/soft/cp2k/9.1-oneAPI.2022.1-plumed/exe/Linux-x86-64-intel-minimal/../../data
-------------------------------------------------------------------

```

**Comment by oschuett** [comment]
We do test several versions of the Intel compilers [regularly](https://dashboard.cp2k.org) - however on Intel CPUs.

Note that the new Intel Fortran compiler (ifx) is not yet able to build CP2K. See also [this wiki page](https://www.cp2k.org/dev:compiler_support) for a list of working compilers.

**Comment by hongyi-zhao** [comment]
See [here](https://www.amd.com/en/developer/zen-software-studio/applications/spack/hpc-applications-cp2k.html) for the AMD official guide.

**Comment by oschuett** [comment]
Thanks for writing that install guide. I'd like to add a backlink from cp2k.org, but I don't think we have a suitable page yet. Thinking about it, I believe there are a number of installation guides out there from the various vendors and centers.
