### ISSUE TITLE
 [CP2K:11656] list of supported compilers only shows trunk

### ISSUE THREAD

**Issue by juerghutter** [cp2k/cp2k#336]
https://www.cp2k.org/dev:compiler_support only shows the trunk support

It would be really helpful to have a version of this page for the latest official released version.

BGCook@lbl.gov

**Comment by alazzaro** [comment]
That makes sense. I will add this information for the next release. Anyway, I would assume that a compiler version which is valid for the trunk is also valid for the latest CP2K release.

**Comment by oschuett** [comment]
We could make copying the table a task on our [release checklist](https://www.cp2k.org/dev:release_checklist).

**Comment by alazzaro** [comment]
I have updated the table, showing the "last commit tested" and highlighting what versions are currently tested in the dashboard. I think this is enough to close the issue (official release can be taken from the github commits). Please reopen if you have comments.
