### ISSUE TITLE
RI_RPA_grad_MP2_H2O_HF_PBE_ADMM.inp tested on AMD Zen4 cpu with mpich and mkl reports error

### ISSUE THREAD

**Issue by alas-go** [cp2k/cp2k#3396]
[errors_slow_tests.txt](https://github.com/cp2k/cp2k/files/15206354/errors_slow_tests.txt)

Dears.

RI_RPA_grad_MP2_H2O_HF_PBE_ADMM.inp tested on AMD Zen4 cpu with mpich and mkl reports error and other three tests show slow speed as in attachments.

**Comment by fstein93** [comment]
You can ignore the failing and too slow tests.
Change of libraries, compilers, and CPUs/GPUs change the numerical behavior and thus the results. The thresholds we set are chosen to match the configurations we run, yours is not included. Thus, you can ignore the wrong result of the regtest. Furthermore, a deviation of ca. 1E-7 Hartree is negligible anyways. The regtests are designed to run fast, not accurate.
The indicated slow tests are also not to worry, it is a measure for us to accelerate the given tests to save our own ressources for the test infrastructure. We also have a list of very slow tests which would be raised on our infrastructure as well.
