### ISSUE TITLE
CMake VERSION_MAJOR variable not updated for 2024.1 release

### ISSUE THREAD

**Issue by mbanck** [cp2k/cp2k#3397]
Maybe I am missing something, but I assume the `VERSION` in
```
  VERSION ${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}
```
should correspond to the release version, i.e. 2024.1 as of writing. However, `CMakeLists.txt` still has this for `VERSION_MAJOR`:

```
set(VERSION_MAJOR 23)
```
Is the comment directly below it (¨anything above 12 is to indicate that it is devel-branch. The git hash commit is the only important information to give. It is retrieved few lines below.") mean to imply that `VERSION_MAJOR` is irrelevant, or does this apply (as I assume) to `VERSION_MINOR` directly below it)?

**Comment by oschuett** [comment]
Thanks for flagging! I wasn't aware of this. In the past our authoritative version info was at: https://github.com/cp2k/cp2k/blob/b1f098bdf757a0d911df37584392ac41aeb8a328/src/cp2k_info.F#L40

I'd suggest we just remove the info from the CMakefile. What do you think @mtaillefumier?

**Comment by mtaillefumier** [comment]
I will argue that the source code should take this information from the build system not the other way around. It is easy to create a version.h and include that in the source code. All projects do that. Other option generate the string with cmake and include it during compilation time.

**Comment by mtaillefumier** [comment]
Another argument for doing this is that cmake module file uses the version information as well.

**Comment by oschuett** [comment]
Unfortunately, we can't switch to a `version.h` immediately because we're still relying on the old Makefile build system. So for now we'll have to keep the versions in sync.
