### ISSUE TITLE
found an unknown keyword GLOBAL in section __ROOT__

### ISSUE THREAD

**Issue by mikiefromhell** [cp2k/cp2k#3407]
Hello everyone! I am trying to run a geometry optimization on a system with 64 atoms of molten Al and 1 CO2 molecule.
I am not quite sure why I am getting this error - could it be that I did not specify a temperature, and CP2K is struggling to optimize the geometry of solid Al? I ran a tutorial file with the same syntax (except for the file directories, the coordinates and basis sets), and that ran successfully. Thank you kindly for your help!

Here is my input file:

`@SET SYSTEM run-1H2O-GOPT
@SET LIBDIR /shared/centos7/cp2k/cp2k-6.1.0/data/

GLOBAL
  PROJECT ${SYSTEM}
  RUN_TYPE GEO_OPT
  PRINT_LEVEL LOW
  #SAVE_MEM T #commented out TEST
&END GLOBAL

&FORCE_EVAL
  METHOD QuickStep
  &DFT
    BASIS_SET_FILE_NAME ${LIBDIR}/GTH_BASIS_SETS
    POTENTIAL_FILE_NAME ${LIBDIR}/GTH_POTENTIALS
    CHARGE 0
    &MGRID
      CUTOFF 280
      #COMMENSURATE #commented out TEST
    &END MGRID
    &SCF
      #MAX_SCF 50 #commented out TEST
      EPS_SCF 1e-06
      #SCF_GUESS ATOMIC #commented out TEST 
      #&OUTER_SCF #commented out TEST 
        #MAX_SCF 50 #commented out TEST 
        #EPS_SCF 1e-05 #commented out TEST 
    &END SCF
    &XC
      &XC_FUNCTIONAL BLYP
      &END XC_FUNCTIONAL
      &XC_GRID
        XC_DERIV       SPLINE2_smooth
        XC_SMOOTH_RHO  NN10
      &END XC_GRID
    &END XC
  &END DFT
  &SUBSYS
    &CELL
    A      15.0000000       0.0000000       0.0000000
    B       0.0000000      15.0000000       0.0000000
    C       0.0000000       0.0000000      15.0000000
    &END CELL
    &COORD
    Al       0.00000      0.00000      0.00000
    Al       7.50000      3.75000      2.50000
    Al       3.75000      0.00000      2.50000
    Al       3.75000      3.75000      0.00000
    Al       7.50000      0.00000      0.00000
    Al       7.50000      7.50000      0.00000
    Al       7.50000      0.00000      5.00000
    Al       0.00000      7.50000      0.00000
    Al       0.00000      7.50000      5.00000
    Al       0.00000      0.00000      5.00000
    Al       7.50000      7.50000      5.00000
    Al       0.00000      3.75000      2.50000
    Al       3.75000      7.50000      2.50000
    Al       3.75000      3.75000      5.00000
    Al       7.50000      0.00000      0.00000
    Al      15.00000      3.75000      2.50000
    Al      11.25000      0.00000      2.50000
    Al      11.25000      3.75000      0.00000
    Al      15.00000      0.00000      0.00000
    Al      15.00000      7.50000      0.00000
    Al      15.00000      0.00000      5.00000
    Al       7.50000      7.50000      0.00000
    Al       7.50000      7.50000      5.00000
    Al       7.50000      0.00000      5.00000
    Al      15.00000      7.50000      5.00000
    Al       7.50000      3.75000      2.50000
    Al      11.25000      7.50000      2.50000
    Al      11.25000      3.75000      5.00000
    Al       0.00000      7.50000      0.00000
    Al       7.50000     11.25000      2.50000
    Al       3.75000      7.50000      2.50000
    Al       3.75000     11.25000      0.00000
    Al       7.50000      7.50000      0.00000
    Al       7.50000     15.00000      0.00000
    Al       7.50000      7.50000      5.00000
    Al       0.00000     15.00000      0.00000
    Al       0.00000     15.00000      5.00000
    Al       0.00000      7.50000      5.00000
    Al       7.50000     15.00000      5.00000
    Al       0.00000     11.25000      2.50000
    Al       3.75000     15.00000      2.50000
    Al       3.75000     11.25000      5.00000
    Al       7.50000      7.50000      0.00000
    Al      15.00000     11.25000      2.50000
    Al      11.25000      7.50000      2.50000
    Al      11.25000     11.25000      0.00000
    Al      15.00000      7.50000      0.00000
    Al      15.00000     15.00000      0.00000
    Al      15.00000      7.50000      5.00000
    Al       7.50000     15.00000      0.00000
    Al       7.50000     15.00000      5.00000
    Al       7.50000      7.50000      5.00000
    Al      15.00000     15.00000      5.00000
    Al       7.50000     11.25000      2.50000
    Al      11.25000     15.00000      2.50000
    Al      11.25000     11.25000      5.00000
    Al       0.00000      0.00000      5.00000
    Al       7.50000      3.75000      7.50000
    Al       3.75000      0.00000      7.50000
    Al       3.75000      3.75000      5.00000
    Al       7.50000      0.00000      5.00000
    Al       7.50000      7.50000      5.00000
    Al       7.50000      0.00000     10.00000
    Al       0.00000      7.50000      5.00000
    Al       0.00000      7.50000     10.00000
    Al       0.00000      0.00000     10.00000
    Al       7.50000      7.50000     10.00000
    Al       0.00000      3.75000      7.50000
    Al       3.75000      7.50000      7.50000
    Al       3.75000      3.75000     10.00000
    Al       7.50000      0.00000      5.00000
    Al      15.00000      3.75000      7.50000
    Al      11.25000      0.00000      7.50000
    Al      11.25000      3.75000      5.00000
    Al      15.00000      0.00000      5.00000
    Al      15.00000      7.50000      5.00000
    Al      15.00000      0.00000     10.00000
    Al       7.50000      7.50000      5.00000
    Al       7.50000      7.50000     10.00000
    Al       7.50000      0.00000     10.00000
    Al      15.00000      7.50000     10.00000
    Al       7.50000      3.75000      7.50000
    Al      11.25000      7.50000      7.50000
    Al      11.25000      3.75000     10.00000
    Al       0.00000      7.50000      5.00000
    Al       7.50000     11.25000      7.50000
    Al       3.75000      7.50000      7.50000
    Al       3.75000     11.25000      5.00000
    Al       7.50000      7.50000      5.00000
    Al       7.50000     15.00000      5.00000
    Al       7.50000      7.50000     10.00000
    Al       0.00000     15.00000      5.00000
    Al       0.00000     15.00000     10.00000
    Al       0.00000      7.50000     10.00000
    Al       7.50000     15.00000     10.00000
    Al       0.00000     11.25000      7.50000
    Al       3.75000     15.00000      7.50000
    Al       3.75000     11.25000     10.00000
    Al       7.50000      7.50000      5.00000
    Al      15.00000     11.25000      7.50000
    Al      11.25000      7.50000      7.50000
    Al      11.25000     11.25000      5.00000
    Al      15.00000      7.50000      5.00000
    Al      15.00000     15.00000      5.00000
    Al      15.00000      7.50000     10.00000
    Al       7.50000     15.00000      5.00000
    Al       7.50000     15.00000     10.00000
    Al       7.50000      7.50000     10.00000
    Al      15.00000     15.00000     10.00000
    Al       7.50000     11.25000      7.50000
    Al      11.25000     15.00000      7.50000
    Al      11.25000     11.25000     10.00000
    Al       0.00000      0.00000     10.00000
    Al       7.50000      3.75000     12.50000
    Al       3.75000      0.00000     12.50000
    Al       3.75000      3.75000     10.00000
    Al       7.50000      0.00000     10.00000
    Al       7.50000      7.50000     10.00000
    Al       8.37531      3.33323     14.03022
    Al       0.00000      7.50000     10.00000
    Al       0.00000      7.50000     15.00000
    Al       0.00000      0.00000     15.00000
    Al       7.50000      7.50000     15.00000
    Al       0.00000      3.75000     12.50000
    Al       3.75000      7.50000     12.50000
    Al       3.75000      3.75000     15.00000
    Al       7.50000      0.00000     10.00000
    Al      15.00000      3.75000     12.50000
    Al      11.25000      0.00000     12.50000
    Al      11.25000      3.75000     10.00000
    Al      15.00000      0.00000     10.00000
    Al      15.00000      7.50000     10.00000
    Al      15.00000      0.00000     15.00000
    Al       7.50000      7.50000     10.00000
    Al       7.50000      7.50000     15.00000
    Al       7.50000      0.00000     15.00000
    Al      15.00000      7.50000     15.00000
    Al       7.50000      3.75000     12.50000
    Al      11.25000      7.50000     12.50000
    Al      11.25000      3.75000     15.00000
    Al       0.00000      7.50000     10.00000
    Al       7.50000     11.25000     12.50000
    Al       3.75000      7.50000     12.50000
    Al       3.75000     11.25000     10.00000
    Al       7.50000      7.50000     10.00000
    Al       7.50000     15.00000     10.00000
    Al       7.50000      7.50000     15.00000
    Al       0.00000     15.00000     10.00000
    Al       0.00000     15.00000     15.00000
    Al       0.00000      7.50000     15.00000
    Al       7.50000     15.00000     15.00000
    Al       0.00000     11.25000     12.50000
    Al       3.75000     15.00000     12.50000
    Al       3.75000     11.25000     15.00000
    Al       7.50000      7.50000     10.00000
    Al      15.00000     11.25000     12.50000
    Al      11.25000      7.50000     12.50000
    Al      11.25000     11.25000     10.00000
    Al      15.00000      7.50000     10.00000
    Al      15.00000     15.00000     10.00000
    Al      15.00000      7.50000     15.00000
    Al       7.50000     15.00000     10.00000
    Al       7.50000     15.00000     15.00000
    Al       7.50000      7.50000     15.00000
    Al      15.00000     15.00000     15.00000
    Al       7.50000     11.25000     12.50000
    Al      11.25000     15.00000     12.50000
    Al      11.25000     11.25000     15.00000
    C        6.31336      7.90494      6.67474
    O        7.25666      8.30983      7.29041
    O        5.37005      7.50005      6.05906
    UNIT angstrom
    &END COORD
    &KIND Al
        ELEMENT Al
        BASIS_SET SZV-GTH
        POTENTIAL GTH-PBE-q3
    &END KIND
    &KIND C
        ELEMENT C
        BASIS_SET SZV-GTH
        POTENTIAL GTH-PBE-q4
    &END KIND
    &KIND O
        ELEMENT O
        BASIS_SET SZV-GTH
        POTENTIAL GTH-PBE-q6
    &END KIND
  &END SUBSYS
&END FORCE_EVAL`

And here is the error that I am getting:

` --------------------------------------------------------------------------
[[2842,0],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:
Module: OpenFabrics (openib)
  Host: c0229
Another transport will be used instead, although this may result in
lower performance.
NOTE: You can disable this warning by setting the MCA parameter
btl_base_warn_component_unused to 0.
--------------------------------------------------------------------------
 Possible matches for unknown keyword 
 GLOBAL
   subsection GLOBAL in section %__ROOT__ score:  54
   enum GLOBAL in section %__ROOT__%MOTION%MD%THERMOSTAT for keyword REGION score:  44
   enum GLOBAL in section %__ROOT__%MOTION%MD%SHELL%THERMOSTAT for keyword REGION score:  44
   enum GLOBAL in section %__ROOT__%MOTION%MD%ADIABATIC_DYNAMICS%THERMOSTAT_FAST for keyword REGION score:  
44
   enum GLOBAL in section %__ROOT__%MOTION%MD%ADIABATIC_DYNAMICS%THERMOSTAT_SLOW for keyword REGION score:  
44
 *******************************************************************************
 *   ___                                                                       *
 *  /   \                                                                      *
 * [ABORT]                                                                     *
 *  \___/           found an unknown keyword GLOBAL in section __ROOT__        *
 *    |                                                                        *
 *  O/|                                                                        *
 * /| |                                                                        *
 * / \                                               input/input_parsing.F:246 *
 *******************************************************************************
 ===== Routine Calling Stack ===== 
            2 section_vals_parse
            1 read_input
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.
NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
In: PMI_Abort(1, N/A)
slurmstepd: error: *** STEP 42339098.0 ON c0229 CANCELLED AT 2024-05-08T10:11:40 ***
srun: Job step aborted: Waiting up to 602 seconds for job step to finish.
srun: error: c0229: task 0: Killed`

**Comment by fstein93** [comment]
Your line with `GLOBAL` must be `&GLOBAL`. Without the ampersand, it is interpreted as a keyword, with as a section.

**Comment by mikiefromhell** [comment]
Thank you, @fstein93 !

I ended up changing my input file a bit, and I am now getting a geometry/max_spline error for this:

```
@SET SYSTEM GOPT_Al_CO2_C1
@SET LIBDIR /shared/centos7/cp2k/cp2k-6.1.0/data/

&GLOBAL
  RUN_TYPE GEO_OPT
  PRINT_LEVEL LOW
&END GLOBAL

&FORCE_EVAL
  METHOD QuickStep
  &DFT
    BASIS_SET_FILE_NAME ${LIBDIR}/GTH_BASIS_SETS
    POTENTIAL_FILE_NAME ${LIBDIR}/GTH_POTENTIALS
    CHARGE 0
    &MGRID
      CUTOFF 280
      #COMMENSURATE #commented out TEST
    &END MGRID
    &SCF
      #MAX_SCF 50 #commented out TEST
      EPS_SCF 1e-06
      #SCF_GUESS ATOMIC #commented out TEST 
      #&OUTER_SCF #commented out TEST 
        #MAX_SCF 50 #commented out TEST 
        #EPS_SCF 1e-05 #commented out TEST 
    &END SCF
    &XC
      &XC_FUNCTIONAL BLYP
      &END XC_FUNCTIONAL
      &XC_GRID
        XC_DERIV       SPLINE2_smooth
        XC_SMOOTH_RHO  NN10
      &END XC_GRID
    &END XC
  &END DFT
  &SUBSYS #bigger because Al's overlap due to periodicity
    &CELL
    A      25.0000000       0.0000000       0.0000000
    B       0.0000000      25.0000000       0.0000000
    C       0.0000000       0.0000000      25.0000000
    PERIODIC  XYZ
    MULTIPLE_UNIT_CELL  1 1 1
    &END CELL
    &COORD
    Al       1.34549      1.74126      1.77703
    Al      11.34549      6.74126     11.77703
    Al       6.34549      1.74126     11.77703
    Al       6.34549      6.74126      1.77703
    Al      11.34549      1.74126      1.77703
    Al      11.34549     11.74126      1.77703
    Al      11.34549      1.74126     21.77703
    Al       1.34549     11.74126      1.77703
    Al       1.34549     11.74126     21.77703
    Al       2.50817      0.80609     18.92015
    Al      11.34549     11.74126     21.77703
    Al       1.34549      6.74126     11.77703
    Al       6.34549     11.74126     11.77703
    Al       6.34549      6.74126     21.77703
    Al       1.34549     11.74126      1.77703
    Al      11.34549     16.74126     11.77703
    Al       6.34549     11.74126     11.77703
    Al       6.34549     16.74126      1.77703
    Al      11.34549     11.74126      1.77703
    Al      11.34549     21.74126      1.77703
    Al      11.34549     11.74126     21.77703
    Al       1.34549     21.74126      1.77703
    Al       1.34549     21.74126     21.77703
    Al       1.34549     11.74126     21.77703
    Al      11.34549     21.74126     21.77703
    Al       1.34549     16.74126     11.77703
    Al       6.34549     21.74126     11.77703
    Al       6.34549     16.74126     21.77703
    Al      11.34549      1.74126      1.77703
    Al      21.34549      6.74126     11.77703
    Al      16.34549      1.74126     11.77703
    Al      16.34549      6.74126      1.77703
    Al      21.34549      1.74126      1.77703
    Al      21.34549     11.74126      1.77703
    Al      21.34549      1.74126     21.77703
    Al      11.34549     11.74126      1.77703
    Al      11.34549     11.74126     21.77703
    Al      11.34549      1.74126     21.77703
    Al      21.34549     11.74126     21.77703
    Al      11.34549      6.74126     11.77703
    Al      16.34549     11.74126     11.77703
    Al      16.34549      6.74126     21.77703
    Al      11.34549     11.74126      1.77703
    Al      21.34549     16.74126     11.77703
    Al      16.34549     11.74126     11.77703
    Al      16.34549     16.74126      1.77703
    Al      21.34549     11.74126      1.77703
    Al      21.34549     21.74126      1.77703
    Al      21.34549     11.74126     21.77703
    Al      11.34549     21.74126      1.77703
    Al      11.34549     21.74126     21.77703
    Al      11.34549     11.74126     21.77703
    Al      21.34549     21.74126     21.77703
    Al      11.34549     16.74126     11.77703
    Al      16.34549     21.74126     11.77703
    Al      16.34549     16.74126     21.77703
    Al       1.70331      7.44861      7.83571
    Al       0.63393     14.72032      9.64093
    Al       5.97846      2.68566     11.07462
    Al       6.58830      1.54189     15.07796
    Al       1.40469     10.36359      9.06441
    Al       8.20151      2.37425     16.86446
    Al       5.43465      3.15803     16.17498
    Al       9.43969      0.71737     10.38646

    UNIT angstrom
    &END COORD
    &KIND Al
        ELEMENT Al
        BASIS_SET SZV-GTH
        POTENTIAL GTH-PBE-q3
    &END KIND
    &KIND C
        ELEMENT C
        BASIS_SET SZV-GTH
        POTENTIAL GTH-PBE-q4
    &END KIND
    &KIND O
        ELEMENT O
        BASIS_SET SZV-GTH
        POTENTIAL GTH-PBE-q6
    &END KIND
  &END SUBSYS
&END FORCE_EVAL

&END
```

This is the error:
```
 A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: c0221
Another transport will be used instead, although this may result in
lower performance.
NOTE: You can disable this warning by setting the MCA parameter
btl_base_warn_component_unused to 0.
--------------------------------------------------------------------------
 DBCSR| Multiplication driver                                               XSMM
 DBCSR| Multrec recursion limit                                              512
 DBCSR| Multiplication stack size                                           1000
 DBCSR| Maximum elements for images                                    UNLIMITED
 DBCSR| Multiplicative factor virtual images                                   1
 DBCSR| Multiplication size stacks                                             3
 DBCSR| Number of 3D layers                                               SINGLE
 DBCSR| Use MPI memory allocation                                              T
 DBCSR| Use RMA algorithm                                                      F
 DBCSR| Use Communication thread                                               T
 DBCSR| Communication thread load                                             60
 ***** ** ***  *** **   PROGRAM STARTED ON                                 c0221
 **    ****   ******    PROGRAM STARTED BY                             benazzi.m
 ***** **    ** ** **   PROGRAM PROCESS ID                                 26389
  **** **  *******  **  PROGRAM STARTED IN             /home/benazzi.m/CP2K/Al64
 CP2K| version string:                                          CP2K version 6.1
 CP2K| source code revision number:                                    svn:18464
 CP2K| cp2kflags: omp libint fftw3 libxc parallel mpi3 scalapack xsmm libderiv_m
 CP2K|            ax_am1=5 libint_max_am=6
 CP2K| is freely available from                            https://www.cp2k.org/
 CP2K| Program compiled at                          Thu Dec  6 14:46:17 EST 2018
 CP2K| Program compiled on                                                 c0004
 CP2K| Program compiled for                                                local
 CP2K| Data directory path                  /shared/centos7/cp2k/cp2k-6.1.0/data
 CP2K| Input file name                    /home/benazzi.m/CP2K/Al64/Al64_GOPT.in
 GLOBAL| Force Environment number                                              1
 GLOBAL| Basis set file name            /shared/centos7/cp2k/cp2k-6.1.0/data//GT
 GLOBAL| Potential file name            /shared/centos7/cp2k/cp2k-6.1.0/data//GT
 GLOBAL| MM Potential file name                                     MM_POTENTIAL
 GLOBAL| Coordinate file name                                      __STD_INPUT__
 GLOBAL| Method name                                                        CP2K
 GLOBAL| Project name                                                    PROJECT
 GLOBAL| Preferred FFT library                                             FFTW3
 
 
 GLOBAL| Preferred diagonalization lib.                                       SL
 GLOBAL| Run type                                                        GEO_OPT
 GLOBAL| All-to-all communication in single precision                          F
 GLOBAL| FFTs using library dependent lengths                                  F
 GLOBAL| Global print level                                                  LOW
 GLOBAL| Total number of message passing processes                             1
 GLOBAL| Number of threads for this process                                    8
 GLOBAL| This output is from process                                           0
 GLOBAL| CPU model name :  Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
 MEMORY| system memory details [Kb]
 MEMORY|                        rank 0           min           max       average
 MEMORY| MemTotal            131141092     131141092     131141092     131141092
 MEMORY| MemFree               8444176       8444176       8444176       8444176
 MEMORY| Buffers                     0             0             0             0
 MEMORY| Cached              114378392     114378392     114378392     114378392
 MEMORY| Slab                   928648        928648        928648        928648
 MEMORY| SReclaimable           732488        732488        732488        732488
 MEMORY| MemLikelyFree       123555056     123555056     123555056     123555056
 WARNING| Particles:      51     25 at distance [au]:     0.00000000 less than:      0.01889726; increase EM
AX_SPLINE.
*******************************************************************************
 *   ___                                                                       *
 *  /   \                                                                      *
 * [ABORT]                                                                     *
 *  \___/                GEOMETRY wrong or EMAX_SPLINE too small!              *
 *    |                                                                        *
 *  O/|                                                                        *
 * /| |                                                                        *
 * / \                                               fist_neighbor_lists.F:607 *
 *******************************************************************************
 ===== Routine Calling Stack ===== 
            7 build_neighbor_lists
            6 build_fist_neighbor_lists
            5 topology_generate_bond_3
            4 topology_generate_bond
            3 connectivity_control
            2 topology_control
            1 CP2K
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.
NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
In: PMI_Abort(1, N/A)
slurmstepd: error: *** STEP 42342022.0 ON c0221 CANCELLED AT 2024-05-08T14:44:19 ***
srun: Job step aborted: Waiting up to 602 seconds for job step to finish.
srun: error: c0221: task 0: Killed
```

I got that error with the previous input file as well, and then I got the suggestion to make sure I did not have any atoms on the edges due to the periodic condition I applied, but it is still giving that error. Could anybody suggest a fix?

**Comment by fstein93** [comment]
Did you check the geometry? There is one atom pair with a distance of 1.2 A which is less than the atomic radius of aluminum in its fcc structure. Is this intended?
I also recommend you to post your question in the CP2K user group. The github issues are mainly meant for development-related issues and I am not an expert with force fields methods.

**Comment by mikiefromhell** [comment]
Thank you, @fstein93 !
It was not intended and I fixed it now, but I am still getting the same error:
WARNING| Particles:      51     25 at distance [au]:     0.00000000 less than:      0.01889726; increase EMAX_SPLINE

The particles are not on the edge of the unit cell, so I do not think it is because of periodic conditions. I will post there, thank you!

**Comment by mkrack** [comment]
The issue appears to be resolved by this [CP2K forum conversation](https://groups.google.com/g/cp2k/c/fom2F3QYuuI/m/z6sGwMKwBQAJ).
