### ISSUE TITLE
Building the manual often stops (OOM?)

### ISSUE THREAD

**Issue by fstein93** [cp2k/cp2k#3474]
If I build the manual according to the README in docs/, Make often returns with error 137 (probably OOM). Rerunning `make html` apparently finished building the manual. Testing parts of the manual works as expected.
I am building on Ubuntu22 on WSL2, my system has ca. 12 GB memory available which is sufficient to build CP2K with all processes without running out of memory.

**Comment by oschuett** [comment]
12 GB might not be enough😬 At GCP we're running this on an [t2d-standard-32](https://cloud.google.com/compute/docs/general-purpose-machines#t2d_machine_types) instance with 128 GB.

I believe the problem is that Sphinx reads all pages into memory and we have *a lot* of pages. I already reduced the pages by inlining the XC functionals. There might be some more optimizations we could do in Sphinx. I haven't looked into that yet.

**Comment by fstein93** [comment]
I have just checked considering the shared sections of which I am aware of
- &HF is used in each &XC section and independently by &RI_RPA (1.2 MiB each, 270 files)
- &XC is used by FORCE_EVAL%DFT, ATOM, FORCE_EVAL%PROPERTIES%TDDFPT, FORCE_EVAL%DFT%ENERGY_CORRECTION, FORCE_EVAL%DFT%TDDFPT (will be removed somewhen later), FORCE_EAL%DFT%KG_METHOD (10 MiB each, 2500 files)
- &SCF is used in FORCE_EVAL%DFT and FORCE_EVAL%DFT%XAS (2.87 MiB, 2389 files)
- &XC_FUNCTIONAL is used in &XC and FORCE_EVAL%DFT%XAS_TDP%KERNEL (60 KiB, 233 files)
If one could merge them somehow, the manual could be shrunken down a bit.

**Comment by oschuett** [comment]
You're right that we have some duplicate sections. However, I think it affects only a few files. The entire input reference consists of 2471 Markdown files.

Furthermore, I don't think there is a way to dedup those pages for Sphinx without distorting the clear structure of the resulting html pages.

We may want to consider to refactor the actual input structure, but that's a different discussion.

As for the manual, I think we just have to live with the build time for now. The CI run finishes in about 25 minutes, which is comparable to our sdbg run.

For local development one does not need to include the (full) input reference. I've added this as a tip to the README.
