### ISSUE TITLE
FFTW fails with non-default FFTW_PLAN_TYPE

### ISSUE THREAD

**Issue by fstein93** [cp2k/cp2k#3491]
#2686 apparently introduced a bug such that calculations fail if FFTW_PLAN_TYPE has a different value than ESTIMATE (default) and FFTW3 tries to import a wisdom file. Currently, there are at least two bugs, one is an incorrect conversion of Fortran characters to C strings (easy to fix) but still, CP2K fails if FFTW3 attempts to import a wisdom file. Exporting wisdom does work after fixing the conversion issue locally.

The current workaround is to use ESTIMATE mode and not reading from a wisdom file. This is usual not a performance issue for 3D periodic systems because they are usually dominated by grid operations and/or DBCSR.

Currently, I cannot reproduce the issue with a simple CP2K-independent tester.

**Comment by fstein93** [comment]
After merging the PR, wisdom files created during a CP2K run are still not accessible. I have no idea why and I am also not able to reproduce it without CP2K.

**Comment by oschuett** [comment]
Some random thoughts:
To start, I'd add an explicit interface with `BIND(C)` just to be sure.
Then I'd write a simple C program to try and read the wisdom file created by CP2K.
Finally, the file is written only by the first rank, but read by all ranks. Maybe there is an issue with the network filesystem?

**Comment by fstein93** [comment]
I have just retried with the current master and FFTW small Fortran test code I wrote for that purpose a few days ago. Now, it does work. I am not sure why it didn't work before. (I usually run small tests on my notebook with Ubuntu@WSL2)

**Comment by fstein93** [comment]
Apparently, I was already too tired last night. I have run several tests:
1) I can run the master trunk if the wisdom file was created by fftw-wisdom (plan type: exhaustive) no matter the plan type used by CP2K. I just copied the created file to my directory and set the path accordingly.
2) Wisdom files created during a CP2K run cannot be imported again no matter the plan type if CP2K has write access to the wisdom file. (I reran the input file with the same executable.
3) If the wisdom file is read-only (I moved it to its default path /etc/fftw/wisdom), then the code does not fail no matter the plan type set in the input file or how the wisdom file was created (by CP2K or by fftw-wisdom).

With my small test code resembling the structure of CP2K and the different calls, this issues do no exist.

This behavior suggests, that the way we call the import routine now is correct.

**Comment by fstein93** [comment]
Here is my test code for reference
[fftw_test.tar.gz](https://github.com/user-attachments/files/15942952/fftw_test.tar.gz)

**Comment by oschuett** [comment]
> Wisdom files created during a CP2K run cannot be imported again ...

So, it still doesn't work properly?

I really think we should have an explicit interface for calling those C functions. For example, I'm not sure if `CHARACTER(LEN=:, KIND=C_CHAR), ALLOCATABLE` can be passed directly as a `char *`.

**Comment by fstein93** [comment]
> I really think we should have an explicit interface for calling those C functions. For example, I'm not sure if `CHARACTER(LEN=:, KIND=C_CHAR), ALLOCATABLE` can be passed directly as a `char *`.

Our FFTW3 interface module implements an explicit interface via `fftw3.f03`. The FFTW3 manual just asks to pass the filename as C_CHAR (https://www.fftw.org/fftw3_doc/Wisdom-File-Export_002fImport-from-Fortran.html, we obviously need a conversion). On my notebook, it does not matter whether I pass the array as `CHARACTER(LEN=:, KIND=C_CHAR), ALLOCATABLE` or as `CHARACTER(C_CHAR), DIMENSION(:), ALLOCATABLE`. The second version might be preferred.

Nevertheless, I have no issues with importing wisdom from external sources.

I have just checked the first lines of my wisdom files. I have found that the one created by fftw-wisdom (1836 plans) and my test file (8 plans), match each other, but they do not the one created by CP2K. As soon as I replace the header line of the file created by CP2K with the one by fftw-wisdom/my test file, CP2K can read the wisdom file. Thus, somehow, FFTW screws up the header lines with CP2K although I use exactly the same FFTW3 installation (the one of CP2K's toolchain). I have just contacted the developers of FFTW3 for some advice.

**Comment by fstein93** [comment]
Matteo Frigo (main developer of FFTW3) told me that we do not initialize FFTW properly: We are missing the call to `fftw_init_threads`. This call is required in threaded environments but we never used it. I will patch our library file tomorrow.
