### ISSUE TITLE
[exts/dbcsr] remove CXXOMPFLAGS upon updating DBCSR to new release

### ISSUE THREAD

**Issue by shoshijak** [cp2k/cp2k#350]
DBCSR's build system is slightly changed with the introduction of https://github.com/cp2k/dbcsr/pull/184. 

When upgrading DBCSR to the newest release, the variable `CXXOMPFLAGS` should be removed from the arch files and from `tools/toolchain/scripts/generate_arch_files.sh` (essentially reversing PR #345). 

Instead, the variable `CXXFLAGS` should contain the OpenMP compilation flags.

**Comment by alazzaro** [comment]
closed via #461
