### ISSUE TITLE
A test fails after fixing the FFT backend

### ISSUE THREAD

**Issue by fstein93** [cp2k/cp2k#3504]
Can anyone send me the output file(s) of the failing test QS/regtest-ri-rpa-exchange/RPA_AXK_H2O_hfx.inp on Daint/GPU or i386? I tried to reproduce the failing test using Docker but the test passed on my machine.

**Comment by mkrack** [comment]
Recently, the regression testers on Piz Daint did not run properly, because the computational budget of the related project for the current quarter is exceeded. I did run the tests in QS/regtest-ri-rpa-exchange separately on daint-gpu and no problem was detected (all OK).
