### ISSUE TITLE
OpenMP is disabeld for elpa when using Intel classic icc and ifort.

### ISSUE THREAD

**Issue by alas-go** [cp2k/cp2k#3508]
![image](https://github.com/cp2k/cp2k/assets/63892049/2fc44b7d-8346-4997-9c37-249034ba33bb)

Why OpenMP is disabled? 
Here, Classic intel ifort and icc are used for trunck on github.

**Comment by fstein93** [comment]
We had repeatedly issues with the OpenMP version of ELPA with Intel compilers (see #3473). We intend to turn it on again soon: #3510, it will be part of the next release again. But nothing prevents you from installing ELPA yourself with the Intel compilers while turning on OpenMP.
