### ISSUE TITLE
LibXC LDA_X wrongly categorized in manual

### ISSUE THREAD

**Issue by stefabat** [cp2k/cp2k#3517]
According to the manual, the functional `LDA_X` is a built-in functional. However, a search through the source code does not show anything related to `LDA_X`. Therefore, I believe that `LDA_X` actually uses the libXC functional (also, the name matches with the name used by libXC) and should therefore be shown in the manual under the paragraph with title "Libxc LDA_X Functionals".

**Comment by oschuett** [comment]
I believe you are right. Thanks for reporting! Unfortunately, that functional does not follow libxc's naming convention and get therefore [misclassified](https://github.com/cp2k/cp2k/blob/4eca575c9117390db7ca3dfb58838f104addab37/docs/generate_input_reference.py#L193). I'll add a special case for it.
