### ISSUE TITLE
Failed to compiler cp2k with hip 

### ISSUE THREAD

**Issue by OTTHao** [cp2k/cp2k#3552]
Dear developers,
        I failed while trying to compile cp2k for hip acceleration. I saw that when compiling dbcsr, it prompted that I couldn't find the definition associated with symbols such as libsmm_acc_is_thread_stafe, c_dbcsr_acc_det_active_device. I installed the relevant dependencies through the toolchain method and successfully compiled them. I cannot find a solution to the problem. Especially, why use_acc is cuda, I configure with hip. Can you help me check it? Here are my toolchain log and compilation error log files.
        command for toolchain is nohup ./install_cp2k_toolchain.sh --no-check-certificate --gpu-ver=Mi50 --enable-hip --with-cmake=system --with-deepmd  --with-plumed > output 2>&1 &
[compile errors.txt](https://github.com/user-attachments/files/16260644/compile.errors.txt)
[toolchain.txt](https://github.com/user-attachments/files/16260646/toolchain.txt)

**Comment by OTTHao** [comment]
plus：I tried to compile with this command: make -j 32 ARCH=local_hip VERSION=psmp. The newer output is pasted as following
[newer compile errors.txt](https://github.com/user-attachments/files/16260782/newer.compile.errors.txt)

**Comment by alazzaro** [comment]
> plus：I tried to compile with this command: make -j 32 ARCH=local_hip VERSION=psmp. The newer output is pasted as following [newer compile errors.txt](https://github.com/user-attachments/files/16260782/newer.compile.errors.txt)

This is the right one to use. However, I'm not sure why calculate_norms.cpp is compiled via mpic++, which is wrong.
No sure what the toolchain does... Could you try the CP2K v2024.1?

**Comment by OTTHao** [comment]
Thanks for your reply, actually I am compiling CP2K v2024.1.

 

发件人: ***@***.*** ***@***.***> 代表 Alfio Lazzaro
发送时间: 2024年7月17日 15:53
收件人: cp2k/cp2k ***@***.***>
抄送: OTTHao ***@***.***>; Author ***@***.***>
主题: Re: [cp2k/cp2k] Failed to compiler cp2k with hip (Issue #3552)

 

plus：I tried to compile with this command: make -j 32 ARCH=local_hip VERSION=psmp. The newer output is pasted as following newer compile errors.txt <https://github.com/user-attachments/files/16260782/newer.compile.errors.txt> 

This is the right one to use. However, I'm not sure why calculate_norms.cpp is compiled via mpic++, which is wrong.
No sure what the toolchain does... Could you try the CP2K v2024.1?

Alfio

**Comment by alazzaro** [comment]
> Thanks for your reply, actually I am compiling CP2K v2024.1. 

Then v2024.1 comes with DBCSR 2.6.0, which doesn't have `calculate_norms.cpp` file. Are you updating DBCSR for any reason? Could you check `exts/dbcsr/VERSION` file and see which version is used? For v2024.1 I have:

```
MAJOR = 2
MINOR = 6
PATCH = 0
# A specific DATE (YYYY-MM-DD) fixes an official release, otherwise
# it is considered Development version.
DATE  = 2023-07-10
```

**Comment by OTTHao** [comment]
> > Thanks for your reply, actually I am compiling CP2K v2024.1.
> 
> Then v2024.1 comes with DBCSR 2.6.0, which doesn't have `calculate_norms.cpp` file. Are you updating DBCSR for any reason? Could you check `exts/dbcsr/VERSION` file and see which version is used? For v2024.1 I have:
> 
> ```
> MAJOR = 2
> MINOR = 6
> PATCH = 0
> # A specific DATE (YYYY-MM-DD) fixes an official release, otherwise
> # it is considered Development version.
> DATE  = 2023-07-10
> ```

Dear alazzaro
        I have confirmed I got the right version of cp2k, however the wrong version of dbcsr. The compilation is beginning, I will report the results later.

**Comment by OTTHao** [comment]
CP2K with HIP is successfully compiled, Thank you

**Comment by alazzaro** [comment]
OK, however, depending on the CP2K input you are interested to run, it can be that DBCSR is performing well (I see you are using Mi50). For that case, I would recommend to use the current develop of CP2K (which includes a new DBCSR). Of course, you need to recompile everything...

**Comment by OTTHao** [comment]
> OK, however, depending on the CP2K input you are interested to run, it can be that DBCSR is performing well (I see you are using Mi50). For that case, I would recommend to use the current develop of CP2K (which includes a new DBCSR). Of course, you need to recompile everything...

I will try that, how ever when I run a energy calculation, errors comes from deepmd. Did I download the wrong version of deepmd lib
/public/home/lh_ott/softwares/apps/cp2k/2024.1/rocm+plumed+deepmd/exe/local_hip/cp2k.psmp cp2k.inp cp2k.o
ut
2024-07-17 16:37:36.839234: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-07-17 16:37:37.340693: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-17 16:37:37.340776: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-17 16:37:37.340868: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
DeePMD-kit: Cannot find libcudart.so.11.0
implib-gen: libcudart.so.11.0: failed to load library 'libcudart.so.11.0' via callback 'DP_cudart_dlopen'
implib-gen: libcudart.so.11.0: failed to resolve symbol '__cudaRegisterFatBinary', library failed to load
implib-gen: libcudart.so.11.0: failed to load library 'libcudart.so.11.0' via callback 'DP_cudart_dlopen'
implib-gen: libcudart.so.11.0: failed to resolve symbol '__cudaRegisterFunction', library failed to load
implib-gen: libcudart.so.11.0: failed to load library 'libcudart.so.11.0' via callback 'DP_cudart_dlopen'
implib-gen: libcudart.so.11.0: failed to resolve symbol '__cudaRegisterFatBinaryEnd', library failed to load

**Comment by alazzaro** [comment]
Oh, this is another issue... I'm not expert of CP2K, only DBCSR.. I suggest to open a new issue. Closing here.

**Comment by OTTHao** [comment]
> Oh, this is another issue... I'm not expert of CP2K, only DBCSR.. I suggest to open a new issue. Closing here.

Thanks again!
