### ISSUE TITLE
about the use of &DFT/&SIC fields for CP2K

### ISSUE THREAD

**Issue by Yvvq0217** [cp2k/cp2k#3564]
When using self-Interaction Correction (SIC), I can see information about SIC settings in the "DFT |" information of the output file. However, when calculating, a "CPASSERT failed" error occurred. The SIC setting parameters are as follows:
   **&SIC 
      ORBITAL_SET ALL
      SIC_METHOD AD
      SIC_SCALING_A 0.2
      SIC_SCALING_B 0.25
   &END SIC**
May I ask what caused the error? (The attachment is my relevant input and output file)
[premd.txt](https://github.com/user-attachments/files/16327145/premd.txt)
[premd-out.txt](https://github.com/user-attachments/files/16327188/premd-out.txt)

**Comment by mkrack** [comment]
SIC requires spin polarisation (LSD) [UKS](https://manual.cp2k.org/trunk/CP2K_INPUT/FORCE_EVAL/DFT.html#CP2K_INPUT.FORCE_EVAL.DFT.UKS).

**Comment by Yvvq0217** [comment]
Thanks so much!



---- Replied Message ----
| From | Matthias ***@***.***> |
| Date | 07/22/2024 15:40 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [cp2k/cp2k] about the use of &DFT/&SIC fields for CP2K (Issue #3564) |

SIC requires spin polarisation (LSD) UKS.
