### ISSUE TITLE
Question about MGRID.CUTOFF

### ISSUE THREAD

**Issue by Fisherd99** [cp2k/cp2k#3598]
Hi. I'm confused with input parameter. When I set CUTOFF = 800， I found the output file writes

```
  ----                             MULTIGRID INFO                            ----
 -------------------------------------------------------------------------------
 count for grid        1:         127715          cutoff [a.u.]          400.00
 count for grid        2:          26695          cutoff [a.u.]          133.33
 count for grid        3:          18565          cutoff [a.u.]           44.44
 count for grid        4:           3623          cutoff [a.u.]           14.81
```

But according to this manual https://manual.cp2k.org/trunk/methods/dft/cutoff.html, I think the multigrid should be {800, 266.67, 88.89,  29.63} .

The same situation also occurs in all these examples, like https://github.com/cp2k/cp2k-examples/blob/master/converging_grid/sample_output/cutoff_250Ry/Si_bulk8.out, it sets CUTOFF=250, but gets multigrid as {125.00, 41.67 ,13.89, 4.63}.

Is there anything wrong here? Or the units here are different?

**Comment by fstein93** [comment]
The default energy unit in the input file is Rydberg whereas the energy unit in the output is in Hartree differing by a factor of 2.

**Comment by fstein93** [comment]
Apparently, the issue is resolved. Feel free to reopen it if there is still something unclear regarding this issue.

**Comment by Fisherd99** [comment]
Thanks, I get it

**Comment by Fisherd99** [comment]
> Apparently, the issue is resolved. Feel free to reopen it if there is still something unclear regarding this issue.

Thanks, I get it.
