### ISSUE TITLE
Accurate forces for hybrid functionals / exact exchange 

### ISSUE THREAD

**Issue by svandenhaute** [cp2k/cp2k#3599]
Hi, 
For most GGA functionals, I succeed in reducing numerical noise on the forces down to the order of meV/angstrom by increasing NGRIDS, REL_CUTOFF, CUTOFF, and decreasing the EPS_SCF values. However, for calculations with exact exchange, I can't get this to work. For a unit cell with ~400 atoms (H, C, O, Zr), I'm still obtaining a total net force of about 200 meV/angstrom, although this value should be close to zero.

I've pasted my input settings below. Is there anything I can still change or tighten in order to reduce the numerical noise?

```
&FORCE_EVAL
  &PRINT
	&FORCES
	&END FORCES
  &END PRINT
  &DFT
    BASIS_SET_FILE_NAME BASIS_MOLOPT_UZH
    BASIS_SET_FILE_NAME BASIS_ADMM_UZH
    POTENTIAL_FILE_NAME POTENTIAL_UZH
    &MGRID
      CUTOFF 800
      REL_CUTOFF 60
      NGRIDS 6
    &END MGRID
    &SCF
      MAX_SCF 20
      EPS_SCF 1.0E-8
      &OT
        MINIMIZER CG
        PRECONDITIONER FULL_ALL
      &END OT
      &OUTER_SCF
        MAX_SCF 20
        EPS_SCF 1.0E-8
      &END OUTER_SCF
    &END SCF
    &QS
      EPS_DEFAULT 1.0E-12
      EPS_PGF_ORB 1.0E-16
      EPS_FILTER_MATRIX 0.0e0
      EXTRAPOLATION_ORDER 5
    &END QS
    &XC # revPBE0-TC-D3
      &XC_FUNCTIONAL
        &PBE
          PARAMETRIZATION REVPBE
          SCALE_X 0.75
          SCALE_C 1.0
        &END
      &END XC_FUNCTIONAL
      &HF
        FRACTION 0.25
        &SCREENING
          EPS_SCHWARZ 1.0E-7
	 EPS_SCHWARZ_FORCES 1.0E-5
	 SCREEN_P_FORCES FALSE
          SCREEN_ON_INITIAL_P TRUE
        &END
        &MEMORY
          MAX_MEMORY 64000
          EPS_STORAGE_SCALING 0.1
        &END
        &INTERACTION_POTENTIAL
          POTENTIAL_TYPE TRUNCATED
          CUTOFF_RADIUS 6.0
          T_C_G_DATA t_c_g.dat
        &END
        &HF_INFO
        &END HF_INFO
      &END
      &VDW_POTENTIAL
         POTENTIAL_TYPE PAIR_POTENTIAL
         &PAIR_POTENTIAL
            TYPE DFTD3
            R_CUTOFF 15
            LONG_RANGE_CORRECTION TRUE
            REFERENCE_FUNCTIONAL revPBE0
            PARAMETER_FILE_NAME dftd3.dat
         &END
      &END
    &END XC
    &AUXILIARY_DENSITY_MATRIX_METHOD
      METHOD BASIS_PROJECTION
      ADMM_PURIFICATION_METHOD MO_DIAG
    &END AUXILIARY_DENSITY_MATRIX_METHOD
  &END DFT
  &SUBSYS
    &KIND H
      BASIS_SET         TZV2P-MOLOPT-PBE-GTH-q1
      BASIS_SET	AUX_FIT admm-tz2p-q1
      POTENTIAL         GTH-PBE-q1
    &END KIND
    &KIND O
      BASIS_SET         TZV2P-MOLOPT-PBE-GTH-q6
      BASIS_SET	AUX_FIT admm-tz2p-q6
      POTENTIAL         GTH-PBE-q6
    &END KIND
    &KIND C
      BASIS_SET         TZV2P-MOLOPT-PBE-GTH-q4
      BASIS_SET AUX_FIT admm-tz2p-q4
      POTENTIAL         GTH-PBE-q4
    &END KIND
    &KIND Zr
      BASIS_SET         TZV2P-MOLOPT-PBE-GTH-q12
      BASIS_SET	AUX_FIT admm-tz2p-q12
      POTENTIAL         GTH-PBE-q12
    &END KIND
  &END SUBSYS
&END FORCE_EVAL
```

**Comment by fstein93** [comment]
Are you sure that you converged the EPS_SCHWARZ and EPS_SCHWARZ_FORCES parameters well enough? ADMM and SCREEN_ON_INITIAL_P independently increase the requirements on these two parameters. What happens if you decrease EPS_DEFAULT?

**Comment by svandenhaute** [comment]
If I reduce EPS_SCHWARZ and EPS_SCHWARZ_FORCES by an additional order of magnitude, the calculation crashes without any error message (simple a bunch of 'task terminated' logs from `srun`)... Any idea why? 
I'm running on 128-core nodes, with 512GB each. On 8 nodes, it already takes between 30 and 60 minutes...

**Comment by fstein93** [comment]
May I see an output file? At the end, it tells you the amount of maximum used memory per rank. The HF output (right before the SCF calculation) displays similar information for HF only. HF tries to keep all integrals in memory (by default 512 MB per rank) and replicates the density and Fock matrix. It may then help to use more threads instead of ranks.

**Comment by svandenhaute** [comment]
```
  HFX_MEM_INFO| Est. max. program size before HFX [MiB]:                     419
  HFX_MEM_INFO| Number of cart. primitive ERI's calculated:        8452855627838
  HFX_MEM_INFO| Number of sph. ERI's calculated:                   4944300334372
  HFX_MEM_INFO| Number of sph. ERI's stored in-core:               3136688292253
  HFX_MEM_INFO| Number of sph. ERI's stored on disk:                           0
  HFX_MEM_INFO| Number of sph. ERI's calculated on the fly:                    0
  HFX_MEM_INFO| Total memory consumption ERI's RAM [MiB]:                2664517
  HFX_MEM_INFO| Whereof max-vals [MiB]:                                    34467
  HFX_MEM_INFO| Total compression factor ERI's RAM:                         8.98
  HFX_MEM_INFO| Total memory consumption ERI's disk [MiB]:                     0
  HFX_MEM_INFO| Total compression factor ERI's disk:                        0.00
  HFX_MEM_INFO| Size of density/Fock matrix [MiB]:                           728
  HFX_MEM_INFO| Size of buffers [MiB]:                                        51
  HFX_MEM_INFO| Number of periodic image cells considered:                    27
  HFX_MEM_INFO| Est. max. program size after HFX  [MiB]:                    3966
```

That part?

**Comment by fstein93** [comment]
From the last line, I can see that each rank needs ~ 4GiB of memory for HF (`Est. max. program size after HFX`). If you run your calculation on 128 ranks per node (just a guess!), you will use up all of your memory of 512 GiB per node. To reduce the memory demands, you can employ less ranks per node and increase the number of threads per rank (OMP_NUM_THREADS). This reduces the number of copies of density matrices (`Size of density/Fock matrix`) significantly because they are shared by the threads assigned to a rank. Alternatively, you can use more nodes.

**Comment by fstein93** [comment]
Apparently, the issue was resolved. Feel free to reopen this issue, if it still occurs.
