### ISSUE TITLE
fprettify

### ISSUE THREAD

**Issue by juerghutter** [cp2k/cp2k#3608]
Since the new setup for the prettify module I get the following problem:

git fetch 

Fetching submodule tools/prettify/fprettify
Username for 'https://github.com': XXXXXXXXX
Password for 'https://XXXXXXXXX@github.com': 
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/pseewald/fprettify.git/'
Errors during submodule fetch:
        tools/prettify/fprettify

I'm especially worried about
fatal: Authentication failed for 'https://github.com/pseewald/fprettify.git/'
                                                                                                       ^^^^^^^^

**Comment by oschuett** [comment]
I think you need to [add your ssh key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) to GitHub and then change the url of your remote repository:
```
git remote remove origin
git remote add origin git@github.com:cp2k/cp2k.git
```

The other issue with the fprettify repository is that it was recently moved from [pseewald](https://github.com/pseewald/fprettify) to [fortran-lang](https://github.com/fortran-lang/fprettify). 

 Since I was never a fan of git submodules, I've now removed it and just copied the relevant files into our repo (#3603). 

So, after you solved the above auth problem things should just work.

**Comment by juerghutter** [comment]
The solution is (for an already cloned repo)

git rm tools/prettify/fprettify
rm 'tools/prettify/fprettify'
git commit

This removes the link to the no longer existing repo.

**Comment by oschuett** [comment]
Note that the DBCSR project also used to have a submodule of fprettify.
So, one might have to delete both stale directories:

```
rm -r tools/prettify/fprettify
rm -r exts/dbcsr/tools/fprettify
```

**Comment by marci73** [comment]
Sorry, 
but this does not work for me. 
I cannot remove the submodule of the submodule, 

git rm -r exts/dbcsr/tools/fprettify
fatal: pathspec 'exts/dbcsr/tools/fprettify' did not match any files

and I keep getting the same error

 git pull --rebase upstream master 
From github.com:cp2k/cp2k
 * branch                master     -> FETCH_HEAD
Fetching submodule exts/dbcsr
Fetching submodule exts/dbcsr/tools/build_utils/fypp
Fetching submodule exts/dbcsr/tools/fprettify
Username for 'https://github.com': 
Password for 'https://github.com': 
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/pseewald/fprettify/'
Errors during submodule fetch:
	tools/fprettify
Errors during submodule fetch:
	exts/dbcsr

**Comment by oschuett** [comment]
Another thing you could try is to remove the relevant entry from git module files manually:

- `cp2k/.gitmodules`
- `cp2k/exts/dbcsr/.gitmodules`
