### ISSUE TITLE
Error compiling cp2k with cosma

### ISSUE THREAD

**Issue by Schroedingers0216** [cp2k/cp2k#3611]
When compiling CP2K using the COSMA HIP version, I encountered numerous undefined function errors. Below are my compilation method and the errors:

./install_cp2k_toolchain.sh --no-check-certificate --gpu-ver=Mi50 --enable-hip --with-cmake  --with-plumed --with-elpa --with-cosma

error:
/work/home/opt/cp2k-2024.1/tools/toolchain/build/COSMA-2.6.6/src/cosma/local_multiply.cpp:103: undefined reference to `void gpu::gemm<std::complex<double> >(gpu::mm_handle<std::complex<double> >&, char, char, int, int, int, std::complex<double>, std::complex<double>*, int, std::complex<double>*, int, std::complex<double>, std::complex<double>*, int, bool, bool)'
/work/home/opt/cp2k-2024.1/tools/toolchain/install/COSMA-2.6.6-hip/lib/libcosma.a(local_multiply.cpp.o): In function `void cosma::local_multiply<std::complex<float> >(gpu::mm_handle<std::complex<float> >*, std::complex<float>*, std::complex<float>*, std::complex<float>*, int, int, int, std::complex<float>, std::complex<float>, bool, bool)':
/work/home/opt/cp2k-2024.1/tools/toolchain/build/COSMA-2.6.6/src/cosma/local_multiply.cpp:103: undefined reference to `void gpu::gemm<std::complex<float> >(gpu::mm_handle<std::complex<float> >&, char, char, int, int, int, std::complex<float>, std::complex<float>*, int, std::complex<float>*, int, std::complex<float>, std::complex<float>*, int, bool, bool)'
/work/home/opt/cp2k-2024.1/tools/toolchain/install/COSMA-2.6.6-hip/lib/libcosma.a(local_multiply.cpp.o): In function `void cosma::local_multiply<double>(gpu::mm_handle<double>*, double*, double*, double*, int, int, int, double, double, bool, bool)':
/work/home/opt/cp2k-2024.1/tools/toolchain/build/COSMA-2.6.6/src/cosma/local_multiply.cpp:103: undefined reference to `void gpu::gemm<double>(gpu::mm_handle<double>&, char, char, int, int, int, double, double*, int, double*, int, double, double*, int, bool, bool)'
/work/home/opt/cp2k-2024.1/tools/toolchain/install/COSMA-2.6.6-hip/lib/libcosma.a(local_multiply.cpp.o): In function `void cosma::local_multiply<float>(gpu::mm_handle<float>*, float*, float*, float*, int, int, int, float, float, bool, bool)':
/work/home/opt/cp2k-2024.1/tools/toolchain/build/COSMA-2.6.6/src/cosma/local_multiply.cpp:103: undefined reference to `void gpu::gemm<float>(gpu::mm_handle<float>&, char, char, int, int, int, float, float*, int, float*, int, float, float*, int, bool, bool)'
/work/home/opt/cp2k-2024.1/tools/toolchain/install/COSMA-2.6.6-hip/lib/libcosma.a(local_multiply.cpp.o): In function `void cosma::local_multiply<std::complex<double> >(gpu::mm_handle<std::complex<double> >*, std::complex<double>*, std::complex<double>*, std::complex<double>*, int, int, int, std::complex<double>, std::complex<double>, bool, bool)':
/work/home/opt/cp2k-2024.1/tools/toolchain/build/COSMA-2.6.6/src/cosma/local_multiply.cpp:103: undefined reference to `void gpu::gemm<std::complex<double> >(gpu::mm_handle<std::complex<double> >&, char, char, int, int, int, std::complex<double>, std::complex<double>*, int, std::complex<double>*, int, std::complex<double>, std::complex<double>*, int, bool, bool)'
/work/home/opt/cp2k-2024.1/tools/toolchain/install/COSMA-2.6.6-hip/lib/libcosma.a(local_multiply.cpp.o): In function `void cosma::local_multiply<std::complex<float> >(gpu::mm_handle<std::complex<float> >*, std::complex<float>*, std::complex<float>*, std::complex<float>*, int, int, int, std::complex<float>, std::complex<float>, bool, bool)':
/work/home/opt/cp2k-2024.1/tools/toolchain/build/COSMA-2.6.6/src/cosma/local_multiply.cpp:103: undefined reference to `void gpu::gemm<std::complex<float> >(gpu::mm_handle<std::complex<float> >&, char, char, int, int, int, std::complex<float>, std::complex<float>*, int, std::complex<float>*, int, std::complex<float>, std::complex<float>*, int, bool, bool)'
/work/home/opt/cp2k-2024.1/tools/toolchain/build/COSMA-2.6.6/src/cosma/local_multiply.cpp:103: undefined reference to `void gpu::gemm<std::complex<float> >(gpu::mm_handle<std::complex<float> >&, char, char, int, int, int, std::complex<float>, std::complex<float>*, int, std::complex<float>*, int, std::complex<float>, std::complex<float>*, int, bool, bool)'
/work/home/opt/cp2k-2024.1/tools/toolchain/install/COSMA-2.6.6-hip/lib/libcosma.a(local_multiply.cpp.o): In function `void cosma::local_multiply<std::complex<double> >(gpu::mm_handle<std::complex<double> >*, std::complex<double>*, std::complex<double>*, std::complex<double>*, int, int, int, std::complex<double>, std::complex<double>, bool, bool)':
/work/home/opt/cp2k-2024.1/tools/toolchain/build/COSMA-2.6.6/src/cosma/local_multiply.cpp:103: undefined reference to `void gpu::gemm<std::complex<double> >(gpu::mm_handle<std::complex<double> >&, char, char, int, int, int, std::complex<double>, std::complex<double>*, int, std::complex<double>*, int, std::complex<double>, std::complex<double>*, int, bool, bool)'
/work/home/opt/cp2k-2024.1/tools/toolchain/install/COSMA-2.6.6-hip/lib/libcosma.a(local_multiply.cpp.o): In function `void cosma::local_multiply<float>(gpu::mm_handle<float>*, float*, float*, float*, int, int, int, float, float, bool, bool)':
/work/home/opt/cp2k-2024.1/tools/toolchain/build/COSMA-2.6.6/src/cosma/local_multiply.cpp:103: undefined reference to `void gpu::gemm<float>(gpu::mm_handle<float>&, char, char, int, int, int, float, float*, int, float*, int, float, float*, int, bool, bool)'
/work/home/opt/cp2k-2024.1/tools/toolchain/install/COSMA-2.6.6-hip/lib/libcosma.a(local_multiply.cpp.o): In function `void cosma::local_multiply<double>(gpu::mm_handle<double>*, double*, double*, double*, int, int, int, double, double, bool, bool)':
/work/home/opt/cp2k-2024.1/tools/toolchain/build/COSMA-2.6.6/src/cosma/local_multiply.cpp:103: undefined reference to `void gpu::gemm<double>(gpu::mm_handle<double>&, char, char, int, int, int, double, double*, int, double*, int, double, double*, int, bool, bool)'

**Comment by alazzaro** [comment]
I suggest to compile COSMA outside the toolchain, just follow the COSMA instructions...

**Comment by Schroedingers0216** [comment]
> I suggest to compile COSMA outside the toolchain, just follow the COSMA instructions...

I've tried compiling it separately, but the issue still persists.

**Comment by alazzaro** [comment]
then I suggest to post in https://github.com/eth-cscs/COSMA.
But, if you have a previous COSMA version already compiled, then I will use that one for CP2K toolchain...
