### ISSUE TITLE
pretty checks the CMAKE build file

### ISSUE THREAD

**Issue by jpoto** [cp2k/cp2k#3622]
If I build CP2K using CMAKE I create (as in the instructions) a folder with the name build. 

If I run 'make pretty' without deleting it, the whole build folder is checked resulting in a long list of errors. 

Is there any way to tell pretty to ignore the build directory?

**Comment by oschuett** [comment]
You can add it to [this list](https://github.com/cp2k/cp2k/blob/master/tools/precommit/precommit.py#L83) of ignored file pattern.
