### ISSUE TITLE
How to solve the heterojunction band gap is almost 0?

### ISSUE THREAD

**Issue by xyq1234567** [cp2k/cp2k#3667]
Hello! I am currently using CP2K-2022.2 to calculate the XTB properties of a MoS2/SWCNT/WSe2 heterostructure . 
1.Using the XTB method, the calculated band gap is almost zero; 
2.I tried to solve this issue by using level shift, but the following error occurred:Intel MKL ERROR: Parameter 4 was incorrect on entry to DLASCL. How can I solve the problem of a nearly zero band gap, and if level shift doesn't work, are there any other adjustment methods in XTB?
Thank you!

Below are the input file, coordinate file, and output file. 
[xtb.zip](https://github.com/user-attachments/files/16927362/xtb.zip)

**Comment by fstein93** [comment]
Regarding your second issue: I have checked the routines raised errors/warnings in your output file. CP2K does not make use of them directly suggesting that they are used by routines within MKL. So, I think it is a bug in MKL. What version of MKL are you using? Do you have the possibility do upgrade MKL or check a different BLAS/Lapack/Scalapack distribution?

**Comment by xyq1234567** [comment]
> Regarding your second issue: I have checked the routines raised errors/warnings in your output file. CP2K does not make use of them directly suggesting that they are used by routines within MKL. So, I think it is a bug in MKL. What version of MKL are you using? Do you have the possibility do upgrade MKL or check a different BLAS/Lapack/Scalapack distribution?

Thanks for your answer. I will try to use IMKL2021.3.0.
