### ISSUE TITLE
Bug fix patch for D4 in V 2024.3 

### ISSUE THREAD

**Issue by juerghutter** [cp2k/cp2k#3688]
This patch fixes a bug in the D4 dispersion correction in CP2K Version 2024.3

**Comment by juerghutter** [comment]
[Patch_1_2024.txt](https://github.com/user-attachments/files/17093994/Patch_1_2024.txt)

**Comment by RMeli** [comment]
I'll include it in the Spack package ASAP.

**Comment by RMeli** [comment]
https://github.com/spack/spack/pull/46545

**Comment by oschuett** [comment]
I'm closing this issue as the patch has been picked up by Spack and the master branch was fixed via #3685.
