### ISSUE TITLE
IGNORE_CONVERGENCE_FAILURE for SIRIUS SCF

### ISSUE THREAD

**Issue by hmhoseini** [cp2k/cp2k#3690]
This is rather a suggestion than an issue.
A parameter similar to IGNORE_CONVERGENCE_FAILURE in the DFT/SCF section is necessary for SIRIUS calculations. 
Currently, if SIRIUS SCF is converge after N iterations, the following message is printed:
[find] converged after N SCF iterations!
Otherwise, nothing is printed and the calculations (e.g. cell optimization) continue. 
I think a warning message should be printed if SCF is not converged and a parameter similar to  IGNORE_CONVERGENCE_FAILURE is also needed. 
Thanks!

**Comment by oschuett** [comment]
CC @mtaillefumier

**Comment by mtaillefumier** [comment]
I would advice against having the possibility to continue a calculation with non converged quantities in general. Having a message indicating that SIRIUS did not converge is a good suggestion though.

**Comment by hmhoseini** [comment]
I think having the option to continue or stop the calculation is a good idea and consistent with the SCF section. 
Talking to SIRIUS developers, I learned that sirius_find_ground_state() API function has an optional output parameter “converged”. If SCF is not converged in the given number of iterations, it will be set to “false”.

**Comment by mtaillefumier** [comment]
I will make it FALSE by default. It is a very simple patch. should get something later today.

**Comment by mtaillefumier** [comment]
PR #3694 should add the necessary option.
