### ISSUE TITLE
compile CP2K v2024.3 using the toolchain

### ISSUE THREAD

**Issue by OTTHao** [cp2k/cp2k#3705]
I tried to compile CP2K v2024.3 using the toolchain, and my command was: ./install_cp2k_toolchain.sh -j 16 --no-check-certificate --with-cmake=system --with-plumed=install --with-intel-classic=yes --with-mkl=system. I specified the math library as MKL, but the toolchain still downloaded OpenBLAS. Is this a bug in the toolchain?

**Comment by mkrack** [comment]
OpenBLAS is always downloaded in a toolchain run, because it is used in a first step to detect the system architecture.

**Comment by OTTHao** [comment]
> OpenBLAS is always downloaded in a toolchain run, because it is used in a first step to detect the system architecture.

OK, thanks for your answering!
