### ISSUE TITLE
Requested to use plumed for metadynamics，but cp2k was not compiled with plumed support

### ISSUE THREAD

**Issue by sfmnewbie** [cp2k/cp2k#3718]
I compiled cp2k with: . /install_cp2k_toolchain.sh --with-plumed=install -j 48. Also made sure to download plumed-2.9.0, but it gives an error when running cp2k: requested to use plumed for metadynamics, but cp2k was not compiles with plumed support. May I ask why this error occurs?
![1728548672004](https://github.com/user-attachments/assets/e2045ad3-7f9c-401c-b5a8-366da9bcdec4)

**Comment by fstein93** [comment]
Please provide more information on how you compiled CP2K plus log files. Is it possible that you haven't copied the arch files to your arch file directory or that you have compiled it before without support for plumed and did not remove the old installation?

**Comment by sfmnewbie** [comment]
Maybe it's the version I'm using, I changed the version to 2024.3 and after installing it I could use plumed and everything worked fine!

**Comment by Siva-V99** [comment]
Same problem I am encountering here I installed latest version 2025.1 the error appears to be cp2k is not compiled with plumed please tell a way to solve this

**Comment by hughuang12** [comment]
> Same problem I am encountering here I installed latest version 2025.1 the error appears to be cp2k is not compiled with plumed please tell a way to solve this

Did you fix it, I am also facing this problem

**Comment by Siva-V99** [comment]
No I am still unable to figure it out so I am not using plumed now with
cp2k
