### ISSUE TITLE
ELECTRONIC_STRUCTURE param of ATOM module is not consistent between different RUN_TYPEs?

### ISSUE THREAD

**Issue by kirk0830** [cp2k/cp2k#3734]
I successfully reproduce the pseudopotential optimization procedure with input provided here:
https://github.com/juerghutter/GTH/blob/master/PBE_NLCC/C/q4/C.inp
However, with the GTH-POTENTIAL yielded by task of `RUN_TYPE PSEUDOPOTENTIAL_OPTIMIZATION`, when I was trying to convert it to UPF format, following the way to write input script like examples provided here:
https://github.com/simonpintarelli/lanthanides-nc-pseudos/blob/master/Ce/Ce.inp
, I find the `ELECTRONIC_CONFIGURATION` param seems to accept value in different manner? The former accpets "[He]", while the latter accepts "CORE":
```
ELECTRONIC_STRUCTURE [He] 2s2 2p2
CORE [He]
```
or
```
ELECTRONIC_STRUCTURE CORE 2s2 2p2
CORE [He]
```

**Comment by juerghutter** [comment]
Hi

in a pseudopotential optimization calculation you need the reference (all electron) and the  core definition:

ELECTRONIC_STRUCTURE [He] 2s2 2p2      <-- all electron reference
CORE [He]                                                          <-- how to construct the pseudo atom

Later, if you have a pseudopotential ready, you only do a pseudopotential calculation

ELECTRONIC_STRUCTURE CORE 2s2 2p2      <-- definition of pseudo atom (with a core of He type)
CORE [He]

regards
JH

________________________________________
From: kirk0830 ***@***.***>
Sent: Tuesday, October 22, 2024 10:44 AM
To: cp2k/cp2k
Cc: Subscribed
Subject: [cp2k/cp2k] ELECTRONIC_STRUCTURE param of ATOM module is not consistent between different RUN_TYPEs? (Issue #3734)

I successfully reproduce the pseudopotential optimization procedure with input provided here:
https://github.com/juerghutter/GTH/blob/master/PBE_NLCC/C/q4/C.inp
However, with the GTH-POTENTIAL yielded by task of RUN_TYPE PSEUDOPOTENTIAL_OPTIMIZATION, when I was trying to convert it to UPF format, following the way to write input script like examples provided here:
https://github.com/simonpintarelli/lanthanides-nc-pseudos/blob/master/Ce/Ce.inp
, I find the ELECTRONIC_CONFIGURATION param seems to accept value in different manner? The former accpets "[He]", while the latter accepts "CORE":

ELECTRONIC_STRUCTURE [He] 2s2 2p2
CORE [He]


or

ELECTRONIC_STRUCTURE CORE 2s2 2p2
CORE [He]

**Comment by kirk0830** [comment]
@juerghutter Thanks! now I got it, so the keyword `CORE` has slightly different meanings in two run_types.
