### ISSUE TITLE
Compilation Error for GPU-Accelerated ELPA using Toolchain

### ISSUE THREAD

**Issue by OTTHao** [cp2k/cp2k#3735]
Dear CP2K Developers,

As I mentioned earlier, I am attempting to compile version 24.3 of CP2K. My compilation environment includes the following modules:
Currently Loaded Modulefiles:
  1) compiler/intel/2021.3.0              4) nvidia/cuda/11.3                     7) python/3.8.10
  2) mpi/intelmpi/2021.3.0                5) compiler/cmake/3.23.3
  3) mathlib/fftw/3.3.10_intel21_double   6) compiler/gcc/12.2.0
I encountered the following error:
/public/software/compiler/intel-compiler/2021.3.0/compiler/include/complex:62:3: error: #error "This Intel <complex> is for use only with the Intel C++ compilers!"
   62 | # error "This Intel <complex> is for use only with the Intel C++ compilers!"
      |   ^~~~~
/public/software/compiler/intel-compiler/2021.3.0/compiler/include/complex.h:30:3: error: #error "This Intel <complex.h> is for use with only the Intel compilers!"
   30 | # error "This Intel <complex.h> is for use with only the Intel compilers!"
      |   ^~~~~
ifort: command line warning #10148: option '-fno-lto' not supported
ifort: command line warning #10148: option '-fno-lto' not supported
It seems that the Intel libraries are being loaded when compiling the NVIDIA version of ELPA. Could you advise on how to avoid this issue? If more information is needed, please let me know.

Best regards,
Hao Liu
Let me know if you'd like any further adjustments!

**Comment by oschuett** [comment]
This seems to be an issue with the Intel compiler or the way it's installed.
