### ISSUE TITLE
fail to compile when use toolchain with "intel-8488c" cpu

### ISSUE THREAD

**Issue by hellozhaoming** [cp2k/cp2k#3740]
Toolchain scipt is able to auto generate the local.ssmp/pdbg/...  files

If "make" with these files, there will be many errors like  "/tmp/ccqpMdXL.s:3268: Error: no such instruction: `vmovw %xmm5,(%rsi)' ". And the compile will fail.

I find the flags in these files contains "-march=native".  
If I run 
`gcc -march=native -Q --help=target`

and I get :

  -mavx5124fmaps                        [disabled]
  -mavx5124vnniw                        [disabled]
  -mavx512bf16                          [enabled]
  -mavx512bitalg                        [enabled]
  -mavx512bw                            [enabled]
  -mavx512cd                            [enabled]
  -mavx512dq                            [enabled]
  -mavx512er                            [disabled]
  -mavx512f                             [enabled]
  -mavx512fp16                          [enabled]
  -mavx512ifma                          [enabled]
  -mavx512pf                            [disabled]
  -mavx512vbmi                          [enabled]
  -mavx512vbmi2                         [enabled]
  -mavx512vl                            [enabled]
  -mavx512vnni                          [enabled]
  -mavx512vp2intersect                  [disabled]
  -mavx512vpopcntdq                     [enabled]
  -mavxifma                             [disabled]
  -mavxneconvert                        [disabled]
  -mavxvnni                             [enabled]
  -mavxvnniint8                         [disabled]
  -mbionic                              [disabled]

If I run 
`grep flags /proc/cpuinfo`

I get:
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hfi avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities

I notice "avx512bf16" and some other flags are not supported by the cpu flags but still enabled if use "-march=native -mtune=native". Thus, I repalce it with "-march=sapphirerapids -mno-avx512bf16 -mno-avx512bitalg -mno-avx512fp16 -mno-avx512vnni -mno-avx512vpopcntdq -mtune=sapphirerapids" to disable the unsupported flags.
Finally, I was able to compile the cp2k.

I suggest to conduct a test of flags in the toolchain scripts to avoid the error.

[out.txt](https://github.com/user-attachments/files/17520706/out.txt)

**Comment by fstein93** [comment]
Can you provide the context in which this error occurs by providing a log file?

**Comment by hellozhaoming** [comment]
> Can you provide the context in which this error occurs by providing a log file?

I have uploaded a log file. Error is in line 94

**Comment by fstein93** [comment]
@oschuett Do you have an idea?

**Comment by oschuett** [comment]
I believe `vmovw` is an AVX512 instruction, which we don't use explictly in our code. (We only use AVX2 intrinsics [here](https://github.com/cp2k/cp2k/blob/master/src/grid/cpu/grid_cpu_collint.h)). So this is probably a compiler bug, maybe [this one](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105139).

**Comment by hfp** [comment]
The OS/Linux version not showing certain CPU features does not mean it cannot use them. Well, if there was no AVX512 aka 512-bit vectors known, the OS would not be able to store the extended state (XSAVE). However, this is not the case here but just one feature of AVX-512 not shown by /proc/cpuinfo. It could simply be at the time of release of the OS, the CPU feature was not known. However, a bleeding edge compiler installed later on may know it.

**Comment by zz-y-zz** [comment]
Hello, I've get a similar error and would like to ask which file you modified? Are the files ’libcp2kfpga.a‘ and ’libcp2kfgpu.a‘ ？

The error log is posted below

Discovering programs ...
ar: creating /lustre/data/hp240096/cp2k/lib/local/ssmp/libcp2kgridcpu.a
ar: creating /lustre/data/hp240096/cp2k/lib/local/ssmp/libcp2kgridref.a
/tmp/ccEsmmlT.s: Assembler messages:
/tmp/ccEsmmlT.s:3179: Error: no such instruction: `vmovw %xmm5,(%rsi)'
make[3]: *** [/lustre/data/hp240096/cp2k/Makefile:518: grid_dgemm_utils.o] Error 1
make[3]: *** Waiting for unfinished jobs....
ar: creating /lustre/data/hp240096/cp2k/lib/local/ssmp/libcp2kbase.a
/tmp/ccfWyWeC.s: Assembler messages:
/tmp/ccfWyWeC.s:3179: Error: no such instruction: `vmovw %xmm5,(%rsi)'
make[3]: *** [/lustre/data/hp240096/cp2k/Makefile:518: grid_dgemm_utils.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [/lustre/data/hp240096/cp2k/Makefile:146: all] Error 2
make[1]: *** [/lustre/data/hp240096/cp2k/Makefile:128: psmp] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [/lustre/data/hp240096/cp2k/Makefile:146: all] Error 2
make[1]: *** [/lustre/data/hp240096/cp2k/Makefile:128: ssmp] Error 2
make: *** [Makefile:123: all] Error 2

**Comment by hellozhaoming** [comment]
> Hello, I've get a similar error and would like to ask which file you modified? Are the files ’libcp2kfpga.a‘ and ’libcp2kfgpu.a‘ ？
> 
> The error log is posted below
> 
> Discovering programs ... ar: creating /lustre/data/hp240096/cp2k/lib/local/ssmp/libcp2kgridcpu.a ar: creating /lustre/data/hp240096/cp2k/lib/local/ssmp/libcp2kgridref.a /tmp/ccEsmmlT.s: Assembler messages: /tmp/ccEsmmlT.s:3179: Error: no such instruction: `vmovw %xmm5,(%rsi)' make[3]: *** [/lustre/data/hp240096/cp2k/Makefile:518: grid_dgemm_utils.o] Error 1 make[3]: *** Waiting for unfinished jobs.... ar: creating /lustre/data/hp240096/cp2k/lib/local/ssmp/libcp2kbase.a /tmp/ccfWyWeC.s: Assembler messages: /tmp/ccfWyWeC.s:3179: Error: no such instruction: `vmovw %xmm5,(%rsi)' make[3]: *** [/lustre/data/hp240096/cp2k/Makefile:518: grid_dgemm_utils.o] Error 1 make[3]: *** Waiting for unfinished jobs.... make[2]: *** [/lustre/data/hp240096/cp2k/Makefile:146: all] Error 2 make[1]: *** [/lustre/data/hp240096/cp2k/Makefile:128: psmp] Error 2 make[1]: *** Waiting for unfinished jobs.... make[2]: *** [/lustre/data/hp240096/cp2k/Makefile:146: all] Error 2 make[1]: *** [/lustre/data/hp240096/cp2k/Makefile:128: ssmp] Error 2 make: *** [Makefile:123: all] Error 2

all the local*.* files in "cp2k/arch/" fold

**Comment by oschuett** [comment]
Are there any updates on this? Did upgrading the compiler help?

**Comment by zz-y-zz** [comment]
Yes, it works, but other issues have shown up. I think there's something wrong with the HPC. I don't have any other questions for now, thanks!
