### ISSUE TITLE
i wan to Optimation Ni111slab，It is used for amino adsorption energy test.

### ISSUE THREAD

**Issue by DoumAAAAAA** [cp2k/cp2k#3746]
i wan to Optimation Ni111slab，It is used for amino adsorption energy test.
24 atoms.
I set the k-point to 4,4,1.
The nickel magnetic moment is 1.
The optional multiplicity is 25.
open UKS,smear.
use Rpbe+D3（bj）.
CUTOFF  550
REL_CUTOFF  55
ALPHA 0.4 
NBROYDEN 12
I'm using the cp2k 2024.1 version.
but,the Scf no cover.
[Ni111.zip](https://github.com/user-attachments/files/17517972/Ni111.zip)

It is not known in terms of which parameters need to be modified

_Originally posted by @DoumAAAAAA in https://github.com/cp2k/cp2k/discussions/3744_

**Comment by fstein93** [comment]
Please repost in the CP2K user group. There, you will find folks experienced with running calculations. The issues are meant for code/implementation related discussions.

**Comment by fstein93** [comment]
See https://groups.google.com/g/cp2k/c/hCSqlaVOatc
