### ISSUE TITLE
`find_package(Libxc)` does not cover libxc7

### ISSUE THREAD

**Issue by LecrisUT** [cp2k/cp2k#3767]
https://github.com/cp2k/cp2k/blob/b5a5e3a0a207416f02cf7928d461dbf611d5f851/CMakeLists.txt#L609-L611

**Comment by oschuett** [comment]
A first step would be to upgrade the toolchain to the lastest libxc version:

https://github.com/cp2k/cp2k/blob/7f23908548978f1b46e6d20bc63713a2d5cc4a4c/tools/toolchain/scripts/stage3/install_libxc.sh#L9

**Comment by oschuett** [comment]
Closing as duplicate of #3724.
