### ISSUE TITLE
BASIS_SET_FILE keyword unknown

### ISSUE THREAD

**Issue by Pavel555-star** [cp2k/cp2k#3768]

**Comment by fstein93** [comment]
Dear @Pavel555-star ,
This is not a proper CP2K input file. CP2K input files are divided in sections indicated by an ampersand `&<section name>`. Each section may have subsections and keywords (compare [the input reference](https://manual.cp2k.org/trunk/CP2K_INPUT.html)). Please consult the manual for further information on how to setup a CP2K input file: [here](https://manual.cp2k.org/trunk/methods/dft/cutoff.html).
