### ISSUE TITLE
Missing performance results for RI-MP / RI-RPA

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#377]
Since #358 the performance tests on [GPU](https://dashboard.cp2k.org/archive/cray-xc50-daint-gpu-psmp_perf/index.html) and [CPU](https://dashboard.cp2k.org/archive/cray-xc50-daint-mc-psmp_perf/index.html) are missing the results for RI-MP / RI-RPA. This is most likely because the regex mention in the [report](https://dashboard.cp2k.org/archive/cray-xc50-daint-gpu-psmp_perf/commit_43652b18e02f0ddc735b863d82c5e3e4fcef1a9d.txt) don't match any more:
```
 regex: Total RI-RPA Time= 
 regex: Estimated peak process memory 
 regex: Total MP2 Time= 
 regex: Estimated peak process memory 
```
I only noticed this by chance. In general it would have been better if the test failed entirely.

**Comment by fstein93** [comment]
I am responsible for #358. I have read access to the files on Daint. Due to error message in the slurm output, there is a truncated message from mpi_sendrecv in mp2_ri_gpw/compute_2c_integrals. The regtests are running. I have a look at it now.

**Comment by oschuett** [comment]
Fixed.
