### ISSUE TITLE
Possible memory leak in CP2k shell

### ISSUE THREAD

**Issue by nilsholle** [cp2k/cp2k#3777]
I try to run an MD simulation with ASE and CP2k. ASE uses the CP2k shell to control the calculation. Unfortunately, it seems that some data is not cleaned between calculations and accumulates over time:

![Memory usage with CP2k shell.](https://github.com/user-attachments/assets/4958446a-057a-4665-ae47-795f53f0a365)

The "plateaus" are due to intermediate calculations not related to CP2k. My current "solution" is to close and reopen the CP2k shell every few timesteps, which is of course not ideal.

I appended the input file generated by ASE, and of course I would be happy to provide any further details if needed.

[cp2k.zip](https://github.com/user-attachments/files/17746361/cp2k.zip)

**Comment by fstein93** [comment]
How did you compile CP2K (especially CP2K version, MPI version, Scalapack version)? Some implementations are known to leak. Compare [a](https://github.com/cp2k/cp2k/issues/1830), [b](https://groups.google.com/g/cp2k/c/BJ9c21ey0Ls), [c](https://groups.google.com/g/cp2k/c/uEodASnEFfQ).

**Comment by nilsholle** [comment]
Thank you very much for the quick response! The issue was indeed solved by updating to a newer MPI version (and to CP2k 2024.2).
