### ISSUE TITLE
Linking issue libxc

### ISSUE THREAD

**Issue by mbarbry** [cp2k/cp2k#397]
Dear CP2K developers,

I'm new using CP2K and I'm having issues compiling it. The problem that I'm facing is linking it against libxc. I get the following error,

    ~/cp2k/src/xc/xc_libxc_wrap.F:33:23:
    xc_f03_func_init, &
    Error: Symbol ‘xc_f03_func_set_ext_params’ referenced at (1) not found in module ‘xc_f03_lib_m’

and others of the same kind. I tried with my on installation of libxc (which worked well with other ab initio programs) and the automatic installation from the `./install_cp2k_toolchain.sh` script.

Running `grep` to check if the routine `xc_f03_func_init` is in libxc, I do find it in the library, but not in the module files present in the include directory

    grep -nri "xc_f03_func_init" ~/libxc-4.3.4/
    Binary file ~/libxc-4.3.4/lib/libxcf03.so.5.3.4 matches
    Binary file ~/libxc-4.3.4/lib/libxcf03.a matches

Do you have an idea of what goes wrong in my linking?

I'm trying to compile the master branch. I used the following option with the `install_cp2k_toolchain.sh` script

    ./install_cp2k_toolchain.sh --with-libxsmm=install --with-fftw=system --enable-cuda --enable-omp --gpu-ver=P100 --mpi-mode=no --with-libxc=~/libxc-4.3.4 --with-cmake=system

Below are the arch files

[local.sdbg.txt](https://github.com/cp2k/cp2k/files/3241269/local.sdbg.txt)
[local.sopt.txt](https://github.com/cp2k/cp2k/files/3241271/local.sopt.txt)
[local.ssmp.txt](https://github.com/cp2k/cp2k/files/3241272/local.ssmp.txt)

Best regards,
Marc

**Comment by dev-zero** [comment]
Apologies for not giving feedback earlier. For installation problems you may get a quicker response on [our forum](https://www.cp2k.org/howto:forum).

Please check whether there are additional error messages in the log, like warnings about the linker unable to open a referenced library for example. One possible source of error can be the use of the `~` in `--with-libxc=`: while variables like `$HOME` will be interpolated by the shell before passing the argument to the called command, are `~` and globs (`*`, `?`) passed along directly without expansion and then it depends on the executed command/script whether or not they are expanded.

**Comment by oschuett** [comment]
Closing, since there seems to be no real issue here.
