### ISSUE TITLE
OpenBLAS 0.3.5 bug on AVX512

### ISSUE THREAD

**Issue by robertschade** [cp2k/cp2k#409]
Dear All, 
the avx512-dgemm-kernel in OpenBLAS 0.3.5 is broken. See 
https://github.com/easybuilders/easybuild-easyconfigs/issues/8197
https://github.com/xianyi/OpenBLAS/pull/2061
Hence, we should either patch 0.3.5 in the toolchain or move to 0.3.6.
Best Wishes

**Comment by dev-zero** [comment]
Thanks for the hint, I think upgrade to 0.3.6 is the way to go

**Comment by dev-zero** [comment]
after talking to other people it seems 0.3.6 may still be affected by a similar issue, the only solution being to disable AVX512 completely for now

**Comment by dev-zero** [comment]
wrt 0.3.6, see:
https://github.com/xianyi/OpenBLAS/commit/7ed8431527eb00f161de4dd309fd4d2b6c885b0c
and
https://github.com/xianyi/OpenBLAS/commit/b1561ecc6864428baa4f1336d47d23729b9636f2
