### ISSUE TITLE
Regtest script, split runs and collect results

### ISSUE THREAD

**Issue by alazzaro** [cp2k/cp2k#419]
Currently, the regtest script runs the collection of results at the end, just after the run of the results:

https://github.com/cp2k/cp2k/blob/20ad1a1b303df6bd121f68b2a6f3c6a576bba03e/tools/regtesting/do_regtest#L1140

It turns out that this procedure is very inefficient on Daint since we run in batch and it is sequential (a slow because of disk access). Therefore I would propose to have two phases:

1) running of tests in parallel (i.e. in batch)
2) collection of results in sequential (i.e. on the login node)

This can be achieved by adding a new option to the regtest script, something like:

default (no option): runs tests and collect results
-collect=no: runs only tests
-collect=yes: only collect results

Any opinion?

**Comment by oschuett** [comment]
I've actually just started to rewrite the do_regtest script in Python. I should have a working version in a week or so. I propose we then incorporate your improvements there.

**Comment by oschuett** [comment]
Most tests have now switch to [do_regtest.py](https://github.com/cp2k/cp2k/blob/master/tools/regtesting/do_regtest.py), which offers the new `--keepalive` mode.
