### ISSUE TITLE
libxc warning "unstable" functional for untested

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#421]
libxc introduced the functionality to get a "stable/unstable" flag per functional.
Unfortunately this seems to be a tri-state at the moment: "stable/unstable/unknown", with almost all functionals being "unknown". In CP2K we're treating "unknown" (the absence of "stable") as "unstable", leading to the simplest (and most likely) stable functionals being reported as "unstable".
We must handle this differently. I see two possibilities at the moment:

1. remove the check again
2. treat "unknown" as "stable"

@fstein93 more ideas?

**Comment by fstein93** [comment]
I had a look at libxc's fortran API (libxc_master.f03, libxc 4.3.4 from toolchain). They provide two flags: XC_FLAGS_STABLE and XC_FLAGS_DEVELOPMENT. Only the second one is in use for a few functionals (BMK, KCIS, PBEh, PC07). Thus, I propose to use the second flag. If everybody is okay with this solution, I would set up the PR.
