### ISSUE TITLE
Toolchain: Netlib ScaLAPACK not disabled with MKL ScaLAPACK

### ISSUE THREAD

**Issue by OndrejMarsalek** [cp2k/cp2k#435]
In the toolchain, when MKL is available and its ScaLAPACK is found, Netlib ScaLAPACK is not disabled and still gets installed. The script `scripts/install_mkl.sh` writes `with_scalapack="__DONTUSE__"` into `build/setup_mkl` but as far as I can tell, that does not do anything. Perhaps this is needed as an update to `install/toolchain.conf` instead?

**Comment by oschuett** [comment]
Fixed via #1537.
