### ISSUE TITLE
Toolchain: lapack compilation error with INT_ETIME

### ISSUE THREAD

**Issue by ashermancinelli** [cp2k/cp2k#446]
`cat /etc/os-release`
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
Tried installing all with the main installer script, but failed with a generic error on the lapack installation, so I drilled down to the lapack installer.
The lapack installer in `tools/toolchain/scripts/install_reflapack.sh` tries to compile lapack with the value `TIMER = INT_ETIME` in the generated `make.inc` file, and I had to change to `TIMER = INT_CPU_TIME` to compile successfully. 
Can this variable be set based on the fortran compiler found or make this the default?

**Comment by dev-zero** [comment]
My apologies for not responding earlier: can you please also report the compiler vendor and version as well as the CP2K version plus the original error message?

**Comment by dev-zero** [comment]
While it is ok to have a workaround for an issue we can not apply this if we don't know when we have to. Closing due to missing feedback.
