### ISSUE TITLE
SIRIUS: Use normal CP2K input sections

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#45]
Currently PW_DFT uses json-sections instead of normal CP2K input sections.
This leads to input files with mixed format:
```
&MIXER
   "type" : "broyden1",
   "max_history" : 8
&END MIXER
```
that also lack common [documention](https://manual.cp2k.org/trunk/CP2K_INPUT/FORCE_EVAL/PW_DFT/MIXER.html).

It would be nice if SIRIUS somehow exported its input metadata, which could then be translated into normal CP2K input section.

**Comment by mtaillefumier** [comment]
This was never intended to used openly actually. We can set up everything with the api but it was decided to use SIRIUS input like style instead. This is something that should be decided higher up since it was not my choice in the first place. Writing documentation for sirius input is on our todo list though.

**Comment by mkrack** [comment]
I don't think that such a mixed input format is desirable.

**Comment by mtaillefumier** [comment]
I am working on in the input stuff. I already have most of the code ready.

**Comment by mtaillefumier** [comment]
Should be fixed with my actual pull request. I will work on the problems as soon as I have few hours this week. Do not close it this issue yet

**Comment by mtaillefumier** [comment]
Ok solved with my latest pull request.

**Comment by dev-zero** [comment]
This was solved, closing.
One of the drawbacks of generating the input section by dynamically querying the library is that the CP2K input can change when the library changes its keywords, see #319
