### ISSUE TITLE
Variable "use_virial" is used before it is defined

### ISSUE THREAD

**Issue by alazzaro** [cp2k/cp2k#473]
As a consequence of the #440, CCE test complaints with a CPASSERT at line

https://github.com/cp2k/cp2k/blob/d1f014fd1c6040e6cc57210034decd5105b5f57f/src/xtb_ehess.F#L215

CCE reports that the variable `use_virial` is actually not initialized

**Comment by juerghutter** [comment]
solved with commit 7e3d4803ff4479f8a0d749ff9141d5a61adcdc23
