### ISSUE TITLE
[auto_regtest] removal (of svn2cl)

### ISSUE THREAD

**Issue by alazzaro** [cp2k/cp2k#51]
By using the github search in the repository, I see that there are  

25 code results

https://github.com/cp2k/cp2k/search?q=svn&unscoped_q=svn

Besides the legacy reference in some scripts, for example:

`cp2k/tools/build_utils/get_revision_number`

there are other scripts that can probably be removed, for example:

`cp2k/tools/svn2cl`

**Comment by dev-zero** [comment]
`svn2cl` is used in the `auto_regtest` script which itself seems to rely rather heavily on SVN.
@oschuett @ibethune ideas?

**Comment by oschuett** [comment]
Yes, many of the `auto_regtest` scripts seem obsolete now with the dashboard and git in place. Maybe @mkrack can comment?

**Comment by mkrack** [comment]
Though it seems the scripts in auto_regtest were developed based on my the autoregtester scripts which I am still using locally, I have neither contributed to the development or maintenance of these scripts nor I have used them in the current form. So these scripts might be indeed obsolete unless somebody else still uses them.

**Comment by oschuett** [comment]
Oh, indeed they were committed by @ibethune. So, I guess we can simple remove that dir then.

**Comment by mkrack** [comment]
As far as I am concerned, yes.

**Comment by ibethune** [comment]
Yes, the auto_regtest scripts were what was running at EPCC, they can now be safely deleted.
