### ISSUE TITLE
[manual] cp2k_input.xsl and cp2k_runs.F out-of-sync

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#518]
https://github.com/cp2k/cp2k/blob/ac91bc3e391836d11dfbe433cf78948e2fca5fda/src/start/cp2k_runs.F#L931-L933

https://github.com/cp2k/cp2k/blob/ac91bc3e391836d11dfbe433cf78948e2fca5fda/tools/manual/cp2k_input.xsl#L41-L43

the `--html-manual` obviously uses `cp2k_runs.F` while https://manual.cp2k.org seems to use the XSL:

![manual-screenshot](https://user-images.githubusercontent.com/11307/63515758-df0c6180-c4eb-11e9-9155-fa0775afc1ea.png)

**Comment by oschuett** [comment]
I think we should simply remove the `--html-manual` option.

**Comment by mkrack** [comment]
--html-manual was more or less superseded by --xml. There is clearly a redundancy for some time now. --xml is more lean and versatile. HTML pages generated via Fortran WRITE statements are certainly not a good solution. I agree with @oschuett , we should get rid of --html-manual if possible.

**Comment by dev-zero** [comment]
there we go
