### ISSUE TITLE
Document  libcp2k usage

### ISSUE THREAD

**Issue by ocaisa** [cp2k/cp2k#53]
We have a user at Juelich Supercomputing Centre who wants to use libcp2k but I'm unsure how exactly we provide an installation of this. Is it enough to provide `libcp2k.a` in the `LD_LIBRARY_PATH` and `libcp2k.h`in the `CPATH`? For a Fortran user do I just add `libcp2k.mod` in the `CPATH` or would I require additional `.mod` files?

We use EasyBuild for our installations, if you're interested the relevant rules for CP2K are at https://github.com/easybuilders/easybuild-easyblocks/blob/develop/easybuild/easyblocks/c/cp2k.py

**Comment by dev-zero** [comment]
After building `libcp2k` explicitly using `make ARCH=local VERSION=sopt libcp2k`, it should be sufficient to put `libcp2k.a` in the library path and the header and the `libcp2k.mod` in the include path, yes.

**Comment by dev-zero** [comment]
for further support, please use our [Google Group](https://groups.google.com/group/cp2k)

**Comment by oschuett** [comment]
Should we add a section to [INSTALL.md](https://github.com/cp2k/cp2k/blob/master/INSTALL.md) or rather create a dedicated wiki page?

**Comment by ocaisa** [comment]
I should add here that it looks like `libcp2k.a` and `libcp2k.h` are all that's needed for C interfaces but if you want Fortran you will need a number of the `.mod` files, it was too much effort to figure out which ones (and probably a moving target) so we just included them all.

**Comment by oschuett** [comment]
Yeah, the `.mod` files reference each other. I'm not sure there is a good solution for it :-/

So, it seems a short paragraph in [INSTALL.md](https://github.com/cp2k/cp2k/blob/master/INSTALL.md) is sufficient then. Do you want to send in a PR?

**Comment by ocaisa** [comment]
I could..should I target `2s` or`3c` as the place to make the addition? (Left to my own devices, I probably would choose `3c`)

**Comment by oschuett** [comment]
Yes, `3c` is good.
