### ISSUE TITLE
CP2K prints wrong source code revision number

### ISSUE THREAD

**Issue by pseewald** [cp2k/cp2k#531]
Steps to reproduce:

1. compile cp2k development version
2. run cp2k executable with `--version`
3. change and `git commit` any file in `src`
5. recompile cp2k
6. run cp2k executable with `--version`

The last step shows that the version number has not been updated.

Probably [this line](https://github.com/cp2k/cp2k/blob/master/Makefile#L431) does not work as intended.

**Comment by oschuett** [comment]
Yep: https://github.com/cp2k/cp2k/issues/16
