### ISSUE TITLE
CPP in arch file

### ISSUE THREAD

**Issue by alazzaro** [cp2k/cp2k#532]
If I do set (to gcc) or no declared CPP in the arch file, I get the following error:
```
*** The MPI_Comm_f2c() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
```
whenever I run PSMP version.
The only way to get it to work is to use
```
CPP =
```
in the arch file. From what I see, we only test this case in the dashboard, so my conclusion is that there is something wrong and untested with CPP. Should we remove this variable at all?

**Comment by oschuett** [comment]
AFAIK, this was needed on IBM machines because the Fortran compiler there didn't have a built in preprocessor. I don't know if this is still the case?

**Comment by alazzaro** [comment]
I assume you are referring to the IBM XL compiler. 
Well, no idea it is still the case. I cannot access to the old test:

https://dashboard.cp2k.org/archive/epcc-juqueen-popt/index.html

In any case, the confusion is that you have to explicitly set  `CPP = <empty>` in the arch, otherwise it doesn't work... It would be to include the case when CPP is not declared at all.

**Comment by oschuett** [comment]
> I cannot access to the old test:

Yes, I did not convert them after we switched to git. In any case, JUQEEN was decomissioned last year. Now we should check e.g. Summit. Maybe @mtaillefumier can comment? IIRC, he was running on Summit.

> It would be to include the case when CPP is not declared at all.

If we have to keep it then we should definitely give it a default value.

Related: https://github.com/cp2k/cp2k/issues/344.

**Comment by mtaillefumier** [comment]
It is not summit related. You can not compile CP2K without defining CPP to empty. By default it seems that cp2k is difficult to compile when using the default **cpp**

**Comment by oschuett** [comment]
@trudeaun thanks for clarifying. So, then let's remove the `CPP` variable from `Makefile` and the arch files.
