### ISSUE TITLE
compile fails for current master for rpa_ri_gpw.F

### ISSUE THREAD

**Issue by recohen** [cp2k/cp2k#542]
dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(105): error #6580: Name in only-list does not exist or is not accessible.   [LAPLACE_MINIMAX_APPROX]
   USE mp2_laplace,                     ONLY: laplace_minimax_approx
----------------------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(131): error #6580: Name in only-list does not exist or is not accessible.   [COMMUNICATE_BUFFER]
   USE rpa_im_time,                     ONLY: communicate_buffer,&
----------------------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(133): error #6580: Name in only-list does not exist or is not accessible.   [GAP_AND_MAX_EIG_DIFF_KPOINTS]
                                              gap_and_max_eig_diff_kpoints,&
----------------------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(134): error #6580: Name in only-list does not exist or is not accessible.   [GET_MAT_3C_OVERL_INT_GW]
                                              get_mat_3c_overl_int_gw,&
----------------------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(538): error #6460: This is not a field name that is defined in the encompassing structure.   [DO_GW_IM_TIME]
      IF (my_do_gw .OR. mp2_env%ri_rpa_im_time%do_gw_im_time) THEN
-----------------------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(539): error #6460: This is not a field name that is defined in the encompassing structure.   [SCALING]
         ext_scaling = mp2_env%ri_g0w0%scaling
---------------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(542): error #6460: This is not a field name that is defined in the encompassing structure.   [STOP_CRIT]
         stop_crit = mp2_env%ri_g0w0%stop_crit
-------------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(2211): error #6460: This is not a field name that is defined in the encompassing structure.   [NORMALIZE_SIGMA]
      do_normalize_Sigma = mp2_env%ri_g0w0%normalize_sigma
-------------------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(2212): error #6460: This is not a field name that is defined in the encompassing structure.   [NEGLECT_NORM]
      do_neglect_norm = mp2_env%ri_g0w0%neglect_norm
----------------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(2267): error #6460: This is not a field name that is defined in the encompassing structure.   [N_GROUP_RI_ORIG]
         ngroup_RI_orig = mp2_env%ri_rpa_im_time_util(1)%n_group_RI_orig
---------------------------------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(2673): error #6460: This is not a field name that is defined in the encompassing structure.   [CONTOUR_DEF_START]
            IF(.NOT.(mp2_env%ri_g0w0%contour_def_start == -1))CALL cp__a("rpa_ri_gpw.F",2673)
-------------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(2674): error #6460: This is not a field name that is defined in the encompassing structure.   [CONTOUR_DEF_END]
            IF(.NOT.(mp2_env%ri_g0w0%contour_def_end == -1))CALL cp__a("rpa_ri_gpw.F",2674)
-------------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(2779): error #6632: Keyword arguments are invalid without an explicit interface.   [DO_BETA]
                                            mat_3c_overl_nnP_ic_reflected_beta, qs_env, unit_nr, do_beta=.TRUE.)
-------------------------------------------------------------------------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(2827): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [DO_KPOINTS_CUBIC_RPA]
         CALL setup_mat_for_mem_cut_3c(mat_3c_overl_int_cut, mat_3c_overl_int, cut_memory, cut_RI, &
--------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(2827): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [DO_GW_IM_TIME]
         CALL setup_mat_for_mem_cut_3c(mat_3c_overl_int_cut, mat_3c_overl_int, cut_memory, cut_RI, &
--------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(2827): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [NUM_3C_REPL]
         CALL setup_mat_for_mem_cut_3c(mat_3c_overl_int_cut, mat_3c_overl_int, cut_memory, cut_RI, &
--------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(2837): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [DO_KPOINTS_CUBIC_RPA]
            CALL setup_mat_for_mem_cut_3c(mat_3c_overl_int_mao_for_occ_cut, mat_3c_overl_int_mao_for_occ, &
-----------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(2837): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [DO_GW_IM_TIME]
            CALL setup_mat_for_mem_cut_3c(mat_3c_overl_int_mao_for_occ_cut, mat_3c_overl_int_mao_for_occ, &
-----------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(2837): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [NUM_3C_REPL]
            CALL setup_mat_for_mem_cut_3c(mat_3c_overl_int_mao_for_occ_cut, mat_3c_overl_int_mao_for_occ, &
-----------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(2840): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [DO_KPOINTS_CUBIC_RPA]
            CALL setup_mat_for_mem_cut_3c(mat_3c_overl_int_mao_for_virt_cut, mat_3c_overl_int_mao_for_virt, &
-----------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(2840): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [DO_GW_IM_TIME]
            CALL setup_mat_for_mem_cut_3c(mat_3c_overl_int_mao_for_virt_cut, mat_3c_overl_int_mao_for_virt, &
-----------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(2840): error #6631: A non-optional actual argument must be present when invoking a procedure with an explicit interface.   [NUM_3C_REPL]
            CALL setup_mat_for_mem_cut_3c(mat_3c_overl_int_mao_for_virt_cut, mat_3c_overl_int_mao_for_virt, &
-----------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(3252): error #6351: The number of subscripts is incorrect.   [VEC_SIGMA_X_MINUS_VXC_GW]
                                          mp2_env%ri_g0w0%vec_Sigma_x_minus_vxc_gw(n_level_gw_ref, 1)
----------------------------------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(3270): error #6351: The number of subscripts is incorrect.   [VEC_SIGMA_X_MINUS_VXC_GW]
                                                  mp2_env%ri_g0w0%vec_Sigma_x_minus_vxc_gw(n_level_gw_ref, 2)
------------------------------------------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(3337): error #6460: This is not a field name that is defined in the encompassing structure.   [MIX_EXCHANGE]
         do_mix_exchange = mp2_env%ri_g0w0%mix_exchange
-------------------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(3343): error #6460: This is not a field name that is defined in the encompassing structure.   [FRAC_EXX]
               frac_rix = 1.0_dp-mp2_env%ri_g0w0%frac_exx
-------------------------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(3408): error #6351: The number of subscripts is incorrect.   [VEC_SIGMA_X_MINUS_VXC_GW]
            mp2_env%ri_g0w0%vec_Sigma_x_minus_vxc_gw(:, 1) = &
----------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(3409): error #6351: The number of subscripts is incorrect.   [VEC_SIGMA_X_MINUS_VXC_GW]
               mp2_env%ri_g0w0%vec_Sigma_x_minus_vxc_gw(:, 1)+ &
-------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(3408): error #6366: The shapes of the array expressions do not conform.   [VEC_SIGMA_X_MINUS_VXC_GW]
            mp2_env%ri_g0w0%vec_Sigma_x_minus_vxc_gw(:, 1) = &
----------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(3416): error #6351: The number of subscripts is incorrect.   [VEC_SIGMA_X_MINUS_VXC_GW]
               mp2_env%ri_g0w0%vec_Sigma_x_minus_vxc_gw(:, 2) = &
-------------------------------^
/tmp/di25fix3/ifortcrcEzk.i90(12800): catastrophic error: Too many errors, exiting
compilation aborted for rpa_ri_gpw.F90 (code 1)
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/Makefile:454: recipe for target 'rpa_ri_gpw.o' failed
make[3]: *** [rpa_ri_gpw.o] Error 1
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/Makefile:133: recipe for target 'all' failed
make[2]: *** [all] Error 2
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/Makefile:122: recipe for target 'psmp' failed
make[1]: *** [psmp] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
di25fix3@login03:~/CP2K/cp2k>

**Comment by oschuett** [comment]
According to our [tests](https://dashboard.cp2k.org) everything is working. Could you try once `make distclean` ? If the problem persists please post the arch file and the SHA of the commit you used.

**Comment by recohen** [comment]
Thank you so much! I tried distclean and make again and it failed again the same way.

make distclean


make  ARCH=Linux-x86-64-intel  VERSION=psmp


…

mpipiifort -c -D__MKL -D__FFTW3 -D__LIBXSMM -D__parallel -D__SCALAPACK -D__ELPA=201905 -D__LIBXC -D__LIBINT -D__LIBINT_MAX_AM=7 -D__LIBDERIV_MAX_AM1=6 -D__MAX_CONTR=4 -xHost -O3 -fopenmp -funroll-loops -fpp -free -fp-model precise -g -traceback -I/lrz/sys/intel/studio2019_u4/compilers_and_libraries_2019.4.243/linux/mkl/include -I/lrz/sys/intel/studio2019_u4/compilers_and_libraries_2019.4.243/linux/mkl/include/fftw -I/dss/dsshome1/lrz/sys/spack/release/19.1/opt/x86_avx512/libxsmm/1.10-intel-d5ymttv/include -I/dss/dsshome1/lrz/sys/spack/release/19.1/opt/x86_avx512/libxc/4.3.3-intel-r7num47/include -I/dss/dsshome1/0E/di25fix3/include -I/dss/dsshome1/lrz/sys/spack/release/19.1/opt/x86_avx512/elpa/2019.05.001-intel-bpwrlcy/include/elpa_openmp-2019.05.001/modules -I/dss/dsshome1/lrz/sys/spack/release/19.1/opt/x86_avx512/elpa/2019.05.001-intel-bpwrlcy/include/elpa_openmp-2019.05.001/elpa -D__COMPILE_ARCH="\"Linux-x86-64-intel\"" -D__COMPILE_DATE="\"Thu Sep  5 23:09:01 CEST 2019\"" -D__COMPILE_HOST="\"login03\"" -D__COMPILE_REVISION="\"git:9891594\"" -D__DATA_DIR="\"/dss/dsshome1/0E/di25fix3/CP2K/cp2k/data\"" -D__SHORT_FILE__="\"rpa_ri_gpw.F\"" -I'/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/' -I'/dss/dsshome1/0E/di25fix3/CP2K/cp2k/obj/Linux-x86-64-intel/psmp/exts/dbcsr' rpa_ri_gpw.F90
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(105): error #6580: Name in only-list does not exist or is not accessible.   [LAPLACE_MINIMAX_APPROX]
   USE mp2_laplace,                     ONLY: laplace_minimax_approx
----------------------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(131): error #6580: Name in only-list does not exist or is not accessible.   [COMMUNICATE_BUFFER]
   USE rpa_im_time,                     ONLY: communicate_buffer,&
----------------------------------------------^
/dss/dsshome1/0E/di25fix3/CP2K/cp2k/src/rpa_ri_gpw.F(133): error #6580: Name in only-list does not exist or is not accessible.   [GAP_AND_MAX_EIG_DIFF_KPOINTS]
                                              gap_and_max_eig_diff_kpoints,&

The SHA is:
git log
commit 9891594724b793180801bde6d0b5783920474f52
Author: Tiziano Müller <tiziano.mueller@chem.uzh.ch>
Date:   Wed Sep 4 14:54:47 2019 +0200


TThe make line is:
make  ARCH=Linux-x86-64-intel  VERSION=psmp


The arch file is attached.

Sincerely,

Ron

**Comment by fstein93** [comment]
What have you done to obtain the (latest) files? I am asking because the file rpa_ri_gpw.F does not exist anymore in the latest trunk. (see commit 9317ff0 in PR #412)

**Comment by recohen** [comment]
Aha.I did:

git pull https://github.com/cp2k/cp2k.git master

I guess that does not delete removed files.

But I read that git pull should remove deleted files?

Sincerely,

Ron

---
Ronald Cohen
Extreme Materials Initiative
Geophysical Laboratory
Carnegie Institution
5251 Broad Branch Rd., N.W.
Washington, D.C. 20015
rcohen@carnegiescience.edu <mailto:rcohen@carnegiescience.edu>
office: 202-478-8937
skype: ronaldcohen
twitter: @recohen3

**Comment by recohen** [comment]
I see—it did delete the file, but I am rsyncihng to a supercomputer that does not have git access. I thought I rsynced to an empty source, but apparently not!

Thanks for your help!

Sincerely,

Ron

---
Ronald Cohen
Extreme Materials Initiative
Geophysical Laboratory
Carnegie Institution
5251 Broad Branch Rd., N.W.
Washington, D.C. 20015
rcohen@carnegiescience.edu <mailto:rcohen@carnegiescience.edu>
office: 202-478-8937
skype: ronaldcohen
twitter: @recohen3

**Comment by dev-zero** [comment]
`rsync` needs an extra option to remove files on the target which don't exist on the source since it can potentially be disastrous if you have a typo/error in your command line (use `setopt -o noundef` in your scripts)

On 6 September 2019 16:00:11 CEST, Ronald Cohen <notifications@github.com> wrote:
>I see—it did delete the file, but I am rsyncihng to a supercomputer
>that does not have git access. I thought I rsynced to an empty source,
>but apparently not!>
>>
>Thanks for your help!>
>>
>Sincerely,>
>>
>Ron>
>>
>--->
>Ronald Cohen>
>Extreme Materials Initiative>
>Geophysical Laboratory>
>Carnegie Institution>
>5251 Broad Branch Rd., N.W.>
>Washington, D.C. 20015>
>rcohen@carnegiescience.edu <mailto:rcohen@carnegiescience.edu>>
>office: 202-478-8937>
>skype: ronaldcohen>
>twitter: @recohen3>
>>
>> On Sep 6, 2019, at 1:48 AM, Frederick Stein
><notifications@github.com> wrote:>
>> >
>> rpa_ri_gpw.F>
>>
>>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/cp2k/cp2k/issues/542#issuecomment-528866330

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by recohen** [comment]
I don’t know if I should start a new thread on this, but now it compiles, but fails after a single cycle
of MD on water at high pressures. Ihave tried 1 OMP thread, no elpa, and different number of nodes
to check for memory issues but they all fail the same:

Step     Update method      Time    Convergence         Total energy    Change
  ------------------------------------------------------------------------------
     1 OT DIIS     0.15E+00    0.5     0.00000853     -1111.5581966437 -1.11E+03

  *** SCF run converged in     1 steps ***


  Electronic density on regular grids:       -512.0000000016       -0.0000000016
  Core density on regular grids:              511.9999999836       -0.0000000164
  Total charge density on r-space grids:       -0.0000000180
  Total charge density g-space grids:          -0.0000000180

  Overlap energy of the core charge distribution:               0.00001037749297
  Self energy of the core charge distribution:              -2838.21791979120962
  Core Hamiltonian energy:                                    836.75826385004586
  Hartree energy:                                            1174.77689502164276
  Exchange-correlation energy:                               -288.13418702956056
  Dispersion energy:                                            3.25874092788224

  Total energy:                                             -1111.55819664370665

  outer SCF iter =    1 RMS gradient =   0.85E-05 energy =      -1111.5581966437
  outer SCF loop converged in   1 iterations or    1 steps


===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 144 PID 49240 RUNNING AT i01r01c04s08
=   KILLED BY SIGNAL: 9 (Killed)

err file:

forrtl: severe (174): SIGSEGV, segmentation fault occurred

…
*** Error in `/dss/dsshome1/0E/di25fix3/bin/cp2k.psmp': corrupted double-linked list: 0x000000001b46dac0 ***
forrtl: severe (174): SIGSEGV, segmentation fault occurred
*** Error in `/dss/dsshome1/0E/di25fix3/bin/cp2k.psmp': double free or corruption (!prev): 0x000000
…
/lrz/sys/intel/studio2019_u4/compilers_and_libraries_2019.4.243/linux/compiler/lib/intel64/libiomp5.so(+0xe830b)[0x2a
af659d630b]
/lib64/libpthread.so.0(+0x8724)[0x2aaf62822724]
/lib64/libc.so.6(+0x79646)[0x2b6054405646]
00400000-18e4f000 r-xp 00000000 00:30 2018798829                         /dss/dsshome1/0E/di25fix3/bin/cp2k.psmp
1904e000-19080000 r--p 18a4e000 00:30 2018798829                         /dss/dsshome1/0E/di25fix3/bin/cp2k.psmp
19080000-19417000 rw-p 18a80000 00:30 2018798829                         /dss/dsshome1/0E/di25fix3/bin/cp2k.psmp
1

I am using the latest intel compiler and mkl suite.

I ran the regtests for 30 minutes (I can vrun longer but would go in a slower queue)
and most passed so far (up to 25 of 241)

I ONLY SEE FAILS IN PIMD:

06-29/tests/Pimd/regtest-2
    water-micro-helium.inp                                1.071348962019063E-003     OK (  29.05 sec)
    water-micro-helium-therminit.inp                                                     RUNTIME FAIL
    w512_pint_nose.inp                                          9.57807115302091     OK (   1.60 sec)
    w512_pint_gle.inp                                          -3.56464970020227     OK (   2.45 sec)
    w512_pint_pile.inp                                          3.10799805735345     OK (   3.25 sec)
    w512_pint_piglet.inp                                        218.991146527087     OK (  21.34 sec)
    w512_pint_qtb_fp0.inp                                       3.10971526265291     OK (   3.59 sec)
    w512_pint_qtb_fp1.inp                                       3.11027040180356     OK (   3.67 sec)
    w512_pint_qtb_fp1-1.restart                                 8.51704405380519     OK (   4.07 sec)
    centroid_velocity_init.inp                                 0.329997519912023     OK (   0.34 sec)
    he32_density.inp                                                                     RUNTIME FAIL
    he32_only_worm.inp                                                                   RUNTIME FAIL
    he32_only_worm_restart.inp                                                           RUNTIME FAIL
    water-in-helium-worm.inp                             -4.231359480085733E-004     OK (  17.88 sec)
    water-in-helium-striding.inp                          9.215502797214617E-002     OK (  18.07 sec)



Sincerely,

Ron


---
Ronald Cohen
Extreme Materials Initiative
Geophysical Laboratory
Carnegie Institution
5251 Broad Branch Rd., N.W.
Washington, D.C. 20015
rcohen@carnegiescience.edu <mailto:rcohen@carnegiescience.edu>
office: 202-478-8937
skype: ronaldcohen
twitter: @recohen3

**Comment by recohen** [comment]
I recompiled with -O2 and took out “precide” it works now!
So -O3 has a problem it seems.

Ron

---
Ronald Cohen
Extreme Materials Initiative
Geophysical Laboratory
Carnegie Institution
5251 Broad Branch Rd., N.W.
Washington, D.C. 20015
rcohen@carnegiescience.edu <mailto:rcohen@carnegiescience.edu>
office: 202-478-8937
skype: ronaldcohen
twitter: @recohen3

**Comment by recohen** [comment]
Unfortunately it dies after about 3300 steps:

with
*******************************************************************************
 *             MPI error 672742415 in mpi_cart_sub @ mp_cart_sub : Other MPI   *
 *   ___         error, error stack:
PMPI_Cart_sub(228)..................:     *
 *  /   \        MPI_Cart_sub(comm=0xc4040010, remain_dims=0x7f200ce27e80,     *
 * [ABORT]                       comm_new=0x2b5549318b64)                      *
 *  \___/              failed
PMPI_Cart_sub(167)..................:            *
 *    |
MPIR_Comm_split_impl(253)...........:               *
 *  O/|
MPIR_Get_contextid_sparse_group(604): Too many communicators   *
 * /| |                 (0/32768 free on this process; ignore_id=0)            *
 * / \                                                    dbcsr_mpiwrap.F:1098 *
 *******************************************************************************


 ===== Routine Calling Stack =====

           14 mp_cart_sub
           13 dbcsr_complete_redistribute
           12 copy_dbcsr_to_fm
           11 cp_dbcsr_sm_fm_multiply
           10 make_basis_sm
            9 reorthogonalize_vectors
            8 wfi_extrapolate
            7 scf_env_initial_rho_setup
            6 init_scf_run
            5 qs_energies
            4 qs_forces
            3 velocity_verlet
            2 qs_mol_dyn_low
            1 CP2K

---
Ronald Cohen
Extreme Materials Initiative
Geophysical Laboratory
Carnegie Institution
5251 Broad Branch Rd., N.W.
Washington, D.C. 20015
rcohen@carnegiescience.edu <mailto:rcohen@carnegiescience.edu>
office: 202-478-8937
skype: ronaldcohen
twitter: @recohen3
