### ISSUE TITLE
cp2k.psmp compilation freezes when mp2_ri_gpw.F90 is compiling

### ISSUE THREAD

**Issue by ldgibson** [cp2k/cp2k#547]
When I try compiling `cp2k.psmp`, the compilation runs until `mp2_ri_gpw.F90` is reached, and then it hangs. I have tried leaving it overnight to see if it continues compiling (~12 hours), but it never completes and the job times out. I am trying to build on CentOS 7 with Intel compilers. When I run `lscpu`, this is my output:

```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
On-line CPU(s) list:   0-39
Thread(s) per core:    1
Core(s) per socket:    20
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz
Stepping:              7
CPU MHz:               2100.000
BogoMIPS:              4200.00
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              1024K
L3 cache:              28160K
NUMA node0 CPU(s):     0-19
NUMA node1 CPU(s):     20-39
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36
 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art
 arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni 
pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca 
sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 
3dnowprefetch epb cat_l3 cdp_l3 intel_pt ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow 
vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm 
mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl 
xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida 
arat pln pts hwp_epp pku ospke avx512_vnni spec_ctrl intel_stibp flush_l1d arch_capabilities
```

And this is the arch file that I am using to build `cp2k.psmp`:
```make
LIBROOT=/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_06-09-2019/tools/toolchain/install

CC          = mpiicc
CXX         = mpiicpc
CPP         =
AR          = ar -r
FC          = mpiifort
LD          = mpiifort
#
DFLAGS      = -D__BLACS -D__INTEL -D__MKL -D__LIBXSMM  -D__parallel  -D__FFTW3 \
              -D__LIBINT -D__LIBINT_MAX_AM=6 -D__LIBDERIV_MAX_AM1=5 -D__LIBXC \
              -D__SCALAPACK
#
WFLAGS      =
#
FCDEBFLAGS  =
CFLAGS      =    -O2 -fopenmp -m64 \
                -I$(MKLROOT)/include \
                -I$(MKLROOT)/include/fftw \
                -I$(LIBROOT)/libint-1.1.6/include \
                -I$(LIBROOT)/libxc-4.0.3/include \
                -I$(LIBROOT)/libxsmm-1.9.0/include \
                $(DFLAGS)
FCFLAGS     =    -O2 -fopenmp -fpp -free -fp-model precise -g -traceback -m64 \
                -I$(MKLROOT)/include \
                -I$(MKLROOT)/include/fftw \
                -I$(LIBROOT)/libint-1.1.6/include \
                -I$(LIBROOT)/libxc-4.0.3/include \
                -I$(LIBROOT)/libxsmm-1.9.0/include \
                $(FCDEBFLAGS) $(WFLAGS) $(DFLAGS)
#
LDFLAGS     = $(FCFLAGS) -static-intel
LDFLAGS_C   = $(FCFLAGS) -static-intel -nofor_main
LIBS        = -Wl,--start-group \
                $(MKLROOT)/lib/intel64/libmkl_scalapack_lp64.a \
                $(MKLROOT)/lib/intel64/libmkl_gf_lp64.a \
                $(MKLROOT)/lib/intel64/libmkl_sequential.a \
                $(MKLROOT)/lib/intel64/libmkl_core.a \
                $(MKLROOT)/lib/intel64/libmkl_blacs_intelmpi_lp64.a \
                -Wl,--end-group -lpthread -lm

LIBS       += -L'/gscratch/sw/intel-2019/compilers_and_libraries_2019.0.117/linux/mpi/intel64/lib/release' -lmpi -lmpicxx
LIBS       += -L$(LIBROOT)/libxsmm-1.9.0/lib -lxsmmf -lxsmm -ldl
LIBS       += -L$(LIBROOT)/libxc-4.0.3/lib -lxcf03 -lxc
LIBS       += -L$(LIBROOT)/libint-1.1.6/lib -lderiv -lint -lstdc++

# Required due to memory leak that occurs if high optimisations are used
mp2_optimize_ri_basis.o: mp2_optimize_ri_basis.F
             $(FC) -c $(subst O2,O0,$(FCFLAGS)) $<
```

This arch file comes from me adjusting the output from the `install_cp2k_toolchain.sh` after installing libxsmm, libxc, and libint to more closely match `Linux-x86-64-intel.psmp`

If it is helpful, this is the output from running `mpirun --version`:
```
Intel(R) MPI Library for Linux* OS, Version 2019 Build 20180829 (id: 15f5d6c0c)
Copyright 2003-2018, Intel Corporation.
```
and `mpiifort --version`:
```
ifort (IFORT) 19.0.0.117 20180804
Copyright (C) 1985-2018 Intel Corporation.  All rights reserved.
```

Is there anything wrong with my arch file that could lead to this behavior that I am seeing?

Thank you

**Comment by alazzaro** [comment]
So, we found that the version of your compile (19.0.0) is broken with CP2K (see https://www.cp2k.org/dev:compiler_support). However, you are facing another specific problem. I think you can reduce the level of optimizations for the fle `mp2_ri_gpw.F` by adding the following at the end of the arch file:

```
mp2_ri_gpw.o: mp2_ri_gpw.F
$(FC) -c $(subst O2,O1,$(FCFLAGS)) $<
```

Try with O1, if still fails move to O0. 
The file `mp2_ri_gpw.F` is pretty large and thee compiler get stuck to optimize it. Likely there can be other files with the same problem.

**Comment by ldgibson** [comment]
I tried adding your suggested lines to the arch file, which did get the compilation past `mp2_ri_gpw.F`, but the following file also got stuck (`mp2_ri_grad.F`). I then tried the same thing as you suggested for that file, but it never finished compiling.

These are the lines that I added:
```make
mp2_ri_gpw.o: mp2_ri_gpw.F
             $(FC) -c $(subst O2,O0,$(FCFLAGS)) $<
mp2_ri_grad.o: mp2_ri_grad.F
             $(FC) -c $(subst O2,O0,$(FCFLAGS)) $<
```

Instead of completing the compilation for `mp2_ri_grad.F`, I received the following error:
```
ifort: error #10106: Fatal error in /gscratch/sw/intel-2019/compilers_and_libraries_2019.0.117/linux/bin/intel64/fortcom, terminated by kill signal
compilation aborted for pao_param_linpot.F90 (code 1)
make[3]: *** [pao_param_linpot.o] Error 1
make[3]: *** Waiting for unfinished jobs....
```
I will try to compile with another compiler instead of Intel and report back.

**Comment by alazzaro** [comment]
As I told you, we found that 19.0.0 compiler is somehow broken, so it can that you see errors.
The list of tested compilers is at:

https://www.cp2k.org/dev:compiler_support

**Comment by ldgibson** [comment]
Thank you for the help so far. I have changed to gcc 6.2.0 (which I see is a compatible compiler in the list you linked me) with mpich 3.2. However, I am getting errors which seem to be related to undefined references in openblas and scalapack, but I am unsure and have attached the output from `make -j 4 ARCH=local VERSION=psmp`: [make_gcc_psmp.txt](https://github.com/cp2k/cp2k/files/3598237/make_gcc_psmp.txt)

I am also using the exact arch file that was generated by the toolchain:

CC          = mpicc
CXX         = mpicxx
CPP         =
AR          = ar -r
FC          = mpif90
LD          = mpif90

DFLAGS      = -D__LIBXSMM  -D__parallel  -D__FFTW3  -D__LIBINT -D__LIBINT_MAX_AM=6 -D__LIBDERIV_MAX_AM1=5 -D__LIBXC -D__SCALAPACK

WFLAGS      = -Werror=aliasing -Werror=ampersand -Werror=c-binding-type -Werror=intrinsic-shadow -Werror=intrinsics-std -Werror=line-truncation -Werror=tabs -Werror=realloc-lhs-all -Werror=target-lifetime -Werror=underflow -Werror=unused-but-set-variable -Werror=unused-variable -Werror=unused-dummy-argument -Werror=conversion -Werror=zerotrip -Werror=uninitialized -Wno-maybe-uninitialized -Wuse-without-only

FCDEBFLAGS  = -ffree-form -std=f2003 -fimplicit-none
CFLAGS      = -march=native -fno-omit-frame-pointer -g  -O3 -funroll-loops -ffast-math $(PROFOPT) -fopenmp   -I'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/openblas-0.2.20/include' -I'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/fftw-3.3.7/include' -I'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libint-1.1.6/include' -I'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libxc-4.0.3/include' -I'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libxsmm-1.9.0/include' $(DFLAGS)
FCFLAGS     = -march=native -fno-omit-frame-pointer -g  -O3 -funroll-loops -ffast-math $(PROFOPT) -fopenmp   -I'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/openblas-0.2.20/include' -I'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/fftw-3.3.7/include' -I'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libint-1.1.6/include' -I'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libxc-4.0.3/include' -I'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libxsmm-1.9.0/include' $(FCDEBFLAGS) $(WFLAGS) $(DFLAGS)
LDFLAGS     = $(FCFLAGS) -Wl,--enable-new-dtags -L'/gscratch/sw/contrib/mpich/3.2/lib' -Wl,-rpath='/gscratch/sw/contrib/mpich/3.2/lib'  -L'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/openblas-0.2.20/lib' -Wl,-rpath='/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/openblas-0.2.20/lib' -L'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/fftw-3.3.7/lib' -Wl,-rpath='/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/fftw-3.3.7/lib' -L'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libint-1.1.6/lib' -Wl,-rpath='/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libint-1.1.6/lib' -L'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libxc-4.0.3/lib' -Wl,-rpath='/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libxc-4.0.3/lib' -L'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libxsmm-1.9.0/lib' -Wl,-rpath='/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libxsmm-1.9.0/lib' -L'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/scalapack-2.0.2/lib' -Wl,-rpath='/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/scalapack-2.0.2/lib'
LIBS        = -lscalapack -lxsmmf -lxsmm -ldl -lpthread -lxcf03 -lxc -lderiv -lint -lfftw3 -lfftw3_omp  -lmpi -lmpicxx  -lopenblas_omp -lstdc++

**Comment by alazzaro** [comment]
Yes, you are right, the error message is linking to lapack. The toolchain installs blas and scalapack and from your arch file I see the following paths:
```
/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/openblas-0.2.20/lib
/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/scalapack-2.0.2/lib
```
The names of the libraries are: `libscalapack` and `libopenblas_omp`.
Could you check if the paths are correct and the libraries accessible?

**Comment by alazzaro** [comment]
OK, that's to be sure.
So, from your log I see that the linking which fails is:

```
mpif90 -march=native -fno-omit-frame-pointer -g  -O3 -funroll-loops -ffast-math  -fopenmp   -I'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/openblas-0.2.20/include' -I'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/fftw-3.3.7/include' -I'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libint-1.1.6/include' -I'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libxc-4.0.3/include' -I'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libxsmm-1.9.0/include' -ffree-form -std=f2003 -fimplicit-none  -Werror=aliasing -Werror=ampersand -Werror=c-binding-type -Werror=intrinsic-shadow -Werror=intrinsics-std -Werror=line-truncation -Werror=tabs -Werror=realloc-lhs-all -Werror=target-lifetime -Werror=underflow -Werror=unused-but-set-variable -Werror=unused-variable -Werror=unused-dummy-argument -Werror=conversion -Werror=zerotrip -Werror=uninitialized -Wno-maybe-uninitialized -Wuse-without-only  -D__LIBXSMM  -D__parallel  -D__FFTW3  -D__LIBINT -D__LIBINT_MAX_AM=6 -D__LIBDERIV_MAX_AM1=5 -D__LIBXC -D__SCALAPACK   -D__COMPILE_ARCH="\"local\"" -D__COMPILE_DATE="\"Tue Sep 10 17:13:03 PDT 2019\"" -D__COMPILE_HOST="\"n2232.hyak.local\"" -D__COMPILE_REVISION="\"svn:18464\"" -D__DATA_DIR="\"/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/data\"" -Wl,--enable-new-dtags -L'/gscratch/sw/contrib/mpich/3.2/lib' -Wl,-rpath='/gscratch/sw/contrib/mpich/3.2/lib'  -L'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/openblas-0.2.20/lib' -Wl,-rpath='/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/openblas-0.2.20/lib' -L'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/fftw-3.3.7/lib' -Wl,-rpath='/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/fftw-3.3.7/lib' -L'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libint-1.1.6/lib' -Wl,-rpath='/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libint-1.1.6/lib' -L'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libxc-4.0.3/lib' -Wl,-rpath='/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libxc-4.0.3/lib' -L'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libxsmm-1.9.0/lib' -Wl,-rpath='/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/libxsmm-1.9.0/lib' -L'/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/scalapack-2.0.2/lib' -Wl,-rpath='/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/tools/toolchain/install/scalapack-2.0.2/lib' -L/gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/lib/local/psmp -o /gscratch/pfaendtner/ldgibson/codes/cp2k/cp2k_v6.1_09-09-2019/exe/local/dbcsr_unittest.psmp dbcsr_unittest.o  -ldbcsr -ldbcsrmm -ldbcsrops -ldbcsrbblock -ldbcsrbdist -ldbcsrbase -ldbcsrdata -lcp2kmpiwrap -lmicsmm -lclsmm -lcp2kacc -lcp2kaccmic -lcp2kaccopencl -lcp2kbase -lscalapack -lxsmmf -lxsmm -ldl -lpthread -lxcf03 -lxc -lderiv -lint -lfftw3 -lfftw3_omp  -lmpi -lmpicxx  -lopenblas_omp -lstdc++
```

which seems fine...  What's missing from the error is LAPACK, which should be part of the openblas installation... So, could you check that the symbol `dlarnv` is in `libopenblas.a`? 
Another possibility is to add `-static` to the LDFLAGS in the arch file.

**Comment by ldgibson** [comment]
I have tried compiling with and without `-static` in the LDFLAGS--both result in the same undefined references.

I do not find `dlarnv` in `libopenblas.a` using `nm libopenblas.a`. I checked a few other symbols that were raised in the error, and could not find any of them.

If it is helpful, here is the output for `nm libopenblas.a`: [symbols_libopenblas.txt](https://github.com/cp2k/cp2k/files/3602535/symbols_libopenblas.txt)
and `nm libopenblas_omp.a`: [symbols_libopenblas_omp.txt](https://github.com/cp2k/cp2k/files/3602537/symbols_libopenblas_omp.txt)

Also, this is the command I used to install all of my dependencies:
`./install_cp2k_toolchain.sh --enable-omp=yes --enable-cuda=no --with-fftw=install --with-mpich=system --with-libint=install --with-libxc=install --with-libxsmm=install --with-reflapack=no --with-scalapack=install --with-openblas=install -j 40`

**Comment by alazzaro** [comment]
Well, I'm not an expert of the toolchain, but could you try

`--with-reflapack=yes`

?

**Comment by dev-zero** [comment]
@ldgibson did you finally manage to solve this? If not, can you please attach the full build logs from the toolchain OpenBLAS build? Currently the following files:

```
build/OpenBLAS-0.3.6/install.serial.log
build/OpenBLAS-0.3.6/make.serial.log
build/OpenBLAS-0.3.6/install.omp.log
build/OpenBLAS-0.3.6/clean.omp.log
build/OpenBLAS-0.3.6/make.omp.log
```

and please note that when reconfiguring the toolchain (changing options on what to build and how), and you're encountering build errors, please try to build from scratch (`rm -rf build/ install/` and then re-run the toolchain).

**Comment by oschuett** [comment]
I'm closing this as the users' problem seems to have been resolved.
