### ISSUE TITLE
Validation error for PR

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#56]
I have an issue with a hanging PR. It seems that the PR creation was interrupted during processing and it does not show up in the PR list (should be #55) as an issue. When I try now to create the PR again a validation error is shown claiming that the PR already exists. Does anybody know how to resolve this?

**Comment by dev-zero** [comment]
The reason for this was an [incident at GitHub](https://blog.github.com/2018-10-21-october21-incident-report/), which seems to be solved now.
