### ISSUE TITLE
Segmentation fault when using Hirshfeld in CDFT 

### ISSUE THREAD

**Issue by MoleOrbitalHybridAnalyst** [cp2k/cp2k#560]
Hi,

I got a seg fault when running CDFT using Hirshfeld while Becke is totally fine. The problem is in both cp2k/5.1 and cp2k/6.1 but not cp2k/7.0. 

I believe the seg fault comes from line 856 of qs_scf_output.F of branch cp2k/5.1 where you try to access the constraint_type from group section which does not exist for Hirshfeld input structure. The suspicious usage of "group % constraint_type" for Hirshfeld happens many times elsewhere in the code.

Best,
Chenghan

**Comment by oschuett** [comment]
Just to clarify: Is this bug already fixed and now you're asking for back ports to older releases, or is the issue still present in the master branch? In the latter case, could you please provide an input file to reproduce it.

**Comment by MoleOrbitalHybridAnalyst** [comment]
> Just to clarify: Is this bug already fixed and now you're asking for back ports to older releases, or is the issue still present in the master branch? In the latter case, could you please provide an input file to reproduce it.

Hi,

I do not think the master branch has that problem. It seems you rewrote the corresponding part in v7.0 instead of direct fixes based on old versions as the input structure for CDFT was altered a lot, so I was not sure you were aware of the potential glitch. I am using v7.0 since then and it works fine.

Best Regards,
Chenghan

**Comment by dev-zero** [comment]
@MoleOrbitalHybridAnalyst thank you very much for the feedback, closing the issue then
