### ISSUE TITLE
Changes to the LibXC API

### ISSUE THREAD

**Issue by AStegm** [cp2k/cp2k#572]
Compiling the current development version of cp2k with the current development version of LibXC showed some API changes. For example the function `xc_f03_mgga(...)` from LibXC seems to provide third derivatives (and requires the corresponding arguments). It is also possible that the order of arguments might have changed slightly.

The functions get called in `xc/xc_libxc.F` from cp2k and is implemented in `libxcf03.f90`.

**Comment by fstein93** [comment]
For now, there is no official release of Libxc 5.0. After that, we can bump Libxc to 5.0, or we had to maintain wrapper and tests for both, Libxc 4.x and Libxc 5.0 for reasons of stability. If requested, I have a patch for the latest master branch of Libxc available. but not everything runs properly, for now.

EDIT: I pushed the files to my cp2k repository, branch libxc_5_0. I still don't know why but the TPSSh test provides wrong numbers across the executables, the others are working.

**Comment by AStegm** [comment]
Thank you very much! That is very helpful! I'll give it a try and tell you if I find any issues (besides TPSSh).

**Comment by oschuett** [comment]
Closing, there seems to be no real issue here.
