### ISSUE TITLE
killing job in CP2K

### ISSUE THREAD

**Issue by Mohammad143** [cp2k/cp2k#573]
I ran my job based on BOMD-DFT via CP2K, my system is a water droplet into a big box.my question is this that when I run my job after killing, the direction of the center of mass will be changed? please help me, I use CP2K 4.1.
Thank you in advance

**Comment by dev-zero** [comment]
Dear Mohammad,

please use our [Google Group/Form](https://www.cp2k.org/howto:forum) for questions about using CP2K. This bug tracker is for reporting issues with the software only.
