### ISSUE TITLE
Remove deprecated `cufftSetCompatibilityMode` 

### ISSUE THREAD

**Issue by shoshijak** [cp2k/cp2k#576]
Remove deprecated API `cufftSetCompatibilityMode` used in `src/pw/cuda/fft_cuda_z.cu`

**Comment by oschuett** [comment]
I believe this is very relevant because `cufftSetCompatibilityMode` actually got [removed](https://docs.nvidia.com/cuda/cufft/index.html#unique_1370957890) in CUDA 9.1.

**Comment by shoshijak** [comment]
You're right. I wrote 

> So sorry, this is not relevant anymore. Closing issue.

because I couldn't find the occurrences of `cufftSetCompatibilityMode` while browsing CP2K's code on Github. Turns out I was looking in the wrong file. 

`cufftSetCompatibilityMode` is to be found in: 
- https://github.com/cp2k/cp2k/blob/master/src/pw/cuda/fft_cuda_z.cu#L74
- https://github.com/cp2k/cp2k/blob/master/src/pw/cuda/fft_cuda_z.cu#L145
- https://github.com/cp2k/cp2k/blob/master/src/pw/cuda/fft_cuda_z.cu#L215

**Comment by shoshijak** [comment]
All the occurrences of `cufftSetCompatibilityMode` are actually already in an `#if (__CUDACC_VER_MAJOR__<8)`, so this shouldn't cause any problems. 
Since CP2K doesn't seem to have a clear requirement on the CUDA version, I think it is okay to leave these lines as they are now. 
In the future though, if CUDA versions inferior to 8.0 are dropped, these lines should be removed.

Closing this issue for now.
