### ISSUE TITLE
Compilation flag `-D__DBCSR_ACC=2` isn't documented

### ISSUE THREAD

**Issue by shoshijak** [cp2k/cp2k#577]
As far as I can tell, the compilation flag `-D__DBCSR_ACC=2` isn't documented. 

It enables the multiplication of large (>80) blocks on GPU by CUBLAS (see https://github.com/cp2k/dbcsr/blob/develop/src/mm/dbcsr_acc_operations.F#L149-L195)

**Comment by shoshijak** [comment]
This type of documentation issue would be solved by #351. 
Indeed, the subtleties of compiling DBCSR shouldn't have to all be documented inside CP2K. Rather, a version of DBCSR with sensible options should be compiled by the toolchain.

**Comment by shoshijak** [comment]
And a question for @alazzaro : why doesn't the [arch file for Piz Daint's GPU partition](https://www.cp2k.org/static/regtest/trunk/cscs-daint-xc50_gpu_perf/CRAY_XC50-gfortran_gpu.psmp.out) use `-D__DBCSR_ACC=2` ?

**Comment by alazzaro** [comment]
Closing this issue since it doesn't require the flag anymore (see PR https://github.com/cp2k/dbcsr/pull/334 )
