### ISSUE TITLE
ELPA [pre-fail]: Problem contains processor column with zero width.

### ISSUE THREAD

**Issue by rybkinjr** [cp2k/cp2k#578]
Dear all,

I have got the following issue on Piz Daint CPU partitioning:
```
*******************************************************************************
 *   ___                                                                       *
 *  /   \                                                                      *
 * [ABORT]                                                                     *
 *  \___/  ELPA [pre-fail]: Problem contains processor column with zero width. *
 *    |                                                                        *
 *  O/|                                                                        *
```
It happens in the middle of SCF with OT for a periodic Hartree-Fock calculation with one of the recent trunk versions. It's a huge calculation (256 nodes, 2 tasks per node) and I can't reproduce it on the smaller scale.

**Comment by rybkinjr** [comment]
The problem is unfortunately rather persistent for large systems. I was able to cure it by setting the following section in the &GLOBAL:
  &FM_DIAG_SETTINGS
     ELPA_FORCE_REDISTRIBUTE .TRUE.
  &END

**Comment by dev-zero** [comment]
as discussed, the solution might be to check the distribution prior to passing it to ELPA and automatically do a redistribute if necessary

**Comment by dev-zero** [comment]
seems we already have a check, but obviously something seems to go wrong:

https://github.com/cp2k/cp2k/blob/40b00f536451d9fe0a932a1f8dd0d163d98b2a1e/src/fm/cp_fm_diag_utils.F#L302-L314

**Comment by dev-zero** [comment]
@rybkinjr is there a chance you can rerun with `PRINT_FM_REDISTRIBUTE = .TRUE.` (without `ELPA_FORCE_REDISTRIBUTE`) to see whether matrices got redistributed prior to the call?

**Comment by dev-zero** [comment]
ok, with [my patch](https://github.com/dev-zero/cp2k/tree/feature/fm-redist-info) I get the following before crash:

```
CP_FM_DIAG| Matrix order:                  385
CP_FM_DIAG| Matrix distributed on   1296 processes
CP_FM_DIAG| Optimal number of CPUs:          8
CP_FM_DIAG| Max number of CPUs (with non-zero columns):   682
CP_FM_DIAG| The matrix will be redistributed onto   682 processes
 

CP_FM | Name:                           yevd_new_mat
CP_FM_STRUCT | No. of matrix columns:            385
CP_FM_STRUCT | No. of matrix rows:               385
CP_FM_STRUCT | No. of block columns:              13
CP_FM_STRUCT | No. of block rows:                 13
CP_FM_STRUCT | Number of local columns: 
CP_FM_STRUCT | CPUs     0..    7:     13    13    13    13    13    13    13    13
CP_FM_STRUCT | CPUs     8..   15:     13    13    13    13    13    13    13    13
CP_FM_STRUCT | CPUs    16..   23:     13    13    13    13    13    13    13    13
CP_FM_STRUCT | CPUs    24..   31:     13    13    13    13    13     8     0
CP_FM_STRUCT | Number of local rows:    
CP_FM_STRUCT | CPUs     0..    7:     26    26    26    26    26    26    26    21
CP_FM_STRUCT | CPUs     8..   15:     13    13    13    13    13    13    13    13
CP_FM_STRUCT | CPUs    16..   23:     13    13    13    13    13    13
```

**Comment by rybkinjr** [comment]
Indeed, a column of zero width. It looks like the reason is that the matrix is distributed onto 682 processes, whereas we have 1296.

**Comment by dev-zero** [comment]
No, that in principle is fine: to avoid zero-width columns, the matrix is redistributed to fewer processors than available. With Scalapack it would be redistributed to 8 processors even.
The problem seems to be that the calculation for which there are no zero-width columns does not match what the redistribution ends up to be in the end. Here it should redistribute to 660 processes, rather than the 682.

**Comment by dev-zero** [comment]
ok, I think I got one issue (will fix tomorrow): https://github.com/cp2k/cp2k/blob/32e6c1369bbc34e276bca7b334b623e4f2c37c8c/src/fm/cp_fm_diag_utils.F#L358-L362

Here we don't pass along the old block size which makes `cp_fm_create` chose the optimal one.
This is fine for the ScaLAPACK case where we anyway redistribute for the optimal size (which matches the optimal block size). But in the ELPA case we don't necessarily have the blacs optimal block size, meaning we're calculating the maximum number of processors such that no processor has 0 columns, but possibly for a different block size. Indeed, when I hack in another debug output, in the routine to find non-zero column width distributions, I get:

```
 checking for        1294 CPUs, found         612 processors with zero-width columns, ncol_global:         385 , ncol_block:          11
 checking for         682 CPUs, found           0 processors with zero-width columns, ncol_global:         385 , ncol_block:          11

CP_FM_DIAG| Matrix order:                  385
CP_FM_DIAG| Matrix distributed on   1296 processes
CP_FM_DIAG| Optimal number of CPUs:          8
CP_FM_DIAG| Max number of CPUs (with non-zero columns):   682
CP_FM_DIAG| The matrix will be redistributed onto   682 processes
 

CP_FM | Name:                           yevd_new_mat
CP_FM_STRUCT | No. of matrix columns:            385
CP_FM_STRUCT | No. of matrix rows:               385
CP_FM_STRUCT | No. of block columns:              13
CP_FM_STRUCT | No. of block rows:                 13
CP_FM_STRUCT | Number of local columns: 
CP_FM_STRUCT | CPUs     0..    7:     13    13    13    13    13    13    13    13
CP_FM_STRUCT | CPUs     8..   15:     13    13    13    13    13    13    13    13
CP_FM_STRUCT | CPUs    16..   23:     13    13    13    13    13    13    13    13
CP_FM_STRUCT | CPUs    24..   31:     13    13    13    13    13     8     0
CP_FM_STRUCT | Number of local rows:    
CP_FM_STRUCT | CPUs     0..    7:     26    26    26    26    26    26    26    21
CP_FM_STRUCT | CPUs     8..   15:     13    13    13    13    13    13    13    13
CP_FM_STRUCT | CPUs    16..   23:     13    13    13    13    13    13
```
So, we get a valid distribution for a block size of 11, but the final block size will be 13, leading to processors without work.
