### ISSUE TITLE
[toolchain] broken with macOS

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#579]
The toolchain seems to be largely untested with macOS.

The setup:

* macOS Mojave (10.14.6)
* XCode 11 + matching Command Line Tools
* Homebrew-based gfortran/gcc

Using simply `./install_cp2k_toolchain.sh` will not work: `gcc` points to `clang`, which doesn't support `-fopenmp`. First one to complain is OpenBLAS, which can be made to build with `--with-openmp=no`, but our `fftw` script does not support building without OpenMP-support in the compiler.

Using `CC=gcc-9 CXX=g++-9 ./install_cp2k_toolchain.sh` fails in OpenBLAS since those vars are inconsistently forwarded: CMake picks them up correctly, OpenBLAS does not.

Using `./install_cp2k_toolchain.sh --with-gcc=/usr/local/Cellar/gcc/9.2.0_1/` fails since it always assumes a multilib-system (where `lib64` is available):

```
==================== Linking GCC to user paths ====================
Found directory /usr/local/Cellar/gcc/9.2.0_1/bin
Found directory /usr/local/Cellar/gcc/9.2.0_1/lib
ERROR: (./scripts/install_gcc.sh) Cannot find /usr/local/Cellar/gcc/9.2.0_1/lib64
ERROR: (./scripts/install_gcc.sh, line 21) Non-zero exit code detected.
```

**Comment by dev-zero** [comment]
@oschuett is this fixed then?

**Comment by oschuett** [comment]
>  is this fixed then?

Not to my knowledge, but since the report is now 2.5 years old I consider it outdated and non-actionable.
