### ISSUE TITLE
Printout of stress tensor components

### ISSUE THREAD

**Issue by mkrack** [cp2k/cp2k#583]
Recently, a printout of the stress tensor components has been added to the CP2K output. I observe the following issues:
- No units are specified with that output
- The values for the total stress do not match the numbers of the STRESS TENSOR output above in GPa which is confusing. It seems that the cell volume is not taken into account in the latter printout.
- Stars may appear in the printout:

```STRESS TENSOR [GPa]

            X               Y               Z
  X      -8.12148507      0.00066905      0.00076261
  Y       0.00066905     -8.10240224      0.00016433
  Z       0.00076261      0.00016433    -12.15978599

  1/3 Trace(stress tensor):  -9.46122443E+00

  Det(stress tensor)      :  -8.00156939E+02


 EIGENVECTORS AND EIGENVALUES OF THE STRESS TENSOR

        -12.15978614     -8.12150836     -8.10237880

         -0.00018884      0.99938737      0.03499791
         -0.00004047     -0.03499791      0.99938738
          0.99999998      0.00018730      0.00004706

  ==============================================================================
   Stress Tensor Components (GPW/GAPW)
                                                1/3 Trace           Determinant
   Kinetic Energy Stress                      -0.02107807           -0.00000007
   Basis Overlap Stress                        0.00342786            0.00001055
   ES + XC Stress                          -8971.64620698      ****************
   vdW correction (ff) Stress                  0.00000000            0.00000000
   Local Pseudopotential/Core Stress           0.09389117            0.00022704
   Nonlocal Pseudopotential Stress             2.16156421            9.48633323
   Exact Exchange Stress                      -0.00000000           -0.00000000
   Sum of Parts Stress                     -8969.40840182      ****************
   Total Stress                               -7.90266322         -466.28727580
  ==============================================================================
```

**Comment by oschuett** [comment]
Is this issue still present?

**Comment by mkrack** [comment]
Yes.

**Comment by oschuett** [comment]
The output you pasted is produced by two different routines: [write_stress_tensor](https://github.com/cp2k/cp2k/blob/master/src/force_env_utils.F#L413) and [write_stress_components](https://github.com/cp2k/cp2k/blob/master/src/virial_methods.F#L159). 
As you correctly assumed, only the former takes the cell volume into [account](https://github.com/cp2k/cp2k/blob/master/src/force_env_utils.F#L435).
```
stress_tensor(:, :) = pv_virial(:, :)/cell%deth*pascal*1.0E-9_dp
```

The cell volume is also missing [here](https://github.com/cp2k/cp2k/blob/master/src/force_env_methods.F#L510) when [atomic pressure](https://manual.cp2k.org/trunk/CP2K_INPUT/FORCE_EVAL/PROPERTIES/ATOMIC.html#list_PRESSURE) is enabled.
So, I guess we should fix both occurrences.

Fortunately, in [f77_interface.F](https://github.com/cp2k/cp2k/blob/master/src/f77_interface.F#L1127) and [motion_utils.F](https://github.com/cp2k/cp2k/blob/master/src/motion_utils.F#L509) we seem to have gotten it right.
