### ISSUE TITLE
What arch file is using in Dashboard

### ISSUE THREAD

**Issue by vitesselin** [cp2k/cp2k#587]
How can I retrieve the arch file setting in detail within each dashboard test?
In general case, what kind of the CUDA arch setting is using in Dashboard?
I only found this one "https://dashboard.cp2k.org/archive/cuda-pascal/index.html".

Thanks,
Vitesse.

**Comment by oschuett** [comment]
The employed arch file is included in the [report](https://storage.googleapis.com/cp2k-ci/dashboard_cuda-pascal_report.txt). Just search for `--- ARCH-file ---`.

**Comment by dev-zero** [comment]
@vitesselin please use our Forum/Google Group for general questions and limit the use of the issue tracker to actual issues: https://www.cp2k.org/howto:forum?s[]=forum
