### ISSUE TITLE
SpFFT does not work with MKL

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#605]
When building the toolchain with `--math-mode=mkl` the SpFFT library does not pick up MKL.
This is why the CUDA Pascal test is [currently failing](https://dashboard.cp2k.org/archive/cuda-pascal/index.html).

Later when compiling CP2K one gets the following warnings:
```
/usr/bin/ld: warning: libmkl_intel_lp64.so, needed by /opt/cp2k-toolchain/install/SpFFT-0.9.8/lib/../lib/libspfft.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libmkl_sequential.so, needed by /opt/cp2k-toolchain/install/SpFFT-0.9.8/lib/../lib/libspfft.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libmkl_core.so, needed by /opt/cp2k-toolchain/install/SpFFT-0.9.8/lib/../lib/libspfft.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libmkl_intel_lp64.so, needed by /opt/cp2k-toolchain/install/SpFFT-0.9.8/lib/../lib/libspfft.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libmkl_sequential.so, needed by /opt/cp2k-toolchain/install/SpFFT-0.9.8/lib/../lib/libspfft.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libmkl_core.so, needed by /opt/cp2k-toolchain/install/SpFFT-0.9.8/lib/../lib/libspfft.so, not found (try using -rpath or -rpath-link)
```
Only at runtime there is finally a hard failure:
```
../local_cuda/cp2k.psmp: error while loading shared libraries: libmkl_intel_lp64.so: cannot open shared object file: No such file or directory
```

**Comment by AdhocMan** [comment]
When installing the library, the rpath is cleared to make the library relocatable. Therefore, the location of MKL libraries has to be in LD_LIBRARY_PATH. If the toolchain does not require a relocatable library and you don't want to adjust the default library search path, I suggest you try to configure SpFFT  to always use the full rpath before installation:
```
cmake <path_to_cmakelists> -DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE
```
Please let me know, if this does not solve the issue.

**Comment by oschuett** [comment]
Thanks for the quick reply!
I will try the `-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE` as you suggested.

Generally, we used to link our binary statically, because e.g. Cray required it. However looking at our current dashboard reports, I realize that we're now using quite a lot of dynamics libraries too.
Hence, I'm wondering if Cray dropped that requirement or if we should enforce it more thoroughly?

**Comment by alazzaro** [comment]
static linking is not possible on GPU system anyway.

Concerning, MC, it is still "suggested" (default option for the wrappers), not mandatory. You can control during the compilation with the env variable `CRAYPE_LINK_TYPE` to dynamic or static to change the default link type.
If `dynamic`, I do suggest to use `CRAY_ADD_RPATH=yes`, otherwise you have to specifically load all modules when you run (and make sure they are the right ones)...

**Comment by oschuett** [comment]
> dynamic linking is not possible on GPU system anyway.

Oh, I thought the opposite is true. I thought the Cuda runtime has to be linked dynamically.

**Comment by alazzaro** [comment]
Sorry, you are right, typo.... I changed my comment :)
