### ISSUE TITLE
build error with current master

### ISSUE THREAD

**Issue by recohen** [cp2k/cp2k#614]
home/rcohen/CP2K/cp2k/src/cp_dbcsr_cp2k_link.F(222): error #6627: This is an actual argument keyword name, and not a dummy argument name.   [USE_MEMPOOLS_CPU]
      CALL dbcsr_get_default_config(use_mempools_cpu=ldefault)
------------------------------------^
/home/rcohen/CP2K/cp2k/src/cp_dbcsr_cp2k_link.F(378): error #6627: This is an actual argument keyword name, and not a dummy argument name.   [USE_MEMPOOLS_CPU]
      CALL dbcsr_set_config(use_mempools_cpu=lval)
----------------------------^
compilation aborted for cp_dbcsr_cp2k_link.F90 (code 1)

**Comment by alazzaro** [comment]
This seems due to the recent update of DBCSR...
Some questions:
1) Are you updating to the current master or cloning a new copy?
2) Are you setting: `git config submodule.recurse true` ?
3) Could you check which DBCSR is installed with `less exts/dbcsr/VERSION`? The current one is
```
MAJOR = 2
MINOR = 0
PATCH = 0-rc9
```

**Comment by recohen** [comment]
Thank you so much. It is a bit strange. I do have this set, but have a different version. Here is what I see:

git config submodule.recurse true
rcohen@tomcat:~/CP2K/cp2k$ cat exts/dbcsr/VERSION
MAJOR = 2
MINOR = 0
PATCH = 0-rc6
# A specific DATE (YYYY-MM-DD) fixes an official release, otherwise
# it is considered Development version.
DATE  = 2019-07-08
rcohen@tomcat:~/CP2K/cp2k$ git pull
Already up-to-date.
rcohen@tomcat:~/CP2K/cp2k$ git pull https://github.com/cp2k/cp2k.git
From https://github.com/cp2k/cp2k
 * branch            HEAD       -> FETCH_HEAD
Already up-to-date.
git branch
* master

Maybe I have done something wrong with git. I also have a fork of my own, but you see here it is the master branch and the pull from cp2k .

Apologies if I have done something wrong with git, but I do not see what.

Sincerely,

Ron

---
Ronald Cohen
Extreme Materials Initiative
Carnegie Institution for Science
5251 Broad Branch Rd., N.W.
Washington, D.C. 20015
rcohen@carnegiescience.edu <mailto:rcohen@carnegiescience.edu>
office: 202-478-8937
skype: ronaldcohen
twitter: @recohen3

**Comment by dev-zero** [comment]
if `submodule.recurse` was not set to `true` from the start, then `git pull` only updated the directly managed files but not the submodule itself.

Please run: `git submodule update --recursive` and report the output of `git submodule` if it doesn't resolve the issue.

**Comment by recohen** [comment]
Thank you so much! So now I have the correct dbscr, but I still had the same build problem. I found the problem
was that I had libdbscr.a and dbscr includes in my lib and include directories. When I deleted those it built OK!


FYI:
cohen@tomcat:~/CP2K/cp2k$ git branch
* master
rcohen@tomcat:~/CP2K/cp2k$ git submodule
 15fdaba855385f12db7599a6e69b51a7a4ce8a9a exts/dbcsr (v2.0.0-rc9)
rcohen@tomcat:~/CP2K/cp2k$ git pull
Already up-to-date.
rcohen@tomcat:~/CP2K/cp2k$ git status
# On branch master


/home/rcohen/CP2K/cp2k/src/cp_dbcsr_cp2k_link.F(222): error #6627: This is an actual argument keyword name, and not a dummy argument name.   [USE_MEMPOOLS_CPU]
      CALL dbcsr_get_default_config(use_mempools_cpu=ldefault)
------------------------------------^
/home/rcohen/CP2K/cp2k/src/cp_dbcsr_cp2k_link.F(378): error #6627: This is an actual argument keyword name, and not a dummy argument name.   [USE_MEMPOOLS_CPU]
      CALL dbcsr_set_config(use_mempools_cpu=lval)
----------------------------^
compilation aborted for cp_dbcsr_cp2k_link.F90 (code 1)


I deleted all my obj exe and lib directories before the make.

But after:

rm ~/include/*dbcsr*
rm ~/lib/*dbcsr*

it built fine.

There are many ways to go wrong!

Thanks for your help,

Ron

**Comment by dev-zero** [comment]
The build system should pick up changes like these automatically and rebuild as required, but obviously it sometimes fails.
Anyway, glad it worked out, closing the issue then.
