### ISSUE TITLE
How to check test result of wat_mode_sel_range.inp when np=1/2

### ISSUE THREAD

**Issue by jjsbear** [cp2k/cp2k#615]
For np=1, regress test reports this: 
      MS| TRACKED FREQUENCY (1) IS: 1736.718534   cm-1
For np=2, regress test reports these:
      MS| TRACKED FREQUENCY (1) IS: 1736.709744   cm-1
      MS| TRACKED FREQUENCY (2) IS:    7.162315   cm-1
Regress test think np=2 got wrong result as below description:
      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      /home/mpich-ucx/TEST-local_cpu-psmp-2019-11-04_01-56- 
      07/Fist/regtest-5-vib/wat_mode_sel_range.inp.out :
      MS| TRACKED FREQUENCY : old = 1736.718534 new = 7.162315
      relative error :   2.41480055e+02 >  numerical tolerance = 7e-08
      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Is this a bug of regress test to check wat_mode_sel_range.inp result? thanks.

**Comment by dev-zero** [comment]
This is an issue tracker, to get help on testing and compiling, please use our [User Forum](https://www.cp2k.org/howto:forum).

No, there is no known issue with the tests, see https://dashboard.cp2k.org/

In general, when reporting issues/asking questions, please provide at least: version of CP2K, MPI vendor & version, compiler vendor & version, some documentation on how you built the version of CP2K in question.
