### ISSUE TITLE
[input] unit specification is case sensitive

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#618]
initially reported by @rybkinjr:

The documentation for units for example in `&COORD` says: `ANGSTROM`, but in fact it has to be all lowercase `angstrom`, otherwise one gets the CPABORT `Unknown unit: Angstrom` (or `Bohr`, ...).

Possible fixes:

* fix the documentation (disable the auto-capitalization of default options)
* make the thing case insensitive (but at which point of the parsing)
* add specific aliases

**Comment by mkrack** [comment]
The CP2K input should be case insensitive. Looks like a missing CALL uppercase in cp_unit_create. Will fix that.
