### ISSUE TITLE
Provide Dockerfile for building production binary

### ISSUE THREAD

**Issue by shoshijak** [cp2k/cp2k#621]
Is there a reason why the Dockerfiles in `cp2k/tools/toolchain/` aren't mentioned in `cp2k/INSTALL.md` ?

**Comment by oschuett** [comment]
Unfortunately, so far we only use docker for testing. We don't have a Dockerfile to build a production binary. Until then, I think, it makes little sense to point the users to the toolchain Dockerfile.

I'll rename this issue accordingly.

**Comment by oschuett** [comment]
Done via https://github.com/cp2k/cp2k/commit/52a7d92d8bbe0b9c86ffbd5eaa4f22e5c4af9db2.
