### ISSUE TITLE
Add Arch Linux to the list of supported distributions

### ISSUE THREAD

**Issue by antoscha** [cp2k/cp2k#656]
Dear developers,

We created CP2K package that can be used in Arch Linux:
https://aur.archlinux.org/packages/cp2k
and we are going to maintain and improve it.
Could you please review our work and mark the distribution as supported on cp2k.org/download, if it's alright? Otherwise just close the issue.

**Comment by schulkov** [comment]
Dear Anton

Thank you for your efforts.

All Linux distributives listed on the webpage cp2k.org/download provide generic binary cp2k packages via their standard repositories. Users of these distributives do not need to compile anything if they do not want to do so. These pre-compiled binaries, however, are intended to run on a variety of CPU microarchitectures. They take no advantage of many recent SIMD instruction sets, therefore they are relatively slow.

If Arch Linux support is required, there are two ways to go. One option is to set up an "official" custom pacman repository with pre-compiled generic cp2k packages somewhere (e.g. on github).

Another option (what you have done) is to upload a package description file to Arch User Repository; everyone then can compile their own cp2k binaries using this description file. However, in the latter case there is no reason why users should rely on non-optimised system libraries (such as SSE2 version of Netlib lapack), when they can compile optimised libraries (such as OpenBLAS) for their own CPU as well and statically link cp2k against them. So you may wish to drop all dependencies except 'gcc-libs' (provides libgfortran.so) and 'openmpi' / 'mpich', and then simply launch the toolchain script (cp2k/tools/toolchain/install_cp2k_toolchain.sh) with the relevant command-line options.

**Comment by dev-zero** [comment]
> So you may wish to drop all dependencies except 'gcc-libs' (provides libgfortran.so) and 'openmpi' / 'mpich', and then simply launch the toolchain script (cp2k/tools/toolchain/install_cp2k_toolchain.sh) with the relevant command-line options.

I disagree here: the idea of Linux distributions (and by some extent also the AUR in Arch) is to rely on distro packages whenever possible. Arch Linux provides OpenBLAS (like many others) and the recommendation if you really want to build a package tailored to your CPU is to [rebuild it manually](https://wiki.archlinux.org/index.php/Makepkg#Building_optimized_binaries).
Besides, the speed improvement would likely rather come from using libxsmm and/or ELPA.

**Comment by dev-zero** [comment]
> Dear developers,
> 
> We created CP2K package that can be used in Arch Linux:
> https://aur.archlinux.org/packages/cp2k
> and we are going to maintain and improve it.
> Could you please review our work and mark the distribution as supported on cp2k.org/download, if it's alright? Otherwise just close the issue.

Very nice! Will add the link.

Some notes for the `PKGBUILD`:
* since you're directly linking to `-lblas` and `-llapack` you should probably also explicitly depend on them
* libxsmm support might be nice
* next version of CP2K will properly work with Python 3

for your comment below the AUR see #234

**Comment by dev-zero** [comment]
done
