### ISSUE TITLE
SIRIUS crashes in cublasCreate

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#668]
It seems that somewhere between 4bbeda1 and 4594d24 our [CUDA Pascal test](https://dashboard.cp2k.org/archive/cuda-pascal/index.html) started failing. Unfortunately, the reports with all the stacktraces got too large for the dashboard to handle. Nevertheless, I managed to fish our some logs from the cloud storage bucket:

- [Last good report](https://storage.googleapis.com/cp2k-ci/run-cp2k-cuda-pascal-56c92859_report.txt), for 4bbeda1 (got preempted).

- [First failure report](https://storage.googleapis.com/cp2k-ci/run-cp2k-cuda-pascal-efc27454_report.txt) for 4594d24.

That being said, I actually [observed](https://storage.googleapis.com/cp2k-ci/run-cp2k-benchmarks-cuda-kepler-502cc631_artifacts.tgz) the problem already on the 2019-11-28 while working on #652. So, my guess is that the recent update of [Nvidia's Docker image](https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=10.1-devel-ubuntu18.04) surfaced a dormant bug in SIRIUS.

In any case, the error message says:

```
SIRIUS 6.4.1, git hash: 04226063af2b64ff6b303967c89adc2af5768592
the library was not initialized
hostname: f75fb6ebc79f
Error in cublasCreate at line 184 of file /opt/cp2k-toolchain/build/SIRIUS-6.4.1/src/SDDK/GPU/cublas.hpp

...

Backtrace for this error:
#0  0x7f33a7e9a2da in ???
#1  0x7f33a7e99503 in ???
#2  0x7f33976cdf1f in ???
#3  0x7f33a8e36727 in ???
#4  0x55d46ff36a7a in _Z15stack_backtracev
	at /opt/cp2k-toolchain/build/SIRIUS-6.4.1/src/SDDK/GPU/acc.hpp:127
#5  0x556d215ec81b in _ZN6cublas21create_stream_handlesEv
	at /opt/cp2k-toolchain/build/SIRIUS-6.4.1/src/SDDK/GPU/cublas.hpp:184
#6  0x556d215d8503 in _ZN6sirius10initializeEb
	at /opt/cp2k-toolchain/build/SIRIUS-6.4.1/src/sirius.h:99
#7  0x556d215d8503 in sirius_initialize
	at /opt/cp2k-toolchain/build/SIRIUS-6.4.1/src/sirius_api.cpp:71
#8  0x556d1f83fd2f in __sirius_interface_MOD_cp_sirius_init
	at /workspace/cp2k/src/sirius_interface.F:89
#9  0x556d1f4ba9b8 in cp2k_run
	at /workspace/cp2k/src/start/cp2k_runs.F:205
#10  0x556d1f4be49f in __cp2k_runs_MOD_run_input
	at /workspace/cp2k/src/start/cp2k_runs.F:965
#11  0x556d1f4b9d1d in cp2k
	at /workspace/cp2k/src/start/cp2k.F:296
#12  0x556d1f3b6d3e in main
	at /workspace/cp2k/src/start/cp2k.F:45
```

@mtaillefumier, could you have a look?

**Comment by mtaillefumier** [comment]
Question. Are you running on a multi-gpu node ? Could you give the
running parameters ?

It can fail for many reasons but a look at the code does not provide any
meaningful info. It can fail at that point for the following reasons

- Not enough resources

- A cuda call before initializing sirius failed but was not properly
handled.

- a multigpu problem.

- Problem with the container.

- SIRIUS initialization process is messed up somehow.

I have being using cuda 10.1 for some times now (since the beginning of
the 10.1 lines) and never encountered this behavior on both intel and
power nodes.

**Comment by mtaillefumier** [comment]
Would it be possible for you to deactivate SIRIUS and retest the full thing. I suspect that it is coming from the container itself.

**Comment by oschuett** [comment]
Apparently, this was indeed a mistake on Nvidia's side: https://github.com/NVIDIA/nvidia-docker/issues/1143. They committed a [fix](https://gitlab.com/nvidia/container-images/cuda/commit/d442ff6975fb8310da90e6c3f35a988b6920b017) and pushed a new [docker image](https://hub.docker.com/layers/nvidia/cuda/10.1-devel-ubuntu18.04/images/sha256-31e2a1ca7b0e1f678fb1dd0c985b4223273f7c0f3dbde60053b371e2a1aee2cd) today. Now [our tests](https://dashboard.cp2k.org/archive/cuda-pascal/commit_e8954371fa6103e07561f2bc1bea3ec8340bc395.txt) started working again, too.
