### ISSUE TITLE
xTB + RTP/EMD fail with multiples of 8 MPI ranks in release, 6 MPI ranks in debug

### ISSUE THREAD

**Issue by vitesselin** [cp2k/cp2k#673]
Dear all,
Is there any limitation on these cases?

[h2o_emd.inp.txt](https://github.com/cp2k/cp2k/files/3944201/h2o_emd.inp.txt)
[h2o_rtp.inp.txt](https://github.com/cp2k/cp2k/files/3944202/h2o_rtp.inp.txt)
[H2O-NMR-4.inp.txt](https://github.com/cp2k/cp2k/files/3944203/H2O-NMR-4.inp.txt)

I set total number of message passing processes to 2, 4, 8, 12 and only hit abort in 8.

Reproduce Steps:
cd tests/xTB/regtest-3
CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=2 /home/vitesse/cp2k/mpich/bin/mpirun -np 8 ../../../exe/local_cuda/cp2k.psmp h2o_rtp.inp
CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=2 /home/vitesse/cp2k/mpich/bin/mpirun -np 8 ../../../exe/local_cuda/cp2k.psmp h2o_emd.inp

cd tests/QS/regtest-nmr-1/
CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=2 /home/vitesse/cp2k/mpich/bin/mpirun -np 8 ../../../exe/local_cuda/cp2k.psmp H2O-NMR-4.inp 2>&1 | tee H2O-NMR-4.inp.txt

On the architecture/host/platform:
Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz + V100

CP2K error messages:
h2o_rtp.inp and h2o_emd.inp
```
 *** WARNING in xtb_matrices.F:1088 :: Atomic charges outside chemical   ***
 *** range were detected. Switch-off CHECK_ATOMIC_CHARGES keyword in the ***
 *** &xTB section if you want to force to continue the calculation.      ***

 *******************************************************************************
 *   ___                                                                       *
 *  /   \                                                                      *
 * [ABORT]                                                                     *
 *  \___/                               xTB Charges                            *
 *    |                                                                        *
 *  O/|                                                                        *
 * /| |                                                                        *
 * / \                                                     xtb_matrices.F:1091 *
 *******************************************************************************


 ===== Routine Calling Stack =====

            7 build_xtb_ks_matrix
            6 rebuild_ks_matrix
            5 qs_ks_update_qs_env
            4 propagation_step
            3 velocity_verlet
            2 qs_mol_dyn_low
            1 CP2K
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

H2O-NMR-4.inp
```
 *******************************************************************************
 *   ___                                                                       *
 *  /   \                                                                      *
 * [ABORT]                                                                     *
 *  \___/              The matrix diagonalization with dsyev failed            *
 *    |                                                                        *
 *  O/|                                                                        *
 * /| |                                                                        *
 * / \                                                    common/mathlib.F:408 *
 *******************************************************************************


 ===== Routine Calling Stack ===== 

            4 diamat_all
            3 linres_calculation_low
            2 linres_calculation
            1 CP2K
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```

Environment:
CentOS
One node: Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz + V100

Thanks.

**Comment by dev-zero** [comment]
I can reproduce it with 8bc402c2628c1c56e286dc7e72b2dc361f6fcb16 and `popt` as well :(

**Comment by oschuett** [comment]
So, this only affects XTB and only with 8 MPI ranks?

**Comment by oschuett** [comment]
I did some digging. Both, [h2o_emd.inp](https://github.com/cp2k/cp2k/blob/master/tests/xTB/regtest-3/h2o_emd.inp) and [h2o_rtp.inp](https://github.com/cp2k/cp2k/blob/master/tests/xTB/regtest-3/h2o_rtp.inp), suffer from the same problem. With 8 mpi ranks they crashes at [xtb_matrices.F:1091](https://github.com/cp2k/cp2k/blob/master/src/xtb_matrices.F#L1091), because the charges returned by `ao_charges()` are wrong.

Interestingly, using `pdbg` the same regtests also fail with 6 mpi ranks at [rt_propagation_methods.F:757](https://github.com/cp2k/cp2k/blob/master/src/emd/rt_propagation_methods.F#L757):
```
At line 757 of file /home/ole/git/cp2k/src/emd/rt_propagation_methods.F
Fortran runtime error: Array bound mismatch for dimension 1 of array 'fm_tmp' (4/3)
```

That piece of code uses [cp_fm_struct_double](https://github.com/cp2k/cp2k/blob/master/src/fm/cp_fm_struct.F#L559) to constructs a temporary matrix with larger blocks to speed up the following matrix multiplication. It seems this doubling somehow goes wrong, probably due to xTB's small block sizes.

**Comment by oschuett** [comment]
Btw, I also noticed that [here](https://github.com/cp2k/cp2k/blob/master/src/xtb_matrices.F#L1034) are the wrong matrices beeing passed, but apparently it doesn't matter. So, maybe that `IF (nimg > 1)` is not needed?

**Comment by oschuett** [comment]
> xTB + RTP/EMD fail with multiples of 8 MPI ranks

As I've written above, it also fails with 6 ranks.

**Comment by schulkov** [comment]
As mentioned by @oschuett, this is due to a bug in `cp_fm_struct_double` that leads to an incorrect  number of global rows/columns in the doubled matrix. I am just locally testing a patch and will commit it later today.

**Comment by dev-zero** [comment]
@schulkov after talking to Jürg it seems to right thing to do at the moment is to disable xTB for/with RTP/EMD completely since that part of the code needs more testing as there might be more bugs hidden beyond this one.

**Comment by schulkov** [comment]
@dev-zero This particular bug does not relate to the xTB code, but to the RTP/EMD code itself that uses `cp_fm_struct_double`. By the way, subroutine `arnoldi` also seems to be affected.

**Comment by oschuett** [comment]
@schulkov, it's true that `cp_fm_struct_double` is used throughout the RTP/EMD code. However, I believe this bug only occurs for tiny block sizes. Do do you agree? In that case disabling xTB for RTP/EMD would indeed be a reasonable mitigation, which allows us to move forward with the 2019 release.

Nevertheless, I'm very curious to see your patch :-)

**Comment by oschuett** [comment]
@dev-zero, are you preparing a PR to disable xTB+RTP/EMD or should I look into it?

**Comment by oschuett** [comment]
@schulkov, thanks a lot for the patch. I love the ASCII art!
