### ISSUE TITLE
ELPA build failure

### ISSUE THREAD

**Issue by stanos4** [cp2k/cp2k#684]
Hello all,

While this is not CP2K problem on it's own.. I'm having problems compiling ELPA for CP2K. I get following error during the build:

      839 |         state = ELPA_ERROR_CRITICAL
          |                                   1
    Error: Symbol 'elpa_error_critical' at (1) has no IMPLICIT type
    ../src/elpa_api.F90:825:38:
    
      825 |         error = ELPA_ERROR_API_VERSION
          |                                      1
    Error: Symbol 'elpa_error_api_version' at (1) has no IMPLICIT type; did you mean 'api_version'?

I see that the problematic constants are defined in "elpa/elpa_constants.h.in", but I couldn't figure out where it is being miscompiled/wrong compilation order, or what is going on.

Do you have any suggestions please?

system:
Fedora 5.3.14-300.fc31.x86_64
MPICH + gcc 9.2.1
ELPA 2019.05.001 as well as 2019.11.001.rc1 
Thank you!

**Comment by dev-zero** [comment]
Which version of CP2K and ELPA do you have?
How did you obtain them (toolchain, spack, easybuild, custom)?

**Comment by stanos4** [comment]
it's 31ce44dbd CP2K git master version (with all the submodules). ELPA 2019.05.001 is the toolchain version, the 2019.11.001.rc1 is downloaded from ELPA's site. Here's the toolchain installation command:

    ./install_cp2k_toolchain.sh -j 4 --mpi-mode=mpich --math-mode=openblas --libint-lmax=7 --with-gcc=system --with-cmake=system --with-mpich=system --with-libxc=install --with-libint=install --with-fftw=system --with-reflapack=no --with-openblas=install --with-libsmm=no --with-libxsmm=install --with-ptscotch=no --with-parmetis=no --with-metis=no --with-superlu=no --with-pexsi=no --with-quip=no --with-plumed=no --with-sirius=no --with-gsl=install --with-libvdwxc=no --with-spglib=no --with-hdf5=no --with-spfft=no --enable-omp=yes --with-elpa=no

i.e., only the cmake, gcc, fftw and mpich are from system, everything is CP2K toolchain installed. My intention is to build the SIRIUS support in the end as well.

Also, on top of this, new gcc versions (9.2.1 on my system) on some systems will require "-fPIC" / "-fpic" / "-fpie" compiler flags as I just found out.

Thank you!

**Comment by dev-zero** [comment]
> ```
> ./install_cp2k_toolchain.sh -j 4 --mpi-mode=mpich --math-mode=openblas --libint-lmax=7 --with-gcc=system --with-cmake=system --with-mpich=system --with-libxc=install --with-libint=install --with-fftw=system --with-reflapack=no --with-openblas=install --with-libsmm=no --with-libxsmm=install --with-ptscotch=no --with-parmetis=no --with-metis=no --with-superlu=no --with-pexsi=no --with-quip=no --with-plumed=no --with-sirius=no --with-gsl=install --with-libvdwxc=no --with-spglib=no --with-hdf5=no --with-spfft=no --enable-omp=yes --with-elpa=no
> ```

is that `--with-elpa=no` a typo?

IF you are building ELPA with the toolchain despite the given commandline, can you please attach the full ELPA build logs (possibly as a tarball)? Most likely the following files while some of them might be missing:

```
build/elpa-2019.05.001/obj_thread/configure.log
build/elpa-2019.05.001/obj_thread/install.log
build/elpa-2019.05.001/obj_thread/config.log
build/elpa-2019.05.001/obj_thread/make.log
build/elpa-2019.05.001/obj_no_thread/configure.log
build/elpa-2019.05.001/obj_no_thread/install.log
build/elpa-2019.05.001/obj_no_thread/config.log
build/elpa-2019.05.001/obj_no_thread/make.log
```

**Comment by stanos4** [comment]
Hi, yes, that was a typo, if I didn't overlook anything else, remaining of the command should be what I actually used (even though it should not really matter). Attached are the requested files.
[config.log](https://github.com/cp2k/cp2k/files/3969474/config.log)
[configure.log](https://github.com/cp2k/cp2k/files/3969475/configure.log)
[make.log](https://github.com/cp2k/cp2k/files/3969476/make.log)

edit: also, it seems to be related to gcc 9.2, or other, machine specific things. Compilation on cluster with gcc 7.3 went fine.

**Comment by dev-zero** [comment]
So far I'm unable to reproduce the issue with vanilla gcc 9.2.0 and mpich 3.3.2. Guessing from the `make.log` it seems that for some reason the dependencies are not generated in the same order as our test systems even though ELPA is built with `-j1`.

```
@@ -284,1014 +284,105 @@
   F90 MOD  [libelpatest_la] ../test/shared/test_prepare_matrix.F90
   F90 MOD  [libelpatest_la] ../test/shared/test_analytic.F90
   F90 MOD  [libelpatest_la] ../test/shared/test_output_type.F90
-  F90 DEPS /data/tiziano/cp2k/tools/toolchain/build/elpa-2019.05.001/obj_no_thread/.fortran_dependencies/dependencies.mk
+  F90 DEPS /home/stano/install/cp2k-git/tools/toolchain/build/elpa-2019.05.001/obj_no_thread/.fortran_dependencies/dependencies.mk
   PPFC     src/libelpa_public_la-elpa_constants.lo
+f951: Warning: '-Werror=' argument '-Werror=format-security' is not valid for Fortran
   PPFC     src/general/libelpa_private_la-elpa_utilities.lo
+f951: Warning: '-Werror=' argument '-Werror=format-security' is not valid for Fortran
   PPFC     src/libelpa_private_la-elpa_generated_fortran_interfaces.lo
-  PPFC     src/libelpa_public_la-elpa_api.lo
-  PPFC     src/ftimings/libelpa_private_la-ftimings_type.lo
-  PPFC     src/ftimings/libelpa_private_la-ftimings_value.lo
-  PPFC     src/ftimings/libelpa_private_la-ftimings.lo
-  PPFC     src/libelpa_private_la-elpa_abstract_impl.lo
-  PPFC     src/libelpa_private_la-elpa_autotune_impl.lo
-  PPFC     src/helpers/libelpa_private_la-mod_precision.lo
-  PPFC     src/helpers/libelpa_private_la-mod_omp.lo
-  PPFC     src/helpers/libelpa_private_la-mod_mpi.lo
-  PPFC     src/GPU/libelpa_private_la-mod_cuda.lo
[...]
```

But even with a Fedora 32 and gcc-9.2.1 I'm unable to reproduce it.

**Comment by stanos4** [comment]
for reference: the problem seems to be with either MPICH (Fedora's 3.3.2-1) version of MPI or FFTW of MPICH. Building with toolchain version of MPICH, and therefore of toolchain's FFTW, goes fine. Also, using the Fedora's version of OpenMPI (and the corresponding system FFTW) compiles fine.

Thank you!

**Comment by dev-zero** [comment]
I've contacted the ELPA developers, unfortunately the error is also unknown there. But since this is not the first time I've seen this, can you please post the `obj_no_thread/src/fortran_constants.F90` from the faulty build? I suspect that something goes wrong in the following build commands:

```make
src/fortran_constants.F90: $(top_srcdir)/src/fortran_constants.h | src
    @$(CPP) $(CPPFLAGS) -I$(top_builddir)/ -I$(top_srcdir)/ -I. $< -o $@_ || { rm -f $@; exit 1; }
    @awk '/!ELPA_C_DEFINE/ {gsub(/!ELPA_C_DEFINE/, "\n"); gsub(/NEWLINE/, "\n"); print;}' < $@_ > $@ || { rm -f $@; exit 1; }
    @rm $@_
```

**Comment by dev-zero** [comment]
You can also try to apply the attached patch (`cd tools/toolchain; patch -p1 < ~/Downloads/elpa-debug.patch.txt`) and rerun the toolchain. The build will then interrupt after the configuration step and then you should upload `elpa-2019.05.001/obj_no_thread/config.log`, `elpa-2019.05.001/obj_no_thread/src/fortran_constants.F90` and `elpa-2019.05.001/obj_no_thread/src/fortran_constants.F90_`.

[elpa-debug.patch.txt](https://github.com/cp2k/cp2k/files/3983549/elpa-debug.patch.txt)

**Comment by stanos4** [comment]
took some time because I was trying several build options.
In the attached tar you will find the requested log and fortran files after applying the patch.

Also, I am not sure whether this could possibly be related, but, using the system OpenMPI + toolchain FFTW I can "successfully" build the tools, but cp2k build fails afterwards (I tried local, popt versions only). See the cp2k-OpenMPIinstall.log file.
[error.tar.zip](https://github.com/cp2k/cp2k/files/3987651/error.tar.zip)
[cp2k-OpenMPIinstall.log](https://github.com/cp2k/cp2k/files/3987657/cp2k-OpenMPIinstall.log)

**Comment by dev-zero** [comment]
@stanos4 as a side-note for testing: when changing options in the toolchain (especially when switching the MPI mode) you may have to force rebuild of dependent packages manually (like scalapack or elpa) by removing their directory and the corresponding `setup_...` script in `build/` and the installed files in `install/`.

**Comment by stanos4** [comment]
yep, that's what I'm doing and that's why it takes so long. Everytime I delete the build & install dirs to be sure to rebuild properly everything (and using libint-lmax=7 takes some time on my laptop to finish). Also, before compilation of cp2k itself I do "make distclean", that, as far as I can see removes all previous-build related files.
I also try not to forget open new terminal every rebuild. Which makes me remember, to successfully build libint I think, I need to set CPPFLAGS before running the install script:

    export CPPFLAGS=" -no-pie -fPIC "

**Comment by dev-zero** [comment]
TBH I'm a bit lost now: the generated `fortran_constants.F90` are exact matches and there are not many possibilities on what could go wrong between `elpa_api.F90` which uses `elpa_constants.F90` which `#include`s the `fortran_constants.F90`.
What we have seen in the past are that some warnings flags (of which a large number seems to be implicitly enabled on your system) may lead to the compiler not being standards compliant anymore.

There are now multiple things you could check:
* if you can reproduce the issue manually with `mpif90 -fdump-fortran-original -DHAVE_CONFIG_H -I. -I..   -no-pie -fPIC   -Imodules -Jmodules -Iprivate_modules -O2 -ftree-vectorize -g -fno-omit-frame-pointer -march=native  -I'/home/stano/install/cp2k-git/tools/toolchain/install/openblas-0.3.6/include'  -ffree-line-length-none -mavx2 -mfma -msse4  -c -o src/libelpa_public_la-elpa_api.lo ../src/elpa_api.F90` in `elpa-2019.05.001/obj_no_thread` you could add `-fdump-fortran-original` and compare the output with 
[mine](https://github.com/cp2k/cp2k/files/3988465/fortran-original.dump.txt).
* You could try to remove `-O2 -ftree-vectorize -g -fno-omit-frame-pointer -march=native` to see whether that changes it.
* Adding `-echo` or `-show` to obtain the final compiler call as generated by the MPICH wrapper might also be something.
