### ISSUE TITLE
Remove Subversion references in do_regtest

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#7]

**Comment by dev-zero** [comment]
Does it really make sense to have `do_regtest` update the repository and therefore possibly itself?
Especially in cases where we're running `do_regtest` multiple times for different configurations on one host, it is definitely better to have one shared repository for the different builds and not update them in-between.
I would at least disable the update by default, especially now with Git where there is the possibility that there is no remote to pull from.
maybe also @alazzaro your opinion?

**Comment by oschuett** [comment]
I agree, that `git pull` should be independent from `git log`. The later should, if possible, always be executed.

I wouldn't mind changing the default behavior, but we should consult with @mkrack first.

**Comment by mkrack** [comment]
The PSI regtester run also do_regest with the -nogit -nosvn flags. The git pull is done as the svn update before in the local wrapper script. So, I would also not mind, if the default behavior of do_regtest is changed to -nogit.

**Comment by oschuett** [comment]
Well, if nobody uses the feature then maybe we should remove it altogether?

**Comment by dev-zero** [comment]
Agreed. There is also an easy way to pull out the SHA if a `.git` is present without Git. Will do tomorrow.
