### ISSUE TITLE
toolchain: filter variables in bash environment preservation

### ISSUE THREAD

**Issue by owainkenwayucl** [cp2k/cp2k#709]
I'm trying to build the toolchain from CP2K 7.1 with GCC + OpenMPI on our RHEL 7.x cluster but I'm running into a weird issue where it's running out of environment space just after the step where it runs `scripts/install_parmetis`.

```
$ ./install_cp2k_toolchain.sh --with-sirius=no --with-spfft=no --with-elpa=no --with-libvdwxc=no --with-hdf5=no --with-parmetis=no
MPI is detected and it appears to be OpenMPI
nvcc not found, disabling CUDA by default
Compiling with 40 processes.
==================== Finding GCC from system paths ====================
path to gcc is  /shared/ucl/apps/gcc/4.9.2/bin/gcc
path to g++ is  /shared/ucl/apps/gcc/4.9.2/bin/g++
path to gfortran is  /shared/ucl/apps/gcc/4.9.2/bin/gfortran
Found include directory /usr/include
Found lib directory /lustre/shared/ucl/applications/gcc/4.9.2/lib64
Step gcc took 8.00 seconds.
==================== Getting proc arch info using OpenBLAS tools ====================
OpenBLAS detected LIBCORE = haswell
OpenBLAS detected ARCH    = x86_64
==================== Installing CMake ====================
cmake-3.15.1 is already installed, skipping it.
Step cmake took 0.00 seconds.
Step valgrind took 0.00 seconds.
==================== Finding OpenMPI from system paths ====================
path to mpirun is  /shared/ucl/apps/openmpi/ucl-wrapper-omp3+/bin/mpirun
path to mpicc is  /shared/ucl/apps/openmpi/3.1.4/gnu-4.9.2/bin/mpicc
path to mpif90 is  /shared/ucl/apps/openmpi/3.1.4/gnu-4.9.2/bin/mpif90
path to mpic++ is  /shared/ucl/apps/openmpi/3.1.4/gnu-4.9.2/bin/mpic++
Step openmpi took 0.00 seconds.
Step reflapack took 0.00 seconds.
==================== Installing OpenBLAS ====================
openblas-0.3.6 is already installed, skipping it.
Step openblas took 0.00 seconds.
==================== Installing FFTW ====================
fftw-3.3.8 is already installed, skipping it.
Step fftw took 1.00 seconds.
Step spfft took 0.00 seconds.
==================== Installing LIBINT ====================
libint-2.6.0 is already installed, skipping it.
Step libint took 0.00 seconds.
==================== Installing LIBXC ====================
libxc-4.3.4 is already installed, skipping it.
Step libxc took 1.00 seconds.
Step libsmm took 0.00 seconds.
==================== Installing Libxsmm ====================
libxsmm-1.14 is already installed, skipping it.
Step libxsmm took 1.00 seconds.
==================== Installing ScaLAPACK ====================
scalapack-2.0.2 is already installed, skipping it.
Step scalapack took 0.00 seconds.
Step elpa took 0.00 seconds.
Step ptscotch took 1.00 seconds.
Step parmetis took 0.00 seconds.
/lustre/home/uccaoke/Source/cp2k-7.1-gnu/tools/toolchain/scripts/tool_kit.sh: line 12: /usr/bin/date: Argument list too long
```

I've tried removing various optional packages but it doesn't really help as lots of environment variables are still set as things progress.

Looking at `install/toolchain.env` it's quite large:

```
$ ls -alh install/toolchain.env
-rw------- 1 uccaoke uccapc3 276K Jan  7 12:07 install/toolchain.env
```

In the middle is a massive blob of termcap data with `^A` repeated endlessly.

I'm starting to think this may be GNU screen related - I'm going to update this ticket as I investigate.

**Comment by owainkenwayucl** [comment]
Outside of GNU screen the toolchain proceeds as designed.

**Comment by dev-zero** [comment]
@owainkenwayucl can you identify the name of the variable with the huge content?
We likely have improve the naive way of preserving the environment and do something more elaborate, like the Gentoo package managers [portage](https://github.com/gentoo/portage/blob/cb9be3d608ed219893f917af42fb5337196304ee/bin/save-ebuild-env.sh) or [paludis](http://git.exherbo.org/paludis/paludis.git/tree/paludis/repositories/e/ebuild/builtin_saveenv.bash?id=df502f2988a1810dd1bf770bc07fc46cae037306).

**Comment by oschuett** [comment]
The toolchain stores its environment variables in `toolchain/install/toolchain.env`.

**Comment by owainkenwayucl** [comment]
@dev-zero The variable is `TERMCAP`.

**Comment by oschuett** [comment]
Unfortunately, I can not reproduce this. I tried the following:
```
$ screen
$ cd cp2k/tools/toolchain
$ ./install_cp2k_toolchain.sh --libint-lmax=4
....
$ du -h install/toolchain.env 
20K     install/toolchain.env
```
While `TERMCAP` is present within the screen and gets stored in the `toolchain.env` things don't blow up.

So, my guess is that you have some kind of special setup for your shell or screen?

**Comment by oschuett** [comment]
I'm closing this as it appears to be a one-off problem.

**Comment by dev-zero** [comment]
as cited: distributions filter variables in (bash) environment preservation scripts for a good reason

**Comment by e-kwsm** [comment]
I also encounter this issue with `TERM=xterm-256color`, screen 4.01.00devel, and zsh 5.7.1, while zsh 5.0.2 is successful on the same machine. In my case the `kb` field (Backspace key) is messed.
On a different machine (`TERM=xterm-256color`, screen 4.06.02, and zsh 5.7.1), `TERM` is not overwritten in screen, i.e., `$TERM != screen`, and `TERMCAP` is fine.

I don't know the details but `^A` is the default escape character for screen, which possibly causes the issue.

Workaround:
- `unset TERMCAP` after attaching screen
- `screen -d -m` and then `screen -r` (https://unix.stackexchange.com/q/67450)

**Comment by dev-zero** [comment]
most likely the same issue appeared again: https://groups.google.com/d/msg/cp2k/4iwvz2cuh80/X0fEdPdxAgAJ
