### ISSUE TITLE
Should SIRIUS be activated by default

### ISSUE THREAD

**Issue by mtaillefumier** [cp2k/cp2k#71]
During a meeting with the others developers of sirius, it was suggested that sirius should be activated by default in cp2k (it is not at the moment because of some others issues hopefully fixed now). SIRIUS integration to cp2k is already in good shape despite the few glitches with the build system. We have few test cases for regression and basic functionalities up and running. The build has passed basic CI tests (I do not the psmp tests activated) but I think it would be a good opportunity to catch others potential problems (like the farming issue) in a more systematic way if SIRIUS is built by default. 

I already have a patch ready for it but I wanted to have your view on this before making a pull request. I know it goes against the changes I made yesterday, but most of the changes where needed anyway.

**Comment by oschuett** [comment]
Addressed via #88.
