### ISSUE TITLE
tests: SE/regtest-3-2/SiO2 unstable

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#713]
mentioned test turned out to be unstable, needs to be updated

**Comment by oschuett** [comment]
We have quite a few regtests with loose thresholds. I don't think it makes sense to open individual issues for each of them. Instead one can look at the [Regtest Survey](https://dashboard.cp2k.org/regtest_survey.html). Nevertheless, it might be good to keep a generic issue around as a reminder.

Btw, we also have many regtests which have stabilized and where we could tighten the threshold (marked in green).

**Comment by oschuett** [comment]
I haven't noticed `SE/regtest-3-2/SiO2` in a while. So, it seem the tolerance is now sufficient and we can close this issue.
