### ISSUE TITLE
Toolchain build stuck at spfft

### ISSUE THREAD

**Issue by anneb101** [cp2k/cp2k#727]
Hello all,
I am trying to build CP2K using the default toolchain script and it gives an error at the point of spfft installation. I am not able to trace the source of the error. Any help on how to address this is greatly appreciated. I am using version 6.1.
Thanks,
Anne

`$ ./install_cp2k_toolchain.sh

MPI is detected and it appears to be OpenMPI
nvcc not found, disabling CUDA by default
Compiling with 16 processes.
==================== Finding GCC from system paths ====================
path to gcc is  /opt/ohpc/pub/compiler/gcc/5.4.0/bin/gcc
path to g++ is  /opt/ohpc/pub/compiler/gcc/5.4.0/bin/g++
path to gfortran is  /opt/ohpc/pub/compiler/gcc/5.4.0/bin/gfortran
Found include directory /usr/include
Found lib directory /opt/ohpc/pub/compiler/gcc/5.4.0/lib64
Step gcc took 0.00 seconds.
==================== Getting proc arch info using OpenBLAS tools ====================
OpenBLAS detected LIBCORE = sandybridge
OpenBLAS detected ARCH    = x86_64
==================== Installing CMake ====================
cmake-3.15.1 is already installed, skipping it.
Step cmake took 0.00 seconds.
Step valgrind took 0.00 seconds.
==================== Finding OpenMPI from system paths ====================
path to mpirun is  /export/apps/openmpi-4.0.1_gcc/bin/mpirun
path to mpicc is  /export/apps/openmpi-4.0.1_gcc/bin/mpicc
path to mpif90 is  /export/apps/openmpi-4.0.1_gcc/bin/mpif90
path to mpic++ is  /export/apps/openmpi-4.0.1_gcc/bin/mpic++
Step openmpi took 0.00 seconds.
==================== Installing LAPACK ====================
lapack-3.8.0 is already installed, skipping it.
Step relapack took 0.00 seconds.
==================== Installing OpenBLAS ====================
openblas-0.3.6 is already installed, skipping it.
Step openblas took 0.00 seconds.
==================== Installing FFTW ====================
fftw-3.3.8 is already installed, skipping it.
Step fftw took 1.00 seconds.
==================== Installing spfft ====================
SpFFT-0.9.8.tar.gz is found
Installing from scratch into /home/CP2KDIR/tools/toolchain/install/SpFFT-0.9.8
ERROR: (./scripts/install_spfft.sh, line 41) Non-zero exit code detected.
`

**Comment by dev-zero** [comment]
Are you sure about the version? AFAIK SpFFT was added in v7.1.
To get more details about the build failure, please take a look at `*.log` files found in `build/SpFFT-0.9.8/build-cpu/`. If unsure, generate an archive of the builds logs using

    find build/ -iname '*.log' -or -iname 'setup_*' -print0 | xargs -0 tar cfz logs.tar.gz

and attach them to this issue.

**Comment by mtaillefumier** [comment]
Hi,

my best bet is that their is a problem with the environment. Could you give the output of the command  `export` in a shell. Also, 

I also think you are compiling cp2k 7.1 not 6.1.

**Comment by sasha-computer** [comment]
I have the same issue with 7.1, attached is my logs.as @dev-zero  requested
[logs.tar.gz](https://github.com/cp2k/cp2k/files/4065532/logs.tar.gz).

**Comment by mtaillefumier** [comment]
Unfortunately the logs are missing. We only have the setup files.

**Comment by sasha-computer** [comment]
> Unfortunately the logs are missing. We only have the setup files.

Apologies! I have edited my original comment with an update logs.tar.gz file.

**Comment by mtaillefumier** [comment]
it is a problem of compiler. you are using a version of gcc that does not fully support c++11. the problem is here

`The CXX compiler identification is GNU 4.8.5`

Are you compiling gcc yourself with the toolchain or rely on the gcc installed on your machine. If it is the later then update your compiler (or load the relevant module), if it is the former then I have to adjust the scripts accordingly.

**Comment by sasha-computer** [comment]
> it is a problem of compiler. you are using a version of gcc that does not fully support c++11. the problem is here
> 
> `The CXX compiler identification is GNU 4.8.5`
> 
> Are you compiling gcc yourself with the toolchain or rely on the gcc installed on your machine. If it is the later then update your compiler (or load the relevant module), if it is the former then I have to adjust the scripts accordingly.

It is the latter, I loaded an updated GCC and it has worked now! Thanks for your help.

**Comment by mtaillefumier** [comment]
That's good. 

Any compiler not supporting c++11 at least will fail to compile SIRIUS or spfft.
