### ISSUE TITLE
SIRIUS: Switch to CP2K's parser for UPF files.

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#728]
I think there are currently two problems with the way SIRIUS reads pseudo potentials:

1.  SIRIUS uses a custom json format while UPF files are [commonly](https://www.materialscloud.org/discover/sssp) distributed in the [XML format](https://www.quantum-espresso.org/pseudopotentials/unified-pseudopotential-format). For the conversion users have to run the [upf_to_json.py](https://github.com/electronic-structure/SIRIUS/blob/develop/apps/upf/upf_to_json.py) tool, which is an unnecessary burden.

2. SIRIUS handles the parsing [all by itself](https://github.com/cp2k/cp2k/blob/master/src/atom_upf.F#L120), which leaves the CP2K datastructures uninitialized, including e.g. `pot%zion`. We [once](https://github.com/cp2k/cp2k/commit/595591190969e81cdeaa0688b21cdc2aab1c7497) parsed the json file twice, which was just a brittle workaround.

In my opinion, the clean solution is to use [CP2K's UPF parser](https://github.com/cp2k/cp2k/blob/master/src/atom_upf.F#L180) and then pass the values on to SIRIUS. While CP2K's parser is probably not yet up to the task, we can look at Quantum ESPRESSO's [implementation](https://github.com/QEF/q-e/blob/master/Modules/read_upf_v2.f90) for inspiration.

**Comment by mtaillefumier** [comment]
I also agree with you. 

This was a choice at the beginning. SIRIUS has absolutely everything to pass information about pseudo-potentials in the interface. It is done that way in QE for instance. However it was decided to postpone this. Note that we still need the mechanism of passing the potential file for the full-potential case because there is no standard at all. 

I remember looking at the UPF parser and found how that it is incomplete. PAW potentials are ignored, etc...

**Comment by alas-go** [comment]
The latest SIRUS download process could not been finished.  several hours passed, it only downloaded 15.5 MB but the size of  early editon 7.0.0 is 55 MB. I don't think the main problem is the slow connection speed of the internet. kindly, please upload the file pack to www.cp2k.org/static/downloads as soon as possible.
thks.


######I tried to install the cp2k master on Feb. 18,  The latest edition of SIRUS is 7.0.2 but the script for toolchain installation ######does not match the latest edtion. it need an update. when i download it from github, it is sure that the package is only 15 MB and it report an unexpected ending.

**Comment by oschuett** [comment]
@toxa81, gentle ping :-)

I still think this would really help with on-boarding new users.

**Comment by toxa81** [comment]
We have all the functionality to load UPF files (set radial grid, beta projectors, augmentation operator, wave-functions, D_ion) programmaticaly. If you have UPF parser, this is a good simplification. We will start looking at it after NY. I wil put a cross-reference issue on our page.

**Comment by mtaillefumier** [comment]
It is not that simple to use the cp2k upf parser. The parser is only implementing half of the information we need in SIRIUS which makes it unusable in practice. 
Unless someone knows a library that conveniently parses all UPF files and supports more than one language then it could be considered as a valid solution. Any other option would be a time consuming process as no UPF standard exist.

**Comment by oschuett** [comment]
Probably the easiest solution is to extend CP2K's parser. As you said, it's already half way there ;-)

But seriously, your [current parser](https://github.com/electronic-structure/SIRIUS/blob/develop/apps/upf/upf2_to_json.py) is only 400 lines of Python code. So, it shouldn't be that much effort, right?

An alternative would be to use QE's [upflib](https://github.com/QEF/q-e/tree/develop/upflib), but that is most likely more work.

**Comment by oschuett** [comment]
Resolved via #3651.
