### ISSUE TITLE
Drop support for non-OpenMP builds

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#729]
We now got CPUs with [64 cores](https://www.amd.com/de/products/cpu/amd-ryzen-threadripper-3970x) per socket. Hence, running serial binaries will become very rare. On the other hand supporting non-OpenMP binaries has a real maintenance cost to it, in particular for the toolchain. 

Users who still want to run with a single thread, e.g. the high throughput folks,  can use `OMP_NUM_THREADS=1`. We know from our [scaling tests](https://dashboard.cp2k.org/archive/scaling/index.html) that the performance overhead for OpenMP is negligible.

**Comment by alazzaro** [comment]
I like this idea, we are an HPC code anyway and all compiles we support have OpenMP...

**Comment by mkrack** [comment]
This makes sense and therefore I have close down two regression tester (#732)
