### ISSUE TITLE
Lots of tools not ported to python3 yet

### ISSUE THREAD

**Issue by mbanck** [cp2k/cp2k#737]
python2 is EOL and it seems to me that lots of tools (also in dbcsr) are still python2:

```
$ egrep -r '(bin|env)'.python  | grep -v python3
exts/dbcsr/tests/generate_libcusmm_unittest_multiply.py:#!/usr/bin/env python
exts/dbcsr/tests/generate_libcusmm_timer_multiply.py:#!/usr/bin/env python
exts/dbcsr/.pre-commit/check_header.py:#!/usr/bin/env python
exts/dbcsr/tools/fprettify/run_tests.py:#!/usr/bin/env python
exts/dbcsr/tools/fprettify/fprettify/tests/__init__.py:#!/usr/bin/env python
exts/dbcsr/tools/fprettify/fprettify/__init__.py:#!/usr/bin/env python
exts/dbcsr/tools/fprettify/fprettify.py:#!/usr/bin/env python
exts/dbcsr/tools/fprettify/setup.py:#!/usr/bin/env python
exts/dbcsr/tools/build_utils/test_makedep.py:#!/usr/bin/env python
exts/dbcsr/tools/build_utils/check_archives.py:#!/usr/bin/env python
exts/dbcsr/tools/build_utils/fypp/tools/waf/fypp_preprocessor.py:#!/usr/bin/env python
exts/dbcsr/tools/build_utils/fypp/tools/waf/fypp_fortran.py:#!/usr/bin/env python
exts/dbcsr/tools/build_utils/fypp/bin/fypp:#!/usr/bin/env python
exts/dbcsr/tools/build_utils/makedep.py:#!/usr/bin/env python
exts/dbcsr/Makefile:	/usr/bin/env python --version
exts/dbcsr/src/acc/libsmm_acc/libcusmm/generate_parameters.py:#!/usr/bin/env python
exts/dbcsr/src/acc/libsmm_acc/libcusmm/generate_kernels.py:#!/usr/bin/env python
tools/package_planner/plan_packages.py:#!/usr/bin/env python
tools/prettify/prettify.py:#!/usr/bin/env python
tools/prettify/fprettify/run_tests.py:#!/usr/bin/env python
tools/prettify/fprettify/fprettify/tests/__init__.py:#!/usr/bin/env python
tools/prettify/fprettify/fprettify/__init__.py:#!/usr/bin/env python
tools/prettify/fprettify/fprettify.py:#!/usr/bin/env python
tools/prettify/fprettify/setup.py:#!/usr/bin/env python
tools/prettify/prettify_test.py:#!/usr/bin/env python
tools/manual/generate_sitemap.py:#!/usr/bin/env python
tools/plot_mem_from_trace.py:#!/usr/bin/python
tools/maple2f90/maple2f90.py:#!/bin/env python
tools/diff_cp2k.py:#!/usr/bin/env python
tools/find_openmp_mistakes.py:#!/usr/bin/python
tools/regtesting/timings.py:#!/usr/bin/env python
tools/regtesting/test_scaling.py:#!/usr/bin/python
tools/regtesting/prettify_TEST_FILES.py:#!/usr/bin/python
tools/fix_unused_public.py:#!/usr/bin/env python
tools/build_utils/check_archives.py:#!/usr/bin/env python
tools/build_utils/discover_programs.py:#!/usr/bin/env python
tools/build_utils/fypp:#!/usr/bin/env python
tools/build_utils/makedep.py:#!/usr/bin/env python
tools/conventions/analyze_gfortran_ast.py:#!/usr/bin/env python
tools/conventions/summarize_issues.py:#!/usr/bin/env python
tools/conventions/analyze_src.py:#!/usr/bin/env python
tools/conventions/analyze_gfortran_warnings.py:#!/usr/bin/env python
tools/find_bitrot_code.py:#!/usr/bin/python
tools/minimax_tools/minimax_to_fortran_source.py:#!/usr/bin/env python
tools/logo/gen_cp2k_logo.py:#!/usr/bin/python
tools/coverage/test_coverage.py:#!/usr/bin/python
tools/doxify/is_fypp.py:#!/usr/bin/env python
tools/toolchain/scripts/parse_if.py:#!/usr/bin/env python
Makefile:PYTHON       := /usr/bin/env python
src/start/python/test/test_force_env.py:#!/usr/bin/env python
src/start/python/test/test_standalone.py:#!/usr/bin/env python
src/start/python/sample_force_env.py:#!/usr/bin/env python
src/start/python/setup.py:#!/usr/bin/env python
```

Are there plans to tackle this in the near future, or are most of those false positives?

**Comment by dev-zero** [comment]
All the relevant tools (doxify, prettify, build_tools) are already Python 2+3 compatible (and I think our regtesters build with Python 3 only), so most of those are false positives. DBCSR's CUDA scripts are even Python 3 only.
Is this how distros determine Python 3 compatibility, when the shebang explicitly states Python 3?

**Comment by mbanck** [comment]
>  Is this how distros determine Python 3 compatibility, when the shebang explicitly states Python 3?

That is my understanding, i.e. they won't switch to `/usr/bin/python` being python3, that binary will just vanish. I might be mistaken though.

**Comment by oschuett** [comment]
I guess, we could consider dropping Python 2 support for the next release.

A year ago 50% of our users where still using Python 2. If we assume a half-life of one year, then this will have dropped to ~10% by the end of 2020.

Also, ASE already dropped Python 2 in [July 2019](https://wiki.fysik.dtu.dk/ase/releasenotes.html#version-3-18-0).

**Comment by mbanck** [comment]
> A year ago 50% of our users where still using Python 2

Are you saying that they do not have python3 installed and/or no option to run python3, or just that they are still using python2 as well?

**Comment by oschuett** [comment]
The questions was _"Which Python version are you using? (Run: python --version)"_.

The survey was sent out 2018-11-22 and the results were:

| Python version | Number of replies |
| -------------- | ----------------- |
| 2              |  1                |
| 2.6            |  2                |
| 2.7            | 23                |
| 3              |   3               |
| 3.4            |  1                |
| 3.5            |  4                |
| 3.6            |  8                |
| 3.7            |  4                |

A few people gave multiple answers, which I then counted towards the later version.

**Comment by mbanck** [comment]
Well, ok maybe if you had written "Run pythont3 --version, and if that does not exist, python --version" the results would have been different, who knows.

In any case, there is quite a lot of pressure in Debian/Ubuntu right now to drop python2 for the next version (not sure what will happen for 20.04 LTS, they might not be willing to support python2 over its lifespan), so maybe keep this issue open as a reminder that tools should be gradually migrated.

However, the programs in `tools/build_utils` (like `discover_programs.py`) might be more urgent as CP2K won't be buildable once distributions start to remove python2.

**Comment by oschuett** [comment]
I'm also mostly worried about `tools/build_utils`. Somehow, I always assumed that `python` (without a version) would stay to allow for backwards compatibility. Of course, if that's not the case, then we should really switch now.

Nevertheless, our next release will probably not be in time for 20.04 LTS. So, I'm afraid you'll have to patch the shebangs yourself just once. All our scripts should already work with Python3.

**Comment by mbanck** [comment]
I now checked back with a Ubuntu developer, and 20.04 will ship python2, but they will rename the binary from `/usr/bin/python` to `/usr/bin/python2`  (and it will not be installed by default).

We've now updated the shebangs in build_utils with a patch and will upload a python3-ready version of CP2K to Debian/Ubuntu in due course.
