### ISSUE TITLE
elpa cuda build

### ISSUE THREAD

**Issue by stanos4** [cp2k/cp2k#749]
Hi, I'm trying to build the recent master version with Cuda 10.1.105 support for V100, gcc 7.3.0. After ELPA's configure, I need to manually modify Makefile for both _obj_no_thread_ and _obj_thread_ builds. I need to change the NVCCFLAGS variable - copy the content of the LDFLAGS to NVCCFLAGS, but modify:
-Wl,--enable-new-dtags  --> -Xlinker=--enable-new-dtags
-Wl,-rpath='/path.../'   -->  -Xlinker=-rpath,'/path.../'

and then, everywhere where the NVCCFLAGS and LDFLAGS are combined, remove the LDFLAGS, i.e.

    .cu.lo:
            NVCC="$(NVCC)" libtool --mode=compile --tag=CC $(top_srcdir)/nvcc_wrap $(NVCCFLAGS) $(LDFLAGS) -I$(top_builddir)/ -I$(top_srcdir)/  -c $< -o $@

to

    .cu.lo:
            NVCC="$(NVCC)" libtool --mode=compile --tag=CC $(top_srcdir)/nvcc_wrap $(NVCCFLAGS) -I$(top_builddir)/ -I$(top_srcdir)/  -c $< -o $@

as far I could find, this should not be a problem of CP2K, but of the CMake. On some places, they report that Cmake 3.12+ should make the trick, unfortunately, it does not seem to be the case here - I use the toolchain provided 3.15.1

**Comment by oschuett** [comment]
Unfortunately, we have not yet managed to build ELPA with CUDA. However, this is certainly on our agenda. See #464 for further discussions.
