### ISSUE TITLE
Formatting check not working

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#750]
In the current master branch 42 files are not formatted correctly.

For earlier discussions see [here](https://github.com/cp2k/cp2k/pull/636#issuecomment-555996021) and [here](https://github.com/cp2k/cp2k/pull/632#issuecomment-555705513).

Reproducer:
```
$ git clone git@github.com:cp2k/cp2k.git
$ cd cp2k
$ git submodule update --init --recursive
$ make -j10 pretty
...
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   src/arnoldi/arnoldi_data_manipulation.f90
	modified:   src/arnoldi/arnoldi_data_methods.F
	modified:   src/arnoldi/arnoldi_data_selection.f90
	modified:   src/arnoldi/arnoldi_methods.F
	modified:   src/common/callgraph.F
	modified:   src/common/cp_array_sort.F
	modified:   src/common/cp_array_utils.F
	modified:   src/common/list.F
	modified:   src/common/list_callstackentry.F
	modified:   src/common/list_routinereport.F
	modified:   src/common/list_routinestat.F
	modified:   src/common/list_timerenv.F
	modified:   src/common/memory_utilities.F
	modified:   src/common/routine_map.F
	modified:   src/cp_dbcsr_operations.F
	modified:   src/dbcsrx/dbcsr_vector.F
	modified:   src/eri_mme/eri_mme_lattice_summation.F
	modified:   src/ewalds_multipole.F
	modified:   src/fm/cp_fm_elpa.F
	modified:   src/fm/cp_linked_list_fm.F
	modified:   src/gauss_colloc.F
	modified:   src/grid/xyz_to_vab_optimised.F
	modified:   src/input/cp_linked_list_input.F
	modified:   src/input/cp_parser_inpp_types.F
	modified:   src/input_optimize_input.F
	modified:   src/libint_wrapper.F
	modified:   src/mp2_eri.F
	modified:   src/mpiwrap/message_passing.F
	modified:   src/mpiwrap/message_passing.f90
	modified:   src/negf_integr_utils.F
	modified:   src/pw/cp_linked_list_pw.F
	modified:   src/qmmm_gpw_forces.F
	modified:   src/se_fock_matrix_integrals.F
	modified:   src/subsys/atomic_kind_list_types.F
	modified:   src/subsys/molecule_kind_list_types.F
	modified:   src/subsys/molecule_list_types.F
	modified:   src/subsys/particle_list_types.F
	modified:   src/swarm/swarm_message.F
	modified:   src/xc/cp_linked_list_xc_deriv.F
	modified:   src/xc/xc_libxc_wrap.F
	modified:   src/xc/xc_perdew_wang.F
	modified:   src/xc/xc_sr_lda.F
```

**Comment by dev-zero** [comment]
yes, prettify was not rewinding the filehandle properly when it found fypp directories, which unintentionally also skipped the `fprettify`, which was fixed by edd8f9718549e5d588dc225d8608b4602f990535.
And since we check for prettified files as-needed now in the CI I decided against yet another "prettify everything".

**Comment by oschuett** [comment]
I think, we should ensure that the master branch is always fully compliant. Then `make pretty` becomes useful again and we don't obfuscate random future commits with reformatting.

This applies of course to all the other pre-commit based tests as well, where we're most like not in compliance either.

**Comment by oschuett** [comment]
As predicted the _"prettify everything"_ that should have been part of https://github.com/cp2k/cp2k/commit/edd8f9718549e5d588dc225d8608b4602f990535 was shoehorned into an [unrelated pull request](#759). This shows that the _"prettify as-needed"_ approach does not work.

The root cause is that since https://github.com/cp2k/cp2k/commit/b7e6611d7a7da1c2fe66dd48e8d8950acd4fd13b we are using the [pre-commit](https://pre-commit.com) framework within the CI. The problem is that they serve two different use cases: While the CI should do a thorough and exhaustive check, the pre-commit hooks should only use modest resources to find the most common issues.

I therefore propose that we remove the pre-commit framework from the CI again. This will restore the old behavior incl. useful error messages, reduce complexity, and allow us to add new checks (#637).

Those who really want run all checks by themselves can always use the docker containers locally.

**Comment by dev-zero** [comment]
> As predicted the _"prettify everything"_ that should have been part of [edd8f97](https://github.com/cp2k/cp2k/commit/edd8f9718549e5d588dc225d8608b4602f990535) was shoehorned into an [unrelated pull request](#759).

Cool, so this issue is fixed then. I would most likely not have added it directly in edd8f97 but would have added a separate commit for it myself, as has been done now in commit 40778af2170fa69cf3cc416b2f3623d9b1fc4381.

> The root cause is that since [b7e6611](https://github.com/cp2k/cp2k/commit/b7e6611d7a7da1c2fe66dd48e8d8950acd4fd13b) we are using the [pre-commit](https://pre-commit.com) framework within the CI. The problem is that they serve two different use cases: While the CI should do a thorough and exhaustive check, the pre-commit hooks should only use modest resources to find the most common issues.

I would recommend to check how things are [currently implemented](https://github.com/cp2k/cp2k/blob/0482296e8bc855161dba846c8f1044897fbba701/tools/docker/scripts/test_formatting.sh#L14). Feel free to change this to `pre-commit run -a`.
