### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by oerc0122** [cp2k/cp2k#765]
https://github.com/cp2k/cp2k/blob/af259e795fe8697fbf34c367c1cece11df2c890b/tools/prettify/prettify_cp2k/normalizeFortranFile.py#L12

Regex (just after `?P<value>`, line attempts to match `:?`. Think this is intended to be non-matching group (?:).

**Comment by dev-zero** [comment]
Knowledge about this is probably lost to history, but your assumption likely makes sense. Do you want to fix it as part of #763 ?
