### ISSUE TITLE
Regtests in QS/regtest-corr_dipm take too long

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#779]
The [newly added](https://github.com/cp2k/cp2k/commit/5ffbcad9ea8227fd8543f587798aec8a93f0d613) regests in [QS/regtest-corr_dipm](https://github.com/cp2k/cp2k/tree/master/tests/QS/regtest-corr_dipm) take quite long, which occasionally leads to [timeouts](https://dashboard.cp2k.org/archive/minimal-sdbg/commit_5bb94ebccdf5243fb3bec20cb3c479a0f89e5718.txt).

@hforbert, could you please have a look? Ideally, tests shouldn't run longer than [30 seconds](https://github.com/cp2k/cp2k/issues/174).

**Comment by hforbert** [comment]
Got feedback from the implementor, hopefully iit is better/fixed with merge request #780, but
CI is either slow or not working atm.

**Comment by oschuett** [comment]
The CI got stuck somehow. I just restarted it which seems to have done the trick.

Thanks for reducing the runtimes!
