### ISSUE TITLE
add linters for Shell scripts and Python files

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#78]
A growing fraction of our code are bash scripts. Hence, we should look into using a linter like 
[ShellCheck](https://github.com/koalaman/shellcheck).

**Comment by dev-zero** [comment]
I also started using `pylint`/`flake8` for the Python scripts, I will come up with a `pre-commit` configuration for all of it.

**Comment by oschuett** [comment]
Yes, flake8 is a good idea. While you build the pre-commits, I'd add this to the CI-system. However, it will probably take a while until all our scripts are made to pass.

**Comment by dev-zero** [comment]
@oschuett you could then use the `pre-commit run -a` feature in the CI

**Comment by oschuett** [comment]
Yes, we should re-use your pre-commit scripts for the CI. I would like to run the flake8 as part of the existing [python test](https://dashboard.cp2k.org/archive/python/index.html) and create a similar test for shell scripts.

**Comment by oschuett** [comment]
We are now using `shellcheck` and `mypy` for new scripts.
