### ISSUE TITLE
cp2k shell binary missing from 7.1 release artifacts

### ISSUE THREAD

**Issue by ltalirz** [cp2k/cp2k#789]
The [latest release](https://github.com/cp2k/cp2k/releases/tag/v7.1.0) no longer includes a binary of the cp2k shell.

Is this on purpose? If not, could it be added?

Mentioning @oschuett

**Comment by oschuett** [comment]
The shell got integrated into the main binary. You can invoke it via command line flags `-s` / `--shell` or create a symlink:
```
ln -s cp2k.psmp cp2k_shell.psmp
```

**Comment by ltalirz** [comment]
Ah, great!
Maybe mention this in the release notes?
