### ISSUE TITLE
Typo in install_fftw.sh leads to build failures

### ISSUE THREAD

**Issue by LStuber** [cp2k/cp2k#796]
There is an error in the install_fftw.sh script:

https://github.com/cp2k/cp2k/blob/552c70dd21f9941e515a971f7079262164def7ba/tools/toolchain/scripts/install_fftw.sh#L100

The call to prepend-path is incorrect because of "=", I believe it should be
`prepend_path PKG_CONFIG_PATH "$pkg_install_dir/lib/pkgconfig"`

This results in install_fftw.sh overriding PKG_CONFIG_PATH instead of prepending to it.

**Comment by oschuett** [comment]
Thanks for reporting! Fixed via #824.
