### ISSUE TITLE
Update sourceforge support page to point to the Git

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#8]
https://sourceforge.net/projects/cp2k/support

**Comment by oschuett** [comment]
I don't have sufficient permissions for this. Maybe @mkrack or @juerghutter could have a look?

**Comment by oschuett** [comment]
Maybe we can start by removing more stuff from the Sourceforge project? In particular the download files and the svn repo could be scrapped.

**Comment by oschuett** [comment]
I just checked, the files are gone but the svn repo is still there. Is this the final state in which we want to leave the sourceforge project behind?

**Comment by mkrack** [comment]
I think we can only request now to delete the whole sourceforge project, since I found nothing more to drain or drop.

**Comment by oschuett** [comment]
I once proposed to empty the svn repository and got some opposition. I guess removing the entire project will upset even more people. So, should we just leave it as is and close this issue?

**Comment by mkrack** [comment]
I did not recognise such opposition, but if there is still somebody interested in the svn repositories of CP2K at sourceforge then this is fine and we can close this issue.
