### ISSUE TITLE
Benchmarks tests outdated / missing files

### ISSUE THREAD

**Issue by alazzaro** [cp2k/cp2k#816]
As described in https://github.com/cp2k/cp2k/pull/652#issuecomment-597372059, some of the benchmarks are outdated. For example:

https://github.com/cp2k/cp2k/blob/master/benchmarks/QS_mp2_rpa/32-H2O/RI-MP2.inp

gives

```
found an unknown keyword METHOD in section WF_CORRELATION    
```

Also, the file

https://github.com/cp2k/cp2k/blob/master/benchmarks/QS_mp2_rpa/32-H2O/RI-RPA.inp

wants to include the file

H2O-32-RI-RPA-TZ.inp

that doesn't exist...

**Comment by shoshijak** [comment]
> Also, the file
>
> https://github.com/cp2k/cp2k/blob/master/benchmarks/QS_mp2_rpa/32-H2O/RI-RPA.inp
>
> wants to include the file
>
> H2O-32-RI-RPA-TZ.inp
>
> that doesn't exist...

I guess it should include `H2O-32-RI-dRPA-TZ.inp` (with a `d`) instead.

**Comment by pseewald** [comment]
I guess these issues mostly come from input changes #806 - @JWilhelm could you have a look at it?

**Comment by kabicm** [comment]
I think @shoshijak is right! I have that file: `H2O-32-RI-dRPA-TZ.inp` currently in `/scratch/snx3000/kabicm/cp2k-master/benchmarks/QS_mp2_rpa/32-H2O/H2O-32-RI-dRPA-TZ.inp` if needed.

**Comment by pseewald** [comment]
In #806 a new benchmark was added - could this be included in the performance tester?

**Comment by alazzaro** [comment]
> In #806 a new benchmark was added - could this be included in the performance tester?

Sure, I think this is the benchmarks/QS_low_scaling_GW/GW.inp... I wil do once the other problems are fixed...

**Comment by alazzaro** [comment]
Update: Performance tests on Daint are back. Thanks @shoshijak , @JWilhelm , @pseewald 
Leaving this issue open, I will add the other benchmark...

**Comment by oschuett** [comment]
I added a check to the CI to catch unknown keywords in the benchmark inputs (#822).

**Comment by JWilhelm** [comment]
@alazzaro Could you already add the test

https://github.com/cp2k/cp2k/tree/master/benchmarks/QS_low_scaling_GW

to a performance tester? I couldn't find it on https://dashboard.cp2k.org/archive/cray-xc50-daint-mc-psmp_perf/index.html 

Did I overlook something?
