### ISSUE TITLE
Improving Python Tests

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#83]
Currently all our Python scripts are tested by calling them with `--selftest`. Unfortunately, virtually no script actually implements a proper self test. Still this test is useful as it verifies that syntax and imports work across different versions of Python.

I'd propose that in the future we require all scripts to support `-h` instead. Furthermore, scripts that match `*_unittest.py` are called again without any arguments.

**Comment by oschuett** [comment]
Sure `*_test.py` is fine too. This way it stays close to the script it's testing.

Just for completeness: The original goal of the Python dashboard test was to ensure that our build scripts work across different versions of Python.

**Comment by dev-zero** [comment]
The proper way is to use something like `check-ast` from https://github.com/pre-commit/pre-commit-hooks
