### ISSUE TITLE
Segmentation fault with Hirshfeld constraint

### ISSUE THREAD

**Issue by chrisahart** [cp2k/cp2k#847]
Dear CP2K developers,

When performing CDFT with Hirshfeld constraint I am getting the following error: "Program received signal SIGSEGV: Segmentation fault - invalid memory reference." This appears to be an issue reported previously (https://github.com/cp2k/cp2k/issues/560), however I am encountering it again in CP2K 7.1. This error occurs on both my local machine and on a cluster.

I have found this error to be difficult to reproduce, being sensitive to the system and to the atoms included in &ATOM_GROUP. For certain combinations of atoms CP2K runs successfully while with other combinations it crashes. Becke constraint runs in all cases, so this is isolated to Hirshfeld. 

I have attached two example input and output files, one with an atom combination that runs while another which fails. I have confirmed that Hirshfeld runs successfully for the input files included in the CP2K CDFT tutorial.

Regards,
Chris

(Originally posted on CP2K user forum: https://groups.google.com/forum/#!topic/cp2k/jaQdteFzSDc)

[fail.error](https://github.com/cp2k/cp2k/files/4404470/fail_error.log)
[fail.inp](https://github.com/cp2k/cp2k/files/4404471/fail_input.log)
[fail.out](https://github.com/cp2k/cp2k/files/4404472/fail_output.log)
[sucess.inp](https://github.com/cp2k/cp2k/files/4404479/sucess_input.log)
[sucess.out](https://github.com/cp2k/cp2k/files/4404480/sucess_output.log)
[input.xyz](https://github.com/cp2k/cp2k/files/4404473/input_xyz.log)

**Comment by juerghutter** [comment]
I fixed an indexing error in the CDFT Hirshfeld code. Hope this fixes the problems.

**Comment by chrisahart** [comment]
Thanks for the quick bug fix, this has indeed solved the problem.
