### ISSUE TITLE
OPTIONAL argument referenced but not PRESENT 

### ISSUE THREAD

**Issue by vzecca** [cp2k/cp2k#856]
Running many test cases, at line 836 of dbcsr_api.F the optional argument TEMPLATE is referenced
but it is not PRESENT.
dbcsr_api.F:836 "call dbcsr_distribution_new_prv(dist%prv, template%prv, group, pgrid, row_dist, col_dist, &"

Some test cases: UNIT/libcp2k_unittest, QS/regtest-corr_dipm/run-corr_dipm-UKS.inp and many more

**Comment by alazzaro** [comment]
This is definitely a bug in DBCSR. Can I ask you which compiler you are using?

**Comment by vzecca** [comment]
nagfor from NAG www.nag.com/nag-compiler

**Comment by alazzaro** [comment]
That's the only compiler we don't test and it is actually the only one that does good checkings... I've actually fixed in DBCSR. Could you test it? 

1. `exts/dbcsr`

2. `git co develop`

3. `git pull`

4. Recompiler CP2K

I will update DBCSR in CP2K with a new release next week.

**Comment by vzecca** [comment]
git commit develop did not work. I am doing without it.

I have no experience with git, I got the following:
git co develop
git: 'co' is not a git command. See 'git --help'.

The most similar commands are
	commit
	cl
[vitti dbcsr]$git commit develop
error: pathspec 'develop' did not match any file(s) known to git
[vitti dbcsr]$git pull
remote: Enumerating objects: 258, done.
remote: Counting objects: 100% (258/258), done.
remote: Compressing objects: 100% (97/97), done.
remote: Total 185 (delta 165), reused 108 (delta 88), pack-reused 0
Receiving objects: 100% (185/185), 47.50 KiB | 675.00 KiB/s, done.
Resolving deltas: 100% (165/165), completed with 67 local objects.
From https://github.com/cp2k/dbcsr
   18fcdb18..3fd51f63  develop    -> origin/develop
   4a96976f..91a280e2  gh-pages   -> origin/gh-pages
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>



I remember I recommended the nagfor compiler years ago to the cp2k team.

nagfor does the BEST testing, with undefined variables detection as well.

**Comment by alazzaro** [comment]
Sorry, sorry, I was using the alises:

```
git checkout develop
git pull
```
(co is an alias for checkout, sorry!)

Concerning nagfor, I know the compiler, but we don't have any license... 
BTW, if you are interested, we are organizing this event: https://tcevents.chem.uzh.ch/event/12/
Maybe, you can present nagfor there...

**Comment by vzecca** [comment]
You may ask for 30 days trial free license to NAG.

And you may ask NAG to send a person to present nagfor, they know it
better than me...

**Comment by vzecca** [comment]
After applying your fixes I rerun the test suite, without extensions
like LIBINT etc,
and the error messages on template not PRESENT disappeared.

Now I have three test cases in error because a disassociated pointer
is referenced.

And many more because nagfor is good at detecting access to floating
point variables
undefined/not initialized.
I'll look into them.

Best regards and happy Easter
Vittorio

**Comment by vzecca** [comment]
I believe this issue may be closed.
