### ISSUE TITLE
Toolchain generates broken sdbg and pdbg arch files

### ISSUE THREAD

**Issue by abussy** [cp2k/cp2k#876]
Compilation of the sdbg and pdbg versions of CP2K based on toolchain generated arch files fails because of undefined reference to BLAS routines. I am using the default OpenBLAS and noticed that the `-lopenblas` flag is missing from LIBS, both in local.sdbg and local.pdbg. Adding it back fixes the problem.

I ran the following command for the toolchain installation:

./install_cp2k_toolchain -j 32 --install-all --with-valgrind=no --with-reflapack=no --with-ptscotch=no --with-parmetis=no --with-metis=no --with-superlu=no --with-pexsi=no --with-quip=no --with-plumed=no --with-sirius=no --with-gsl=no --with-libvdwxc=no --with-spglib=no --with-hdf5=no --with-spfft=no --mpi-mode=openmpi --with-cmake=install --enable-omp

**Comment by dev-zero** [comment]
Did you test with a recent version and regenerated the complete toolchain with it? Because d3bb14123198692c365539cd145cf403ea1a067e should have fixed that and worked in my tests.

**Comment by abussy** [comment]
My working branch was, indeed, not up to date. Updating it fixed the issue. Apologies!
