### ISSUE TITLE
force printed from reftraj is zero

### ISSUE THREAD

**Issue by robinzyb** [cp2k/cp2k#894]
Hi guys,
  I'm using the cp2k-7.1 compiled with intel compiler and arch file Linux-intel-minimum.popt.
Compilation and regression test are successful. 
But when I try to use the reftraj ensemble, the force printed out is all zero. Here I attach the test file.
Might be some bug inside source code.
[test.zip](https://github.com/cp2k/cp2k/files/4563517/test.zip)

**Comment by oschuett** [comment]
This does indeed look like a bug. Thanks for reporting.

**Comment by OndrejMarsalek** [comment]
Isn't it just a question of the `EVAL_FORCES` keyword? It was added later (I am not sure when exactly) and defaults to false. The `EVAL_ENERGY_FORCES` keyword now has an unfortunate name. It is good to have the option to not calculate forces (sometimes they are not free), but this pair of keywords is a little confusing.

https://manual.cp2k.org/trunk/CP2K_INPUT/MOTION/MD/REFTRAJ.html#EVAL_FORCES

**Comment by oschuett** [comment]
The fact that we got this issue twice within three months shows how confusing it is.

The cleanest solution would probably be to merge the two keywords into an enum like e.g. [RUN_TYPE](https://manual.cp2k.org/trunk/CP2K_INPUT/GLOBAL.html#RUN_TYPE).
At the very least we should add a warning to the descriptions.

**Comment by oschuett** [comment]
Fixed via #2974.

**Comment by oschuett** [comment]
For posterity: I've refactor the input structure. See #2981 for details.
