### ISSUE TITLE
Adapt UZH regtester (tcopt5) to new Git infra

### ISSUE THREAD

**Issue by dev-zero** [cp2k/cp2k#9]

**Comment by dev-zero** [comment]
@oschuett can you please check on sham.cp2k.org? The tests ran through on tcopt5 but the dashboard still shows an error when parsing the report.

**Comment by oschuett** [comment]
The reports are missing the `CommitSHA:` line. Maybe you are running `do_regtest` with `-nogit`?

**Comment by alazzaro** [comment]
I'm not fully sure, but I think it is missing the commit SHA in the log file.
For instance, on Daint I use:

git -C ${cp2k_dir} log -1 --pretty="format:%nCommitSHA: %H%nCommitTime: %ci%nCommitAuthor: %an%nCommitSubject: %s%n%n" > ${log_file_store} 2>&1

**Comment by dev-zero** [comment]
@oschuett @alazzaro thanks, will update PR #11 with some more patches tomorrow. I really do not want `do_regtest` to interfere with our Git repository in that way, see also the https://github.com/cp2k/cp2k/issues/7#issuecomment-426700057

**Comment by dev-zero** [comment]
Ran into issue #1, but seems to be working with the latest commits for `do_regtest`.
