### ISSUE TITLE
Conduct User Survey

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#90]
Many of our strategic decisions are based on assumptions about our user base. Unfortunatelly, we have very little hard evidence in this regard. I therefore propose that we conduct a simple survey among our google group subscribers.

Possible questions could be:
- How long have you been using CP2K?
- How often do you use CP2K?
- How do you obtain CP2K (distro, compile myself, provided by admin, ...)?
- What kind of hardware do you have (CPU / GPU generation, memory per node,...)?
- What kind of software do you have (versions of compiler, python, git, cmake, ...)?
- What kind of simulations do you run (QMMM, Metadyn, CDFT, kpoints, ...)?
- What do you consider CP2K's greatest strength?
- What do you consider CP2K's biggest weakness?

**Comment by mkrack** [comment]
That's a good idea. One could also add the questions which features are missing or should be improved in the first place.

**Comment by oschuett** [comment]
Yes, my "biggest weakness" question was kind of aiming at that, but I guess it's too vague. Phrasing survey questions is an art.

**Comment by hfp** [comment]
I can imagine to state CP2K's vision in front of the survey (there should be a vision anyway). It makes it clear that development is not democratized on a per-feature basis but inspired by the most demanding needs of the user base. Perhaps the survey can be also help to eventually prune code or focus efforts.

**Comment by oschuett** [comment]
Ok, here is [a draft](https://docs.google.com/forms/d/e/1FAIpQLSeIKygipUMONrKeNzfO-mvIU9iNgkglKQlsJVyBHWrrxkoVHg/viewform). Any comments?

@hfp, I don't think we have to be worried about of raising false expectations.

**Comment by mkrack** [comment]
Thanks, that looks good, but it is also quite technical. The questionnaire appears for me as a mixture of German and English, but that is possibly due to some of my settings. We could add the question "How did you learn about CP2K?: friend/colleague/supervisor; google; journal paper; lecture; conference etc." .

**Comment by oschuett** [comment]
@mkrack, I added your questions. The language mix up is most probably due to browser settings.

@hfp, I added "...with CP2K" to the question. When I send out the survey invitation, I'll mention my email in case of questions.

**Comment by oschuett** [comment]
Done, results sent out to cp2k dev list.
