### ISSUE TITLE
libxc-5.1 support

### ISSUE THREAD

**Issue by antoscha** [cp2k/cp2k#909]
Hi all,

Are you planning to add Libxc 5 support? I tried to build cp2k 7.1.0 with this version of the library, but got a lot of errors like:  
`Error: Type mismatch in argument ‘np’ at (1); passed INTEGER(4) to INTEGER(8)`
when compiling src/xc/xc_libxc.F

Thanks in advance

**Comment by fstein93** [comment]
Thank you for the hint. I was waiting for the release of Libxc 5.0 and it seems, I missed it. I will add the support soon.

**Comment by dev-zero** [comment]
As @mkrack also wrote in the PR #914 the consensus is to ignore libxc-5.0.0 for now since [the Fortran interface is not the only thing broken](https://gitlab.com/libxc/libxc/-/merge_requests/316).

**Comment by dev-zero** [comment]
it seems libxc is finally going for a 5.1 release: https://gitlab.com/libxc/libxc/-/issues/186#note_466678774

**Comment by fstein93** [comment]
It seems the hotfix will be released next week: https://gitlab.com/libxc/libxc/-/issues/186#note_484100076

**Comment by ltalirz** [comment]
libxc 5.1 has been released
