### ISSUE TITLE
Regtest G0W0_H2O_PBE0_30_pts.inp fails on PASCAL

### ISSUE THREAD

**Issue by alazzaro** [cp2k/cp2k#911]
I've noticed that the test

QS/regtest-gw-cubic/G0W0_H2O_PBE0_30_pts.inp

is failing from time to time on the CUDA Pascal dashboard (check the latest commits). The message is:
```
 *** WARNING in rpa_util.F:919 :: The Cholesky decomposition before        ***
 *** inverting the RPA matrix / dielectric function failed. In case of     ***
 *** low-scaling RPA/GW, decreasing EPS_FILTER in the &LOW_SCALING section ***
 *** might increase the overall accuracy making the matrix positive        ***
 *** definite. Code will abort.                                            ***
```
It seems that the problem started somewhere after with commit 2b878fb

**Comment by pseewald** [comment]
The failure of this regtest seems to be really specific to this system or configuration. I think Cholesky decomposition is using pdgemm so could it be an issue with COSMA?

Judging from the [dashboard](https://dashboard.cp2k.org/archive/cuda-pascal/index.html) this issue was introduced somewhere between 
c9a73d8af15f4c1569558323638c3ee4ad53d705 and b04255bb341f02ca9ce559e82f1d9644be817dd9

Was there any update in the libraries between those commits?

This commit range also includes a DBCSR update. I noticed that DBCSR behaves differently since rc-13: in this regtest we are filtering DBCSR matrices with `eps_filter` of `0.0` which previously did not remove blocks with exact zeroes but now it does. I see this from a diff on the RPA output:
```
<      Time:                                                              0.077661
<      Occupancy of D occ:                                      3.2E+03 / 100.000%
<      Occupancy of D virt:                                     3.2E+03 / 100.000%
---
>      Time:                                                              0.014462
>      Occupancy of D occ:                                      0.0E+00 /   0.000%
>      Occupancy of D virt:                                     0.0E+00 /   0.000%
```

This is probably not the reason for this issue, but I wonder whether that change in DBCSR is intended.

**Comment by alazzaro** [comment]
> This commit range also includes a DBCSR update. I noticed that DBCSR behaves differently since rc-13: in this regtest we are filtering DBCSR matrices with `eps_filter` of `0.0` which previously did not remove blocks with exact zeroes but now it does. I see this from a diff on the RPA output:
> 
> ```
> <      Time:                                                              0.077661
> <      Occupancy of D occ:                                      3.2E+03 / 100.000%
> <      Occupancy of D virt:                                     3.2E+03 / 100.000%
> ---
> >      Time:                                                              0.014462
> >      Occupancy of D occ:                                      0.0E+00 /   0.000%
> >      Occupancy of D virt:                                     0.0E+00 /   0.000%
> ```
> 
> This is probably not the reason for this issue, but I wonder whether that change in DBCSR is intended.

Not sure I understand, is this a problem? In principle, it should not happen since the norm of zeros blocks will be zero and we are checking for <= eps, see https://github.com/cp2k/dbcsr/blob/a00094c449ed37c028267c70f883a9dae1d7cf02/src/mm/dbcsr_mm_multrec.F#L743 

We did some changes in the norms of the blocks, but my changes are after rc14 and I don't see any other change between rc12 and rc14...

**Comment by pseewald** [comment]
> This commit range also includes a DBCSR update. I noticed that DBCSR behaves differently since rc-13: in this regtest we are filtering DBCSR matrices with `eps_filter` of `0.0` which previously did not remove blocks with exact zeroes but now it does.

I found that this behavior is intended and was introduced by me in commit cp2k/dbcsr@0ffa950509c09174b3b352b5de53b00ad1295b41
Again I don't think this is causing any issues.

My first guess is still COSMA, can we test without COSMA just to see whether the same failure also happens with scalapack?

**Comment by oschuett** [comment]
The easiest way to test this would be to open a draft PR which removes COSMA.

**Comment by alazzaro** [comment]
> The easiest way to test this would be to open a draft PR which removes COSMA.

The problem is that it happens in about 50% of the cases (for instance, now it is green)...

**Comment by oschuett** [comment]
As a quick and dirty solution we could remove all [TEST_DIRS](https://github.com/cp2k/cp2k/blob/master/tests/TEST_DIRS) except for `QS/regtest-gw-cubic` and within that dir create several copies of `G0W0_H2O_PBE0_30_pts.inp`.

**Comment by alazzaro** [comment]
OK, the test is now failing on Daint (same message) and there we don't use COSMA...

**Comment by alazzaro** [comment]
And rerunning it fixed the problem... It smells like a race-conditions?
Should we run it with a GCC thread-checker? (needs to rebuild GCC)

**Comment by oschuett** [comment]
@alazzaro, can you do a bisection to narrow down the commit that introduced it?
Since we're not seeing it in any of the other `psmp` runs, it's probably CUDA related.

**Comment by alazzaro** [comment]
yes, I agree, it is GPU related. And yes, we can try to use daint to check the error, but I cannot do it now... Now, can we make a pre-build container with GCC for thread-checking?

**Comment by oschuett** [comment]
The toolchain has some [reminiscence](https://github.com/cp2k/cp2k/blob/master/tools/toolchain/install_cp2k_toolchain.sh#L111) of ThreadSanitizer. However, I've never used it and expect it requires some effort to get it working. Nevertheless, it would be great to have ThreadSanitizer available.

**Comment by alazzaro** [comment]
yesterday I did a test and the problem of the false-positive is still there (reported by Joost ages ago, https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55561 ). We need to compile GCC with `--disable-linux-futex` and check if it fixed the problem... I'm not sure if there can be other problems... It is on my to-do list for DBCSR...

**Comment by hfp** [comment]
I felt guilty enough (due to the commit range) and setup a test on P100 even using GCC 7.5. I cannot reproduce the problem on my system. Is there anything specific we know that must be present to trigger the problem?

**Comment by oschuett** [comment]
@hfp, thanks for investigating! You can reproduce what the CI is doing like this:
```
cd cp2k/tools/toolchain/
nvidia-docker build --build-arg LIBINT_LMAX=4 --build-arg GPU_VERSION=P100 -f Dockerfile.cuda_mkl -t cuda_toolchain .
cd ../docker/
export DOCKER="nvidia-docker"
./build_test.sh cuda-psmp --build-arg TOOLCHAIN=cuda_toolchain
./run_test_master.sh cuda-psmp
```

Once time permits I shall look into https://github.com/cp2k/cp2k-ci/issues/54

**Comment by hfp** [comment]
I was able to reproduce the problem without relying on specific bits or Docker.

```bash
OMP_NUM_THREADS=4 mpirun -np 2 ~/cp2k/exe/Linux-x86-64-intelx/cp2k.psmp G0W0_H2O_PBE0_30_pts.inp
```

Multiple OpenMP threads seem to be a prerequisite (two threads per rank are able to reproduced the problem). More threads does not seem to increase the likelihood of the issue (maybe it decreases beyond 12 threads) . Also, multiple MPI-ranks seem to be a prerequisite (but two ranks are sufficient). I was not able to reproduce the problem with using a single rank.

I will now remove/exchange some of the library components and see if it can be narrowed.

**Comment by oschuett** [comment]
@hfp, have you been able to narrow this down?

The problem seems to have appeared somewhere between c9a73d8 and b04255b.
Since this involves Cuda, the most likely candidate is the large DBCSR update in 4826a90d12846adaa7dd359f3b04d4ab46d9ff6b.

**Comment by hfp** [comment]
It is reproducible just by using the GPU version and does not depend on specific library/runtime versions, or any of the optional libraries. It looks like a data race (SMP). I have not investigated any more. Certainly a good idea to focus on DBCSR.

**Comment by oschuett** [comment]
I believe the culprit is https://github.com/cp2k/dbcsr/commit/3fdbfc6ea0af8725bad716329b1d829ca55a9a4f, which enabled cuBLAS.

The problem is that libcusmm is [called](https://github.com/cp2k/dbcsr/blob/develop/src/mm/dbcsr_mm_accdrv.F#L580) with `stackbuf%stream` and then uses that stream to [launch](https://github.com/cp2k/dbcsr/blob/develop/src/acc/libsmm_acc/libsmm_acc.cpp#L311) cuBLAS kernels. Unlike our own kernels, which use `atomicAdd`, the cuBLAS kernels require exclusive access to the C matrix. Hence, the cuBLAS kernels should instead use `c_area%memory_type%acc_stream`.

**Comment by alazzaro** [comment]
The densification is not the default for the GPU implementation, so I would not expect big blocks in general.
CUBLAS is used only when big blocks are implied (any dimension of the blocks > 80). 
However, you are right, that specific test has a mix of big and small blocks.

So I did two wrong assumptions here:
1. We can have big and small blocks, even without densification. This means that we can have our kernels and cublas running at the same time.
2. The CPU thread-safe mechanism of using different buffers was replicated on the GPU, which is wrong

Your point is definitely correct, I will fix it (BTW, now we Shoshana changed that code, need to understand how to change it).

**Comment by oschuett** [comment]
Ideally we could just rollback to the latest working version of DBCSR, which in this case would be [v2.1.0-rc12 ](https://github.com/cp2k/dbcsr/releases/tag/v2.1.0-rc12). Unfortunately, CP2K does not compile anymore with that version  and we are effectively locked into [v2.1.0-rc16](https://github.com/cp2k/dbcsr/releases/tag/v2.1.0-rc16) now.

So, I think from now on we should make sure that we can return to an older version of DBCSR for at least 6 month.

**Comment by alazzaro** [comment]
The change to the API is due to the Tensor interface, which is probably the last big change expected for the coming years.

**Comment by oschuett** [comment]
> which is probably the last big change expected for the coming years.

Right, I also don't expect this to be much of a constraint.

The ability to rollback  will allow us to continue upgrading DBCSR at a high rate, because we have a contingency plan.

This is good for both projects.

**Comment by alazzaro** [comment]
@oschuett any clue what's the problem with the CUDA Pascal? https://storage.googleapis.com/cp2k-ci/dashboard_cuda-pascal_report.txt

**Comment by oschuett** [comment]
Yeah, unfortunately the GPU sometimes fails to initialize for some unknown reason. I restarted the [run](https://storage.googleapis.com/cp2k-ci/run-cp2k-cuda-pascal-93eee02a_report.txt).

**Comment by alazzaro** [comment]
OK, it is green, but let's give some other trials before closing the issue...

**Comment by oschuett** [comment]
The dashboard [test](https://dashboard.cp2k.org/archive/cuda-pascal/index.html) has now passed three times in a row. So, I think it's safe to say we nailed it :-)
Thanks @alazzaro for the quick DBCSR upgrade!
