### ISSUE TITLE
MPI compilers should be used for C, not only for Fortran

### ISSUE THREAD

**Issue by yurivict** [cp2k/cp2k#919]
Here https://github.com/cp2k/cp2k/blob/master/arch/FreeBSD-gfortran.psmp#L1 if ```FC``` uses the MPI compiler ```mpif90```, ```CC``` should also use the MPI compiler ```mpicc```, not ```gcc```.

Same for all other files in this directory.

**Comment by oschuett** [comment]
All our MPI communication happens in Fortran. While this might change in the future, for now it's correct to use `gcc` instead of `mpicc`.
