### ISSUE TITLE
MPI Memory Error

### ISSUE THREAD

**Issue by RobinLi-95** [cp2k/cp2k#924]
Hi, 

I am a new user of CP2K. I tried to do the geometry relaxation of Mg(0001) slab(number of layers = 9)/self-interstitial(octahedral and tetrahedral sites) of bulk Mg  theses days but I met the following error from the calculations:

 *******************************************************************************
 *   ___       MPI error 471936271 in mpi_cart_sub @ mp_cart_sub : Other MPI   *
 *  /   \             error, error stack:
PMPI_Cart_sub(224).......:           *
 * [ABORT]         MPI_Cart_sub(comm=0xc400006d, remain_dims=0x317ea5d0,       *
 *  \___/         comm_new=0x31618c44) failed
PMPI_Cart_sub(163).......:	 *
 *    |
MPIR_Comm_split_impl(384):
MPIR_Comm_commit(516)....:	*
 *  O/|
MPIR_Info_alloc(61)......: Out of memory (unable to allocate a  *
 * /| |                                 'MPI_Info')                            *
 * / \                                          mpiwrap/message_passing.F:1109 *
 *******************************************************************************

This error often occurs after some BFGS steps with stop of the scf process.
It seems that this due to the memory leak of mpi. I have found reducing the number of k-points does help on this problem while the accuracy is scarified.

I use cp2k/6.1 with mpi/intel-2019 and do the calculations on Imperial College High Performance Computer Cluster with 32 cores. Here's the input file corresponds to this error.

&GLOBAL
  PROJECT Mg_0001
  RUN_TYPE GEO_OPT
  PRINT_LEVEL MEDIUM
&END GLOBAL
&FORCE_EVAL
  METHOD Quickstep
  &SUBSYS
    &KIND Mg
      ELEMENT   Mg
      BASIS_SET RC-MOLOPT-SPD-GTH-8pt0
      POTENTIAL GTH-PBE-q2
    &END KIND
    &CELL
      A [angstrom]  3.2200000286  0.0000000000  0.0000000000
      B [angstrom] -1.6100000143  2.7886018250  0.0000000000
      C [angstrom]  0.0000000000  0.0000000000 65.9399986267
    &END CELL
    &COORD
     Mg   0.000000008    1.859067917     1.298499942
     Mg   1.609999895    0.929533899    50.641498566
     Mg   1.609999895    0.929533899     3.895499945
     Mg   0.000000008    1.859067917     6.492499828
     Mg   1.609999895    0.929533899    45.447498322
     Mg   1.609999895    0.929533899     9.089500427
     Mg   0.000000008    1.859067917    48.044498444
     Mg   0.000000008    1.859067917    11.686500549
     Mg   1.609999895    0.929533899    40.253501892
     Mg   1.609999895    0.929533899    14.283499718
     Mg   0.000000008    1.859067917    42.850502014
     Mg   0.000000008    1.859067917    16.880500793
     Mg   1.609999895    0.929533899    35.059497833
     Mg   1.609999895    0.929533899    19.477499008
     Mg   0.000000008    1.859067917    37.656501770
     Mg   0.000000008    1.859067917    22.074499130
     Mg   1.609999895    0.929533899    29.865501404
     Mg   1.609999895    0.929533899    24.671499252
     Mg   0.000000008    1.859067917    32.462497711
     Mg   0.000000008    1.859067917    27.268497467
    &END COORD
  &END SUBSYS
  &DFT
    BASIS_SET_FILE_NAME  BASIS_MOLOPT
    POTENTIAL_FILE_NAME  GTH_POTENTIALS
    &QS
      EPS_DEFAULT 1.0E-12
    &END QS
    &KPOINTS
      SYMMETRY .TRUE.
      SCHEME MONKHORST-PACK 20 20 1
    &END KPOINTS
    &MGRID
      NGRIDS 4
      CUTOFF 300
      REL_CUTOFF 60
    &END MGRID
    &XC
      &XC_FUNCTIONAL PBE
      &END XC_FUNCTIONAL
    &END XC
    &SCF
      SCF_GUESS ATOMIC
      EPS_SCF 1.0E-8
      MAX_SCF 300
      ADDED_MOS 50
      &DIAGONALIZATION  ON
        ALGORITHM STANDARD
      &END DIAGONALIZATION
      &MIXING  T
        METHOD BROYDEN_MIXING
        ALPHA 0.2
        BETA 1.5
        NBROYDEN 8
      &END MIXING
      &SMEAR ON
        METHOD FERMI_DIRAC
        ELECTRONIC_TEMPERATURE [K] 157.9
      &END SMEAR
    &END SCF
  &END DFT
  &PRINT
    &FORCES ON
    &END FORCES
  &END PRINT
&END FORCE_EVAL
&MOTION
  &GEO_OPT
    OPTIMIZER BFGS
  &END
&END MOTION 

Could anyone please help me on this error and give me some suggestions?
I am looking forward to your reply.

Best,
Bingxin

**Comment by oschuett** [comment]
Sorry for the late reply. For user question please consult our [google group](https://www.cp2k.org/howto:forum).
