### ISSUE TITLE
Fix minimax_tools and add a test

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#926]
It seems [minimax_to_fortran_source.py](https://github.com/cp2k/cp2k/blob/master/tools/minimax_tools/minimax_to_fortran_source.py) stopped working. That script was used to generate [minimax_exp_k53.F](https://github.com/cp2k/cp2k/blob/master/src/minimax/minimax_exp_k53.F).

As input the script takes a database from http://www.mis.mpg.de/scicomp/EXP_SUM/1_x. Ideally, we should keep a copy of it at cp2k.org, but unfortunately I couldn't find any associated license.

Once we have it working again, we should add a test.

**Comment by dev-zero** [comment]
it runs a bit deeper than that: the data also changed (now `k=63` of just `53`), not only the layout (now contained in the zip file). @pseewald any hints on how to verify the new data?

This would be the diff to make it run again:

```
diff --git a/tools/minimax_tools/fetch_minimax.sh b/tools/minimax_tools/fetch_minimax.sh
index 358efcfce..b2550a833 100755
--- a/tools/minimax_tools/fetch_minimax.sh
+++ b/tools/minimax_tools/fetch_minimax.sh
@@ -1,2 +1,9 @@
 #!/bin/bash
-wget -r -np -e robots=off --reject "index.html*" http://www.mis.mpg.de/scicomp/EXP_SUM/1_x/
+
+set -o errexit
+set -o nounset
+set -o pipefail
+
+wget https://www.mis.mpg.de/scicomp/EXP_SUM/1_x/1_xData.zip
+mkdir -p 1_xData
+unzip -d 1_xData 1_xData.zip
diff --git a/tools/minimax_tools/minimax_to_fortran_source.py b/tools/minimax_tools/minimax_to_fortran_source.py
index 45d42d43e..709e58758 100755
--- a/tools/minimax_tools/minimax_to_fortran_source.py
+++ b/tools/minimax_tools/minimax_to_fortran_source.py
@@ -7,7 +7,7 @@ import os.path
 # 1) parse data #
 #################
 
-reldir = r"www.mis.mpg.de/scicomp/EXP_SUM/1_x/"
+reldir = r"1_xData/"
 
 txt = open(reldir + "tabelle", "r")
 
@@ -29,7 +29,7 @@ a = []
 w = []
 
 start_line = 46
-end_line = 288
+end_line = 540
 
 for l, line in enumerate(txt.readlines()):
     if l < start_line - 1:
@@ -55,7 +55,7 @@ for l, line in enumerate(txt.readlines()):
             Rcval = float(re_body.match(line).group("Rc"))
             Rcstr = re_body.match(line).group("Rc")
             # slight change of notation e.g. 6E09 --> 6E9
-            Rcstr = re.sub("E0(?=\d)", "E", Rcstr)
+            Rcstr = re.sub("E0?(?=\d)", "_", Rcstr)
             errvals = [
                 float(_) if _ != "--" else 0.0
                 for _ in re_body.match(line).group("err").split()
@@ -67,7 +67,7 @@ for l, line in enumerate(txt.readlines()):
                     kstr = str(kvals[i])
                     if len(kstr) == 1:
                         kstr = "0" + kstr
-                    filename = reldir + "1_xk" + kstr + "_" + Rcstr
+                    filename = reldir + "1_xk" + kstr + "." + Rcstr
                     if not os.path.isfile(filename):
                         missing.append(filename)
                         continue
```

**Comment by pseewald** [comment]
I initially assumed we don't need the script and source data anymore since `minimax/minimax_exp_k53.F` is a 1:1 translation. If the data has changed it may be worthwhile to update our Fortran source file to see what has changed, also to get the minimax approximations with `k>53`. @dev-zero so the script is working with the new data or do you need my help adapting it?

For verification of the new data: The script should generate the CP2K source file `minimax/minimax_exp_k53.F`. There is a unit test for minimax `tests/LIBTEST/test_minimax.inp` that checks the error of the minimax approximations numerically and compares with the tabulated error. Possibly the maximum `k` (53 so far) is hard coded in CP2K and needs to be adapted manually.

**Comment by dev-zero** [comment]
> I initially assumed we don't need the script and source data anymore since `minimax/minimax_exp_k53.F` is a 1:1 translation. If the data has changed it may be worthwhile to update our Fortran source file to see what has changed, also to get the minimax approximations with `k>53`. @dev-zero so the script is working with the new data or do you need my help adapting it?

The script is working with the new data after the changes posted above, I think. At least it runs without an error and generates similar data.

> For verification of the new data: The script should generate the CP2K source file `minimax/minimax_exp_k53.F`. There is a unit test for minimax `tests/LIBTEST/test_minimax.inp` that checks the error of the minimax approximations numerically and compares with the tabulated error. Possibly the maximum `k` (53 so far) is hard coded in CP2K and needs to be adapted manually.

OK, I didn't look for the maximum `k` yet.
