### ISSUE TITLE
Performance regression of RPA_kpoints_H2O_batched.inp after #886

### ISSUE THREAD

**Issue by oschuett** [cp2k/cp2k#928]
This regression showed up in [psmp](https://dashboard.cp2k.org/archive/current-psmp/index.html).

Before #886 the `RPA_kpoints_H2O_batched.inp` test took  [37.17s](https://dashboard.cp2k.org/archive/current-psmp/commit_2b878fb9081829de877540ff456b5fbde228c59e.txt), afterwards it takes [89.31s](https://dashboard.cp2k.org/archive/current-psmp/commit_6415e23afddbc24b520d1eca4ef0fc714a80cfe8.txt).

Furthermore, [cray-xc50-daint-gpu-psmp_perf](https://dashboard.cp2k.org/archive/cray-xc50-daint-gpu-psmp_perf/index.html) indicates an increased memory consumption.

**Comment by pseewald** [comment]
Thank you for noticing this

**Comment by oschuett** [comment]
Thanks for fixing it :-)
