### ISSUE TITLE
Incorrect parsing of Amber prmtop files

### ISSUE THREAD

**Issue by vamironov** [cp2k/cp2k#984]
Classical molecular mechanics module gives incorrect energy and forces when using Amber `prmtop` files.

To investigate the origin the problem, I run several simulations of the GTP molecule with Amber force field in various MD software ([cp2k-amber.zip](https://github.com/cp2k/cp2k/files/4893050/cp2k-amber.zip)). The same `prmtop` file was used in Amber and CP2K.

This analysis shows, that the dihedral energy in CP2K is exactly two times smaller than needed. Interestingly, converting topology and force field parameters to CHARMM format results in correct dihedral energy in CP2K.

| Program                        | Dihedral energy        |
|---------------------------|-----------------------|
| CP2K (Amber prmtop)   |   7.866500 kcal/mol |
| CP2K (PSF)                     | 15.727700 kcal/mol |
| Amber 18                       | 15.733000 kcal/mol |
| Gromacs  2018               | 15.791368 kcal/mol |

Source code inspection shows that force constants of all torsions are halved when parsing `prmtop` files:
https://github.com/cp2k/cp2k/blob/51267ca7aef7d7e6e416ad6faf8961c06b61ae0e/src/topology_amber.F#L1616

Removing the factor 0.5 fixed the problem for me.

The issue was observed with CP2K versions 7.1 and 6.1, and it most probably exists in the development version.

**Comment by oschuett** [comment]
Great analysis! Thanks for reporting.

Archaeology shows that the `0.5` factor was added very consciously: https://github.com/cp2k/cp2k/commit/77230a3767636867250e5bfe89f0575b0b29309a

@molet, do you still recall any of the details?

**Comment by molet** [comment]
Well, it's been a while but what I can recall is that the dihedral energy was incorrect without the 0.5 factor for the `dmpoh` system (added to commit https://github.com/cp2k/cp2k/commit/77230a3767636867250e5bfe89f0575b0b29309a). @vamironov would you be able to perform a similar analysis for that system as well (amber vs cp2k)?

**Comment by oschuett** [comment]
I had a look at which sections of the GTP input are [ignored](https://github.com/cp2k/cp2k/blob/master/src/topology_amber.F#L620) by our parser. What stands out are `SCEE_SCALE_FACTOR` and `SCNB_SCALE_FACTOR`. These sections were [introduced](https://ambermd.org/prmtop.pdf) in Amber 11 and here they contribute factors of `1.2` and `2.0` respectively.

So, I guess we should implement those new sections and afterwards maintain an explicit list of section that we want to ignore.

**Comment by vamironov** [comment]
It was a surprise to see that the test input in commit 77230a3 gives same result as Amber!

But in fact the "correct" answer is a result of another bug: a dihedral can be counted two times.
When using Amber parameters, CP2K incorrectly assigns two dihedral definitions with reversed atom order (i.e. A-B-C-D and D-C-B-A) as two components of multicomponent dihedral. Look at the ouputs.

Here are CP2K prmtop dihedral parsing results:

```
     ...    
     AMB TORSION            1 H1 CT OS P   0.19166666650000000                3   0.0000000000000000  
     AMB TORSION            2 P OS CT H1   0.19166666650000000                3   0.0000000000000000  
     AMB TORSION            3 CT OS P O2   0.12500000000000000                3   0.0000000000000000  
     AMB TORSION            4 CT OS P OS   0.59999999999999998                2   0.0000000000000000  
     AMB TORSION            5 CT OS P OS   0.12500000000000000                3   0.0000000000000000  
     AMB TORSION            6 O2 P OS CT   0.12500000000000000                3   0.0000000000000000  
     AMB TORSION            7 OS P OS CT   0.59999999999999998                2   0.0000000000000000  
     AMB TORSION            8 OS P OS CT   0.12500000000000000                3   0.0000000000000000
     ...   

UTIL_INFO| Multiple Torsion declarations: CT,OS,P and O2
UTIL_INFO| Number of defined torsions:      2 .


UTIL_INFO| Multiple Torsion declarations: CT,OS,P and OS
UTIL_INFO| Number of defined torsions:      4 .


UTIL_INFO| Multiple Torsion declarations: H1,CT,OS and P
UTIL_INFO| Number of defined torsions:      2 .


 FORCEFIELD| WARNING: A non Critical ForceField parameter is missing! CP2K GOES!
 FORCEFIELD| Non critical parameters are:Urey-Bradley,Torsions,Impropers, Opbends and 1-4
```
The dihedral energy is 1.6491 kcal/mol
```
FIST energy contributions in kcal/mol:
BOND    =        3.0350  ANGLE   =        6.5494  UBRAD   =        0.0000
TORSION =        1.6491  IMPTORS =        0.0000  OPBEND  =        0.0000
```

When converting Amber topology to PSF and CHARMM parameters:
```
     ...     
     CHM TORSION            1 CT OS P O2   0.25000000000000000                3   0.0000000000000000     
     CHM TORSION            2 CT OS P OS    1.2000000000000000                2   0.0000000000000000     
     CHM TORSION            3 CT OS P OS   0.25000000000000000                3   0.0000000000000000     
     CHM TORSION            4 H1 CT OS P   0.38329999999999997                3   0.0000000000000000     
     ...   

UTIL_INFO| Multiple Torsion declarations: OS,P,OS and CT
UTIL_INFO| Number of defined torsions:      2 .


 FORCEFIELD| WARNING: A non Critical ForceField parameter is missing! CP2K GOES!
```
the dihedral energy is same:
```
 FIST energy contributions in kcal/mol:
 BOND    =        3.0350  ANGLE   =        6.5494  UBRAD   =        0.0000
 TORSION =        1.6490  IMPTORS =        0.0000  OPBEND  =        0.0000
```

Here are Amber results for comparison:
```
   NSTEP       ENERGY          RMS            GMAX         NAME    NUMBER
      0       6.8169E+01     2.2099E+01     7.1802E+01     P           6

 BOND    =        3.0350  ANGLE   =        6.5494  DIHED      =        1.6491
 VDWAALS =       -1.5146  EEL     =       47.6453  HBOND      =        0.0000
 1-4 VDW =        0.4439  1-4 EEL =       10.3613  RESTRAINT  =        0.0000
```

As you can see, in the case of CP2K+Amber topology, all dihedrals for this input are in fact computed twice (see the number of "Multiple Torsion declarations"). That is why the energy was actually two times higher than needed and scaling all dihedral force constants by 0.5 allowed to pass this test.

The test input in commit 77230a3 represents an extreme case, where all torsions are counted twice. For many other systems, this double counting happens only occasionally. The fix from that commit does not really help in these cases.

Re-ordering of atom types in dihedral definition during parameters post-processing (`subroutine post_process_torsions_info`) probably helps.
https://github.com/cp2k/cp2k/blob/60feeed115523b7d56c85acaa405ca7e90217649/src/topology_amber.F#L1589-L1600

**Comment by vamironov** [comment]
> I had a look at which sections of the GTP input are [ignored](https://github.com/cp2k/cp2k/blob/master/src/topology_amber.F#L620) by our parser. What stands out are `SCEE_SCALE_FACTOR` and `SCNB_SCALE_FACTOR`. These sections were [introduced](https://ambermd.org/prmtop.pdf) in Amber 11 and here they contribute factors of `1.2` and `2.0` respectively.
> 
> So, I guess we should implement those new sections and afterwards maintain an explicit list of section that we want to ignore.

This is also very important issue. Non-protein Amber extensions like General Amber Force Field or GLYCAM may have non-default LJ and Coulomb scaling for 1-4 interactions. But for "regular" AmberFF parameters they are same across all dihedrals and one can use `VDW_SCALE14` and `EI_SCALE14` options in CP2K input to specify them.

**Comment by vamironov** [comment]
Now, some Amber-related regtests begin to fail:
```
QMMM/SE/regtest-force-mixing/Lysozyme_small_NVT.inp
Fist/regtest-3/ace_ala_nme-amber.inp
Fist/regtest-14/lamol.inp
Fist/regtest-13/pc-222.inp
```

I run ace_ala_nme test in Amber and in CP2K with increased verbosity. The patched CP2K version gives correct result.
Amber:
```
  NSTEP       ENERGY          RMS            GMAX         NAME    NUMBER
     0      -3.8092E+01     5.7144E+00     2.2745E+01     N           7

BOND    =        0.0206  ANGLE   =        0.3620  DIHED      =        8.1071
VDWAALS =        2.8105  EEL     =      -85.8247  HBOND      =        0.0000
1-4 VDW =        5.0157  1-4 EEL =       31.4173  RESTRAINT  =        0.0000
```
Patched:
```
 FIST energy contributions in kcal/mol:
 BOND    =        0.0206  ANGLE   =        0.3620  UBRAD   =        0.0000
 TORSION =        8.1071  IMPTORS =        0.0000  OPBEND  =        0.0000
```
Non-patched:
```
 FIST energy contributions in kcal/mol:
 BOND    =        0.0206  ANGLE   =        0.3620  UBRAD   =        0.0000
 TORSION =        4.0535  IMPTORS =        0.0000  OPBEND  =        0.0000
```

**Comment by vamironov** [comment]
Well, it seems, that the problem is more complex, than I thought before. Dihedral atom reordering does not help when certain improper types which are present in topology.

There is a problem, that an improper can have exactly the same sequence of atomic types as another regular torsion. The example is a peptide backbone:
```
       Ca (1)
        \
         C==O
        /
    H--N
        \
         Ca (2)
```
Here, the torsion Ca(2)-N-C-O and improper Ca(1)-N-C-O have the same type: Ca-N-C-O. Note, that in Amber the central atom of improper is third in a sequence. I observed, that in Amber force field files, atomic kinds of impropers listed in opposite order than in corresponding proper torsions. If so, we can use it to distinguish these two distinct types of dihedrals.

Currently, CP2K will use **both** definitions for **every** dihedral of this kind. They will be used as two components of multicomponent dihedral.
https://github.com/cp2k/cp2k/blob/d6ab4f1c5b0ba8293bc00abfc2afcd67c7ffcf41/src/force_fields_all.F#L1394-L1416

First, I removed the second half of the `IF` statement in this piece of code. After that, the energy becomes correct for all my test systems. Also, Amber `prmtop` files does not have undefined dihedrals, so the search for torsions with blank (`X`) atoms can be skipped as well.

However, I can't guarantee that the order of atomic types in impropers will be always different than in regular torsions. I believe, that using the raw dihedral data in Amber `prmtop` file is less error-prone. For that reason I modified the code which sets up dihedral parameters to work with raw data. Please, revise the PR with these changes.
